### ISSUE TITLE
Old forum on Sourceforge down?

### ISSUE THREAD

**Issue by Lennart-Winter** [shankar1729/jdftx#1]
Dear Shankar,

just a quick question: Is the old forum on Sourceforge down? I can't get access to old Tickets anymore, since it says "Read Access required".

Thank you very much and best regards,

Lennart

**Comment by shankar1729** [comment]
Hi Lennart,

Indeed, we're in the process of migrating everything over to github.  Please post new questions here.

But yes, I should have left read access open on sourceforge tickets and discussion.  I've done that now: please that confirm it works for you.

Best,
Shankar

**Comment by Lennart-Winter** [comment]
Dear Shankar,

it works fine now. Thank you for your continued support.

Best,

Lennart
