### ISSUE TITLE
GVectors corresponding to each band

### ISSUE THREAD

**Issue by gvarnavi** [shankar1729/jdftx#102]
Hey Shankar,

I need to compute some BZ integrals with band-index sums, and it's more convenient to work in the extended zone scheme.
I was wondering if there's a way to dump the mapping b/w (kpt-in-reduced-scheme,band-index) -> kpt-in-extended-scheme.
I tried `dump Gvectors`, but I take it those are the planewave coefficient gvectors.

And advice would be much appreciated!
Cheers,
George

**Comment by shankar1729** [comment]
Hi George,

There is no unique definition of extended zone scheme for general band structures beyond free / nearly-free cases. Perhaps you are looking for something like band structure unfolding? (Chris has used this.)

Best,
Shankar

**Comment by gvarnavi** [comment]
Hey Shankar,

Thanks for your prompt reply!
I think I wasn't being clear. Essentially what I need is the wave-vector relating two states.
In particular I want to compute the overlap B integrals in dielectric function calculations of the form:
```
B_{mn}(k,q,G) = <k+q+G|e^{-iq.r}|k>
```
where G is the wave-vector relating bands n and m.

E.g. consider state (k1,e1) and (k2,e2), there should be a unique wavevector connecting these two states in the unfolded BZ, right?


Cheers,
George

**Comment by shankar1729** [comment]
No, each state is a linear combination of several G's and there isn't a single wave vector connecting any two states. There will be several wave vectors connecting states k and k+q, which are equivalent to q up to an arbitrary reciprocal lattice vector G.

Best,
Shankar

**Comment by gvarnavi** [comment]
Hey Shankar,

We were indeed confused with notation - thanks for clarifying!

Cheers,
George
