### ISSUE TITLE
A question about dump End Dipole

### ISSUE THREAD

**Issue by Yanhuanjin** [shankar1729/jdftx#103]
Hello shankar,

When I applied "dump End Dipole" to a symmetric system (X-Y symmetry), it wrote these lines in the common.Moments

```
Electron moment of order 1: 406.856140  155.193985      3020.872325
Ion moment of order 1: 1037.872550      1330.259177     -2822.119130
Total moment of order 1: 1444.728689    1485.453162     198.753195
```
I think along the z axis, the moment should be zero since it's on x-y plane symmetry. But I am not sure about each column's meaning(x, y, z ???), so could you please tell me how this orders were calculated?(Or which part of the code?) 

Best regards,
Daniel

**Comment by shankar1729** [comment]
Hi Daniel,

It appears that the current implementation of the dipole moment dumping is quite old and does not take in to account coulomb-truncation-embed etc. It seems to always assume that the molecule / slab etc is centered on the origin.

Please share the input file and ionpos for the case you are currently testing. I will try to bring this code up to date with remaining features of the code in the meantime.

Best,
Shankar

**Comment by Yanhuanjin** [comment]
Hi Shankar,
Here is another simplified test example, with the similar output.
```
lattice\
16.318393507080597 0.000000000000000 0.000000000000000 \
0.000000000000000 16.318393507080597 0.000000000000000 \
0.000000000000000 0.000000000000000 39.884746647936701 \

ion  Ag  10.878980521203484  10.878980521203484  19.567803343679824  0
ion  Ag  5.439408668655792  10.878980521203484  19.567803343679824  0
ion  Ag  0.000000000000000  10.878980521203484  19.567803343679824  0
ion  Ag  10.878980521203484  5.439408668655792  19.567803343679824  0
ion  Ag  5.439408668655792  5.439408668655792  19.567803343679824  0
ion  Ag  0.000000000000000  5.439408668655792  19.567803343679824  0
ion  Ag  10.878980521203484  0.000000000000000  19.567803343679824  0
ion  Ag  5.439408668655792  0.000000000000000  19.567803343679824  0
ion  Ag  0.000000000000000  0.000000000000000  19.567803343679824  0
ion  Ag  8.167391744351756  13.602101168450698  23.467744745135541  1
ion  Ag  2.733441816254422  8.163478144301759  23.473605735112894  1
ion  Ag  8.182381071727093  2.725501082919848  23.478650608246880  1
ion  Ag  8.173604548030509  8.165477048626585  23.484358886350130  1
ion  Ag  13.592596363040581  8.161935191306004  23.485919764848020  1
ion  Ag  2.709505151040274  13.609527297955308  23.498589092957417  1
ion  Ag  2.742640333936052  2.703367383084562  23.500704943467703  1
ion  Ag  13.617698766606170  2.697125397768926  23.509277929220115  1
ion  Ag  13.599709958218915  13.603756403533817  23.511615890327391  1
ion  Ag  0.039537467436382  5.429813383929651  27.344712072187882  1
ion  Ag  5.494649573231178  5.453586985338926  27.348484400521158  1
ion  Ag  16.305944644684743  10.854269891026858  27.366212474274029  1
ion  Ag  5.433138863130167  10.912545844599515  27.375935834968903  1
ion  Ag  10.927797877985510  5.438481470135045  27.395090925908839  1
ion  Ag  5.490020271640243  0.000501625880315  27.409689439376852  1
ion  Ag  10.872277578174883  16.310639080832399  27.419662477243374  1
ion  Ag  10.840036907038247  10.886707860692372  27.420395012391587  1
ion  Ag  0.038889354786853  16.309636040900781  27.469236325370289  1
ion  H  8.257317649687595  8.202030604377223  28.515910566382395  1
ion  Ag  8.167391744351756  13.602101168450698  15.667861942224107  1
ion  Ag  2.733441816254422  8.163478144301759  15.662000952246753  1
ion  Ag  8.182381071727093  2.725501082919848  15.656956079112767  1
ion  Ag  8.173604548030509  8.165477048626585  15.651247801009518  1
ion  Ag  13.592596363040581  8.161935191306004  15.649686922511627  1
ion  Ag  2.709505151040274  13.609527297955308  15.637017594402231  1
ion  Ag  2.742640333936052  2.703367383084562  15.634901743891945  1
ion  Ag  13.617698766606170  2.697125397768926  15.626328758139532  1
ion  Ag  13.599709958218915  13.603756403533817  15.623990797032256  1
ion  Ag  0.039537467436382  5.429813383929651  11.790894615171766  1
ion  Ag  5.494649573231178  5.453586985338926  11.787122286838489  1
ion  Ag  16.305944644684743  10.854269891026858  11.769394213085619  1
ion  Ag  5.433138863130167  10.912545844599515  11.759670852390744  1
ion  Ag  10.927797877985510  5.438481470135045  11.740515761450808  1
ion  Ag  5.490020271640243  0.000501625880315  11.725917247982796  1
ion  Ag  10.872277578174883  16.310639080832399  11.715944210116273  1
ion  Ag  10.840036907038247  10.886707860692372  11.715211674968060  1
ion  Ag  0.038889354786853  16.309636040900781  11.666370361989358  1
ion  H  8.257317649687595  8.202030604377223  10.619696120977252  1
```
Output
```

Electron moment of order 1: 94.487825	96.151490	567.125234
Ion moment of order 1: 936.583963	946.240308	-3089.139365
Total moment of order 1: 1031.071788	1042.391799	-2522.014132
```

[ex1.zip](https://github.com/shankar1729/jdftx/files/3979144/ex1.zip)

**Comment by 20190111** [comment]
Hi Shankar,
I also meet a problem for understanding the magnetic moment. I use the coulomb-interaction Slab 001, coulomb-truncation-embed 0 0 0, after a spin-polarization calculation  I get the .Moments and .out. 
In the .out , it shows "FillingsUpdate:  mu: -0.156111791  nElectrons: 648.000000  magneticMoment: [ Abs: 3.69117  Tot: -0.00000 ]" and in the .moments, it shows
Electron moment of order 1: 38.877293	177.113500	393.237719
Ion moment of order 1: 722.829765	-493.374267	-780.267997
Total moment of order 1: 761.707058	-316.260766	-387.030278
My questions are:
1. which number I should regard as the  magnetic moment of my structure ?
2. What's the meaning of each value in the .monments ?
3. How could I get the spin density of my structure ? 

Best
Anna

**Comment by shankar1729** [comment]
The Moments file contain the *electric* dipole moment, with each line corresponding to electronic, nuclear and total dipole moment vectors. There is some bug here that needs to be fixed as per the discussion above.

The value in the fillings line is the magnetic moment. Note that for spin-z calculations, this is a single number without a definite spatial direction. Magnetic dipole vectors are only meaningful in spinorial vector-spin calculations.

Use dump End ElecDensity to get n_up and n_dn fo your calculation. The difference between these is the spin density.

Best,
Shankar

**Comment by shankar1729** [comment]
The latest commit fixes the dipole moment issues. (Note that the new code will explicitly set dipole moments in periodic directions to zero since this is not the Berry-phase implementation that can account for polarization lattices of periodic systems.)

Best,
Shankar
