### ISSUE TITLE
LCAOM and ElecMinimize not converged

### ISSUE THREAD

**Issue by 20190111** [shankar1729/jdftx#104]
Dear  Shankar,
I carried out calculations with jdftx for some structures, but often meet an error information:
LCAOMinimize: Iter:   6  F: -1023.0404557796450717
LCAOMinimize: Encountered beta<0, resetting CG.
LCAOMinimize: 	Bad step direction: g.d > 0.
LCAOMinimize: 	Undoing step.
LCAOMinimize: 	Step failed along negative gradient direction.
LCAOMinimize: Probably at roundoff error limit. (Stopping)
Sometimes, the following ElecMinimize could be carried out normally and converged, but sometime, the following ElecMinimize could not be converged. So I wonder whether I need to take care of this error information? Should I make another calculation through adjusting parameters to make LCAOMInimize converge even the following ElecMinimize has converged ?

Another question is that even I set the input with 
electronic-minimize energyDiffThreshold  1e-07
fluid-minimize knormThreshold 3e-12
for a solvation calculation with CANDLE, I still get the following error information: 
![图片](https://user-images.githubusercontent.com/46814723/71054321-93618000-218c-11ea-9fdd-137fe71b1fb6.png)
What should I do next for a converged calculation ?
I'm looking forward to your help!

Best,
Chen

**Comment by shankar1729** [comment]
HI Chen,

My best guess is that in these cases the calculation is already quite converged, but it gets stuck with the grad_K NAN issue that sometimes creates problems in the final convergence. You can try reading in the final state of this calculation and running electronic-SCF from there; that should get good final convergence and should avoid any SCF instabilities since starting from a well-converged case.

Best,
Shankar

**Comment by 20190111** [comment]
Hi Shankar，
I'm sorry, it seems that I could not understand you. I try to analyze your meaning, please correct me if I'm wrong:
1. For the case of not converged LCAOMinimize but then the next steps of  electronic-minimize and ion-minimize converged , I should ignore the information of not converged LCAOMinimize, and only look at the final electronic-minimize for the final Ion-minimize,then extract the final energy and mu from the .out file.
2.  For the not converged electronic-minimize of solvation calculation, I should change electronic-minimize  to be  electronic-SCF, then do the calculation again.
3. No matter how many steps in the .out the electronic-minimize does not converge when running different steps of ion optimization, just make sure the self-consistent iteration of the last step in the output converges. 

Best.
Chen

**Comment by shankar1729** [comment]
Yep, that's right.

**Comment by 20190111** [comment]
Dear Shankar,
I'm sorry to bother you again. In the last question, I find the LCAOMinimize not converged but both of the final ElecMinimize and IonicMinimize converged. I wonder the information of not converged LCAOMinimize may influence my results, so I do a test. I try the structure optimization again by using the same input and reading the .ionpos, .wfns, .fillings from the last converged calculation. I want to compare the final results between the twice calculation. But this time I get more bad information, the
ion optimization not converged. The error is:
IonicMinimize: 	Step failed along negative gradient direction.
IonicMinimize: Probably at roundoff error limit. (Stopping)
Here is my .out
[vacuum.out.txt](https://github.com/shankar1729/jdftx/files/3986303/vacuum.out.txt)
What should I do now ?
I'm looking forward to your help.

Best,
Chen

**Comment by shankar1729** [comment]
Your forces are already very small, which means your ionic minimize is already practically converged. The step failed because the electronic convergence accuracy is insufficient at forces this small. If you want to further converge the forces, you will need to reduce the energyDiffThreshold of electronic-minimize/SCF.

Best,
Shankar
