### ISSUE TITLE
Electron behavior at "extreme" voltages?

### ISSUE THREAD

**Issue by anneb101** [shankar1729/jdftx#105]
Hi Dr. Shankar,

Building off the constant-mu-in-electrolyte tutorial, I did a sweep of 1000 points on a similar FCC(100) copper slab  across a 10 V range. The geometry was adjusted for the copper lattice constant and range of mu values here is deliberately chosen.  I was seeing some noise in the data at extreme voltages. I just wanted to check if this is an artifact of running the simulation at extreme voltages (and therefore could be addressed by data-smoothing), or if this is the physical behavior.

![electron_noise](https://user-images.githubusercontent.com/20980002/71368833-fb420d00-2576-11ea-9975-7ef9f3874a4c.png)

Thank you,
Anne

**Comment by shankar1729** [comment]
Hi Anne,

The issues you are seeing is in the range where the absolute mu is near zero, which makes the electrons unbound and escape the electrode. So that range is misbehaving for an understandable physical reason, and would not be experimentally meaningful anyway.

Best,
Shankar
