### ISSUE TITLE
electron localization function

### ISSUE THREAD

**Issue by 20190111** [shankar1729/jdftx#106]
Dear Shankar,
I want to analyze the bonding type  of my structure. I need to calculate the electron localization function which can be obtained with the LELF=.TRUE. in the vasp. So I want to know whether I can calculate the electron localization function in jdftx ?

Best,
Anna

**Comment by shankar1729** [comment]
Hi Anna,

ELF functionality is not currently implemented in JDFTx.

Best,
Shankar
