### ISSUE TITLE
GPU help

### ISSUE THREAD

**Issue by mef362** [shankar1729/jdftx#108]
Hi, I have been trying to compile the GPU version of jdftx but can't seem to get it to work. I have no problem compiling / generating the executable (jdftx_gpu); however, when I run a calculation it dies right in the beginning:

### End of output file ###
  Partial core density with radius 1.45
  Transforming core density to a uniform radial grid of dG=0.02 with 1833 points.
  Transforming local potential to a uniform radial grid of dG=0.02 with 1833 points.
  Transforming nonlocal projectors to a uniform radial grid of dG=0.02 with 432 points.
  Transforming density augmentations to a uniform radial grid of dG=0.02 with 1833 points.
  Transforming atomic orbitals to a uniform radial grid of dG=0.02 with 432 points.
[dd1] *** Process received signal ***
[dd1] *** Process received signal ***
[dd1] Signal: Floating point exception (8)
[dd1] Signal code: Integer divide-by-zero (1)
[dd1] Failing at address: 0x2aaaab152cb1
###

I have tried various combinations of libraries:
openmpi / intel-mpi
intel / gnu
mkl
cudatoolkit/9.0 / cudatoolkit/10.1

The beginning of the output after trying to run looks good:
### Begin of input file ###
Executable /QMcodes/jdftx-master/build/jdftx_gpu with command-line: -i Si.in
Running on hosts (process indices):  dd4 (0-3)
Divided in process groups (process indices):  0 (0)  1 (1)  2 (2)  3 (3)
gpuInit: Found compatible cuda device 0 'Tesla P100-SXM2-16GB'
gpuInit: Found compatible cuda device 1 'Tesla P100-SXM2-16GB'
gpuInit: Found compatible cuda device 2 'Tesla P100-SXM2-16GB'
gpuInit: Found compatible cuda device 3 'Tesla P100-SXM2-16GB'
gpuInit: Selected device 0
Resource initialization completed at t[s]:      1.26
Run totals: 4 processes, 36 threads, 4 GPUs

Input parsed successfully to the following command list (including defaults):
###

I'm compiling with cmake; I have tried explicitly adding some library locations but still have the same problem. Also, I have looked at the CMakeCache.txt file and cmake seems to be finding the different libraries. 
### cmake line ###
CC=icc CXX=icc cmake \
   -D EnableCUDA=yes \
   -D CudaAwareMPI=yes \
   -D EnableMKL=yes \
   -D ForceFFTW=yes \
   -D MKL_PATH=/opt/intel/16.0/mkl \
   ../jdftx
###

Job run command:
mpirun -n $(($n*$np)) /QMcodes/jdftx-master/build/jdftx_gpu -c $theards -i Si.in | tee Si.out

I assume there is some communication issue with the GPUs; any suggestions on how to determine and fix the problem would be appreciated.

Thanks in advance for any help!

**Comment by shankar1729** [comment]
Do you get the same error if you compile with CudaAwareMPI=no? (Please clear out build directory before recompiling to make sure change takes effect.)

Best,
Shankar

**Comment by mef362** [comment]
Yes

**Comment by mef362** [comment]
Also,
ompi_info --parsable --all | grep mpi_built_with_cuda_support:value
mca:mpi:base:param:mpi_built_with_cuda_support:value:true

**Comment by mef362** [comment]
Not sure if the information below is helpful or not. I get slight different information when using different compilers.

[dd4] *** Process received signal ***
[dd4] Signal: Floating point exception (8)
[dd4] Signal code: Integer divide-by-zero (1)
[dd4] Failing at address: 0x2aaaab4a6cb8
[dd4] [ 0] /lib64/libpthread.so.0(+0xf630)[0x2aaab04c6630]
[d94] [ 1] /QMcodes/jdftx-master/build/libjdftx_gpu.so(_Z16matrixSubSet_gpuiiiiiiiPK7complexPS_+0x58)[0x2aaaab4a6cb8]
[dd4] [ 2] /QMcodes/jdftx-master/build/libjdftx_gpu.so(_ZN6matrix3setEiiiiiiRKS_+0x187)[0x2aaaaaf2ebc7]
[dd4] [ 3] /QMcodes/jdftx-master/build/libjdftx_gpu.so(_ZN11SpeciesInfo5setupERK10Everything+0xd3f)[0x2aaaab18cdff]
[dd4] [ 4] /QMcodes/jdftx-master/build/libjdftx_gpu.so(_ZN7IonInfo5setupERK10Everything+0x1ef)[0x2aaaab14f6ef]
[dd4] [ 5] /QMcodes/jdftx-master/build/libjdftx_gpu.so(_ZN10Everything5setupEv+0xb51)[0x2aaaab10fe21]
[dd4] [ 6] /QMcodes/jdftx-master/build/jdftx_gpu(main+0x7ab)[0x40ab1b]
[dd4] [ 7] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2aaabd56d545]
[dd4] [ 8] /projects/QMcodes/jdftx-master/build/jdftx_gpu[0x40a2a9]
[dd4] *** End of error message ***

**Comment by shankar1729** [comment]
If you're still encountering this issue, try running through cuda-gdb. You may get a more useful error message from there.

Do you also get the same errors when running with a single GPU (without mpirun). (Just trying to eliminate mpi-gpu interface as an issue altogether.)

Finally, did you set CUDA_ARCH and CUDA_CODE in CMake to match the settings for your P100 GPUs? This should usually only be a performance issue if you use the old defaults, but worth a shot. (For P100, they should be compute_60 and sm_60 respectively.) See section GPU Support in http://jdftx.org/Customization.html

Please let me know if any of those work.

Best,
Shankar

**Comment by mef362** [comment]
Hi Shankar,

Actually, I got it to work a couple days ago. I was setting CUDA_ARCH and CUDA_CODE to 60 the whole time but also tried other things. I got it to work using gnu/7.3.1, openmpi-gnu/3.0 and cudatoolkit/9.2. Basically, I switched from intel/mkl to gnu and went to cudatoolkit/9.2 from 10.1. Not sure what the difference is but a colleague told me that intel compilers are notoriously problematic with GPUs (in his opinion).

I have another question, I was doing fixed-potential calculations (PBEsol, CANDLE (H2O, Na, F) ) on a metal surface OH terminated and I’m seeing a jump in charge at V-PZC (see image). I did the same calculation with just O on the surface and the results look fine. Any ideas?

Thanks,
Mike

[cid:image003.png@01D5D5BB.2B66DDA0]

**Comment by shankar1729** [comment]
Great to hear that. Yes, in general, Intel compilers also remained problematic with C++11 support long after the gnu ones, so we have consistently been working with gnu compilers.

The image didn't come through. I'm guessing this is CANDLE's charge asymmetry turning on at PZC. FOr the O, did you do the same absolute potential range, or the same range relative to its PZC?

Shankar

**Comment by mef362** [comment]
I guess the figure can’t be imbedded in an email.  I did the same range relative to its PZC in both cases. Does it make more sense to use the PZC of the metal surface itself (no O or OH)?

**Comment by mef362** [comment]
![Picture1](https://user-images.githubusercontent.com/59264959/73272669-bf6f1880-41b0-11ea-9df4-805a1e25d0ec.png)

**Comment by shankar1729** [comment]
Yes, this must be the asymmetry correction. We now think that CANDLE is too abrupt with the asymmetry and there needs to be a more physical parametrization for the switch. We are working towards a potential CANDLE2 in 2020.

I think comparing on the absolute potential range of interest for the experiment would make more sense, especially if you are comparing different surfaces. During the model development though, we focus on V-PZC as we care about the changing behavior with surface charge more than energetics at an absolute potential.

Best,
Shankar

**Comment by mef362** [comment]
Thanks
