### ISSUE TITLE
ionic dynamics

### ISSUE THREAD

**Issue by Masssnet** [shankar1729/jdftx#109]
Dear Dr,
 I am going to simulate an explicit water-Pt interface system, and I am confused about the parameters "kT" and "alpha‘’ in ：
ionic-dynamics <time-step> <total-time> [<kT>=0.001] [<alpha>=0.0]
what are their meanings and how can I get the value of my simulated system?

Beside, I am wondering if the dipole correction can be added in JDFTx simulation.

Thanks a lot !
Best regards !

**Comment by mef362** [comment]
kT is simply the temperature of the simulation, this is up to you. The purpose of alpha is clearly stated in the manual; however, I'm not sure what the units are, maybe time (fs). Likely if you run a short simulation you can figure it out.

**Comment by shankar1729** [comment]
Thanks @mef362 for the input. Indeed, kT is temperature and alpha is a scale factor for a velocity rescaling thermostat. Roughly speaking, 1/alpha will be the number of time steps over which temperature is equilibriated. Make sure alpha << 1.

The ion dynamics code in JDFTx in general needs to be revamped; it has not been used in production calculations so far. We will make the documentation more extensive when we do this as well.

Best,
Shankar

**Comment by Masssnet** [comment]
> kT is simply the temperature of the simulation, this is up to you. The purpose of alpha is clearly stated in the manual; however, I'm not sure what the units are, maybe time (fs). Likely if you run a short simulation you can figure it out.

Ok, thanks a lot !

**Comment by Masssnet** [comment]
> Thanks @mef362 for the input. Indeed, kT is temperature and alpha is a scale factor for a velocity rescaling thermostat. Roughly speaking, 1/alpha will be the number of time steps over which temperature is equilibriated. Make sure alpha << 1.
> 
> The ion dynamics code in JDFTx in general needs to be revamped; it has not been used in production calculations so far. We will make the documentation more extensive when we do this as well.
> 
> Best,
> Shankar

Ok, thanks a lot !

**Comment by Masssnet** [comment]
Dear Dr.
I have two problems for ionic-dynamics simulation.

1, the calculation was stoped at "ElecMinimize: Iter: 100  G: -4721.164317607104749  |grad|_K:  4.283e-06  alpha:  2.319e-01  linmin: -1.262e-04  t[s]: 162626.71" , or stoped at "ElecMinimize: Converged (|Delta G|<1.000000e-08 for 2 iters)." 
**It seems that the task terminated at the default value of electronic-minimize, not the time I set in "ionic-dynamics 1.0 100 0.03 0.2"; I was wondering if I missed some other important parameters** ?

2, **how to understand the negtive value of time in output file** "ElecMinimize: Iter:  89  G: -4721.050098535649340  |grad|_K:  3.484e-05  alpha:  1.434e-02  linmin: -5.780e-06  t[s]: -2010219.19"

I’m looking forward to your insights, thanks a lot !
Best regards !

My input file is attached below:

ion-species /public/home/users/shtu004/jdftx-1.4.2/build/pseudopotentials/GBRV/$ID_pbe.uspp                         
elec-cutoff 15 100                       
elec-ex-corr gga-PBE
#--- Geometry ---                                                         
lattice \
    20.9331 0 0 \
    0 20.9331 0 \
    0 0 75.5890

coulomb-interaction Slab 001     #Make z nonperiodic
coulomb-truncation-embed 0 0 0   #Specify center
symmetries none
coords-type Lattice              #fractional coordinates
ion Pt 0.99416 0.74556 0.14809 1
ion Pt 0.98950 0.73831 0.04523 0
ion Pt 0.98883 0.49623 0.14493 1
( omitting more atom positions)

ionic-dynamics 1.0 100 0.03 0.2

#--- Electronic ---
kpoint-folding 1 1 1
elec-smearing Fermi 0.03
target-mu -0.163

#--- Fluid ---
fluid LinearPCM
pcm-variant CANDLE
fluid-solvent H2O
fluid-cation Na+ 1.
fluid-anion F- 1.

#--- Outputs ---
dump Ionic IonicPositions ElecDensity BoundCharge
dump-name H-br-0.$VAR

**Comment by shankar1729** [comment]
1. The termination you point to is the electronic convergence, which is independent from the ionic dynamics. Within each step of the ionic dynamics, you have to specify how to converge the electronic wavefunctions. (Note this is Born-Oppenheimer MD, and not Car-Parinello MD, if that is your confusion.)

2. That seems to be a transient bug due to some overflow in the clock() counter on your system. It should not show up again if you reran the calculation. Also, note that the t[s] value you are looking at is the CPU time in seconds since start of the simulation, and does not correspond to the simulated (physical) MD time.

Best,
Shankar

**Comment by Masssnet** [comment]
> 1. The termination you point to is the electronic convergence, which is independent from the ionic dynamics. Within each step of the ionic dynamics, you have to specify how to converge the electronic wavefunctions. (Note this is Born-Oppenheimer MD, and not Car-Parinello MD, if that is your confusion.)
> 2. That seems to be a transient bug due to some overflow in the clock() counter on your system. It should not show up again if you reran the calculation. Also, note that the t[s] value you are looking at is the CPU time in seconds since start of the simulation, and does not correspond to the simulated (physical) MD time.
> 
> Best,
> Shankar

Thanks! I will try it.

**Comment by shankar1729** [comment]
Note that the ionic dynamics code has been substantially revamped over the past few months (on git head; not yet a numbered release). It now has full NVT and NPT support using both Berendsen and Nose-Hoover chain thermo/barostats. See http://jdftx.org/CommandIonicDynamics.html for a documentation of the rewritten ionic-dynamics module, which should hopefully be self-explanatory.

Best,
Shankar
