### ISSUE TITLE
Compilation OK, but test fail 4 systems

### ISSUE THREAD

**Issue by hezhengda** [shankar1729/jdftx#11]
Hi,
I've successfully compiled JDFTx on my server.
But when I run "make test", after the running, I got this:
![image](https://user-images.githubusercontent.com/26743576/29709397-bdb66432-89be-11e7-84b4-c300e3cd2a45.png)
The running time is reasonable for successful tasks, but I don't know why other 4 tasks (3, 4, 9, 10) are wrong.
Could you help me clarify?
Thanks,
Best,
Zhengda

**Comment by shankar1729** [comment]
Could you please send all the output files of the test calculations?  (From within the build directory, you can do "tar cjf tests.tbz2 test/*/*.out")

Also please specify the system and libraries you are compiling with.  You could also just attach the CMakeCache.txt; that will contain most of this info.

Shankar

**Comment by hezhengda** [comment]
Hi,

Thanks for your reply.

I attach the files you asked for in here:
[tests.zip](https://github.com/shankar1729/jdftx/files/1253408/tests.zip)
[CMakeCache.txt](https://github.com/shankar1729/jdftx/files/1253407/CMakeCache.txt)

Because there are too many parameters about library paths, so I attach the Cache file instead.

Hope these will be helpful.

Thanks,

Zhengda

**Comment by shankar1729** [comment]
Hi Zhengda,

The tests that failed seem to be exactly those that invoke MPI I/O calls for writing state (invoked even if only using a single process when compiled with MPI).  Others have recently reported issues when using Intel MPI.  Can you try using OpenMPI or MPICH2 instead?

Shankar

PS: You can also check that this is the issue by compiling without MPI (-D EnableMPI=no).

**Comment by hezhengda** [comment]
Hi, Shankar,
Thanks very much for your advice. I've tried to compile the software without MPI, and it works fine! Every job is passed. 
But When I want to compile JDFTx by using MPI (OpenMPI), then I encounter the same error everytime:
`[ 19%] Building CXX object CMakeFiles/jdftxlib.dir/fluid/ConvCoupling.cpp.o
In file included from /home/chp/jameshzd/JDFTx/jdftx-1.3.1/jdftx/core/Util.cpp:20:0:
/home/chp/jameshzd/JDFTx/jdftx-1.3.1/jdftx/core/Util.cpp: In function ‘void printVersionBanner()’:
/home/chp/jameshzd/JDFTx/jdftx-1.3.1/jdftx/core/Util.cpp:39:51: error: expected ‘)’ before ‘VERSION_MAJOR_MINOR_PATCH’
 { logPrintf("\n*************** " PACKAGE_NAME " " VERSION_MAJOR_MINOR_PATCH
                                                   ^
/home/chp/jameshzd/JDFTx/jdftx-1.3.1/jdftx/core/Util.h:112:43: note: in definition of macro ‘logPrintf’
 #define logPrintf(...) fprintf(globalLog, __VA_ARGS__) //!< printf() for log files
                                           ^
/home/chp/jameshzd/JDFTx/jdftx-1.3.1/jdftx/core/Util.cpp:41:11: error: ‘VERSION_HASH’ was not declared in this scope
   (strlen(VERSION_HASH) ? "(git hash " VERSION_HASH ")" : ""));
           ^
/home/chp/jameshzd/JDFTx/jdftx-1.3.1/jdftx/core/Util.h:112:43: note: in definition of macro ‘logPrintf’
 #define logPrintf(...) fprintf(globalLog, __VA_ARGS__) //!< printf() for log files
                                           ^
/home/chp/jameshzd/JDFTx/jdftx-1.3.1/jdftx/core/Util.cpp:41:40: error: expected ‘:’ before ‘VERSION_HASH’
   (strlen(VERSION_HASH) ? "(git hash " VERSION_HASH ")" : ""));
                                        ^
/home/chp/jameshzd/JDFTx/jdftx-1.3.1/jdftx/core/Util.h:112:43: note: in definition of macro ‘logPrintf’
 #define logPrintf(...) fprintf(globalLog, __VA_ARGS__) //!< printf() for log files
                                           ^
/home/chp/jameshzd/JDFTx/jdftx-1.3.1/jdftx/core/Util.cpp:41:53: error: expected ‘)’ before string constant
   (strlen(VERSION_HASH) ? "(git hash " VERSION_HASH ")" : ""));
                                                     ^
/home/chp/jameshzd/JDFTx/jdftx-1.3.1/jdftx/core/Util.h:112:43: note: in definition of macro ‘logPrintf’
 #define logPrintf(...) fprintf(globalLog, __VA_ARGS__) //!< printf() for log files
                                           ^
make[2]: *** [CMakeFiles/jdftxlib.dir/core/Util.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/jdftxlib.dir/all] Error 2
make: *** [all] Error 2
`

I've tried several methods:
(1) change intel-mpi to gcc-mpi
(2) add -std=c++0x into each compiler configuration
but they didn't help.

The command I used to compile is:
`CC="/opt/openmpi/2.0.0_gcc-4.9.2/bin/mpicc -fPIC -std=c++0x" FC=/opt/openmpi/2.0.0_gcc-4.9.2/bin/mpif90 CXX="/opt/openmpi/2.0.0_gcc-4.9.2/bin/mpicxx -fPIC -std=c++0x" cmake -D GSL_PATH=/home/chp/jameshzd/gsl-2.4 ../jdftx-1.3.1/jdftx`

I attach my CMakeCache.txt in here: 
[CMakeCache.txt](https://github.com/shankar1729/jdftx/files/1259807/CMakeCache.txt)

I'm deeply appreciated if you could help me resolve this problem.

Thanks for your kind help.

Best Regards,
Zhengda

**Comment by shankar1729** [comment]
Did you clean out the build directory completely between the no mpi and
open mpi compilation attempts? That's a very strange error indeed,
completely unrelated to mpi, and not even relying on any c++11 features.

Shankar

**Comment by hezhengda** [comment]
Yes, I've deleted the folder (build) that I created. Then re-mkdir another folder to compile with MPI. The mistake is always there.

**Comment by shankar1729** [comment]
Could you please paste the contents of config.h from the build directory?

Shankar

**Comment by hezhengda** [comment]
`/*-------------------------------------------------------------------
Copyright 2011 Ravishankar Sundararaman

This file is part of JDFTx.

JDFTx is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

JDFTx is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with JDFTx.  If not, see <http://www.gnu.org/licenses/>.
-------------------------------------------------------------------*/

#ifndef JDFTX_CONFIG_H
#define JDFTX_CONFIG_H

//Configuration definitions processed by Cmake
//	Do not edit config.h, it is generated by Cmake
//	Edit config.in.h instead

#define PACKAGE_NAME "JDFTx"
#define PACKAGE_DESCRIPTION "The playground for joint density functional theory"
#define PACKAGE_SUMMARY "Toolkit for rapid development of density-functional methods"
#define VERSION_MAJOR_MINOR_PATCH "1.3.1"
#define VERSION_HASH ""
#define JDFTX_BUILD_DIR "/home/chp/jameshzd/JDFTx/build"

#endif // JDFTX_CONFIG_H`

**Comment by shankar1729** [comment]
I'm not sure why this is happening only for this build configuration as everything so far looks fine.  Can you try commenting out the offending line in util.cpp (and similar version info print lines in few other places where they appear, if you get other similar errors)?
