### ISSUE TITLE
memory consumption of calculation

### ISSUE THREAD

**Issue by shk11** [shankar1729/jdftx#110]
Hello shankar1729,

I tried to run some jDFTx calculation for a lithium metal surface. However, I observed a huge memory consumption for this calculation on the cluster. Attached you can find an example of my investigated system:
[jDFTx_example.zip](https://github.com/shankar1729/jdftx/files/4142409/jDFTx_example.zip)
We used 16 cores for this calculation and the cluster reported us a memory consumption of mem=116231080kb and vmem=123134504kb. 
The calculation was performed with jDFTx 1.5.0 compiled with Intel® Parallel Studio XE 2017 (Intel MKL 2017, Intel MPI 2017, Intel Compiler 2017) and GSL 2.5 (compiled with the same Intel Suite).
If you calculate this system size with other DFT codes (e.g. VASP, Seqquest, Quantum Espresso, ...) the memory requirement is less than 50 GB. 
Are these memory values normal for jDFTx 1.5.0 or do I have a memory leak in my compiled version of jDFTx?

Best wishes,
Dan

**Comment by shankar1729** [comment]
Hi Dan,

Could you please post the log file of the calculation as well? Preferably with EnableProfiling=yes selected during the compilation of the executable.

Best,
Shankar

**Comment by shk11** [comment]
Thank you for your fast reply. Attached you will find the log file of the calculation. Further, I will rerun the calculation with EnableProfiling=yes and send it to you as soon as the calculation is finished.
[output.txt](https://github.com/shankar1729/jdftx/files/4142483/output.txt) 
Best,
Dan

**Comment by shankar1729** [comment]
Hi Dan,

If you are running this on a dual socket 16 core machine (as the output suggests): run it with 2 processes and 8 threads each, rather than 16 processes. That is, something like "mpirun --bind-to none -n 2 jdftx -c8 ..." directly with openMPI, or using "-n 2 -c 8" in SLURM.

That invocation will use much less memory and also be substantially faster due to the aggressive thread parallelization in jdftx. See the notes at the end of http://jdftx.org/GettingStarted.html for more details.

Best,
Shankar

**Comment by shk11** [comment]
Hi Shankar,

Sorry for my late response. Unfortunately, our cluster is quite busy right now. However, I will run some test calculations with a reduced number of processes and an increased number of threats as soon as possible. Thank you for your help!

Best,
Dan

**Comment by shk11** [comment]
Hi Shankar,

the memory consumption of the calculation decreased drastically:
[output.txt](https://github.com/shankar1729/jdftx/files/4204698/output.txt)
Thank you a lot!

Just out of interest: Are there any further possibilities (besides the tag "exchange-block-size") to improve the memory usage of the calculation?

Best wishes,
Dan

**Comment by shankar1729** [comment]
Great to hear that, and no, not at the moment.

Best,
Shankar
