### ISSUE TITLE
isnan-related compiling errors

### ISSUE THREAD

**Issue by ciccarino** [shankar1729/jdftx#111]
Hello Shankar,

I hope you are doing well! 

Recently I've pulled the latest commits and found that recompiling was giving me trouble. I believe it is because some of the `isnan` calls do not have the `std::` prefix. I've tried adding the prefix to the following files/line numbers and the compiling no longer complains:

jdftx/commands/ion.cpp: line 132
jdftx/electronic/IonicDynamics.cpp: line 44, line 140
jdftx/electronic/SpeciesInfo.cpp: line 262

Could this be verified? Thanks very much! 

Regards,
Chris

**Comment by shankar1729** [comment]
Hi Chris,

Indeed, those should be std::isnan. Some gcc versions seem to be accepting it without the std.I have pushed a commit to fix this now. Thanks for catching these errors! 

Best,
Shankar
