### ISSUE TITLE
Scripts problem

### ISSUE THREAD

**Issue by Lly-THU** [shankar1729/jdftx#112]
Dear Dr. Shankar,
when I followed the tutorial of **Setting up molecule geometries ** and used the script xyzToIonposOpt from the JDFTx scripts directory to convert the water.xyz to JDFTx input files (water.ionpos and  water.lattice), I unfortunately encountered the following errors:

```
[haixiao6@ln1%bscc-d water-3]$  xyzToIonposOpt water.xyz 15
initialVolume =  4341.4
error: fun(0): subscripts must be either integers 1 to (2^63)-1 or logicals
error: called from
    fminsearch>nmsmax at line 275 column 8
    fminsearch at line 165 column 25
    .tmp.m at line 42 column 8
```
I don't know why this happen and how to solve it, could you give me some suggestions? 
Thanks!

**Comment by shankar1729** [comment]
This could be due to the optimization pacage in octave being missing. What OS are you using and what is your octave version?

Best,
Shankar

**Comment by Lly-THU** [comment]
I'm using Cent OS Linux,  and the octave version is 5.2.0. 
So you mean this error is caused by my octave?   but what should I do? 
Thanks!

**Comment by Lly-THU** [comment]
I have solved this error by changing my octave version to 4.2.0.
Thanks!

**Comment by shankar1729** [comment]
Glad to hear that!
