### ISSUE TITLE
ionic optimization for adsorption system

### ISSUE THREAD

**Issue by Liuly98** [shankar1729/jdftx#114]
Hi Shankar
I am trying to run ionic optimization for H atom adsorbed on a Pt 111 slab surface,but always end up failing with this error: Atom 17 lies within the margin of 5 bohrs from the truncation boundary.
Expand unit cell, or if absolutely sure, reduce coulomb-truncation-ion-margin
I think this is because I set " coulomb-truncatoin-embed 0 0 0" in the common.in
(when i do ionic optimization for bare Pt111 slab surface without H atom  just like in the VASP, " coulomb-truncatoin-embed 0 0 0" is OK, no problem happened.) 
my system.ionpos (I get it by converting VASP POSCAR into ionpos file and the unit problem has been considered ) is:

# Ionic positions in lattice coordinates:
ion Pt  -0.000000000062500  -0.000000001500000   0.000000000000000 0
ion Pt  -0.000000000062500   0.499999998500000   0.000000000000000 0
ion Pt   0.499999999937500  -0.000000001500000   0.000000000000000 0
ion Pt   0.499999999937500   0.499999998500000   0.000000000000000 0
ion Pt   0.333333333270833   0.166666665166667   0.104720000000000 0
ion Pt   0.333333333270833   0.666666665166667   0.104720000000000 0
ion Pt   0.833333333270833   0.166666665166667   0.104720000000000 0
ion Pt   0.833333333270833   0.666666665166667   0.104720000000000 0
ion Pt   0.166666666604167   0.333333331833333   0.206069870770766 0
ion Pt   0.166666666604167   0.833333331833333   0.206069870770766 0
ion Pt   0.666666666604167   0.333333331833333   0.206069870770766 0
ion Pt   0.666666666604167   0.833333331833333   0.206069870770766 0
ion Pt  -0.000000000062500  -0.000000001500000   0.308398910700304 0
ion Pt  -0.000000000062500   0.499999998500000   0.308398910700304 0
ion Pt   0.499999999937500  -0.000000001500000   0.308398910700304 0
ion Pt   0.499999999937500   0.499999998500000   0.308398910700304 0
ion H    0.499999999937500   0.499999998500000   0.367837264000000 1

I still feel confused about this problem after I see your answers in other questions, and just don't know how to set "coulomb-truncatoin-embed  (?)  (?)  (?)" correctly, does the "center" in the coulomb-truncatoin-embed mean the center of the slab? 
I'm looking forward to your suggestions!
Thanks!

**Comment by shankar1729** [comment]
Yes, set the center approximately to the geometric center of your system along the truncated directions eg. ~ 0 0 0.18 in your example above. Note that the values along the periodic directions are irrelevant.

It does not have to be exactly centered. The logic is that the unit cell is sliced to break periodicity centered on this position. So if you left the center at zero, then you have a lot of room on the lower side (0.5 Lz), but very little on the upper side (~ 0.13 Lz). You must have had 0.13 Lz < 5 bohrs leading to the error. Once you center it, you will have margins symmetrically of approximately 0.31 Lz on both sides which should be comfortably larger than 5 bohrs. (Here Lz is the length of the unit cell along the truncated direction.)

Best,
Shankar

**Comment by jiangkaijiangkai** [comment]
Dear Shankar,
I got a similar problem when I calculated the no3 molecule.  The calculation always ended up with the error:**"
Atom 1 lies within the margin of 5 bohrs from the truncation boundary.
Expand unit cell, or if absolutely sure, reduce coulomb-truncation-ion-margin.
Failed."**
I have looked through the issues about this situation, then I tried to adjust the parameters of "coulomb-truncation-embed". Although I picked up the center location in fractional coordinates of the third direction, like 0 0 0.15, it still failed. More parameters of  "coulomb-truncation-embed" were also tested, and all the calculations ended up with the same error. It is my first time doing my own calculation after finishing the tutorials on Molecules, are all input files appropriate?  (I converted the no3 POSCAR in vasp to the lattice and ionpos formate in JDFTx, and  the  coords-type is lattice.) I have attached the output files below. 
Thanks!
Kai
[output-test-0.12-0.18.file.txt](https://github.com/shankar1729/jdftx/files/9834919/output-test-0.12-0.18.file.txt)
[output-test-0.1-0.9.file.txt](https://github.com/shankar1729/jdftx/files/9834920/output-test-0.1-0.9.file.txt)

**Comment by shankar1729** [comment]
You seem to be using `coulomb-interaction Isolated` here to capture a molecular geometry, but are only specifying the center along the third direction, which is the only ones that matter if you are using a Slab geometry as in the original issue above.

If you want to do the molecule correctly, you need to specify the center correctly in all three directions, because you are truncating all three directions. Your example probably needs something close to `coulomb-truncation-embed 0.5 0.5 0.15`.

Best,
Shankar
