### ISSUE TITLE
Tutorial on Oxide surfaces

### ISSUE THREAD

**Issue by khyeoh** [shankar1729/jdftx#115]
Dear Dr Shankar,

I am trying the tutorial on the Oxide surfaces in the jDFTx website. In the python script that extracts the potentials, there is a line S = [ 56, 28, 160 ] which labelled as Sample Count. May I know what is Sample Count and how do we set those values?

Thanks
Yeoh

**Comment by shankar1729** [comment]
Hi Yeoh,

Sample count is the dimensions of the fourier transform grid, labeled fftbox in the initialization portion of the jdftx log.

Best,
Shankar

**Comment by khyeoh** [comment]
Dear Dr Shankar,

If I were to modify the oxide surface tutorial to read the ElecDensity, for example by modifying one of the line to: 

**dump End ElecDensity**

By adopting the python script in the tutorial, what will be the unit of the ElecDensity per grid point? Is it <_number of electron_> / bohr^3 or Coulomb/bohr^3 ?

Thanks
Yeoh

**Comment by shankar1729** [comment]
The _electron density_ output is in number of electrons / bohr^3.

Best,
Shankar
