### ISSUE TITLE
Relaxation of Graphene

### ISSUE THREAD

**Issue by khyeoh** [shankar1729/jdftx#116]
Dear Dr Shankar,

I tried to relax the graphene structure by using the ion position and lattice parameter given in the tutorial. I am trying to relax the ionic position and lattice parameter with the input script as attached:

lattice Hexagonal 4.651 15
ion C   0.000000000000000   0.00000000000000    0.000000000000000 1
ion C   0.333333333333333  -0.33333333333333    0.000000000000000 1
coulomb-interaction Slab 001
coulomb-truncation-embed 0 0 0 
kpoint-folding 18 18 1
ion-species ./c_pbe_v1.2.uspp 
elec-cutoff 25 200
elec-smearing Fermi 0.01
electronic-SCF                   #Electronic state optimization
latt-move-scale 1 1 0
lattice-minimize  \
 dirUpdateScheme L-BFGS \
 nIterations 100
dump-name c.$VAR
dump Ionic State                 #Output state every geometry (ionic/lattice) step

After the relaxation, the graphene structure is distorted. I have attached the output of the  file  ion position and cell parameter  here. 

I have tried different relaxation scheme other than L-BFGS but it gave the same result.

[c.ionpos.txt](https://github.com/shankar1729/jdftx/files/4572724/c.ionpos.txt)
[c.lattice.txt](https://github.com/shankar1729/jdftx/files/4572725/c.lattice.txt)
[latticeOpt.out.txt](https://github.com/shankar1729/jdftx/files/4572726/latticeOpt.out.txt)

Did I miss out something? Hope you can give me some advice.

Thanks

**Comment by shankar1729** [comment]
The output structure seems fine and only marginally changed from the input structure: 0.1% strain and no change of internal coordinates. 

Are you perhaps misreading the final lattice in converting and visualizing? Remember that jdftx lattice vectors are in columns indicating that is a matrix of basis vectors, unlike say VASP.

Best,
Shankar

**Comment by khyeoh** [comment]
Dear Dr Shankar,

Thanks! You are right. I forgot that the jdftx lattice vectors are in columns instead of rows.
Thank you so much.

Yeoh
