### ISSUE TITLE
Errors with R-3m structure

### ISSUE THREAD

**Issue by Yaxian0516** [shankar1729/jdftx#118]
Dear Shankar,

I have been running into some issues when calculating phonons with R-3m structure as the following. 
`/path-to-jdftx/jdftx-1.5.0/jdftx/electronic/ColumnBundleTransform.cpp:64: ColumnBundleTransform:
        Assertion '*std::min_element(index.begin(), index.end()) >= 0' failed---`

There are 12 symmetries found, as expected, so could you please point out what can cause such errors? I copied the .lattice and .ionpos here, and I used the fully relativistic Optimized Norm-Conserving Vanderbilt (ONCV) pseudopotentials for spin-orbit coupling calculation.
#lattice \
          11.496496673686419   10.272596963966738   10.272596318790315  \
           0.019862178274213    5.161715467279558    2.445176959316493  \
           0.011900740471432    0.011900186170055    4.545877806195309 #Note: latt-scale has been absorbed into these lattice vectors.
# Ionic positions in lattice coordinates:
ion Pd   0.000000002000000   0.000000002000000   0.000000002000000 1
ion Co   0.500000002000000   0.500000002000000   0.500000002000000 1
ion O   0.887549145813834   0.887549146274165   0.887549145075580 1
ion O   0.112450858186166   0.112450857725835   0.112450858924420 1

Best,
Yaxian Wang

**Comment by shankar1729** [comment]
Did you read in the wave functions of the unit cell calculation into the phonon one? That's the usual cause of this error.

(I do need to add a check for this and put in a more meaningful error message.)

Best,
Shankar

**Comment by Yaxian0516** [comment]
Shankar,
Thanks for your reply!
I did start from `initial-states`. However, I just tried to comment this line and to start from `/$VAR/fillings` and still got the same error.

Thanks,
Yaxian

**Comment by shankar1729** [comment]
Hi Yaxian,

Please post your phonon output file: I'll check for other problems.

Starting from fillings alone is not enough; you need the fillings and wavefunctions (wfns) file to be read in.

Best,
Shankar

**Comment by shankar1729** [comment]
Also, I just added a check for uninitialized wavefunction in phonon in commit [5d7b781](https://github.com/shankar1729/jdftx/commit/5d7b781c3c6f02e26975ba43d26366dfab073975). Try running with the updated code.

Best,
Shankar

**Comment by Yaxian0516** [comment]
Hi Shankar,

Thanks very much for your help! I tried using the new code with 1. `initial-state /$VAR/wfns` and 2. `initial-state totalE.$VAR` to calculate the first perturbation I obtained from the dry run without issue. I attached the phonon output files for them, named `phonon.1.out` and `phonon.2.out`.
The rest of `phonon.in` looks like the following:
`#Save the following to phonon.in`
`include totalE.in          #Full specification of the unit cell calculation`
`#initial-state /$VAR/wfns`
`initial-state totalE.$VAR  #Start from converged unit cell state`
`dump-only                  #Don't reconverge unit cell state`
`phonon supercell 2 2 2  ${phononParams}     #Calculate force matrix in a 2x2x2 supercell`
`dump end forces`

Best,
Yaxian


[phonon_out.zip](https://github.com/shankar1729/jdftx/files/4663477/phonon_out.zip)

**Comment by shankar1729** [comment]
Great to hear that: glad it worked out!

**Comment by Yaxian0516** [comment]
Hi Shankar,

Sorry for not being clear enough, but I did not get the expected results still. `phonon.2.out` has the error same as before in `ColumnBundleTransform` and `phonon.1.out` said `Electronic state required for dump-only mode has not been read in (using initial-state or wavefunction).`
Somehow the `phonon` still does not work for me.
Yaxian

**Comment by shankar1729** [comment]
The initial-state command was different between the two perturbations: it was pointing to the correct path in phonon.1.out  but not in phonon.2.out. So check your input files / job scripts to see where the error lies. (I thought you had sent me a right and wrong example for comparison.)

Best,
Shankar

**Comment by Yaxian0516** [comment]
Hi Shankar,
I did try to use different initial-state but neither of them worked for me. 

`phonon.1.out` was obtained with `initial-state /$VAR/wfns` and the error with phonon run was
`Electronic state required for dump-only mode has not been read in (using initial-state or wavefunction).`

`phonon.2.out` was obtained with `initial-state totalE.$VAR` and the error with phonon run was
`/n/home04/yaxianw/util/test_JDFTx/jdftx-1.5.0/jdftx/electronic/ColumnBundleTransform.cpp:64: ColumnBundleTransform:
        Assertion '*std::min_element(index.begin(), index.end()) >= 0' failed`
I ran both with the same output from a `totalE` calculation. I just reran the `jdftx_gpu` job with the new code and got the same results. So I attached the two most recent `phonon.1/2.out` here.

[phonon_out.zip](https://github.com/shankar1729/jdftx/files/4665530/phonon_out.zip)

Best,
Yaxian

**Comment by shankar1729** [comment]
So it should definitely be totalE.$VAR for initial-state.

I'm a little confused about phonon.2out: the file you attached seems to go past the stage where the ColumnBundleTransform assertion was happening previously. Also the output file does not have that error: was the error in a different output stream captured in your slurm output?

**Comment by Yaxian0516** [comment]
Yes, it is in another log file from slurm output.

/n/home04/yaxianw/util/test_JDFTx/jdftx-1.5.0/jdftx/electronic/ColumnBundleTransform.cpp:64: ColumnBundleTransform:
        Assertion '*std::min_element(index.begin(), index.end()) >= 0' failed--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 2 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

**Comment by shankar1729** [comment]
Hi Yaxian,

This error stems from a marginal symmetry corner case which is causing a particular wave in the PW basis to be included within Ecut in one k, but not in the corresponding k after a space group operation. The error you got is a conservative check to make sure that all k's map on to each other in the supercell transformation.

The fix is simple: make the symmetries exact in the lattice specification. For example your geometry can be made exactly symmetric as:

```
lattice Rhombohedral 11.4965182988212 26.5794011462639

ion Pd   0.00000000  0.00000000   0.00000000 1
ion Co   0.50000000  0.50000000   0.50000000 1
ion O   0.887549146  0.887549146  0.887549146 1
ion O   0.112450854  0.112450854  0.112450854 1
```

That removes the error.

Best,
Shankar
