### ISSUE TITLE
Estimating run time and memory in parallel running 

### ISSUE THREAD

**Issue by goudarzi58** [shankar1729/jdftx#120]
Hi Shankar,
I'm trying to run JDFtx calculations for Gold and with 128 k-points in parallel. The calculation was done using version 1.4.2 using 5 CPU with two 2.4GHz Intel Xeon E5-2680 v4 fourteen-core processors. However, such a calculation for the Total Energy took 16 days without any results; the program stops at 
>> Dumping 'totalE.fillings' ...

Then, I  changed executing the script from  'mpirun' to 'mpirun --bind-to none' as you mentioned in **shankar1729/jdftx/Issue#110** . But that did not reduce the time and I am still facing the same problem. 
 My question is that how it is possible to calculate the total time and the required memory for executing such JDFtx calculations. I share the input files below in case you want to take a look at them.

Best regards,
Abbas
``
[inputs.txt](https://github.com/shankar1729/jdftx/files/4639372/inputs.txt)
[slurm.txt](https://github.com/shankar1729/jdftx/files/4639381/slurm.txt)

**Comment by shankar1729** [comment]
Hi Abbas,

Please post your output file as well: that time sounds unreasonable for a bulk calculation, even with that many k-points. 

Did the calculation get to the output stage relatively quickly and then hang at the fillings output? That may indicate some sort of crash, perhaps in the final MPI I/O or the mpi communication prior to I/O (depending on whether you compiled with MPISafeWrite = yes or no).

Best,
Shankar

**Comment by goudarzi58** [comment]
Hi Shankar,
I posted the output file below. It took almost 36 hrs for the calculation to get to the output stage. Also, the calculation for 32-k points took 19 hrs. However, it's good to know that time is much longer than what it should be and the JDFTx code doesn't work normally. I will check with the High-Performance Computer guys in our university about the installation and post the results here. 

Regards
Abbas
[totalE_out.txt](https://github.com/shankar1729/jdftx/files/4651238/totalE_out.txt)

**Comment by shankar1729** [comment]
The problem is with your job submission script. You seem to be using only one node based on the start of the output, and have massively oversubscribed it by running 640 threads on it.

I would suggest a much simpler job configuration for this case which has several k-points and a small system size. Just use MPI without threads for this case. So if you wanted to use 5 nodes with 28 cores each, instead try:

```bash
#SBATCH -n 140 -c 1 ...
mpirun jdftx <inFile>
```

If your slurm and mpirun are properly configured, mpirun should get the number of processes automatically and jdftx wil lfetch the -c from teh automatic environment variables automatically.

Best,
Shankar

**Comment by goudarzi58** [comment]
Shankar,

Sorry for the late update. I did the change in slurm-job script performed multiple runs for 12, 16, 32, 64, and 128 k-folding using a proper number of nodes. Only 12 and 16 k-foldings were completed and the others with more that one node went through an error: Dumping 'totalE.fillings' ... Error opening file 'totalE.fillings' for writing.
The output files for 16 and 128 k-foldings are attached. What could cause such an error?

Best
Abbas
[TotalE_out_16.txt](https://github.com/shankar1729/jdftx/files/4661198/TotalE_out_16.txt)
[TotalE_out_128.txt](https://github.com/shankar1729/jdftx/files/4661199/TotalE_out_128.txt)

**Comment by shankar1729** [comment]
This seems to be an MPI I/O problem then: your cluster + this MPI doesn't seem to support writing in parallel from multiple nodes to this file system. A workaround is to recompile JDFTx with MPISafeWrite=yes. In this mode, JDFTx will transfer all the data to head node and write from there, bypassing MPI I/O: maybe a bit slower in the output, but should be much more stable.

Best,
Shankar

**Comment by goudarzi58** [comment]
Thank you for the clarification!
