### ISSUE TITLE
How to calculate the Bader charge with JDFTx ?

### ISSUE THREAD

**Issue by 20190111** [shankar1729/jdftx#123]
Dear Shankar,
I want to calculate the Bader Charge after the fix-potential calculations and I had installed octave5.2 in my CentOS7.7. I had read the script createVASP , but I still don't know how to use it. I have try the command" createVASP charge.out vasp " but got "error: fread: invalid stream number = -1
error: called from  createVASP.tmp/process.m at line 21 column 4 ". 
Could you please help me to carry out the Bader Charge calculation after the fix-potential calculation ?

Best
Anna

**Comment by shankar1729** [comment]
Hi Anna,

Did you dump ElecDensity in that calculation? createVASP reads in the electron density from the JDFTx ".n" file and converts it into a vasp charge file.

Best,
Shankar

**Comment by 20190111** [comment]
Hi  Shankar,
I have got the .n , .nbound, .wfns, ,ionpos and so on. I have tried the command "createVASP sol.n vasp", but still got the error information "error: dims(3): out of bound 2
error: called from  createVASP.tmp/process.m at line 5 column 12 "
What should I do next ?

Best 
Anna

**Comment by shankar1729** [comment]
Hi Anna,

I think you misunderstood: you need to have output the .n file, but you still run createVASP on the output file (charge.out) as you previously had. 

If that is still not working, try "createVASP charge.out vasp sol.n" instead, where you specify the path to the density file explicitly. Note that the first argument must always be the output file.

Best,
Shankar

**Comment by 20190111** [comment]
Hi Shankar，
Thank you very much, I can obtain the charge density file of vasp now. And I also want to ask how can I get the differential charge density after that fix-potential calculation ?  For example, I have the structure of OH adsorbed on Pt111(denoted as AB, A is OH, B is Pt111), firstly, I get the total charge density of AB(the AB.n file), what should I do next ?   
I need to calculate the charge density of A and B separately without optimizing the structure to get A.n and B.n, then the differential charge density can be obtained by AB.n-A.n-B.n, Am I right ？ Or do you have any other simpler method or script that can extract the differential charge density directly from the total electron density AB.n file ?

Best 
Anna

**Comment by abhiShandy** [comment]
I think you have to launch 2 more calculations with just Pt-111 and just OH.

**Comment by shankar1729** [comment]
Indeed, there is no short cut to that. Run two calculations with the surface and the OH in the same positions and lattice separately, and then subtract the densities. The density is just a flat binary array of double precision numbers, so you can just np.fromfile(), subtract and np.tofile() it in python.

Best,
Shankar

**Comment by RoshiniDantuluri** [comment]
Hi Anna, 
I am trying to find net charges for my system (via DDEC).  I got the CHGCAR using the createVASP command. Now I am trying to figure out a way to make AECCAR0 (core electron density) and AECCAR2 (valence electron density) files. I was hoping you could give some inputs on this. 
Thanks
