### ISSUE TITLE
wanniered band cannot converge

### ISSUE THREAD

**Issue by AmyJcc** [shankar1729/jdftx#127]
Hello,  Shankar,
    I am trying to calculate the wanniered band, but no matter how I adjust the energy range of the outer window, I still cannot get the wanniered band that coincides with the DFT band. Thus, I would like to know how to adjust to solve this problem?

  ###  **This is input file wannier.in :**
include totalE.in
wannier \
    innerWindow 0.42 1.0 \
    outerWindow 0.16 2.0

wannier-center Gaussian  0.287515  0.312143  0.674123
wannier-center Gaussian  0.041902  0.793725  0.823817
wannier-center Gaussian  0.823756  0.213080  0.398541
wannier-center Gaussian  0.718863  0.816706  0.779931
wannier-center Gaussian  0.320902  0.303873  0.343211
wannier-center Gaussian  0.341960  0.250893  0.542283
wannier-center Gaussian  0.911985  0.676534  0.447066
wannier-center Gaussian  0.387494  0.975585  0.986755
wannier-center Gaussian  0.116825  0.266518  0.605090
wannier-center Gaussian  0.503311  0.736503  0.745140
wannier-center Gaussian  0.619495  0.720969  0.466903
wannier-center Gaussian  0.905728  0.576525  0.050935
.........
 
 
wannier-initial-state totalE.$VAR
wannier-dump-name wannier.$VAR
wannier-minimize nIterations 800

**This is the end of wannier.out**

WannierMinimize: Converged (|Delta Omega|<1.000000e-08 for 2 iters).

Optimum spread:
	Omega:  7.015740594798078e+02
	OmegaI: 5.711827428766811e+02

Best,
AmyJcc

**Comment by shankar1729** [comment]
Hi AmyJcc,

Tweaking wannier windows and centers requires information and some chemical intuition about the system. Post the band ranges and the totalE.out to get some of this input.

Quick observation: why is the bottom end of the inner and outer windows not the same: are you trying to do an entangled-bands-style wannierization at the lower end as well? (That is possible, but usually not required and leads to unnecessary convergence problems.)

Best,
Shankar
