### ISSUE TITLE
createXSF script issue

### ISSUE THREAD

**Issue by panxiang126** [shankar1729/jdftx#129]
Dear Dr. Shankar,

I used the command `createXSF latticeOpt.out str-%d.xsf Frames` to extract all structures after the lattice optimization, but I find there are some differences of the lattice vector between the generated xsfFile and the jdftxOutFile, especially the final output structure (the 19th frames, vector-a: 4.59398 _vs_ 4.52786). Please see the table below for details:

Frames | Lattice from   jdftxOutFile (bohrs) |   |   |   | Lattice from   jdftxOutFile (ANG) |   |   |   | Lattice from xsfFile |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 |   |   |   |   |   |   |   |   |   |   |  
  | 8.68136 | 0.00000 | 0.00000 |   | 4.59400 | 0.00000 | 0.00000 |   | 4.59760 | 0.00000 | 0.00000
  | 0.00000 | 8.68136 | 0.00000 |   | 0.00000 | 4.59400 | 0.00000 |   | 0.00000 | 4.59760 | 0.00000
  | 0.00000 | 0.00000 | 5.59167 |   | 0.00000 | 0.00000 | 2.95900 |   | 0.00000 | 0.00000 | 2.97791
2 |   |   |   |   |   |   |   |   |   |   |  
  | 8.68820 | 0.00000 | 0.00000 |   | 4.59762 | 0.00000 | 0.00000 |   | 4.59893 | 0.00000 | 0.00000
  | 0.00000 | 8.68820 | 0.00000 |   | 0.00000 | 4.59762 | 0.00000 |   | 0.00000 | 4.59893 | 0.00000
  | 0.00000 | 0.00000 | 5.62744 |   | 0.00000 | 0.00000 | 2.97793 |   | 0.00000 | 0.00000 | 3.01927
3 |   |   |   |   |   |   |   |   |   |   |  
  | 8.69072 | 0.00000 | 0.00000 |   | 4.59896 | 0.00000 | 0.00000 |   | 4.58975 | 0.00000 | 0.00000
  | 0.00000 | 8.69072 | 0.00000 |   | 0.00000 | 4.59896 | 0.00000 |   | 0.00000 | 4.58975 | 0.00000
  | 0.00000 | 0.00000 | 5.70560 |   | 0.00000 | 0.00000 | 3.01929 |   | 0.00000 | 0.00000 | 3.04812
4 |   |   |   |   |   |   |   |   |   |   |  
  | 8.67337 | 0.00000 | 0.00000 |   | 4.58977 | 0.00000 | 0.00000 |   | 4.57411 | 0.00000 | 0.00000
  | 0.00000 | 8.67337 | 0.00000 |   | 0.00000 | 4.58977 | 0.00000 |   | 0.00000 | 4.57411 | 0.00000
  | 0.00000 | 0.00000 | 5.76011 |   | 0.00000 | 0.00000 | 3.04814 |   | 0.00000 | 0.00000 | 3.07948
5 |   |   |   |   |   |   |   |   |   |   |  
  | 8.64382 | 0.00000 | 0.00000 |   | 4.57414 | 0.00000 | 0.00000 |   | 4.55065 | 0.00000 | 0.00000
  | 0.00000 | 8.64382 | 0.00000 |   | 0.00000 | 4.57414 | 0.00000 |   | 0.00000 | 4.55065 | 0.00000
  | 0.00000 | 0.00000 | 5.81937 |   | 0.00000 | 0.00000 | 3.07949 |   | 0.00000 | 0.00000 | 3.11685
6 |   |   |   |   |   |   |   |   |   |   |  
  | 8.59948 | 0.00000 | 0.00000 |   | 4.55067 | 0.00000 | 0.00000 |   | 4.51742 | 0.00000 | 0.00000
  | 0.00000 | 8.59948 | 0.00000 |   | 0.00000 | 4.55067 | 0.00000 |   | 0.00000 | 4.51742 | 0.00000
  | 0.00000 | 0.00000 | 5.88999 |   | 0.00000 | 0.00000 | 3.11686 |   | 0.00000 | 0.00000 | 3.14278
7 |   |   |   |   |   |   |   |   |   |   |  
  | 8.53668 | 0.00000 | 0.00000 |   | 4.51744 | 0.00000 | 0.00000 |   | 4.51521 | 0.00000 | 0.00000
  | 0.00000 | 8.53668 | 0.00000 |   | 0.00000 | 4.51744 | 0.00000 |   | 0.00000 | 4.51521 | 0.00000
  | 0.00000 | 0.00000 | 5.93900 |   | 0.00000 | 0.00000 | 3.14280 |   | 0.00000 | 0.00000 | 3.12117
8 |   |   |   |   |   |   |   |   |   |   |  
  | 8.53251 | 0.00000 | 0.00000 |   | 4.51523 | 0.00000 | 0.00000 |   | 4.52365 | 0.00000 | 0.00000
  | 0.00000 | 8.53251 | 0.00000 |   | 0.00000 | 4.51523 | 0.00000 |   | 0.00000 | 4.52365 | 0.00000
  | 0.00000 | 0.00000 | 5.89816 |   | 0.00000 | 0.00000 | 3.12119 |   | 0.00000 | 0.00000 | 3.11474
9 |   |   |   |   |   |   |   |   |   |   |  
  | 8.54845 | 0.00000 | 0.00000 |   | 4.52367 | 0.00000 | 0.00000 |   | 4.52961 | 0.00000 | 0.00000
  | 0.00000 | 8.54845 | 0.00000 |   | 0.00000 | 4.52367 | 0.00000 |   | 0.00000 | 4.52961 | 0.00000
  | 0.00000 | 0.00000 | 5.88601 |   | 0.00000 | 0.00000 | 3.11476 |   | 0.00000 | 0.00000 | 3.11619
10 |   |   |   |   |   |   |   |   |   |   |  
  | 8.55972 | 0.00000 | 0.00000 |   | 4.52963 | 0.00000 | 0.00000 |   | 4.52875 | 0.00000 | 0.00000
  | 0.00000 | 8.55972 | 0.00000 |   | 0.00000 | 4.52963 | 0.00000 |   | 0.00000 | 4.52875 | 0.00000
  | 0.00000 | 0.00000 | 5.88874 |   | 0.00000 | 0.00000 | 3.11620 |   | 0.00000 | 0.00000 | 3.11598
11 |   |   |   |   |   |   |   |   |   |   |  
  | 8.55810 | 0.00000 | 0.00000 |   | 4.52878 | 0.00000 | 0.00000 |   | 4.52848 | 0.00000 | 0.00000
  | 0.00000 | 8.55810 | 0.00000 |   | 0.00000 | 4.52878 | 0.00000 |   | 0.00000 | 4.52848 | 0.00000
  | 0.00000 | 0.00000 | 5.88835 |   | 0.00000 | 0.00000 | 3.11600 |   | 0.00000 | 0.00000 | 3.11635
12 |   |   |   |   |   |   |   |   |   |   |  
  | 8.55759 | 0.00000 | 0.00000 |   | 4.52851 | 0.00000 | 0.00000 |   | 4.52825 | 0.00000 | 0.00000
  | 0.00000 | 8.55759 | 0.00000 |   | 0.00000 | 4.52851 | 0.00000 |   | 0.00000 | 4.52825 | 0.00000
  | 0.00000 | 0.00000 | 5.88904 |   | 0.00000 | 0.00000 | 3.11636 |   | 0.00000 | 0.00000 | 3.11698
13 |   |   |   |   |   |   |   |   |   |   |  
  | 8.55716 | 0.00000 | 0.00000 |   | 4.52828 | 0.00000 | 0.00000 |   | 4.52788 | 0.00000 | 0.00000
  | 0.00000 | 8.55716 | 0.00000 |   | 0.00000 | 4.52828 | 0.00000 |   | 0.00000 | 4.52788 | 0.00000
  | 0.00000 | 0.00000 | 5.89024 |   | 0.00000 | 0.00000 | 3.11700 |   | 0.00000 | 0.00000 | 3.11721
14 |   |   |   |   |   |   |   |   |   |   |  
  | 8.55646 | 0.00000 | 0.00000 |   | 4.52791 | 0.00000 | 0.00000 |   | 4.52783 | 0.00000 | 0.00000
  | 0.00000 | 8.55646 | 0.00000 |   | 0.00000 | 4.52791 | 0.00000 |   | 0.00000 | 4.52783 | 0.00000
  | 0.00000 | 0.00000 | 5.89068 |   | 0.00000 | 0.00000 | 3.11723 |   | 0.00000 | 0.00000 | 3.11724
15 |   |   |   |   |   |   |   |   |   |   |  
  | 8.55636 | 0.00000 | 0.00000 |   | 4.52785 | 0.00000 | 0.00000 |   | 4.52778 | 0.00000 | 0.00000
  | 0.00000 | 8.55636 | 0.00000 |   | 0.00000 | 4.52785 | 0.00000 |   | 0.00000 | 4.52778 | 0.00000
  | 0.00000 | 0.00000 | 5.89073 |   | 0.00000 | 0.00000 | 3.11726 |   | 0.00000 | 0.00000 | 3.11719
16 |   |   |   |   |   |   |   |   |   |   |  
  | 8.55626 | 0.00000 | 0.00000 |   | 4.52780 | 0.00000 | 0.00000 |   | 4.52781 | 0.00000 | 0.00000
  | 0.00000 | 8.55626 | 0.00000 |   | 0.00000 | 4.52780 | 0.00000 |   | 0.00000 | 4.52781 | 0.00000
  | 0.00000 | 0.00000 | 5.89064 |   | 0.00000 | 0.00000 | 3.11721 |   | 0.00000 | 0.00000 | 3.11710
17 |   |   |   |   |   |   |   |   |   |   |  
  | 8.55632 | 0.00000 | 0.00000 |   | 4.52783 | 0.00000 | 0.00000 |   | 4.52779 | 0.00000 | 0.00000
  | 0.00000 | 8.55632 | 0.00000 |   | 0.00000 | 4.52783 | 0.00000 |   | 0.00000 | 4.52779 | 0.00000
  | 0.00000 | 0.00000 | 5.89046 |   | 0.00000 | 0.00000 | 3.11711 |   | 0.00000 | 0.00000 | 3.11701
18 |   |   |   |   |   |   |   |   |   |   |  
  | 8.55629 | 0.00000 | 0.00000 |   | 4.52782 | 0.00000 | 0.00000 |   | 4.52784 | 0.00000 | 0.00000
  | 0.00000 | 8.55629 | 0.00000 |   | 0.00000 | 4.52782 | 0.00000 |   | 0.00000 | 4.52784 | 0.00000
  | 0.00000 | 0.00000 | 5.89029 |   | 0.00000 | 0.00000 | 3.11702 |   | 0.00000 | 0.00000 | 3.11700
19 |   |   |   |   |   |   |   |   |   |   |  
  | 8.55637 | 0.00000 | 0.00000 |   | 4.52786 | 0.00000 | 0.00000 |   | 4.59398 | 0.00000 | 0.00000
  | 0.00000 | 8.55637 | 0.00000 |   | 0.00000 | 4.52786 | 0.00000 |   | 0.00000 | 4.59398 | 0.00000
  | 0.00000 | 0.00000 | 5.89027 |   | 0.00000 | 0.00000 | 3.11701 |   | 0.00000 | 0.00000 | 2.95898

Do you have any ideas about this? Thank you in advance!

BTW, I use `1 bohrs = 0.52918 ANG` to do unit conversion, and the version of awk and octave are `GNU Awk 4.0.2` and `GNU Octave, version 5.2.0`.

Best,
Pan

**Comment by shankar1729** [comment]
Hi Pan,

Could you please post your jdftx output (log) file and the xsf that resulted? It looks like there is a circular shift in the list of lattice vectors somehow based on your comparison: the last xsf lattice matches the first jdftx one and the rest are offset by one step. The script uses more decimal places in the conversion factor, so the comparison is good to 5 decimal places after that circular shift.

Thanks!
Best,
Shankar

**Comment by panxiang126** [comment]
Dear Shankar,

Thank you so much for your quick rely!

I post the jdftxOutFile and xsfFile generated by `createXSF optCell.out str.xsf`.

The final output lattice vectors in jdftxOutFile are:
```
[      8.55637            0            0  ]
[            0      8.55637            0  ]
[            0            0      5.89027  ]
```
It is corrsponding to (1 bohrs = 1/1.8897161646320723 ANG):
```
[      4.527859877            0            0  ]
[            0      4.527859877            0  ]
[            0            0      3.117013079  ]
```
However, in the xsfFile, lattice vectors are:
```
  4.593978   0.000000   0.000000
  0.000000   4.593978   0.000000
  0.000000   0.000000   2.958984
```

Best,
Pan
[optCell.zip](https://github.com/shankar1729/jdftx/files/4987794/optCell.zip)

**Comment by shankar1729** [comment]
Hi Pan,

I found a bug in createXSF and pushed a fix in the latest git commit. Thanks for catching this issue!

Best,
Shankar
