### ISSUE TITLE
Complieing 

### ISSUE THREAD

**Issue by fanglinche** [shankar1729/jdftx#13]
Hello,
This is Fanglin. I looked at the JDFTx code. Is that possible to parallelize to at least 1024 cores? I would like to ask the technician guy from BGQ-scinet to compile JDFTx to work on my project.

**Comment by shankar1729** [comment]
Hi Fanglin,

The JDFTx 1.x series does MPI over k-points and threads for remaining parallelism.  JDFTx 2.x, currently under early stages of development, will support multi-level MPI parallelism.

On BGQ, you will currently be able to use as many nodes as you have symmetry reduced k-points in your system, with in-node parallelism done with (16) threads.  Therefore you will be able to use 1024 cores on a BGQ efficiently only for a calculation with 64 (or more) reduced k points.

Best,
Shankar
