### ISSUE TITLE
issues of atoms too close

### ISSUE THREAD

**Issue by panxiang126** [shankar1729/jdftx#130]
Dear Dr. Shankar,

I tried to calculate the single point energy of H2 molecule with lattice and ionpos:
```
latt-scale 1.8897161646320723 1.8897161646320723 1.8897161646320723
lattice \
    22.0000000000000000    0.0000000000000000    0.0000000000000000 \
     0.0000000000000000   22.0000000000000000    0.0000000000000000 \
     0.0000000000000000    0.0000000000000000   22.0000000000000000

coords-type Lattice
# Ionic positions in lattice coordinates:
ion H  0.4997718834778395  0.4999764548036894  0.4999721919325472 1
ion H  0.5334434765221602  0.5034499551963136  0.5040780480674508 1
```

The distence between two H atom should be 0.75 ANG, which  is slightly larger than the bond length of H2 molecule (74 pm). However the job did not run properly for the following reason:
```
WARNING: H #0 and H #1 are closer than the vector-sum of their core radii.

Atoms are too close, have overlapping pseudopotential cores.

End date and time: Wed Aug 12 09:57:50 2020  (Duration: 0-0:00:00.17)
Failed.
```

Do you have any ideas about this? 

The whole jdftx output file is posted for further analysis. [scf.txt](https://github.com/shankar1729/jdftx/files/5060322/scf.txt)

Best,
Pan

**Comment by shankar1729** [comment]
Hi Pan,

Please see the discussion in the http://jdftx.org/FreeEnergy.html tutorial on how to fix this: it is a corner case involving the newer GBRV pseudopotential for H.

Best,
Shankar
