### ISSUE TITLE
Post-processing wannier interpolations on different grids

### ISSUE THREAD

**Issue by gvarnavi** [shankar1729/jdftx#136]
Hey Shankar,

This is less of an issue, as it is me trying to understand the wannier interpolation used by jdftx for post-processing use, so feel free to close if not appropriate - any advice would be much appreciated!

Suppose we have some scalar-valued electronic property computed on a fine kmesh, for simplicity and to enable comparisons with known results let this property be the squared magnitude of the group velocity `||v_{kn}||^2` (actual properties of interest would of-course be more expensive to calculate).
```
E, U, v = calcE(uniform_mesh)
ground_truth_vsq = np.einsum('kax,kax->ka',v,v)
```
where `calcE` is consistent with [the jdftx tutorials](http://jdftx.org/EphMatrixElements.html) and `uniform_mesh` is the (-0.5,0.5] fine kpoint mesh.

We now want to transform the property on the wannier basis, using the wannier centers and weights computed on a coarser mesh given by `kpoint-folding`, to allow for interpolation of this property at arbitrary kpoints. Following the [source code](https://github.com/shankar1729/jdftx/blob/master/jdftx/wannier/WannierMinimizer.cpp#L389), the following approach seemed reasonable to me:
```
#wannier interpolation
def wannierize_scalar(vector,unitary,phase,normalization):
    rotated_vector = np.einsum('kab,kb,kcb->kca',unitary,vector,unitary.conjugate())
    fourier_vector = np.tensordot(phase, rotated_vector, axes=(0,0))/normalization
    return fourier_vector.real

#--- Wannierization to unique cells
unique_cells = cartesian_product(*(np.arange(kpoint) for kpoint in kpoints))
kStride_fine = np.array([kpoints[1]*kpoints[2], kpoints[2], 1])
iReduced_fine = np.dot(np.mod(cellMap, kpoints[None,:]), kStride_fine)

inverse_phase = np.exp((-2j*np.pi)*np.dot(uniform_mesh,unique_cells.T))
wannier_basis = wannierize_scalar(ground_truth_vsq,U,inverse_phase,num_mesh)
```
where `unique_cells` is a uniform mesh given by the cartesian product of cells in the range 0 to kpoint for each dimension of the fine mesh (inspired from [source code here](https://github.com/shankar1729/jdftx/blob/master/jdftx/wannier/WannierMinimizer_save.cpp#L154)), `num_mesh` is the size of the kpoint mesh (and by extension `unique_cells`).

When I try to reconstruct these however, I observe the following behaviour.
```
#--- Reconstructing
vSqReduced = wannier_basis.swapaxes(1,2)
vSqWannier = Wwannier * vSqReduced[iReduced_fine]

phase = np.exp((2j*np.pi)*np.dot(uniform_mesh,cellMap.T))
vSqk = np.tensordot(phase, vSqWannier,  axes=1)
vSqk = np.einsum("kba,kbc,kca->ka", U.conjugate(), vSqk, U)

#-- FT mesh error
wannierization_error_mean = np.mean(np.abs(ground_truth_vsq-vSqk))/np.mean(ground_truth_vsq)
wannierization_error_max = np.amax(np.abs(ground_truth_vsq-vSqk))/np.mean(ground_truth_vsq)
print("Wannierization error (mean,max): ",wannierization_error_mean,wannierization_error_max)
```
On the same size as the `kpoint-folding` mesh, there is indeed no error:
```
george@maui:~/.../tests$ python3 ../scripts/4.1.wannierization-test-slim.py --kpoints 8 8 8
Wannierization error (mean,max):  4.661292211230041e-13 4.1578226859661495e-10
```

If I use a finer mesh however, I get a constant error (essentially regardless of how dense this mesh becomes):
```
george@maui:~/.../tests$ python3 ../scripts/4.1.wannierization-test-slim.py --kpoints 12 12 12
Wannierization error (mean,max):  0.12463515118994815 3.0251572171415857
```

What is more, if I sample at random kpoints:
```
#--- Random points error
kpts_random = np.random.rand(1000,3)
E_random, U_random, v_random = calcE(kpts_random)
ground_truth_vsq_random = np.einsum('kax,kax->ka',v_random,v_random)

phase_random = np.exp((2j*np.pi)*np.dot(kpts_random,cellMap.T))
vSqk_random = np.tensordot(phase_random, vSqWannier,  axes=1)
vSqk_random = np.einsum("kba,kbc,kca->ka", U_random.conjugate(), vSqk_random, U_random)
```
I obtain a similar constant error, even for the `kpoint-folding` mesh:
```
george@maui:~/.../tests$ python3 ../scripts/4.1.wannierization-test-slim.py --kpoints 8 8 8
Wannierization error (mean,max):  4.661292211230041e-13 4.1578226859661495e-10
Random wannierization error (mean,max):  0.14858334923801408 5.272878410031114

george@maui:~/.../tests$ python3 ../scripts/4.1.wannierization-test-slim.py --kpoints 12 12 12
Wannierization error (mean,max):  0.12463515118994815 3.0251572171415857
Random wannierization error (mean,max):  0.12116643740723602 3.7790209969773794
```

Am I missing something here? Thanks in advance!

Cheers,
George

PS: Attached a simple script I've been using to play around with this, in-case it's useful (renamed to *log to allow uploading)
The test-system I've been debugging with is Cu with `kpoint-folding 8 8 8`, 5 d-orbital and 2 s-orbital wannier centers.
[4.1.wannierization-test-slim.log](https://github.com/shankar1729/jdftx/files/5241213/4.1.wannierization-test-slim.log)

**Comment by shankar1729** [comment]
Hi George,

The quick answer to the above is that you need more than just the diagonal matrix elements for effective Wannier interpolation. Except for the energy, all the other Wannier quantities processed by jdftx and friends are not diagonal in the Bloch basis. For example, for the velocities, the wannier representation is constructed from the full velocity operator including the off-diagonal matrix elements.

You lose that in the above, and the quantity being interpolated becomes much more discontinuous in k after the unitary rotations, leading to significant Nyquist-like oscillations. You still get the exact result back at the k-points of the input mesh, but potentially something very noisy everywhere in between.

If you want to interpolate v^2, a much better option would be to compute <v^2> as a full matrix in the DFT code, and then wannierize that. However, this is of course a much more involved option and not trivial for a general dependent operator. Note also that you cannot get the full v^2 matrix elements from the v matrix elements since your basis is not complete.

Best,
Shankar

**Comment by gvarnavi** [comment]
Hey Shankar,

Thanks for the prompt reply, this makes sense!
Just to make sure I understand though, and in-case my toy-example above was over/under-simplifying the situation, you seem to be wannierizing the[ linewidths here](https://github.com/shankar1729/jdftx/blob/master/jdftx/wannier/WannierMinimizer_save.cpp#L488) using just a diagonal matrix element representation right? Do linewidths also happen to be diagonal in the Bloch basis? 

Cheers,
George

**Comment by shankar1729** [comment]
Indeed, and the interpolation of linewidths is nowhere as reliable as the velocity and other matrix elements treated fully. I'm really interpolating ImSigma assumed diagonal; working with the full self-energy operator would work better, but that is not easily available at the level of computational expense we are currently working with.

Best,
Shankar

**Comment by gvarnavi** [comment]
Got it, thanks again - closing issue!

Cheers,
George
