### ISSUE TITLE
some doubts about DFT+U & ONCV file 

### ISSUE THREAD

**Issue by Jing606** [shankar1729/jdftx#140]
Hello,

I am new user of JDFTx and now trying to calculate bandstructure of copper. In the paper  "Theoretical predictions for hot-carrier generation from surface plasmon decay. Nature communications 5.1 (2014): 1-8." and "Nonradiative plasmon decay and hot carrier dynamics: effects of phonons, surfaces, and geometry. Acs Nano 10.1 (2016): 957-966.", it said that it adopted dft+u and full-relativistic norm-conserving pseudopotential. Here are some questions about that:

1. When I have "add-U Cu d 0.0599", the bandstructure didn't match with what paper showed. But the strange thing is that it will look more likely, when I changed it into "add-U Cu d -0.0599". (Here I used Cu_ONCV_PBE.upf) So could I know which is correct usage for this tag? 

![copper_band_posU](https://user-images.githubusercontent.com/58120250/96065928-1eb7aa80-0e5e-11eb-83bc-ea5d66f396d3.png)
![copper_band_negU](https://user-images.githubusercontent.com/58120250/96065952-21b29b00-0e5e-11eb-9ef7-0f38293ea95c.png)

2. About the potential file, I try to use Cu_ONCV_PBE_FR-1.0.upf from the "http://www.quantum-simulation.org/potentials/sg15_oncv/upf/", but there is always an error said, could you help me fix that?

/jdftx-master/jdftx/electronic/SpeciesInfo_atomic.cpp:171: setAtomicOrbitals:
	Assertion 'l < int(psiRadial.size())' failed--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD

Thanks in advance,
Jing

**Comment by Jing606** [comment]
Dear Shankar,

I just fixed the first problem, could you help me on the second question?

Thanks,
Jing

**Comment by shankar1729** [comment]
The default SG15 pseudopotentials do not have atomic orbitals, and hence it fails. I had patched the ONCVPSP code to add atomic orbital support (now included in their release) and regenerate the SG15 non-relativistic pseudopotentials that are distributed with JDFTx.

You may have to regenerate those pseudopotentials yourself using a new version of ONCVPSP that includes my patch.

Alternatively, look for other relativistic pseudopotentials that already include atomic orbitals eg. the ones on the pseudo dojo or PSLIB.

Best,
Shankar
