### ISSUE TITLE
JDFTx output file in ASE

### ISSUE THREAD

**Issue by Liuly98** [shankar1729/jdftx#141]
Dear Shankar,
When I use the JDFTx calculator in ASE (after set up everything successfully follwing the guide from your website)to do calculations (for example, structure optimization) , I still want to get the relevant files (like common.ionpos or common.n), as you write in the website, use "shell('createXSF %s/out CO.xsf %s/n' % ((calculator.runDir,)*2))", but if I don't want to convert the original output file, What should I do ?

Thanks!

**Comment by panxiang126** [comment]
Hi,

If you did not use `calculator.clean()`, you should be able to find them in the directory behind `Set up JDFTx calculator with run files in...`.

BTW, you can also add `dir="./"` to the `tempfile.mkdtemp` function in the line 93 of the JDFTx.py file.

Best,
Pan

**Comment by Liuly98** [comment]
Hi panxiang,

Thank you for your help! I can get the output files successfully follwing your guide.

Best,
Leyu
