### ISSUE TITLE
Compilation error in file core/Coulomb.cpp

### ISSUE THREAD

**Issue by bernipuig** [shankar1729/jdftx#142]
Dear @shankar1729, I have encountered error when trying to build jdftx-1.6.0 in HPC cluster

load modules mkl gsl fftw3
I use gcc/6.3.0, cmake/3.7.2 

**I have tried 2 forms**

**FORM1:**
CC=gcc CXX=g++ cmake -D EnableMKL=yes -D MKL_PATH="/QFsoft/compilers/intel/2019/mkl" -D ForceFFTW=yes -D FFTW3_PATH="/QFsoft/libs/FFTW3/3.3.8/" -D GSL_PATH="/QFsoft/libs/GSL/2.6/" ../jdftx-1.6.0/jdftx/

make -j12

**FORM2:**
cmake -D EnableMKL=yes -D MKL_PATH="/QFsoft/compilers/intel/2019/mkl" -D ForceFFTW=yes -D FFTW3_PATH="/QFsoft/libs/FFTW3/3.3.8/" -D GSL_PATH="/QFsoft/libs/GSL/2.6/" ../jdftx-1.6.0/jdftx/

make -j12

**ERRORS:**

**FORM1:**
Scanning dependencies of target PseudopotentialLibrary
Scanning dependencies of target jdftxlib
[  0%] Building CXX object CMakeFiles/jdftxlib.dir/core/BlasExtra.cpp.o
[  1%] Building CXX object CMakeFiles/jdftxlib.dir/core/Blip.cpp.o
[  2%] Building CXX object CMakeFiles/jdftxlib.dir/core/CoulombIsolated.cpp.o
[  3%] Building CXX object CMakeFiles/jdftxlib.dir/core/CoulombPeriodic.cpp.o
[  3%] Building CXX object CMakeFiles/jdftxlib.dir/core/Coulomb.cpp.o
[  4%] Building CXX object CMakeFiles/jdftxlib.dir/core/CoulombKernel.cpp.o
[  4%] Building CXX object CMakeFiles/jdftxlib.dir/core/CoulombSlab.cpp.o
[  7%] Building CXX object CMakeFiles/jdftxlib.dir/core/Coulomb_ExchangeEval.cpp.o
[  7%] Building CXX object CMakeFiles/jdftxlib.dir/core/GpuUtil.cpp.o
[  7%] Building CXX object CMakeFiles/jdftxlib.dir/core/CoulombWire.cpp.o
[  7%] Building CXX object CMakeFiles/jdftxlib.dir/core/Coulomb_internal.cpp.o
[  8%] Building CXX object CMakeFiles/jdftxlib.dir/core/GridInfo.cpp.o
...
...
make[2]: *** [CMakeFiles/jdftxlib.dir/core/Coulomb.cpp.o] Error 1
make[2]: *** [CMakeFiles/jdftxlib.dir/core/Coulomb_ExchangeEval.cpp.o] Error 1
make[2]: *** [CMakeFiles/jdftxlib.dir/core/CoulombWire.cpp.o] Error 1
make[1]: *** [CMakeFiles/jdftxlib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  8%] Built target PseudopotentialLibrary
make: *** [all] Error 2

**FORM2:**
[  0%] Building CXX object CMakeFiles/jdftxlib.dir/core/BlasExtra.cpp.o
[  1%] Building CXX object CMakeFiles/jdftxlib.dir/core/Blip.cpp.o
[  3%] Building CXX object CMakeFiles/jdftxlib.dir/core/CoulombIsolated.cpp.o
[  4%] Building CXX object CMakeFiles/jdftxlib.dir/core/CoulombPeriodic.cpp.o
[  4%] Building CXX object CMakeFiles/jdftxlib.dir/core/Coulomb.cpp.o
[  4%] Building CXX object CMakeFiles/jdftxlib.dir/core/CoulombKernel.cpp.o
[  4%] Building CXX object CMakeFiles/jdftxlib.dir/core/CoulombSlab.cpp.o
[  5%] Building CXX object CMakeFiles/jdftxlib.dir/core/CoulombWire.cpp.o
[  7%] Building CXX object CMakeFiles/jdftxlib.dir/core/GpuUtil.cpp.o
[  7%] Building CXX object CMakeFiles/jdftxlib.dir/core/Coulomb_ExchangeEval.cpp.o
[  7%] Building CXX object CMakeFiles/jdftxlib.dir/core/Coulomb_internal.cpp.o
[  8%] Building CXX object CMakeFiles/jdftxlib.dir/core/GridInfo.cpp.o
....
....
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-unused-result"
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-unused-result"
make[2]: *** [CMakeFiles/jdftxlib.dir/core/CoulombWire.cpp.o] Error 1
make[2]: *** [CMakeFiles/jdftxlib.dir/core/Coulomb_ExchangeEval.cpp.o] Error 1
make[1]: *** [CMakeFiles/jdftxlib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  8%] Built target PseudopotentialLibrary
make: *** [all] Error 2

Thanks
Bernat

**Comment by shankar1729** [comment]
Hi Bernat,

Please attach the CMakeCache.txt from these builds (so that I can see all the compiler and library versions being used) and the actual error message reported. The snippets you pasted do not include the point where the error actually occurred.

Best,
Shankar

**Comment by bernipuig** [comment]
Hi @shankar1729 

Form1:
[conf.txt](https://github.com/shankar1729/jdftx/files/5458878/conf.txt)

[install.txt](https://github.com/shankar1729/jdftx/files/5458884/install.txt)

[CMakeCache.txt](https://github.com/shankar1729/jdftx/files/5458886/CMakeCache.txt)

Form2:

[conf.txt](https://github.com/shankar1729/jdftx/files/5458893/conf.txt)

[install.txt](https://github.com/shankar1729/jdftx/files/5458894/install.txt)

[CMakeCache.txt](https://github.com/shankar1729/jdftx/files/5458895/CMakeCache.txt)

Thanks
Bernat

**Comment by shankar1729** [comment]
Hi Bernat,

In your first form, you are using a supported g++ version (6.3), but it seems that the standard header files like mutex and thread seem to be from an earlier version. This seems to indicate the module used for the compiler is not properly initializing the include directories that match the compiler. Most likely its seems that your build is trying to use the system C++ headers (4.4.6 version) with the newer C++ compiler. You will need to ask the sysadmin who created the module about this issue. As a workaround, perhaps you can try to set the [path to the include libraries manually](https://stackoverflow.com/questions/25849571/adding-include-directories-to-cmake-when-calling-it-from-the-command-line/35633733).

The second form is using g++ 4.4.6, which does not support C++11 standard fully enough to compile JDFTx. So there is no point trying to fix that one.

Best,
Shankar
