### ISSUE TITLE
parallel parameters of MPI

### ISSUE THREAD

**Issue by panxiang126** [shankar1729/jdftx#143]
Dear Dr. Shankar,

I did a series of tests to study the effect of the number of processes and threads on the JDFTx parallel efficiency using a system containing 30 boron atoms, 90 electrons, 120 bands, 12 states and 6 reduced k-points (see [testParallelParameter.zip](https://github.com/shankar1729/jdftx/files/5395574/testParallelParameter.zip) for more details) on a 64-core (two AMD EPYC 7452 32-Core Processor) compute node. The time difference between the first and the second iteration of LCAOMinimize, and relative to the calculation efficiency and cpu utilization of a single core are shown below:

jobName | CPUs | processes | threadsPerProcess | timeOfOneLCAOMinimize(s) | efficiency | utilization
-- | -- | -- | -- | -- | -- | --
1n1c | 1 | 1 | 1 | 108.39 | 100% | 100%
2n1c | 2 | 2 | 1 | 56.65 | 191% | 96%
1n2c | 2 | 1 | 2 | 58.72 | 185% | 92%
3n1c | 3 | 3 | 1 | 39.13 | 277% | 92%
1n3c | 3 | 1 | 3 | 43.36 | 250% | 83%
2n2c | 4 | 2 | 2 | 30.94 | 350% | 88%
1n4c | 4 | 1 | 4 | 33.13 | 327% | 82%
4n1c | 4 | 4 | 1 | 37.85 | 286% | 72%
5n1c | 5 | 5 | 1 | 29.05 | 373% | 75%
1n5c | 5 | 1 | 5 | 29.31 | 370% | 74%
2n3c | 6 | 2 | 3 | 21.79 | 497% | 83%
3n2c | 6 | 3 | 2 | 22.06 | 491% | 82%
1n6c | 6 | 1 | 6 | 24.25 | 447% | 74%
6n1c | 6 | 6 | 1 | 24.81 | 437% | 73%
1n7c | 7 | 1 | 7 | 21.04 | 515% | 74%
7n1c | 7 | 7 | 1 | 21.81 | 497% | 71%
4n2c | 8 | 4 | 2 | 16.46 | 659% | 82%
2n4c | 8 | 2 | 4 | 17.05 | 636% | 79%
1n8c | 8 | 1 | 8 | 18.99 | 571% | 71%
8n1c | 8 | 8 | 1 | 21.17 | 512% | 64%
3n3c | 9 | 3 | 3 | 16.68 | 650% | 72%
9n1c | 9 | 9 | 1 | 17.76 | 610% | 68%
1n9c | 9 | 1 | 9 | 22.71 | 477% | 53%
2n5c | 10 | 2 | 5 | 14.14 | 767% | 77%
5n2c | 10 | 5 | 2 | 17.07 | 635% | 63%
10n1c | 10 | 10 | 1 | 17.36 | 624% | 62%
1n10c | 10 | 1 | 10 | 19.61 | 553% | 55%
11n1c | 11 | 11 | 1 | 18.95 | 572% | 52%
1n11c | 11 | 1 | 11 | 20.77 | 522% | 47%
3n4c | 12 | 3 | 4 | 13.13 | 826% | 69%
2n6c | 12 | 2 | 6 | 13.6 | 797% | 66%
4n3c | 12 | 4 | 3 | 13.64 | 795% | 66%
6n2c | 12 | 6 | 2 | 13.76 | 788% | 66%
12n1c | 12 | 12 | 1 | 13.89 | 780% | 65%
1n12c | 12 | 1 | 12 | 17.89 | 606% | 50%
13n1c | 13 | 13 | 1 | 13.59 | 798% | 61%
1n13c | 13 | 1 | 13 | 22.03 | 492% | 38%
2n7c | 14 | 2 | 7 | 11.77 | 921% | 66%
14n1c | 14 | 14 | 1 | 12.72 | 852% | 61%
7n2c | 14 | 7 | 2 | 13.08 | 829% | 59%
1n14c | 14 | 1 | 14 | 18.81 | 576% | 41%
15n1c | 15 | 15 | 1 | 11.14 | 973% | 65%
3n5c | 15 | 3 | 5 | 11.97 | 906% | 60%
5n3c | 15 | 5 | 3 | 13.04 | 831% | 55%
1n15c | 15 | 1 | 15 | 20.64 | 525% | 35%
16n1c | 16 | 16 | 1 | 10.46 | 1036% | 65%
4n4c | 16 | 4 | 4 | 10.79 | 1005% | 63%
2n8c | 16 | 2 | 8 | 11.25 | 963% | 60%
8n2c | 16 | 8 | 2 | 12.04 | 900% | 56%
1n16c | 16 | 1 | 16 | 15.67 | 692% | 43%
17n1c | 17 | 17 | 1 | 11.45 | 947% | 56%
1n17c | 17 | 1 | 17 | 21.27 | 510% | 30%
6n3c | 18 | 6 | 3 | 10.03 | 1081% | 60%
9n2c | 18 | 9 | 2 | 11 | 985% | 55%
3n6c | 18 | 3 | 6 | 11.03 | 983% | 55%
18n1c | 18 | 18 | 1 | 11.64 | 931% | 52%
2n9c | 18 | 2 | 9 | 14.89 | 728% | 40%
1n18c | 18 | 1 | 18 | 18.44 | 588% | 33%
19n1c | 19 | 19 | 1 | 10.96 | 989% | 52%
1n19c | 19 | 1 | 19 | 19.4 | 559% | 29%
4n5c | 20 | 4 | 5 | 9.07 | 1195% | 60%
5n4c | 20 | 5 | 4 | 10.03 | 1081% | 54%
2n10c | 20 | 2 | 10 | 10.47 | 1035% | 52%
10n2c | 20 | 10 | 2 | 10.52 | 1030% | 52%
20n1c | 20 | 20 | 1 | 12.09 | 897% | 45%
1n20c | 20 | 1 | 20 | 15.71 | 690% | 34%
7n3c | 21 | 7 | 3 | 9.47 | 1145% | 55%
3n7c | 21 | 3 | 7 | 10.02 | 1082% | 52%
21n1c | 21 | 21 | 1 | 11.9 | 911% | 43%
1n21c | 21 | 1 | 21 | 19.72 | 550% | 26%
11n2c | 22 | 11 | 2 | 9.38 | 1156% | 53%
22n1c | 22 | 22 | 1 | 11.18 | 969% | 44%
2n11c | 22 | 2 | 11 | 11.92 | 909% | 41%
1n22c | 22 | 1 | 22 | 17.96 | 604% | 27%
23n1c | 23 | 23 | 1 | 9.98 | 1086% | 47%
1n23c | 23 | 1 | 23 | 20.45 | 530% | 23%
12n2c | 24 | 12 | 2 | 8.35 | 1298% | 54%
3n8c | 24 | 3 | 8 | 8.4 | 1290% | 54%
4n6c | 24 | 4 | 6 | 8.72 | 1243% | 52%
6n4c | 24 | 6 | 4 | 9.01 | 1203% | 50%
8n3c | 24 | 8 | 3 | 9.12 | 1188% | 50%
2n12c | 24 | 2 | 12 | 10.09 | 1074% | 45%
24n1c | 24 | 24 | 1 | 12.17 | 891% | 37%
1n24c | 24 | 1 | 24 | 16.92 | 641% | 27%
5n5c | 25 | 5 | 5 | 8.84 | 1226% | 49%
25n1c | 25 | 25 | 1 | 11.51 | 942% | 38%
1n25c | 25 | 1 | 25 | 20.68 | 524% | 21%
13n2c | 26 | 13 | 2 | 8.15 | 1330% | 51%
26n1c | 26 | 26 | 1 | 11.21 | 967% | 37%
2n13c | 26 | 2 | 13 | 13.2 | 821% | 32%
1n26c | 26 | 1 | 26 | 18.35 | 591% | 23%
9n3c | 27 | 9 | 3 | 9.13 | 1187% | 44%
3n9c | 27 | 3 | 9 | 10.05 | 1079% | 40%
27n1c | 27 | 27 | 1 | 11.75 | 922% | 34%
1n27c | 27 | 1 | 27 | 21.77 | 498% | 18%
7n4c | 28 | 7 | 4 | 7.91 | 1370% | 49%
14n2c | 28 | 14 | 2 | 8.14 | 1332% | 48%
4n7c | 28 | 4 | 7 | 8.44 | 1284% | 46%
28n1c | 28 | 28 | 1 | 11.85 | 915% | 33%
2n14c | 28 | 2 | 14 | 12.71 | 853% | 30%
1n28c | 28 | 1 | 28 | 19.83 | 547% | 20%
29n1c | 29 | 29 | 1 | 11.4 | 951% | 33%
1n29c | 29 | 1 | 29 | 21.78 | 498% | 17%
6n5c | 30 | 6 | 5 | 7.21 | 1503% | 50%
15n2c | 30 | 15 | 2 | 7.67 | 1413% | 47%
5n6c | 30 | 5 | 6 | 7.82 | 1386% | 46%
10n3c | 30 | 10 | 3 | 8.76 | 1237% | 41%
3n10c | 30 | 3 | 10 | 9.77 | 1109% | 37%
30n1c | 30 | 30 | 1 | 11.47 | 945% | 31%
2n15c | 30 | 2 | 15 | 12.13 | 894% | 30%
1n30c | 30 | 1 | 30 | 22.46 | 483% | 16%
31n1c | 31 | 31 | 1 | 10.2 | 1063% | 34%
1n31c | 31 | 1 | 31 | 20.31 | 534% | 17%
16n2c | 32 | 16 | 2 | 7.7 | 1408% | 44%
4n8c | 32 | 4 | 8 | 7.79 | 1391% | 43%
8n4c | 32 | 8 | 4 | 8.07 | 1343% | 42%
2n16c | 32 | 2 | 16 | 11.23 | 965% | 30%
32n1c | 32 | 32 | 1 | 11.25 | 963% | 30%
1n32c | 32 | 1 | 32 | 20.97 | 517% | 16%
11n3c | 33 | 11 | 3 | 8.4 | 1290% | 39%
3n11c | 33 | 3 | 11 | 9.87 | 1098% | 33%
33n1c | 33 | 33 | 1 | 11.24 | 964% | 29%
1n33c | 33 | 1 | 33 | 24.21 | 448% | 14%
17n2c | 34 | 17 | 2 | 7.93 | 1367% | 40%
34n1c | 34 | 34 | 1 | 11.74 | 923% | 27%
2n17c | 34 | 2 | 17 | 12.85 | 844% | 25%
1n34c | 34 | 1 | 34 | 20.95 | 517% | 15%
7n5c | 35 | 7 | 5 | 8.21 | 1320% | 38%
5n7c | 35 | 5 | 7 | 8.66 | 1252% | 36%
35n1c | 35 | 35 | 1 | 11.29 | 960% | 27%
1n35c | 35 | 1 | 35 | 23.8 | 455% | 13%
12n3c | 36 | 12 | 3 | 6.75 | 1606% | 45%
9n4c | 36 | 9 | 4 | 7.3 | 1485% | 41%
6n6c | 36 | 6 | 6 | 7.89 | 1374% | 38%
18n2c | 36 | 18 | 2 | 8.25 | 1314% | 36%
4n9c | 36 | 4 | 9 | 8.83 | 1228% | 34%
3n12c | 36 | 3 | 12 | 10.56 | 1026% | 29%
36n1c | 36 | 36 | 1 | 11.83 | 916% | 25%
2n18c | 36 | 2 | 18 | 12.15 | 892% | 25%
1n36c | 36 | 1 | 36 | 21.16 | 512% | 14%
37n1c | 37 | 37 | 1 | 11.44 | 947% | 26%
1n37c | 37 | 1 | 37 | 24.62 | 440% | 12%
19n2c | 38 | 19 | 2 | 7.92 | 1369% | 36%
38n1c | 38 | 38 | 1 | 11.46 | 946% | 25%
2n19c | 38 | 2 | 19 | 15.87 | 683% | 18%
1n38c | 38 | 1 | 38 | 23.05 | 470% | 12%
13n3c | 39 | 13 | 3 | 6.78 | 1599% | 41%
39n1c | 39 | 39 | 1 | 11.24 | 964% | 25%
3n13c | 39 | 3 | 13 | 12.14 | 893% | 23%
1n39c | 39 | 1 | 39 | 23.04 | 470% | 12%
8n5c | 40 | 8 | 5 | 7.28 | 1489% | 37%
10n4c | 40 | 10 | 4 | 7.3 | 1485% | 37%
5n8c | 40 | 5 | 8 | 7.55 | 1436% | 36%
20n2c | 40 | 20 | 2 | 7.56 | 1434% | 36%
4n10c | 40 | 4 | 10 | 8.53 | 1271% | 32%
40n1c | 40 | 40 | 1 | 11.7 | 926% | 23%
2n20c | 40 | 2 | 20 | 14.16 | 765% | 19%
1n40c | 40 | 1 | 40 | 23.32 | 465% | 12%
41n1c | 41 | 41 | 1 | 11.33 | 957% | 23%
1n41c | 41 | 1 | 41 | 25.47 | 426% | 10%
7n6c | 42 | 7 | 6 | 6.68 | 1623% | 39%
6n7c | 42 | 6 | 7 | 6.87 | 1578% | 38%
14n3c | 42 | 14 | 3 | 6.97 | 1555% | 37%
21n2c | 42 | 21 | 2 | 7.76 | 1397% | 33%
3n14c | 42 | 3 | 14 | 9.98 | 1086% | 26%
42n1c | 42 | 42 | 1 | 11.58 | 936% | 22%
2n21c | 42 | 2 | 21 | 13.22 | 820% | 20%
1n42c | 42 | 1 | 42 | 24.75 | 438% | 10%
43n1c | 43 | 43 | 1 | 11.4 | 951% | 22%
1n43c | 43 | 1 | 43 | 25.59 | 424% | 10%
11n4c | 44 | 11 | 4 | 7.68 | 1411% | 32%
22n2c | 44 | 22 | 2 | 7.8 | 1390% | 32%
44n1c | 44 | 44 | 1 | 10.26 | 1056% | 24%
4n11c | 44 | 4 | 11 | 10.94 | 991% | 23%
2n22c | 44 | 2 | 22 | 13.23 | 819% | 19%
1n44c | 44 | 1 | 44 | 23.76 | 456% | 10%
15n3c | 45 | 15 | 3 | 6.72 | 1613% | 36%
9n5c | 45 | 9 | 5 | 6.99 | 1551% | 34%
5n9c | 45 | 5 | 9 | 7.26 | 1493% | 33%
45n1c | 45 | 45 | 1 | 11.57 | 937% | 21%
3n15c | 45 | 3 | 15 | 11.74 | 923% | 21%
1n45c | 45 | 1 | 45 | 25.02 | 433% | 10%
23n2c | 46 | 23 | 2 | 8.14 | 1332% | 29%
46n1c | 46 | 46 | 1 | 11.85 | 915% | 20%
2n23c | 46 | 2 | 23 | 16.41 | 661% | 14%
1n46c | 46 | 1 | 46 | 25.88 | 419% | 9%
47n1c | 47 | 47 | 1 | 12.07 | 898% | 19%
1n47c | 47 | 1 | 47 | 26.32 | 412% | 9%
8n6c | 48 | 8 | 6 | 6.22 | 1743% | 36%
12n4c | 48 | 12 | 4 | 6.32 | 1715% | 36%
6n8c | 48 | 6 | 8 | 6.57 | 1650% | 34%
16n3c | 48 | 16 | 3 | 6.78 | 1599% | 33%
24n2c | 48 | 24 | 2 | 7.62 | 1422% | 30%
4n12c | 48 | 4 | 12 | 8.65 | 1253% | 26%
3n16c | 48 | 3 | 16 | 10.31 | 1051% | 22%
48n1c | 48 | 48 | 1 | 11.59 | 935% | 19%
2n24c | 48 | 2 | 24 | 12.39 | 875% | 18%
1n48c | 48 | 1 | 48 | 23.78 | 456% | 9%
7n7c | 49 | 7 | 7 | 7.51 | 1443% | 29%
49n1c | 49 | 49 | 1 | 11.31 | 958% | 20%
1n49c | 49 | 1 | 49 | 25.54 | 424% | 9%
10n5c | 50 | 10 | 5 | 6.99 | 1551% | 31%
5n10c | 50 | 5 | 10 | 7.07 | 1533% | 31%
25n2c | 50 | 25 | 2 | 8.32 | 1303% | 26%
50n1c | 50 | 50 | 1 | 11.96 | 906% | 18%
2n25c | 50 | 2 | 25 | 12.91 | 840% | 17%
1n50c | 50 | 1 | 50 | 23.45 | 462% | 9%
17n3c | 51 | 17 | 3 | 6.74 | 1608% | 32%
3n17c | 51 | 3 | 17 | 11.68 | 928% | 18%
51n1c | 51 | 51 | 1 | 12.05 | 900% | 18%
1n51c | 51 | 1 | 51 | 26.03 | 416% | 8%
13n4c | 52 | 13 | 4 | 6.64 | 1632% | 31%
26n2c | 52 | 26 | 2 | 7.65 | 1417% | 27%
4n13c | 52 | 4 | 13 | 10.32 | 1050% | 20%
2n26c | 52 | 2 | 26 | 12.69 | 854% | 16%
52n1c | 52 | 52 | 1 | 12.7 | 853% | 16%
1n52c | 52 | 1 | 52 | 24.83 | 437% | 8%
53n1c | 53 | 53 | 1 | 12.18 | 890% | 17%
1n53c | 53 | 1 | 53 | 25.38 | 427% | 8%
9n6c | 54 | 9 | 6 | 6.6 | 1642% | 30%
6n9c | 54 | 6 | 9 | 6.62 | 1637% | 30%
18n3c | 54 | 18 | 3 | 7.48 | 1449% | 27%
27n2c | 54 | 27 | 2 | 7.83 | 1384% | 26%
3n18c | 54 | 3 | 18 | 11.14 | 973% | 18%
54n1c | 54 | 54 | 1 | 12.29 | 882% | 16%
2n27c | 54 | 2 | 27 | 13.54 | 801% | 15%
1n54c | 54 | 1 | 54 | 25.08 | 432% | 8%
11n5c | 55 | 11 | 5 | 6.89 | 1573% | 29%
5n11c | 55 | 5 | 11 | 8.62 | 1257% | 23%
55n1c | 55 | 55 | 1 | 11.76 | 922% | 17%
1n55c | 55 | 1 | 55 | 26.11 | 415% | 8%
14n4c | 56 | 14 | 4 | 6.07 | 1786% | 32%
7n8c | 56 | 7 | 8 | 6.34 | 1710% | 31%
8n7c | 56 | 8 | 7 | 6.65 | 1630% | 29%
28n2c | 56 | 28 | 2 | 7.96 | 1362% | 24%
4n14c | 56 | 4 | 14 | 9.01 | 1203% | 21%
56n1c | 56 | 56 | 1 | 12.53 | 865% | 15%
2n28c | 56 | 2 | 28 | 12.58 | 862% | 15%
1n56c | 56 | 1 | 56 | 24.66 | 440% | 8%
19n3c | 57 | 19 | 3 | 6.84 | 1585% | 28%
57n1c | 57 | 57 | 1 | 12.13 | 894% | 16%
3n19c | 57 | 3 | 19 | 12.88 | 842% | 15%
1n57c | 57 | 1 | 57 | 26.33 | 412% | 7%
29n2c | 58 | 29 | 2 | 7.92 | 1369% | 24%
58n1c | 58 | 58 | 1 | 11.75 | 922% | 16%
2n29c | 58 | 2 | 29 | 15.82 | 685% | 12%
1n58c | 58 | 1 | 58 | 26.09 | 415% | 7%
59n1c | 59 | 59 | 1 | 11.95 | 907% | 15%
1n59c | 59 | 1 | 59 | 26.03 | 416% | 7%
15n4c | 60 | 15 | 4 | 6.04 | 1795% | 30%
12n5c | 60 | 12 | 5 | 6.15 | 1762% | 29%
6n10c | 60 | 6 | 10 | 6.51 | 1665% | 28%
10n6c | 60 | 10 | 6 | 6.6 | 1642% | 27%
20n3c | 60 | 20 | 3 | 6.9 | 1571% | 26%
30n2c | 60 | 30 | 2 | 7.9 | 1372% | 23%
5n12c | 60 | 5 | 12 | 7.99 | 1357% | 23%
4n15c | 60 | 4 | 15 | 11.3 | 959% | 16%
60n1c | 60 | 60 | 1 | 12.08 | 897% | 15%
3n20c | 60 | 3 | 20 | 12.45 | 871% | 15%
2n30c | 60 | 2 | 30 | 13.26 | 817% | 14%
1n60c | 60 | 1 | 60 | 26.81 | 404% | 7%
61n1c | 61 | 61 | 1 | 11.83 | 916% | 15%
1n61c | 61 | 1 | 61 | 27.92 | 388% | 6%
31n2c | 62 | 31 | 2 | 8.34 | 1300% | 21%
62n1c | 62 | 62 | 1 | 12.32 | 880% | 14%
2n31c | 62 | 2 | 31 | 14.09 | 769% | 12%
1n62c | 62 | 1 | 62 | 26.92 | 403% | 6%
7n9c | 63 | 7 | 9 | 6.15 | 1762% | 28%
9n7c | 63 | 9 | 7 | 6.48 | 1673% | 27%
21n3c | 63 | 21 | 3 | 6.87 | 1578% | 25%
63n1c | 63 | 63 | 1 | 12.5 | 867% | 14%
3n21c | 63 | 3 | 21 | 13.01 | 833% | 13%
1n63c | 63 | 1 | 63 | 27.62 | 392% | 6%
16n4c | 64 | 16 | 4 | 6.5 | 1668% | 26%
8n8c | 64 | 8 | 8 | 6.67 | 1625% | 25%
32n2c | 64 | 32 | 2 | 8.35 | 1298% | 20%
4n16c | 64 | 4 | 16 | 9.68 | 1120% | 17%
64n1c | 64 | 64 | 1 | 11.18 | 969% | 15%
2n32c | 64 | 2 | 32 | 12.15 | 892% | 14%
1n64c | 64 | 1 | 64 | 27.44 | 395% | 6%

As shown above, the calculation time can be reduced from 108 seconds for a single core to  6.5 seconds for a 64 core in the case of using 16 processes and 4 threads. The calculation efficiency is increased by ca. 17 times, but the cpu utilization rate is only 26%. Actually, the calculation time converges at ca. 20 CPU cores that still has 60% cpu utilization in the case of using 4 processes and 5 threads, as shown below:

![image](https://user-images.githubusercontent.com/68883727/96335206-a9401a00-10a9-11eb-8fb9-0d317cfec31e.png)

Therefore, do you have any method to improve the cpu utilization? You know, it is very important, especially for large systems, because  they usually require a lot of cpu cores. If not, is there any way to quickly get the cut-off of cpu cores?

Besides, in most cases, neither using one process and the largest thread, nor using the largest process core and one thread is the optimal solution. It is very strange that the most effective process and thread configuration seems to have nothing to do with some existing parameters, such as the number of reduced k-points, bands, states and so on. Do you have any suggestions for this?

Best,
Pan

**Comment by shankar1729** [comment]
HI Pan,

Thank you for the detailed performance tests! Such systematic benchmarks are always very useful.

First, in the current parallelization note that you cannot really use more than 12 MPI processes efficiently since the states (reduced k-pts) are the only thing parallelized over MPI.

Second, this system is on the smaller side and LCAO initialization is not representative of the actual minimize / SCF in computational cost and efficiency. A better test would be of a certain number of minimize steps or SCF cycles starting from an initial random wave functions or initial state read in. Both factors mentioned above put this system in the FFT-dominated regime of performance: you have a large box with a lot of empty space and relatively few bands. The FFTs tend not to get full CPU usage once you are allocating several cores/threads per MPI process, especially at this small - intermediate system size. When you go to larger systems, and enter a BLAS / LAPACK dominated regime, you should see much better CPU usage.

Regardless, it would be nice to see this benchmark for minimize and/or SCF instead of LCAO. Also, it is not particularly useful to go over all possible combinations as many of them lead to weird splits of the available cores and don't fit neatly into the two socket hardware you describe. I would suggest only doing combinations of -n 1, 2, 4, 6, 12 with -c 1, 2, 3, 4, 6, 8, 12, 16, 32, 64 such that satisfy n*c <= 64. (That should be much fewer than your list above.)

When we get our band-parallelized code out next year, I would love to see such benchmarks again too!
Best,
Shankar
