### ISSUE TITLE
How to set "coulomb-truncation-embed"?

### ISSUE THREAD

**Issue by gvenus** [shankar1729/jdftx#144]
Hi, is there any guideline or algorithm to set the value of coulomb-truncation-embed properly? 

I used the xyzToIonposOpt NH3.xyz 15 command to make the input files, and set the value of coulomb-truncation-embed as 0 0 0. But the calculation stopped with the error saying 

    "Atom 1 lies within the margin of 1 bohrs from the truncation boundary.
      Expand unit cell, or if absolutely sure, reduce coulomb-truncation-ion-margin."
The error still exists even when I set coulomb-truncation-ion-margin as 1. 

What causes the problem and how do I solve it?

**Comment by shankar1729** [comment]
Please post the input file  with dependencies (lattice, ionpos etc.) that gave these errors.

**Comment by gvenus** [comment]
# struct.lattice
lattice \
        15.7332 0 0 \
        0 17.6803 0 \
        0 0 18.0949

#struct.ionpos
#Ionic positions in cartesian coordinates:
ion  N   -0.36660    0.44666    0.00013 1
ion  H    0.36660    1.34014   -1.54744 1
ion  H    0.36656    1.34016    1.54744 1
ion  H    0.36659   -1.34016    0.00018 1

#mol-geo.in 
include struct.lattice
include struct.ionpos

core-overlap-check None
coulomb-interaction Isolated
coulomb-truncation-embed 0 0 0
coulomb-truncation-ion-margin 1

ion-species GBRV/$ID_pbe.uspp
elec-cutoff 20 100

dump-name molecule.$VAR    #Filename pattern for saving outputs
dump End State          #Output State i.e. everything needed to resume the calculation

ionic-minimize \
    nIterations 50 \
    energyDiffThreshold 1e-6 \
    knormThreshold 1e-4  #Threshold on RMS cartesian force

fluid LinearPCM
pcm-variant CANDLE
fluid-solvent H2O
fluid-cation Na+ 1.
fluid-anion F- 1.

target-mu ${mu}
elec-smearing fERMI 0.01

Thank you for your quick response!

**Comment by shankar1729** [comment]
Yep, as guessed above, coords-type is missing, so it is interpreting the coordinates to be fractional instead of Cartesian. Adding coords-type Cartesian should fix it.

Best,
Shankar

**Comment by gvenus** [comment]
Oh! Yeees! coords-type is defaulted to be lattice. Let me try!
