### ISSUE TITLE
What does 'TS' term mean in the energy summary part of the output file?

### ISSUE THREAD

**Issue by gvenus** [shankar1729/jdftx#148]
Dear Ravishankar,
I did optimization using the fixed potential method. What does the 'TS' term mean in the energy summary part of the output file?
![image](https://user-images.githubusercontent.com/30168671/99817758-b6767b80-2b23-11eb-8d38-ad5c6033ba52.png)

**Comment by shankar1729** [comment]
That's the electronic entropy contribution (T=temperature, S=entropy). Then, F = E - TS is Hemholtz free energy, and G = F + muN is grand free energy.

Best,
Shankar

**Comment by gvenus** [comment]
Thank you for the quick response. So, does it mean that if I want to add the zero-point-energy and vibrational entropy contributions, I need to do extra vibration calculations?

**Comment by shankar1729** [comment]
Yes, of course: this is free energy w.r.t the electronic system only. The nuclei are at zero temperature in these results, and will need vibrational contributions accounted for as in any other DFT code.

Best,
Shankar

**Comment by gvenus** [comment]
Thank you very much!
