### ISSUE TITLE
dumping outputfile error

### ISSUE THREAD

**Issue by Liuly98** [shankar1729/jdftx#149]
Hi Shankar,
Recently, I met a very strange error, when I did structure optimization using jdftx calculator through ase interface, it could converge successfully during the calculation, however, it could't dump the specified output file in the end. Did it actually mean that the calculation was failed, and if so, why did the Electrominimize calculation show converged?

[out.pdf](https://github.com/shankar1729/jdftx/files/5640099/out.pdf)

In the above uploaded file, it have done static calculations many times using jdftx calculator and it just broke in the final dumping process. Could you give me some suggestions about this error?
Thanks!

**Comment by shankar1729** [comment]
Unfortunately, the error message does not seem to have shown up: not sure where the stderr stream got piped to in the interface. However, my best guess is a filesystem permissions / capacity issue. Could it be that the temp directory created for the ASE-JDFTx run is somehow not writable by jdftx?
