### ISSUE TITLE
 fix-charge calculation with JDFT

### ISSUE THREAD

**Issue by 20190111** [shankar1729/jdftx#150]
Dear Dr. Shankar,
We know that fix-potential calculations(setting a target-mu) can be done with JDFTx, while can we carry out the general  fix-charge calculations with JDFTx ?  
We can obtain the excess electrons compared to a neutral system after the fix-potential calculation with a target mu and CANDLE, while if we start with the same excess electrons and carry out a fix-charge calculation with CANDLE, we may obtain the same mu as the fixed potential I think. So，I close the parameter target-mu and set elec-initial-charge -0.287(-0.287 means that the total electrons are 655.713 now,  the total electrons in the neutral system are 656) to carry out a calculation. But I get the nElectrons: 656 and the same free energy(F) and mu as the no-charge/no-fix-potential calculation, it seems that the elec-initial-charge -0.287 do nothing, Why is it ?
 
Best
Anna

**Comment by shankar1729** [comment]
Hi Anna,

Please post the output files of the fixed potential calculation in question.

Best,
Shankar

**Comment by 20190111** [comment]
Hi Shankar,
Here are my output files:
[outputs.zip](https://github.com/shankar1729/jdftx/files/5701038/outputs.zip)
There are two files in the output.zip, one named as fix-potentialchg-0.16529836.out, which I carry out the fixed -potential calculation by setting mu as -0.16529836, and I got the nElectrons: 647.713336(total number of electrons in the pseudopotential is 648 ) ; the other file named as fix-charge, which I set the elec-initial-charge -0.28666 without setting mu, then I got mu: -0.160676490  nElectrons: 648.000000. It seems that the parameter of elec-initial-charge could do nothing. I'm looking forward to your answers.

Best
Anna

**Comment by shankar1729** [comment]
Hi Anna,

The issue is that the fillings read in override the charge. This was done to avoid bugs in trying to continue calculations with the same fixed charge. So make sure you don't read in fillings at one charge when you are trying to run another charge. Either drop the initial-state, or read only wfns and fluidstate using separate commands, or most simply, just remove the sol.fillings file before starting.

Best,
Shankar
