### ISSUE TITLE
Parameters for fluid-cation

### ISSUE THREAD

**Issue by shk11** [shankar1729/jdftx#151]
Dear Shankar,

I want to use Li+ as an additional fluid-cation (in combination with GLSSA13/NonLinearPCM). Are there any preliminary parameters for the Li-Cation available yet and if not, would it be possible to get some further information or advise for the optimization of the site properties?

Best,
Daniel

**Comment by shankar1729** [comment]
What solvation model are you using? If it is anything other than ClassalDFT or SaLSA, the identity of the ion in the fluid irrelevant. They are all effectively generic non-adsorbing electrolytes. 

Best,
Shankar

**Comment by shk11** [comment]
Hi Shankar, 

my idea was to an initial study of electrode materials for Li-ion batteries within the framework of the NonLinearPCM/GLSSA13 model and extend it in a second step to the SaLSA approach.

Best,
Daniel

**Comment by shankar1729** [comment]
In that case, just use Na+ and F- as the representative non-adsorbing electrolyte as suggested in the tutorials. For NonlinearPCM, GLSSA13 or CANDLE, it will make no difference what ions you put there.

Best,
Shankar
