### ISSUE TITLE
wannier for magnetic material

### ISSUE THREAD

**Issue by Jing606** [shankar1729/jdftx#152]
Dear Dr.Shankar,

I am now trying to use wannier method for magnetic material Fe and set" spintype vector-spin", but I am confused about these outputs:
1. For the dft band structure calculation, the output bandstruct.eigenval only includes information of spin 0, could I know how to obtain the electronic structure for spin-up and spin-down respectively?
2. The suffix of totalE output are n_re, n_im, n_up, n_dn, could I know what's the relation of n_re and n_im to n_up and n_dn, and if I want to use wannier code for only spin-up electrons, could I just specify "spinMode Up"  in wannier.in file? Could you give some suggestion on that?

Attached is the zip of my input and output files. Thanks for your help in advance.
https://rice-my.sharepoint.com/:u:/g/personal/jz88_rice_edu/ET2T2e0teK5Ns2jp0Yyo6ZsBOCduJ8gQpX1L9YjyK-2VEw?e=JGHfGL

Best,
Jingyi

**Comment by Jing606** [comment]
I just updated something, here is the latest version: https://rice-my.sharepoint.com/:f:/g/personal/jz88_rice_edu/EpBL4ttG8BhPvN6feI4TT0ABSI30yttjIJGsh-NOdhuhzg?e=iVDwY0

**Comment by shankar1729** [comment]
Hi Jingyi,

If you want to do "up" and "down" spins, then you are looking for spintype z-spin. That will create two sets of band eigenvalues for each k etc. In the vector-spin mode (a noncollinear mode), spin could be in any direction at each point in space, and there is no up/down that is well-defined.

The n_re and n_im along with n_up and n_dn define the 2x2 spin density matrix at each point in space. Re and Im refer to the real and imaginary part of the off-diagonal component.

Best,
Shankar
