### ISSUE TITLE
Crash NonlinearPCM / elec-initial-charge

### ISSUE THREAD

**Issue by shk11** [shankar1729/jdftx#153]
Hello Shankar,

I have run into an issue with the tag "elec-initial-charge" in combination with the non-linear PCM/GLSSA13 model. While for the linear model the calculation runs smoothly (jdftx_linear.log, calculation was cancelled after 30 minutes), in the nonlinear case the same calculation crashes at the initiation of the first "Electron <-> Fluid self-consistency loop" (jdftx_nonlinearPCM.log).
The problem occurs both with and without the fluid-anion/fluid-cation tag. Using the self-consistent field optimisation for non-linear PCM fluids resulted in the same issue.

[jdftx_linear.log](https://github.com/shankar1729/jdftx/files/5994424/jdftx_linear.log)
[jdftx_nonlinearPCM.log](https://github.com/shankar1729/jdftx/files/5994300/jdftx_nonlinearPCM.log)
We could reproduce the problem regardless of the selected version (GPU, CPU) (tested with icc 2018 gcc 9.3, both in combination with Intel MKL 2018, openMPI 4.0 and CUDA 11.0 for the GPU version).

Do you have any idea why this might be?

Best wishes,
Daniel

**Comment by shankar1729** [comment]
Hi Daniel,

It appears I broke the nonlinear fluid's iterative mechanism in a recent unrelated performance optimization. I just pushed commits to fix this bug, thanks for reporting it!

Additionally, consider trying the alternate mechanism for nonlinear fluid convergence using the commands:

```
fluid-solve-frequency Inner
pcm-nonlinear-scf
```

This may give you better convergence than the old mechanism (still the default) in many cases.

Best,
Shankar
