### ISSUE TITLE
Negatively charged slab hardly to converge

### ISSUE THREAD

**Issue by zhichao-1699** [shankar1729/jdftx#155]
Dear shankar,
  I am currently using jDFTx to test a series of  charged slabs (like Pt-111/IrO2-110) to calculate the Grand canonical potential. But I found some problems. 
  The first one is that the negatively charged Pt-slab cannot converge even at the tolerance of 1e-6. The common parameters I choose are almost the same as the tutorial http://jdftx.org/MetalSurfaces.html, except that I included 'elec-initial-charge +2.0' in the common.in. The vacuum case cannot converge after 150 SCF steps, not to mention the solvated case :(
  Besides, I also considered about the IrO2-110 slab. This case could converge at 1e-6, but I found that if I change the vacuum thickness, the total energy do not stay constant as the positive cases. Does it mean that the correction scheme is not suitable for negatively charged case?

![IrO2-110-vac-corr](https://user-images.githubusercontent.com/67491987/110728734-8250d300-8258-11eb-8214-4f7f1cf20b0b.jpg)

  Could you please give me some advice about the problems? Is there any other parameter needed to be considered? Thanks a lot.
Best,
Zhichao

**Comment by shankar1729** [comment]
Dear Zhichao,

How many atoms do these slabs have? Adding two full electrons to a slab with five atoms or so is way too much. Your convergence issues are most likely due to these extra electrons being unbound and wanting to escape the slab. In terms of potential, this works be equivalent too raising it beyond the work function, freeing the electrons!

**Comment by zhichao-1699** [comment]
> Dear Zhichao,
> 
> How many atoms do these slabs have? Adding two full electrons to a slab with five atoms or so is way too much. Your convergence issues are most likely due to these extra electrons being unbound and wanting to escape the slab. In terms of potential, this works be equivalent too raising it beyond the work function, freeing the electrons!
> 
> Note that the positive case is different. You can remove many electrons without instability. Only adding more electrons can lead then to become unbound.
> 
> Best,
> Shankar

**Comment by zhichao-1699** [comment]
Hi Shankar,
  Thanks for your reply. I just noticed the problem. IrO2 slab has 56 atoms and maybe it is why this case could converge (Although it converges very slowly after over 90 electronic steps ). I will try larger Pt slabs or reduce the number of additional electrons and see how it will change.
  Now I am more confusing about the second question. How can we explain the divergence of vacuum thickness with the correction scheme ? (It is the IrO2-110 slab with 2 more electrons,  while the correction shows great performance in the positive cases)? It could be partially reduced by applying the CANDLE solvation model, but the convergence tolerance is still not as good as neutral and positive cases.
![IrO2-110-sol-corr](https://user-images.githubusercontent.com/67491987/110780564-cca97280-829f-11eb-83cb-6f13330c14bf.jpg)

Best,
Zhichao

**Comment by zhichao-1699** [comment]
Hi Shankar,
  Thanks for your reply. I just noticed the problem. IrO2 slab has 56 atoms and maybe it is why this case could converge (Although it converges very slowly after over 90 electronic steps ). I will try larger Pt slabs or reduce the number of additional electrons and see how it will change.
  Now I am more confusing about the second question. How can we explain the divergence of vacuum thickness with the correction scheme ? (It is the IrO2-110 slab with 2 more electrons,  while the correction shows great performance in the positive cases)? It could be partially reduced by applying the CANDLE solvation model, but the convergence tolerance is still not as good as neutral and positive cases. Thanks.
![IrO2-110-sol-corr](https://user-images.githubusercontent.com/67491987/110780564-cca97280-829f-11eb-83cb-6f13330c14bf.jpg)

Best,
Zhichao

**Comment by shankar1729** [comment]
Hi Zhichao,

Slabs in vacuum or pure solvent (no ions) will be handled correctly by coulomb-truncation only for neutral slabs. (Truncation will take care of dipoles and all higher multipoles very accurately, but not multipoles.) 

To do charged slabs correctly, you must use a solvent with ions as discussed in the tutorials.

Best,
Shankar
