### ISSUE TITLE
Different mu while changing the number of mpi processes

### ISSUE THREAD

**Issue by aaggX** [shankar1729/jdftx#156]
Dear Shankar,

We are studying a neutral surface using Candle but when we change the number of mpi processes of the run, we are obtaining a different mu for each calculation. The free energy looks the same and our binaries( 1.5.0)  passed all the tests. Any idea where can we start looking to avoid this issue?

|Number of mpi processes  |          F      |                                            mu|
|---|---|---|
|16  |                       -1813.6828439732037168   |      mu  : -0.215795|
|8     |                      -1813.6828439730343234  |       mu  : -0.228043|

Thank you 

Alfredo

**Comment by shankar1729** [comment]
Hi Alfredo,

This is quite an interesting issue! My best guess for why mu is changing with negligible impact to the free energy is that the system is a semiconductor / insulator. In this case, the unoccupied states have negligible impact on the total energy, may not be fully converged (without converge-empty-states or electronic-SCF with unusually high nEigSteps) and hence may end up with different eigenvalues with numerical differences between the different number of processes. This would, in turn, make the mu sensitive to the specific partially converged empty states.

Please check whether the TS in energy components is very small to see if this is true. If this actually happened for a metallic system or a narrow-enough gap material that TS is significant, please share both the log files and I'll see how this could be happening.

Thanks!
Best,
Shankar

**Comment by aaggX** [comment]
Hi Shankar,

You are right, we are working with a semiconductor. Thanks for your help.
