### ISSUE TITLE
Many spikes in calculated DOS

### ISSUE THREAD

**Issue by sergbuto** [shankar1729/jdftx#157]
Dear Shankar,

I have recently installed JDFTx. The installation went fine and all the tests were passed. However, when I calculated DOS for a couple of different systems (insulator and metal) using the default settings, the DOS showed many strong spikes (like a delta function) in both cases. What could be the reason for that and how to eliminate those without significant smearing/broadening of the DOS.? I would attach two images showing these spikes but I did find out how I can do that.

**Comment by shankar1729** [comment]
Were these delta functions at energies signiciantly below the Fermi level / VBM? These would be the semi-core bands from the pseudopotentials then. Just change your axis range in plotting to exclude them.

If not, then the only options are to use a small Esigma in the density-of-states command and potentially increase the k-point sampling.

Best,
Shankar

**Comment by sergbuto** [comment]
No, these spikes appear throughout the whole calculated energy range of the valence and conduction bands on top of the calculated DOS. The use of a small Esigma produces a huge number of points in the written file but does not fully eliminates the problem. The DOSs were calculated for kpoint-folding 8 8 8 and 12 12 12, i.e. the number of k-points were not that small.

**Comment by sergbuto** [comment]
No, these spikes appear throughout the whole calculated energy range of the valence and conduction bands on top of the calculated DOS. The use of a small Esigma produces a huge number of points in the written file but does not fully eliminates the problem. The DOSs were calculated for kpoint-folding 8 8 8 and 12 12 12, i.e. the number of k-points were not that small.

I have attached the images.

Best,
Sergei

**Comment by shankar1729** [comment]
The images don't seem to have come through. You need to use the online interface (not email) to drag-drop figure attachments.

Please also specify the type of system you are calculating DOS for.

Best,
Shankar

**Comment by sergbuto** [comment]
![example-dos](https://user-images.githubusercontent.com/81984128/113607169-315eaf80-9649-11eb-9060-13be11151d25.jpg)
![example-dos2](https://user-images.githubusercontent.com/81984128/113607187-34f23680-9649-11eb-9f96-aa646217b9c4.jpg)

**Comment by shankar1729** [comment]
This would be a signature of two adjacent k-points in the k-mesh yielding (nearly) the same energy for a band: that leads to a spike in the tetrahedron method. Your best bet will be to use a small Esigma ~ 1e-3 Eh. 

Best,
Shankar

**Comment by sergbuto** [comment]
I have tried to increase the number of k-points. Unfortunately, this did not eliminate the spike problem. Esigma ~ 1e-3  produced too large broadening in my opinion. I guess, I'll stick to Esigma ~ 5e-4  as a compromise.

Thank you for your answers.

**Comment by shankar1729** [comment]
I see: thanks for letting me know. Also one final thing, some times using an odd / even k-mesh can avoid the near degeneracies and prevent spikes. For production calculations, I always prefer to use Monte Carlo sampling via Wannierization for artefact-free DOS.

Best,
Shankar

**Comment by J-Plankton** [comment]
Dear Shankar,
I have recently followed the tutorials to calculate the density of state. The DOS of Si in the example was obtained as same as the result in the example. Then I started to calculate DOS of a two-dimension material which included transition metal, carbon and nitrogen. Unfortunately, the DOS only showed  strong spikes. The output file was 1-dos-total.output. After that, I followed your suggestions above, and changed the Esigma as 1e-3 Eh and K-points as 5 5 1.  The result (2-dos-total-JDFTx.jpg) seemed to be better, but still showed many strong spikes. The corresponding output file was 2-dos-total.output. I used the 551 k-points to calculate the this system in VASP, and the result  (2-dos-total-JDFTx.jpg) seemed to be fine.  Could you help me to check the settings in my calculation ?  What could be the reason for this situation? 

THANKS,
Lois
[1-dos-total.output.txt](https://github.com/shankar1729/jdftx/files/8185943/1-dos-total.output.txt)
[2-dos-total.output.txt](https://github.com/shankar1729/jdftx/files/8185947/2-dos-total.output.txt)

![2-dos-total-JDFTx](https://user-images.githubusercontent.com/34933797/156766016-fa36ba02-d949-47dd-8299-bd1bdf510772.jpg)
![2-dos-total-vasp](https://user-images.githubusercontent.com/34933797/156766219-90b38669-82eb-486f-b60e-3a47a5749bfb.JPG)

**Comment by shankar1729** [comment]
Did you zoom into the energy range of the valence/conduction bands? It looks like the spike you are referring to is the semi-core states from your pseudopotential. Note that the energy in the JDFTx DOS output is in Hartrees, so the range you are looking at in VASP will all be within -1 to 0.2 or so Hartrees.

Additionally, for the low k-point sampling of 5x5x1, you may need more broadening. It looks like the VASP result you showed has a broadening on the order of 0.1 - 0.2 eV, which would be about 0.005 to 0.01 Eh, 5-10x larger than you used.

Best,
Shankar

**Comment by J-Plankton** [comment]
Dear  Shankar,
Thanks for your suggestions. My problems were solved after converting units and using a larger value of Esigma. In the subsequent study, I have some questions about the Fermi level (Ef) of a system calculated by JDFTx：
1. For a neutral surface calculation, does the final 'mu' equal Ef?
2. For fixed-potential surface calculation, does the fixed 'mu' equal Ef?  
I got confused by one figure in the paper as follows. The authors calculated the DOS of a metal oxide slab model at different fixed potentials. My understanding of question 2 is that the surface is charged by donating or accepting electrons from the "Virtual electrode“ to match the surface Ef at the fixed potential, so the fixed 'mu' equals  Ef in a fixed potential calculation. Based on this understanding, the blue dotted line (the fixed potential) and the red dotted line (the Fermi level) should coincide. Apparently, they were not coincident lines. Could you give me some explanation?
![fig](https://user-images.githubusercontent.com/34933797/156999696-909a7f64-dbdf-4a10-a96d-51d4d08580af.png)

**Comment by shankar1729** [comment]
Hi Lois,

JDFTx's DOS is in states/Hartree/unit cell. See documentation of [command density-of-states](http://jdftx.org/CommandDensityOfStates.html).

So if VASP's is in states/eV/cell, the JDFTx one would be smaller by 27.2x.

Best,
Shankar
