### ISSUE TITLE
classical DFT for fluid

### ISSUE THREAD

**Issue by maofeng** [shankar1729/jdftx#16]
Dear Ravishankar 

I'd like to play with fluid1D sub-project to study the fluid properties with different functionals, after compiled the fluid1D separately, I got "libfluid1D.dylib", can you kindly let me know how to use fluid1D (like input, output, or scripts)to study the fluid properties, e.g., pair distribution function etc? 

Thank you
cheers
maofeng

**Comment by shankar1729** [comment]
Hi Maofeng,

Compile the executables within the tests subdirectory.

fluid1D is a fairly hacky research code :). It doesn't really have any clearly-defined input files. You would need to modify one of these test executables that link to the common library to do what you want it to, or add a similar one to those. 

Happy hacking!
Shankar
