### ISSUE TITLE
Slow Performance in make test

### ISSUE THREAD

**Issue by carbusta** [shankar1729/jdftx#163]
Hello,

I've installed JDFTx on one of our servers running Debian with a non-root installation of GSL.

The server has an AMD EPYC 7702p (64c/128t) and 512 GB RAM. Single thread performance is on-par with the E5-2620 used in the html docs [https://www.cpubenchmark.net/compare/AMD-EPYC-7702P-vs-Intel-Xeon-E5-2620-v4/3555vs2766](url)

I modified FindCBLAS.cmake line 3 to be
`find_library(CBLAS_LIBRARY NAMES gslcblas PATHS ${CBLAS_PATH})`
so that it uses GSL's implementation of cblas by specifying the CBLAS_PATH to be GSL's path (I had difficulties getting .so files for cblas otherwise).

Running `make test` takes nearly 2 hours with no errors -- see output below.

I've also tried creating a non-root install of FFTW3 and building with it instead, with no change in performance.

Any ideas of things to try to improve performance?

Thanks,

Joshua

`make test` output:

Running tests...
Test project /home/jmann/jdftx/build
      Start  1: openShell
 1/10 Test  #1: openShell ........................   Passed   82.07 sec
      Start  2: vibrations
 2/10 Test  #2: vibrations .......................   Passed  102.15 sec
      Start  3: moleculeSolvation
 3/10 Test  #3: moleculeSolvation ................   Passed  277.22 sec
      Start  4: ionSolvation
 4/10 Test  #4: ionSolvation .....................   Passed  169.53 sec
      Start  5: latticeOpt
 5/10 Test  #5: latticeOpt .......................   Passed  1897.47 sec
      Start  6: metalBulk
 6/10 Test  #6: metalBulk ........................   Passed  1710.41 sec
      Start  7: plusU
 7/10 Test  #7: plusU ............................   Passed  427.78 sec
      Start  8: spinOrbit
 8/10 Test  #8: spinOrbit ........................   Passed  781.74 sec
      Start  9: graphene
 9/10 Test  #9: graphene .........................   Passed  172.57 sec
      Start 10: metalSurface
10/10 Test #10: metalSurface .....................   Passed  926.18 sec

100% tests passed, 0 tests failed out of 10

Total Test time (real) = 6547.18 sec

**Comment by shankar1729** [comment]
I think your issue is all in the BLAS: the timings reported in the html docs were based on an MKL build, and those with ATLAS are about the same. If you linked to a reference BLAS such as that provided by GSL, your matrix multiply and diagonalization performance will be at least an order of magnitude worse.

I would recommend installing ATLAS, and making sure that you are linking to it for both BLAS and LAPACK, and that you are not relying on GSL.

Best,
Shankar

**Comment by carbusta** [comment]
Hi Shankar,

I've installed ATLAS, but was unable to do it properly for now (using the aptly named --cripple-atlas-performance option), with CPU throttling enabled and oftentimes other users utilizing the computer's full CPU resources. So the AT in ATLAS is somewhat nullified in this case.

I suppose the "automatically tuned" part of ATLAS is strictly necessary to see these improvements as performance is actually slightly worse than before.

So I guess this is just an update -- I'll report back when I get a proper installation done.


Thanks,

Joshua

**Comment by carbusta** [comment]
Hi Shankar,

Here is a final update. I've properly installed ATLAS and ran make test. The timings are below. While the sequential speed has improved slightly it is still quite slow. I'd also note that while it has 64c/128t available it is only utilizing up to about 6 cores. Running with MPI helps a lot, bringing the runtime down to 1000 s. Forcing the number of MPI threads to 16 improves the lattice-based operations (what I intend to work with) considerably. The parallelization is likely what I was missing in the first place.

I am satisfied with these results.

**Sequential:**
Running tests...
Test project /home/jmann/jdftx/build
      Start  1: openShell
 1/10 Test  #1: openShell ........................   Passed   69.87 sec
      Start  2: vibrations
 2/10 Test  #2: vibrations .......................   Passed   81.59 sec
      Start  3: moleculeSolvation
 3/10 Test  #3: moleculeSolvation ................   Passed  242.42 sec
      Start  4: ionSolvation
 4/10 Test  #4: ionSolvation .....................   Passed  146.89 sec
      Start  5: latticeOpt
 5/10 Test  #5: latticeOpt .......................   Passed  1532.67 sec
      Start  6: metalBulk
 6/10 Test  #6: metalBulk ........................   Passed  1220.73 sec
      Start  7: plusU
 7/10 Test  #7: plusU ............................   Passed  381.30 sec
      Start  8: spinOrbit
 8/10 Test  #8: spinOrbit ........................   Passed  645.53 sec
      Start  9: graphene
 9/10 Test  #9: graphene .........................   Passed  154.07 sec
      Start 10: metalSurface
10/10 Test #10: metalSurface .....................   Passed  809.41 sec

100% tests passed, 0 tests failed out of 10

Total Test time (real) = 5284.53 sec


**Parallel (-n %d):**
Running tests...
Test project /home/jmann/jdftx/build
      Start  1: openShell
 1/10 Test  #1: openShell ........................   Passed   38.94 sec
      Start  2: vibrations
 2/10 Test  #2: vibrations .......................   Passed   73.08 sec
      Start  3: moleculeSolvation
 3/10 Test  #3: moleculeSolvation ................   Passed  294.15 sec
      Start  4: ionSolvation
 4/10 Test  #4: ionSolvation .....................   Passed  177.37 sec
      Start  5: latticeOpt
 5/10 Test  #5: latticeOpt .......................   Passed  133.46 sec
      Start  6: metalBulk
 6/10 Test  #6: metalBulk ........................   Passed   99.72 sec
      Start  7: plusU
 7/10 Test  #7: plusU ............................   Passed   32.83 sec
      Start  8: spinOrbit
 8/10 Test  #8: spinOrbit ........................   Passed   48.70 sec
      Start  9: graphene
 9/10 Test  #9: graphene .........................   Passed   17.71 sec
      Start 10: metalSurface
10/10 Test #10: metalSurface .....................   Passed  123.79 sec

100% tests passed, 0 tests failed out of 10

Total Test time (real) = 1039.80 sec


**Parallel (-n 16):**
Running tests...
Test project /home/jmann/jdftx/build
      Start  1: openShell
 1/10 Test  #1: openShell ........................   Passed   22.46 sec
      Start  2: vibrations
 2/10 Test  #2: vibrations .......................   Passed   25.49 sec
      Start  3: moleculeSolvation
 3/10 Test  #3: moleculeSolvation ................   Passed  233.05 sec
      Start  4: ionSolvation
 4/10 Test  #4: ionSolvation .....................   Passed  308.43 sec
      Start  5: latticeOpt
 5/10 Test  #5: latticeOpt .......................   Passed   22.98 sec
      Start  6: metalBulk
 6/10 Test  #6: metalBulk ........................   Passed   13.15 sec
      Start  7: plusU
 7/10 Test  #7: plusU ............................   Passed   10.13 sec
      Start  8: spinOrbit
 8/10 Test  #8: spinOrbit ........................   Passed    7.74 sec
      Start  9: graphene
 9/10 Test  #9: graphene .........................   Passed    7.10 sec
      Start 10: metalSurface
10/10 Test #10: metalSurface .....................   Passed   66.14 sec

100% tests passed, 0 tests failed out of 10

Total Test time (real) = 716.73 sec

**Build configuration**

cmake -D LinkTimeOptimization=yes -D CompileNative=yes -D GSL_PATH=/home/jmann/jdftx/gsl/ -D CBLAS_PATH=/home/jmann/jdftx/atlas/ -D ATLAS_PATH=/home/jmann/jdftx/atlas/ ../jdftx-1.6.0/jdftx
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.20.1")
-- Looking for gsl_integration_glfixed_point
-- Looking for gsl_integration_glfixed_point - found
-- Found GSL: /home/jmann/jdftx/gsl/lib/libgsl.so
-- Looking for pthread.h
CMake Warning (dev) at /usr/share/cmake-3.13/Modules/CheckIncludeFile.cmake:70 (message):
  Policy CMP0075 is not set: Include file check macros honor
  CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  CMAKE_REQUIRED_LIBRARIES is set to:

    /home/jmann/jdftx/gsl/lib/libgsl.so;/home/jmann/jdftx/gsl/lib/libgslcblas.so;;m

  For compatibility with CMake 3.11 and below this check is ignoring it.
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindThreads.cmake:121 (CHECK_INCLUDE_FILE)
  CMakeLists.txt:68 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found FFTW3:  /usr/lib/x86_64-linux-gnu/libfftw3_threads.so /usr/lib/x86_64-linux-gnu/libfftw3.so
-- Found LAPACK: /home/jmann/jdftx/atlas/lib/libsatlas.so
-- Found CBLAS: /home/jmann/jdftx/atlas/lib/libcblas.so
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1")
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- Performing Test HAS_NO_UNUSED_RESULT
-- Performing Test HAS_NO_UNUSED_RESULT - Success
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Performing Test HAS_TEMPLATE_DEPTH
-- Performing Test HAS_TEMPLATE_DEPTH - Success
-- Performing Test HAS_MARCH_NATIVE
-- Performing Test HAS_MARCH_NATIVE - Success
-- Performing Test HAS_FAST
-- Performing Test HAS_FAST - Failed
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jmann/jdftx/build

**Comment by shankar1729** [comment]
Hi Joshua,

Thank you for the updates! In the last year, AMD seems to have put in a lot of work in competing with Intel and NVIDIA on their their CPU and GPU performance libraries. Specifically for the CPU, they are now providing optimized BLAS and LAPACK libraries at:

    https://developer.amd.com/amd-aocl/blas-library/

These may be worth looking into for further optimization, but may require tinkering a bit with the jdftx cmake scripts as we have not tried these yet.

Best,
Shankar
