### ISSUE TITLE
Magnetization

### ISSUE THREAD

**Issue by davidwaroquiers** [shankar1729/jdftx#164]
Dear Shankar,

I wanted to know if there was a way to directly have the magnetization at the end of the electronic minimization. It is indeed output for each iteration (be it SCF or minimize), e.g.: 

-------- Electronic minimization -----------
Will mix electronic density at each iteration.
	FillingsUpdate:  mu: +0.691221646  nElectrons: 16.000000  magneticMoment: [ Abs: 2.30122  Tot: +2.24868 ]
	FillingsUpdate:  mu: +0.681756371  nElectrons: 16.000000  magneticMoment: [ Abs: 2.30122  Tot: +2.24868 ]
SCF: Cycle:  0   F: -124.282310398001073   dF: -3.123e-03   |Residual|: 2.737e-01   |deigs|: 3.642e-02  t[s]:      3.76
	FillingsUpdate:  mu: +0.603693804  nElectrons: 16.000000  magneticMoment: [ Abs: 2.19230  Tot: +2.07526 ]
SCF: Cycle:  1   F: -124.306873151343765   dF: -2.456e-02   |Residual|: 1.989e-01   |deigs|: 7.670e-02  t[s]:      4.34

But it is not output for the final density. Indeed, if I'm not wrong, the FillingsUpdate just before each iteration lines refer to the input density before the iteration in question.

Of course it is easy to compute it from the n_up and n_dn and the lowdin population analysis provides an estimate if you sum up all of the magnetic-moments for each atom. In any case, when the system is converged, this should be very different from the just previous iteration in any case.

Thanks a lot,

David

**Comment by shankar1729** [comment]
Dear David,

The FillingsUpdate corresponds to the SCF cycle / minimize energy line that immediately follows it. (This output is emitted by the routine that updates the electron density etc. before the energy computation at the current wavefunctions reported by SCF / minimize.)

So the last FillingsUpdate line should be precisely the line to look at for the final chemical potential, electron count, magnetic moments etc. In any case, once you are close to convergence, these numbers should not be changing very much.

Best,
Shankar

**Comment by davidwaroquiers** [comment]
Dear Shankar,

Thank you for your rapid answer. Indeed, that is what I understood from my tests. What I mean is that then, if you compute the magnetization from the output densities, you don't get the exact same value (of course as you say, these numbers do not change much when you are close to convergence).

Best,

David

**Comment by shankar1729** [comment]
Hi David,

That's strange: can you show an example where the numbers computed from the density differ significantly? The magnetization reported in the fillings update is computed directly from the occupation factors, while integrating over the density could have slight numerical deviations in the normalization of each band's density, especially for ultrasoft pseudopotentials, but these should still be much below the 1E-6 level.

Best,
Shankar

**Comment by davidwaroquiers** [comment]
Hi Shankar,

As you say, when the calculation is converged, there is no way these differ significantly, but the last magnetization reported in the output file is not the same as the one that you can compute from the density. I did a test for BCC Fe in which I cranked down the parameters so that it runs in 5 secs, so there is no physics here of course ;-)

I did one run with 2 scf iterations and one run with 3 scf iterations. The last reported total and absolute magnetizations reported in the output file of the run with 3 scf iterations is exactly equal to the total and absolute magnetizations that I can compute "manually" from the electronic densities of the run with 2 scf iterations.

Here is an archive with the input, output and densities of the two runs, as well as a python script that does the comparison:

[example_magnetization.tar.gz](https://github.com/shankar1729/jdftx/files/6399752/example_magnetization.tar.gz)

In any case, again, it's not an issue as long as the calculation is converged.

Best,

David

**Comment by shankar1729** [comment]
I see: looking back at my code from several years ago, it does seem that the magnetization reported is from the previous density and not from the current occupations.

Best,
Shankar
