### ISSUE TITLE
H-atom: HGH/SIC

### ISSUE THREAD

**Issue by theonov13** [shankar1729/jdftx#165]
Hi, 

I wanted to use your JDFTx code to perform some reference calculations. 
Doing so, I started with the H atom from the examples:  

https://github.com/shankar1729/jdftx/blob/master/jdftx/test/openShell/Hatom.in

However, I was interested to use GTH/HGH pseudopotentials. 
In the documentation and in some forum, I found that HGH in UPF format should work.

https://sourceforge.net/p/jdftx/discussion/general/thread/9183c972/?limit=25

Thus, I tried to download it from the QE website 

https://www.quantum-espresso.org/upf_files/H.pz-hgh.UPF

However, I end up with strange Segmentation Fault/ MPI error messages. 
It seems this is the case for all hgh.UPF files where all electrons 
are treated as valence, e.g., 

https://www.quantum-espresso.org/upf_files/H.pz-hgh.UPF
http://www.quantum-espresso.org/upf_files/He.pz-hgh.UPF
http://www.quantum-espresso.org/upf_files/Li.pz-s-hgh.UPF

On the other hand, the HGH with Zval = 1 for Li seems to work 

http://www.quantum-espresso.org/upf_files/Li.pz-hgh.UPF

Is there a way to overcome this issue? 
I would also be happy if HGH would be available in 
other supported formats (uspp, fhi, etc.). 

Further, the H atom is a prototypical system 
to check self-interaction correction methods, 
where LDA SIC should typically improve the 
total energy to 
-0.4995 to -0.4999 Hartree (depending on the numerical accuracy). 
For the H atom a proper self-consistent SIC or localization 
should not play a crucial role. 

In JDFTx, using 

- elec-ex-corr lda-VWN
- ion-species GBRV/$ID_pbe.uspp
- elec-cutoff 50

I find

- Etot   =   -0.478642
- ESIC =    0.012643
- EPZ ~     -0.478642 - 0.012643 = -0.491285

Increasing the energy cutoff does not 
influence the results significantly. 
I also tried the various options for 
coulomb-interaction (Periodic, Spherical, isolated) 
which also does not influence the result significantly. 

However, changing the pseudopotential changes the 
result drastically. This is why I want to check 
what happens if one uses GTH/HGH pseudopotentials. 

With 
- ion-species SG15/H_ONCV_PBE-1.0.upf

I get 

- Etot  =  -0.478579
- ESIC =   0.020388
- EPZ ~   -0.478579 - 0.020388 = -0.498967

Besides the parameters (Ecut, Ecutrho=4Ecut), is there
another numerical parameter in JDFTx I can tune to get 
"better" numerics? 

I would be grateful for any help or advice. 

Best, 
Sebastian 

Example for input file
```Bash
lattice Cubic 16
ion H  8.00  8.00  8.00  1

spintype z-spin
elec-initial-magnetization +1 yes

elec-ex-corr lda-VWN

ion-species GBRV/$ID_pbe.uspp

elec-cutoff 50

coulomb-interaction isolated
coulomb-truncation-embed 8.0 8.0 8.0

dump End EigStats SelfInteractionCorrection
```

**Comment by shankar1729** [comment]
Hi Sebastian,

I pushed two commits to git just now:

- The all-electron HGH pseudopotentials were purely local, and this triggered a bug in JDFTx where it was trying to determine the core radius from the nonlocal projectors (and there were none). That was an easy fix.
- It looked like the folks who implemented SIC in JDFTx had not accounted for ultrasoft augmentation; hence the discrepancy for GBRV pseudopotentials. I now get around -0.4989 Eh for GBRV and SG15 at their recommended cutoffs (of 20 100, and 30 respectively), and also for the HGH you linked at 50 Eh. Note that the HGH potential is quite hard and seems to need a very high cutoff.

For this case, there should be no other convergence parameters to tweak. The remaining discrepancy may stem from the fact that the H pseudopotential's local potential is based on making the eigenvalue match the true 1/r potential for LDA/PBE, and not for the non-interacting electron case. Perhaps the result will be closer to the exact -0.5 if you use a Hartree-Fock pseudopotential.

Best,
Shankar

**Comment by theonov13** [comment]
Dear Shankar, 

thank you for your impressively, amazingly fast response. 
If different pseudopotentials now converge to the same values 
is a good first indicator that everything works as expected. 
Thank you for pointing out the cutoff convergence of the pseudotentials. 
I'm aware of it and can "live" currently we the higher cutoffs. 
I would not assume that the "problem" comes from the pseudopotential itself, 
for instance other codes give different trends for SIC while 
the pure DFT values agree perfectly between all of them. 
I will check your proposal to use a Hartree-Fock pseudopotential instead. 

Thank you to point out the coordinate issue, 
indeed I wanted to center the atom inside the box 
to may or may not omit problems with the periodic image. 

It's a bit late for me today, but I will test everything in detail
tomorrow and will close the issue if everything works as you described. 

Best,
Sebastian

**Comment by theonov13** [comment]
Dear Shankar, 

I pulled (git pull) the newest version of JDFTx from GitHub and afterward re-compiled everything (cmake and make) 
as advised by the JDFTx homepage (https://jdftx.org/CompilingBasic.html). 

For the spin-polarized case (please see Tab.1) GBRV/$ID_pbe.uspp and SG15/H_ONCV_PBE-1.0.upf indeed now agree very well. 
The parser for the all-electrons variants of HGH.UPF seems to work for DFT now perfectly, 
thank you for fixing this issue. 
However, for me the SIC part crashes now for example for H.pz-hgh.UPF, H.pbe-hgh.UPF and h.optgga1.fhi 
with the same error code [1] (see below). 

I know it makes no physical nor chemical sense to calculate the H atom spin-paired (unpolarized), 
but it is sometimes a good debugging example. 
While also in the spin-paired case (please see Tab.2) the DFT now seems to work for all tested pseudopotentials, 
the SIC somehow delivers -nan for GBRV/$ID_pbe.uspp and crashes for H.pz-hgh.UPF, H.pbe-hgh.UPF, h.optgga1.fhi
also with error code [1]. 

Best, 
Sebastian 

**Tab.1** H atom in cubic box (a = 16 Bohr): spin-polarized (spintype z-spin, elec-initial-magnetization +1 yes)
), elec-ex-corr lda-VWN, elec-cutoff 50


| ion-species | Etot [Hartree] | SIC [Hartree] | EPZ [Hartree] |
| :---------: | :-----: | :----: | :----: | 
| GBRV/$ID_pbe.uspp  | -0.4786417382269620 | 0.020335805953962 | -0.498977544180924 | 
| SG15/H_ONCV_PBE-1.0.upf | -0.4785788375246857 | 0.020388498049170 | -0.4989673355738557 | 
| H.pz-hgh.UPF | -0.4782275057762656 | failed error code [1] | - | 
| H.pbe-hgh.UPF |-0.4782311514774932 | failed error code [1] | - | 
| h.optgga1.fhi |-0.4783893777306069 | failed error code [1] | - | 
| Ref. [NIST](https://www.nist.gov/pml/atomic-reference-data-electronic-structure-calculations/atomic-reference-data-electronic-7-0)     |-0.478671           | - | - | 

**Tab.2** H atom in cubic box (a = 16 Bohr): spin-paired (spintype no-spin), elec-ex-corr lda-VWN, elec-cutoff 50


| ion-species | Etot [Hartree] | SIC [Hartree] | EPZ [Hartree] |
| :---------: | :-----: | :----: | :----: | 
| GBRV/$ID_pbe.uspp  | -0.4456869147754978  | -nan | - | 
| SG15/H_ONCV_PBE-1.0.upf | -0.4456528721214542 |  0.018443383293297 | -0.4640962554147512 | 
| H.pz-hgh.UPF | -0.4452940085900884 | failed error code [1] | - | 
| H.pbe-hgh.UPF |-0.4452973985546073 | failed error code [1] | - | 
| h.optgga1.fhi |-0.4454788561048634 | failed error code [1] | - | 
| Ref. [NIST](https://www.nist.gov/pml/atomic-reference-data-electronic-structure-calculations/atomic-reference-data-electronic-7-0)    | -0.445671 | - | - | 


**error code [1]**

/jdftx-git/jdftx/core/matrixOperators.cpp:52: operator():
    Assertion 'iStart>=0 && iStart<nr' failed--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

Adjusted example for input file
```Bash 
lattice Cubic 16
# default: Lattice == fractional coordinates 
coords-type Cartesian
ion H  8.00  8.00  8.00  1

# spin-polarized 
spintype z-spin
elec-initial-magnetization +1 yes
# spin-paired 
#spintype no-spin

#wavefunction random

elec-ex-corr lda-VWN

ion-species GBRV/$ID_pbe.uspp
#ion-species SG15/H_ONCV_PBE-1.0.upf
#ion-species H.pz-hgh.UPF
#ion-species H.pbe-hgh.UPF
#ion-species h.optgga1.fhi


elec-cutoff 50

coulomb-interaction isolated
# different coulomb-interactions
# - Spherical, isolated, Periodic
coulomb-truncation-embed 8.0 8.0 8.0

dump End EigStats SelfInteractionCorrection

```

**Comment by shankar1729** [comment]
Hi Sebastian.

I pushed another couple of commits to fix these issues. First, the same (lack of) projector issue in the purely local pseudopotential afflicted the code I pushed yesterday. Second, it seems that the SIC code was always using a spin-polarized subtraction regardless of the spin polarization of the overall calculation; I've fixed this now and the overall energy after correction comes closer to the spin-polarized case for the unpolarized H atom.

Best,
Shankar

**Comment by theonov13** [comment]
Dear Shankar,

thank you again for your rapid response. 
Now the H test (spin-polarized and spin-paired) runs 
through without any error for all tested pseudopotentials. 

I agree the spin-unpolarized calculations look now way more reasonable. 
And the trends within are very consistent between the different pseudopotentials. 

Thank you for your time and work. 
I will perform some further tests but will close the issue now. 

Best, 
Sebastian 

**Tab.1** H atom in cubic box (a = 16 Bohr): elec-ex-corr lda-VWN, elec-cutoff 50

| ion-species | Mode | Etot [Hartree] | SIC [Hartree] | EPZ [Hartree] |
| :---------: | :--: | :------------: | :-----------: | :-----------: |     
| GBRV/H_pbe.uspp | spin-polarized | -0.4786417382269704 | 0.020335805953925 | -0.4989775441808954 |
| GBRV/H_pbe.uspp | spin-paired | -0.4456869147755023 | 0.050250346676251 | -0.4959372614517533 |
| SG15/H_ONCV_PBE-1.0.upf | spin-polarized | -0.4785788375246899 | 0.020388498049817 | -0.4989673355745069 |
| SG15/H_ONCV_PBE-1.0.upf | spin-paired | -0.4456528721214535 | 0.05027797908411 | -0.49593085120556346 |
| H.pz-hgh.UPF | spin-polarized | -0.4782275057762674 | 0.020278125198594 | -0.4985056309748614 |
| H.pz-hgh.UPF | spin-paired | -0.44529400859009 | 0.050174865120821 | -0.495468873710911 |
| H.pbe-hgh.UPF | spin-polarized | -0.4782311514774921 | 0.02027839414182 | -0.4985095456193121 |
| H.pbe-hgh.UPF | spin-paired | -0.4452973985546087 | 0.050175274055842 | -0.4954726726104507 |
| h.optgga1.fhi | spin-polarized | -0.4783893777329561 | 0.020382439238838 | -0.49877181697179407 |
| h.optgga1.fhi | spin-paired | -0.4454788561048696 | 0.050256905453084 | -0.49573576155795357 |
