### ISSUE TITLE
He atom SIC

### ISSUE THREAD

**Issue by kaitrepte** [shankar1729/jdftx#166]
Hi, 

we have a questions which is somehow an extension of
a previous issue (https://github.com/shankar1729/jdftx/issues/165). 
Going from the H atom in the box to the He atom in the box, 
we would expect the DFT energy as well as the SIC energy to be equal 
in this case for spin-polarized and spin-paired calculations. 
To justify this expectations we provide some reference values
for DFT as well as SIC, calculated with the all-electron 
GTO code [ERKALE](https://github.com/susilehtola/erkale). 
We used the pc-2 basis set as well as a numerical 
quadrature grid=(75,302), which 
should be sufficient for the reference calculations. 

The jDFTx results for the SG15/He_ONCV_PBE-1.0.upf 
pseudopotential does not change significantly 
changing Ecut from 50 to 100 Hartree, but the HGH results change. 
Thus, we only report the jDFTx values for Ecut = 100 Hartree. 
The spin-polarized jDFTx values (DFT and SIC) for He.pz-hgh.UPF agree 
rather nicely with the performed ERKALE calculations, 
while the spin-paired jDFTx SIC values seem to be a bit off. 
Similarly to the H atom we do not expect the effect of
a proper localization or self-consistent SIC to be 
dominant for this test system.

We would again appreciate any help, hints or suggestions. 

Best, 

Kai and Sebastian 

**Tab.1**: He in a cubic box (a=16 Bohr) for jDFTx, He atom for ERKALE, exchange-correlation=LDA-VWN

| Code | ion-species |  Mode |  EDFT [Hartree] | SIC [Hartree] | EPZ [Hartree] |
| :--: | :---------: | :-----: | :-----: | :----: | :----: | 
| jDFTx | SG15/He_ONCV_PBE-1.0.upf | spin-polarized | -2.740532 | 0.083366 | -2.823898 |
| jDFTx | SG15/He_ONCV_PBE-1.0.upf| spin-paired | -2.740532 | 0.202934 | -2.943467 |
| jDFTx | He.pz-hgh.UPF| spin-polarized | -2.831735 | 0.083214 | -2.914949 |
| jDFTx | He.pz-hgh.UPF| spin-paired | -2.831735 | 0.212852 | -3.044586 |
| ERKALE | pc-2, (75,302) | spin-polarized | -2.834232 | 0.087962 | -2.919540 |
| ERKALE | pc-2, (75,302) | spin-paired | -2.834232 | 0.087962 | -2.919540 |
| [NIST](https://www.nist.gov/pml/atomic-reference-data-electronic-structure-calculations/atomic-reference-data-electronic-7-1)  |  Ref.          | spin-polarized | -2.834836        |  -       | -         | 
| [NIST](https://www.nist.gov/pml/atomic-reference-data-electronic-structure-calculations/atomic-reference-data-electronic-7-1)  |  Ref.          | spin-paired | -2.834836     |  -       | -         |

**Comment by shankar1729** [comment]
Perhaps the choice to use a spin-polarized per-orbital density for SIC, regardless of the overall spin polarization, is the correct choice? I don't use this SIC for any research so haven't looked into it too closely.

So maybe the "fix" I made in the previous commit to address the SIC energy for GBRV ultrasoft pseudopotentials was the issue. Could you do these checks with the version before the last commit (i.e. at [this commit](https://github.com/shankar1729/jdftx/commit/9acd7e1a7dce62347927fe34e30ab70ad7b4bc1d)) and see if it behaves correctly? If so, it would be down to a numerical issue with the ultrasoft augmentation that I can look into.

Best,
Shankar

**Comment by theonov13** [comment]
Hi, 

we did

git checkout bd9d281

and re-compiled everything (cmake and make).

In case of SG15/He_ONCV_PBE-1.0.upf, the results 
for spin-paired and spin-polarized
in the He case are the same.
However, for He.pz-hgh.UPF the SIC calculation 
now fails again with the previous error (error code [1])

Best, 
Sebastian and Kai 

| Code | ion-species |  Mode |  EDFT [Hartree] | SIC [Hartree] | EPZ [Hartree] |
| :--: | :---------: | :-----: | :-----: | :----: | :----: | 
| jDFTx | SG15/He_ONCV_PBE-1.0.upf | spin-polarized | -2.7405323619373467 | 0.083365881075659 | -2.8238982430130055 |
| jDFTx | SG15/He_ONCV_PBE-1.0.upf | spin-paired | -2.7405323619352453 | 0.083365876713855 | -2.8238982386491003 |

**error code [1]**
/jdftx-git/jdftx/core/matrixOperators.cpp:52: operator():
	Assertion 'iStart>=0 && iStart<nr' failed--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD

**Comment by kaitrepte** [comment]
Hi,

In general, I think it is not entirely clear 
what to do in a spin-paired case for SIC.
This is also partially the reason why we started comparing 
different approaches, implementations, and codes. 

Best,
Kai and Sebastian

**Comment by shankar1729** [comment]
Hi Sebastian, Kai,

I was referring to the commit right after that one: i.e. 9acd7e1

So this will have the matrix error fixed, but would not have changed the spin polarization treatment. So it should work for the HGH pseudopotential, but may produce weird results for the ultrasoft GBRV ps.

Best,
Shankar

**Comment by kaitrepte** [comment]
Hi,

thanks for the suggestions.

With 

git checkout 9acd7e1

it seems that indeed it works for the He atom. 
We will check, maybe tomorrow, what happens for the H atom 
and other pseudo potentials. 

Best,
Kai and Sebastian 


| Code | ion-species |  Mode |  EDFT [Hartree] | SIC [Hartree] | EPZ [Hartree] |
| :--: | :---------: | :-----: | :-----: | :----: | :----: | 
| jDFTx | SG15/He_ONCV_PBE-1.0.upf | spin-polarized | -2.740532 | 0.083366 | -2.823898 |
| jDFTx | SG15/He_ONCV_PBE-1.0.upf | spin-paired | -2.740532 | 0.083366 | -2.823898 |
| jDFTx | He.pz-hgh.UPF | spin-polarized | -2.831735 | 0.083214 | -2.914949 |
| jDFTx | He.pz-hgh.UPF | spin-paired | -2.831735 | 0.083214 | -2.914949 |

**Comment by theonov13** [comment]
Dear Shankar, 

sorry for the late reply. 
We still try to figure out 
what the numerically "correct"
answer for a spin-paired H atom 
in SIC might be. 

We performed some reference calculations 
with ERKALE and NWChem and the trends 
for the jDFTx SIC energy for H, He, Li 
compares reasonable with those reference values. 
Also, with the proposed checkout (9acd7e1)
for He one finds that spin-paired gives
identical results to spin-polarized calculations, 
like the other codes and in agreement with expectations. 

Note: The SIC energy is sometimes defined 
with a different sign, as it is done in jDFTx. 

Best, 
Sebastian and Kai 

**Tab.1:** NWChem: 14.05.2021 

|  System | Code | Basis | Method | Spin-polarized | ETOT//DFT [Hartree] | ESIC [Hartree]  | EPZ [Hartree]|
| :----:  | :--:  | :---: | :-------------------: | :------------: | :-----------------: | :-------------------: | :-------------: |
| H | NWChem     | pc-2  | GTO, SIC perturbative | True           | -0.478602     | -0.020298 | -0.498899 |
| He | NWChem      | pc-2  | GTO, SIC perturbative | True           | -2.834232     | -0.082605  | -2.916837 |
| He| NWChem      | pc-2  | GTO, SIC perturbative | False          | -2.834232     | -0.082605  | -2.916837 |
| Li | NWChem      | pc-2  | GTO, SIC perturbative | True           | -7.342517     | -0.164358  | -7.506875 |


**Tab.2:** ERKALE: 14.05.2021 

| System | Code | Basis | Grid | Spin-polarized | Etot//DFT [Hartree] | SIC [Hartree] | EPZ [Hartree] |
| :--: | :---: | :--: | :------------: | :----: | :-----------------: | :-----------: | :-----------: |
| H | ERKALE | pc-2 | [75, 302] | True  | -0.478602 | -0.022229 | -0.499878 |
| He | ERKALE | pc-2 | [75, 302] | True  | -2.834232 | -0.087962 | -2.919540 |
| He | ERKALE | pc-2 | [75, 302] | False  | -2.834232 | -0.087962 | -2.919540 |
| Li | ERKALE | pc-2 | [75, 302] | True  | -7.342517 | -0.166918 | -7.508610 |

**Tab.3:** jDFTx: 14.05.2021 

| System | Code | Pseudo | Ecut [Hartree] | Spin-polarized | Etot [Hartree] | SIC [Hartree] | EPZ [Hartree] | 
| :--: | :----: | :----: | :------------: | :------------: | :------------: | :-----------: | :-----------: | 
| H | jDFTx | SG15/ID_ONCV_PBE-1.0.upf | 100 | False | -0.445654 | 0.018443 | -0.464097 |
| H | jDFTx | ./HGH/ae/ID.pz-hgh.UPF | 100 | False | -0.445631 | 0.018348 | -0.463979 |
| H | jDFTx | SG15/ID_ONCV_PBE-1.0.upf | 100 | True | -0.478580 | 0.020388 | -0.498968 |
| H | jDFTx | ./HGH/ae/ID.pz-hgh.UPF | 100 | True | -0.478603 | 0.020291 | -0.498894 |
| He | jDFTx | SG15/ID_ONCV_PBE-1.0.upf | 100 | False | -2.740532 | 0.083366 | -2.823898 |
| He | jDFTx | ./HGH/ae/ID.pz-hgh.UPF | 100 | False | -2.831735 | 0.083214 | -2.914949 |
| He | jDFTx | SG15/ID_ONCV_PBE-1.0.upf | 100 | True | -2.740532 | 0.083366 | -2.823898 |
| He | jDFTx | ./HGH/ae/ID.pz-hgh.UPF | 100 | True | -2.831735 | 0.083214 | -2.914949 |
| Li | jDFTx | SG15/ID_ONCV_PBE-1.0.upf | 100 | False | -6.971727 | 0.143626 | -7.115353 |
| Li | jDFTx | ./HGH/ae/ID.pz-hgh.UPF | 100 | False | -7.296785 | 0.162805 | -7.459590 |
| Li | jDFTx | SG15/ID_ONCV_PBE-1.0.upf | 100 | True | -6.979695 | 0.143756 | -7.123450 |
| Li | jDFTx | ./HGH/ae/ID.pz-hgh.UPF | 100 | True | -7.304756 | 0.162887 | -7.467642 |

**Comment by shankar1729** [comment]
Great, thanks for the updates. I'll undo the last commit to leave the SIC implementation at 9acd7e1.

Best,
Shankar

**Comment by kaitrepte** [comment]
Hi Shankar,
thank you for taking care of this. 
Best,
Kai
