### ISSUE TITLE
LiH calculation with HGH pseudopotential

### ISSUE THREAD

**Issue by wangenau** [shankar1729/jdftx#167]
Hello,

I have tried to do some calculations with your code, but ran into an error I couldn't resolve.

For context, I have tried to calculate LiH with HGH pseudopotentials taken from [1] and [2].
The script looks like the following:

```bash
include structures/LiH.lattice
include structures/LiH.ionpos
coords-type cartesian

elec-ex-corr lda-VWN

ion-species pspfiles/$ID.pz-hgh.UPF
elec-cutoff 30 120
dump End None
```

But somehow I get an error when using the HGH file for Li without the core electrons.
The produced error is

```bash
Insufficient atomic orbitals to occupy 0.5 electrons (0.5 excess electrons) [per spin channel].
Failed.
```

When using the pseudopotential with all electrons (Li.pz-s-hgh.UPF) the calculation will perform properly.

My git HEAD is at bd9d28138df9d6c0110726818b1960e4bff5be38.

Thanks in advance!

[1] https://www.quantum-espresso.org/pseudopotentials/hartwigesen-goedecker-hutter-pp/h
[2] https://www.quantum-espresso.org/pseudopotentials/hartwigesen-goedecker-hutter-pp/li

**Comment by shankar1729** [comment]
It appears that the Li.pz-hgh.UPF pseudopotential specifically does not have any atomic orbitals stored within. (No PP.CHI section within the UPF file.) Consequently, the LCAO routine for initialization i snot finding enough orbitals.

To continue with this pseudopotential, please use random wavefunctions instead (add command "wavefunction random"). Alternately, see if you are able to find an equivalent PS file that contains atomic orbitals.

Best,
Shankar
