### ISSUE TITLE
H2 in a box

### ISSUE THREAD

**Issue by theonov13** [shankar1729/jdftx#168]
Dear Shankar, 

we tried to calculate the H2 
molecule centered in a box. 
For HGH pseudopotentials (LDA or PBE)
everything works fine. 
This may be realized because you 
disabled to overlap check for HGH
("Disabling overlap check for local pseudopotential"). 

However, using standard pseudopotentials 
(SG15/H_ONCV_PBE-1.0.upf, GBRV/h_lda.uspp) 
leads to an overlap error. 
The used criterion appears 
a bit too "hard" for (some) molecules. 
For H2 the experimental bond 
length is 1.4 Bohr, while the 
vdw radius of H is 2.27 Bohr. 

For SG15/H_ONCV_PBE-1.0.upf the sum 
of the core radii is 2.02 Bohr, 
and it fails the overlap test because the 
used bond lengths is only 1.4 Bohr. 
The same goes for GBRV/h_lda.uspp where 
the sum of the core radii is 2.4 Bohr.

Is there a way to turn the overlap check on and off? 

Best, 
Sebastian and Kai 

Example input 
```Bash 
lattice \
16.000001162141015 0.0 0.0 \
 0.0 16.000001162141015 0.0 \
 0.0 0.0 16.000001162141015
coords-type Cartesian
ion H 8.000000581070507 8.000000581070507 7.299857051447926 1
ion H 8.000000581070507 8.000000581070507 8.70014411069309 1
elec-cutoff  36.749322474956635
elec-ex-corr lda-VWN
ion-species HGH/ae/$ID.pz-hgh.UPF
spintype z-spin
elec-initial-magnetization 0 yes
coulomb-interaction periodic
dump End EigStats SelfInteractionCorrection
``` 

Error messages summaries
```Bash
Error summary (SG15/H_ONCV_PBE-1.0.upf)
.... 
Core radius for overlap checks: 1.01 bohrs.
WARNING: H #0 and H #1 are closer than the vector-sum of their core radii.
Atoms are too close, have overlapping pseudopotential cores.
```
```Bash
Error summary (GBRV/h_lda.uspp)
.... 
Core radius for overlap checks: 1.20 bohrs.
WARNING: H #0 and H #1 are closer than the vector-sum of their core radii.
Atoms are too close, have overlapping pseudopotential cores.
```

**Comment by shankar1729** [comment]
Yes, please use command [core-overlap-check](http://jdftx.org/CommandCoreOverlapCheck.html)

Best,
Shankar

**Comment by kaitrepte** [comment]
Hi Shankar,

thank you. This works.

Best,
Kai

**Comment by theonov13** [comment]
Dear Shankar,

this works perfectly. 
Thank you a lot. 

Best, 
Sebastian
