### ISSUE TITLE
Partial DOS as a sum over all atoms of the same type

### ISSUE THREAD

**Issue by sergbuto** [shankar1729/jdftx#170]
Is there a way to dump partial DOS as a sum over all the atoms of the same type? The printout of partial DOS for each atom becomes inconvenient when there are many atoms in the unit cell/supercell.

**Comment by shankar1729** [comment]
Right: it wasn't before, but added this now in [latest commit](https://github.com/shankar1729/jdftx/commit/2200415). The docs may take a while to update, but specify atom index 0 to sum over all atoms in Orbital or OrthoOrbital mode (index >= 1 will select a specific atom as before). Note that this will not work for AtomSphere or AtomSlice modes.

Please report any bugs in this updated implementation.

Best,
Shankar
