### ISSUE TITLE
Binary to text for  phonon dispersion

### ISSUE THREAD

**Issue by Zeinabmrd** [shankar1729/jdftx#175]
Dear Dr. Shankar,
Hi

I did band structure and phonon dispersion calculation with JDFTx. in next step, I want to draw band and phonon diagrams for different strains in one figure,for this purpose I need the output data stored in the binary output files, but when I use binary to text script to achieve the output data with the following command:

binaryToText  totalE.phononOmegaSq   [innerDim=1] C

 I receive only one column of data, which I cannot be able to plot band and phonon diagrams with this data.

and when I use below command;
binaryToText  totalE.phononOmegaSq   [innerDim=2]  C

this error occur:

"Inner dimension innerDim=2 is not a factor of data count: 1053"

Dear Dr. Shankar, 
How can I access the output data of binary files to draw band structure and phonon diagrams? and What characteristics should be considered to achieve this output data for use in another program such as Origin to plot diagrams  ?
I would be grateful if you could guide me in this problem.

Regards,
zeinab

**Comment by shankar1729** [comment]
Hi Zeinab,

The data in phononOmegaSq is not along a high symmetry path, but is actually a real-space force matrix on the supercell. So it's likely not what you want to put together in a plot.

Instead, see the python script in the [phonon dispersion tutorial](http://jdftx.org/PhononDispersion.html); it has a line `plt.plot(np.sqrt(omegaSq)/meV)`. You can choose to output the phonon frequencies using `np.savetext` instead at that location, collect those data files for different calculations and then plot the comparison. You could also modify the python script to directly process and plot several phonon dispersions at once, if needed. Once again, note that this script is transforming a force matrix in real space to selected q points, so there is no need for or point in converting the raw totalE.phononOmegaSq files to text form.

Best,
Shankar

**Comment by Zeinabmrd** [comment]
Dear Dr. Shankar,

Thank you very much. I really appreciate your help .

I wish you good luck.

Best regards 
Zeinab
