### ISSUE TITLE
Exclude implicit solvent from a region of simulation cell

### ISSUE THREAD

**Issue by yanchoilam** [shankar1729/jdftx#176]
Hi, 

Is there a way to exclude the implicit solvent from a certain region of the simulation cell? In particular, I'd like to exclude implicit solvent from the region where the solvent is modeled explicitly (i.e., with solvent molecules). I am using CANDLE as my solvation model.

Thanks!

**Comment by shankar1729** [comment]
Hi Yan-Choi,

See parameters zMask* in [command pcm-params](http://jdftx.org/CommandPcmParams.html). For example, if you want to exclude both implicit solvent and ions from the fractional z range 0.1 to 0.3, i.e. half-width 0.1 centered at 0.2, you could use something like:

`pcm-params \
   zMask0 0.2 \
   zMaskH 0.1 \
   zMaskIonH 0.1`

You could use that to define separate ionic and fluid cavities if needed.

Best,
Shankar

**Comment by yanchoilam** [comment]
Hi Shankar,

This is very helpful. Thanks!
