### ISSUE TITLE
How to use RPBE functional? Is exchange part of RPBE + correction part of PBE a proper choice?

### ISSUE THREAD

**Issue by zhichao-1699** [shankar1729/jdftx#178]
Hi,
I am currently treating systems with adsorbates, which have shown to be described better by RPBE functionals. But I found that there is no direct RPBE functional in the first part of 'elec-ex-corr' command, while the following exchange part has.
According to the RPBE reference, "The RPBE functional only differs from the PBE functional in the choice of the mathematical form for the exchange energy enhancement factor." 

So, I wonder if it is a proper treatment to use command like: 'elec-ex-corr gga-x-rpbe gga-c-pbe' to activate RPBE functional? If so, how should I change pseudopotentials (for vasp, we could just use those for PBE)? And what about 'van-der-waals'?

Any suggestion would be helpful. Thanks a lot.
Zhichao

**Comment by shankar1729** [comment]
Hi Zhichao,

Yes, that's correct. You can use the libxc rpbe exchange combined with pbe correlation as you indicated; you can also check the LibXC page if they document this further.

If you use PBE pseudopotentials with RPBE in VASP, it should be acceptable to do the same in JDFTx. Note that JDFTx does not force the pseudopotential's generated functional to match elec-ex-corr. So you can simply use the same pseudopotential specification as you would do for PBE, and just switch the elec-ex-corr as you mentioned.

Best,
Shankar

**Comment by zhichao-1699** [comment]
Thanks Shankar,
I got it. And I would like to ask if jDFTx supports more recent vdW correction like DFT-D3? Because I found it a little hard to find parameters for D2 nowadays.

Best,
Zhichao

**Comment by shankar1729** [comment]
No, we don't have D3: it has a much more complicated parameterization compared to D2, so we never found the time to implement it. 

We would of course love a pull request with an implementation of it! :)

Best,
Shankar

**Comment by zhichao-1699** [comment]
Okay, looking forward to it :)

Thanks again,
Zhichao

**Comment by zhichao-1699** [comment]
Great! Thanks a lot. Is there any additional modification I need to do with the compilation or install procedures? 

Best,
Zhichao
