### ISSUE TITLE
Error on compilation on Windows using Cygwin

### ISSUE THREAD

**Issue by maurosgroi** [shankar1729/jdftx#181]
Dear developers,
my name is Mauro Sgroi.
I'm trying to install JDFTx on Windows using cygwin for training purpuse.
I'm using the openblas/lapack library already present on the system.
Here is my compilation test:

cmake  -Wno-dev  -D ThreadedBlas=no  -D LAPACK_LIBRARIES=/lib/liblapack.dll.a ../jdftx/
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git.exe (found version "2.33.0")
-- Forcing static linking for Cygwin/Windows
-- Looking for gsl_integration_glfixed_point
-- Looking for gsl_integration_glfixed_point - found
-- Found GSL: /lib/libgsl.dll.a
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found FFTW3:  /lib/libfftw3_threads.dll.a /lib/libfftw3.dll.a
-- Found LAPACK: /lib/liblapack.dll.a
-- Found CBLAS: /lib/libcblas.dll.a
-- Found MPI_C: /usr/lib/libmpi.dll.a (found version "3.1")
-- Found MPI_CXX: /usr/lib/libmpi.dll.a (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- Performing Test HAS_NO_UNUSED_RESULT
-- Performing Test HAS_NO_UNUSED_RESULT - Success
-- Performing Test HAS_TEMPLATE_DEPTH
-- Performing Test HAS_TEMPLATE_DEPTH - Success
-- Found Doxygen: /usr/bin/doxygen.exe (found version "1.9.2 (91c670c023b34d420122a7e9a8a144af96045db7)") found components: doxygen dot
CMake Error at CMakeLists.txt:363 (add_subdirectory):
  add_subdirectory given source "aux" which is not an existing directory.

-- Configuring incomplete, errors occurred!
See also "/home/sgroi/apps/src/jdftx-1.6.0/build/CMakeFiles/CMakeOutput.log".

Could please help me to solve this issue? 
In the following post I will upload the logs.
Thanks a lor and best regards,
Mauro Sgroi.

**Comment by maurosgroi** [comment]
[CMakeOutput.log](https://github.com/shankar1729/jdftx/files/7178397/CMakeOutput.log)

**Comment by shankar1729** [comment]
HI Mauro,

That's a very strange error, since it is complaining that it can't find one of the source directories (aux) which should be present in the downloaded tar (or in the repository fetched over git). Could you confirm if this directory is indeed missing within the jdftx source folder? If it is, maybe it got deleted accidentally. Try fetching the code again from the repositories.

Best,
Shankar

**Comment by maurosgroi** [comment]
Dear Shankar,
I confirm that your suggestion solved the problem.
Best regards,
Mauro.

**Comment by shankar1729** [comment]
Okay, glad to hear it! By the way, once you move beyond initial learning, I would highly recommend switching to a linux or unix system for performance. If you need to stick to Windows, compiling MPI applications though WSL2 may be a more performant option than Cygwin.

**Comment by maurosgroi** [comment]
Dear Shankar,
thanks a lot for the suggestion.
Best regards,
Mauro.
