### ISSUE TITLE
ASE interface with batch queue system

### ISSUE THREAD

**Issue by maurosgroi** [shankar1729/jdftx#182]
Dear all,
is there a way to launch NEB calculations with the ASE interface through a HPC batch queue system?

By the way, is it planned to implement NEB as a built-in capability?

Thanks a lot and best regards,
Mauro Sgroi.

**Comment by shankar1729** [comment]
Hi Mauro,

You should be able to launch a python script containing an ASE calculation from a job script as `mpirun python <script-file>`. Maybe you may need to an `import mpi4py` at the top of that calculation to initialize MPI before ASE is imported. See [Parallel calculations](https://wiki.fysik.dtu.dk/ase/ase/parallel.html) in the ASE documentation. You may also need to set environment variable `export JDFTx="mpirun /path/to/jdftx"` in the job script so that jdftx is invoked with MPI. I'm assuming SLURM and a SLURM-aware mpi in the above such that all the process counts etc. are automatically picked up by mpirun from environment variables.

This will certainly need some experimentation for your specific setup. Please try the above and post here if you encounter issues.

At the moment, there is no immediate plan to build NEB into JDFTx. We plan to do this more gracefully in the successor to JDFTx, [QimPy](https://qimpy.org), but that code is still in an early stage.

Best,
Shankar

**Comment by maurosgroi** [comment]
Dear Shankar,
our HPC frontend uses PBS.
I'm trying to start an example calculation locally on the frontend with no queue system.
Launching the example from the web page I get the following errors:
aittor16fscp360 ~> python3 neb_first.py
Set up JDFTx calculator with run files in '/workhpc/FCA/FCA_CRF_STRUT/sgroi/JDFTx/NEB/temp/tmp_dyv_u0u'


Input parsing failed with 2 errors (run with -t for command syntax)

Failed.
Traceback (most recent call last):
  File "neb_first.py", line 21, in <module>
    dyn.run(fmax=0.05)
  File "/workhpc/FCA/FCA_CRF_STRUT/sgroi/.local/lib/python3.7/site-packages/ase-3.22.0-py3.7.egg/ase/optimize/optimize.py", line 269, in run
    return Dynamics.run(self)
  File "/workhpc/FCA/FCA_CRF_STRUT/sgroi/.local/lib/python3.7/site-packages/ase-3.22.0-py3.7.egg/ase/optimize/optimize.py", line 156, in run
    for converged in Dynamics.irun(self):
  File "/workhpc/FCA/FCA_CRF_STRUT/sgroi/.local/lib/python3.7/site-packages/ase-3.22.0-py3.7.egg/ase/optimize/optimize.py", line 122, in irun
    self.atoms.get_forces()
  File "/workhpc/FCA/FCA_CRF_STRUT/sgroi/.local/lib/python3.7/site-packages/ase-3.22.0-py3.7.egg/ase/atoms.py", line 788, in get_forces
    forces = self._calc.get_forces(self)
  File "/swbase/app/jdftx/jdftx-master/jdftx/scripts/ase/JDFTx.py", line 122, in get_forces
    self.update(atoms)
  File "/swbase/app/jdftx/jdftx-master/jdftx/scripts/ase/JDFTx.py", line 169, in update
    self.runJDFTx(self.constructInput(atoms))
  File "/swbase/app/jdftx/jdftx-master/jdftx/scripts/ase/JDFTx.py", line 178, in runJDFTx
    shell('cd %s && %s -i in -o out' % (self.runDir, self.executable))
  File "/swbase/app/jdftx/jdftx-master/jdftx/scripts/ase/JDFTx.py", line 15, in shell
    return subprocess.check_output(cmd, shell=True)
  File "/swbase/app/anaconda3/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/swbase/app/anaconda3/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'cd /workhpc/FCA/FCA_CRF_STRUT/sgroi/JDFTx/NEB/temp/tmp_dyv_u0u && /swbase/app/jdftx/build-master/jdftx -i in -o out' returned non-zero exit status 1.

**Comment by maurosgroi** [comment]
The generated input file in the tmp directory is:

lattice \
11.338357  0.000000  0.000000  \
0.000000  11.338357  0.000000  \
0.000000  0.000000  13.228083

dump-name $VAR
initial-state $VAR
elec-cutoff 20 100

coords-type cartesian
ion C 0.000000 0.000000 0.000000         1
ion O 0.000000 0.000000 2.078699         1

ion-species GBRV/$ID_pbe.uspp

coulomb-interaction isolated
coulomb-truncation-embed 0 0 1.03935
dump End State
dump End Forces
dump End Ecomponents

**Comment by maurosgroi** [comment]
and the output is:

Start date and time: Tue Oct  5 22:00:34 2021
Executable /swbase/app/jdftx/build-master/jdftx with command-line: -i in -o out
Running on hosts (process indices):  aittor16fscp360.fiatauto.adfa.local (0)
Divided in process groups (process indices):  0 (0)
Resource initialization completed at t[s]:      0.00
Run totals: 1 processes, 28 threads, 0 GPUs


Encountered 2 errors while parsing input:


Command 'ion'  with command line:
        ion C 0.000000 0.000000 0.000000         1
failed with message:
        Species C has not been defined
The correct usage of this command is described below:
        ion <species-id> <x0> <x1> <x2> [v <vx0> <vx1> <vx2>] <moveScale> [<constraint type>=HyperPlane|Linear|None|Planar <d0> <d1> <d2> [<group> [HyperPlane <d0> ...]]]
Add an atom of species <species-id> at coordinates (<x0>,<x1>,<x2>).

Optionally, for dynamics, specify ion velocity <v0>,<v1>,<v2> after keyword 'v'.

<moveScale> preconditions the motion of this ion (set 0 to hold fixed)

In addition, the ion may be constrained to a line or a plane with line
direction or plane normal equal to (<d0>,<d1>,<d2>) in the coordinate
system selected by command coords-type. Note that the constraints must
be consistent with respect to symmetries (if enabled).

The HyperPlane constraint allows constraining collective motion of many
ions by restricting their motion to a hyperplane with normal specified
by (<d0>,<d1>,<d2>) for all ions specifying a hyperplane constraint.
By default, all hyperplane-constrained ions are included in a single
group; use optional <group> label to specify multiple hyper-planes.
Multiple hyperplane constraints may also be added to each atom,
but this requires an explicit group label for each hyperplane.

Note that when coords-type is lattice, the constraints are in covariant
lattice coordinates (like direction indices) for line constraints, but
contravariant coordinates (like plane indices) for plane constraints.

Command 'ion'  with command line:
        ion O 0.000000 0.000000 2.078699         1
failed with message:
        Species O has not been defined
The correct usage of this command is described below:
        ion <species-id> <x0> <x1> <x2> [v <vx0> <vx1> <vx2>] <moveScale> [<constraint type>=HyperPlane|Linear|None|Planar <d0> <d1> <d2> [<group> [HyperPlane <d0> ...]]]
Add an atom of species <species-id> at coordinates (<x0>,<x1>,<x2>).

Optionally, for dynamics, specify ion velocity <v0>,<v1>,<v2> after keyword 'v'.

<moveScale> preconditions the motion of this ion (set 0 to hold fixed)

In addition, the ion may be constrained to a line or a plane with line
direction or plane normal equal to (<d0>,<d1>,<d2>) in the coordinate
system selected by command coords-type. Note that the constraints must
be consistent with respect to symmetries (if enabled).

The HyperPlane constraint allows constraining collective motion of many
ions by restricting their motion to a hyperplane with normal specified
by (<d0>,<d1>,<d2>) for all ions specifying a hyperplane constraint.
By default, all hyperplane-constrained ions are included in a single
group; use optional <group> label to specify multiple hyper-planes.
Multiple hyperplane constraints may also be added to each atom,
but this requires an explicit group label for each hyperplane.

Note that when coords-type is lattice, the constraints are in covariant
lattice coordinates (like direction indices) for line constraints, but
contravariant coordinates (like plane indices) for plane constraints.



Input parsing failed with 2 errors (run with -t for command syntax)

End date and time: Tue Oct  5 22:00:34 2021  (Duration: 0-0:00:00.00)
Failed.

**Comment by shankar1729** [comment]
It seems that JDFTx is not able to find the pseudopotentials on that system. Please check whether `/swbase/app/jdftx/build-master/pseudopotentials/GBRV` is present and contains pseudopotential files. If not, copy over pseudopotential files from your local machine to that path: it's possible that the pseudopotential files were not fetched during your setup due to network access limitations on the cluster.

Alternatively, create links 'C.uspp' and 'O.uspp' in some location, and set the `JDFTx_pseudo` environment variable to point to that location.

Best,
Shankar

**Comment by maurosgroi** [comment]
Dear Shankar, 
I've tried verified that in the file "in" the path to the pseudopotentials is not inserted.
Even if i set the JDFTx_pseudo using  "export JDFTx_pseudo=/swbase/app/jdftx/build-master/pseudopotentials" command in the shell or if I use the pseudoDir variable in the python script:

calculator = JDFTx(
   executable='/swbase/app/jdftx/build-master/jdftx',
   pseudoDir='/swbase/app/jdftx/build-master/pseudopotentials',
   pseudoSet='GBRV',
   commands={'elec-cutoff' : '20 100'}
)

Is there something that I've to change in the JDFTx.py script?

Thanks a lot and best regards,
Mauro.

**Comment by shankar1729** [comment]
Hi Mauro,

When you specify pseudoDir, the JDFTx ASE calculator searches for pseudopotentials directly in that directory and does not use the pseudoSet variable. It searches for atomName.extension within that directory and adds ion-species lines only for files it finds. You can see the logic in JDFTx.py starting around line 220.

Note that this won't work for the GBRV set which has files named as atomName_xcFunctional.uspp, and is intended to be used with other manually curated functionals.

I suggest you try the following instead:

-  Create a new directory - let's call it /path/to/pseudo/dir - meant just for the pseudopotentials you want to use
-  Within this directory, create links of the form atomName.uspp to the GBRV pseudos you want to use. Example, create a link called H.uspp pointing to /path/to/jdftx/build/pseudopotentials/GBRV/H_pbe.uspp, and similarly for each atom type in your calculation.
- Pass pseudoDir=/path/to/pseudo/dir to the JDFTx calculator and leave pseudoSet blank.

Play around with this approach instead and see if you are able to get JDFTx within ASE to read the pseudopotentials. I fthis doesn't work, try hard-coding the ion-species commands within JDFTx.py as a last resort: it should be fairly straightforward to edit.

Best,
Shankar
