### ISSUE TITLE
How to change the "/tmp" directory in NEB calculations using ase

### ISSUE THREAD

**Issue by maurosgroi** [shankar1729/jdftx#183]
Dear all,
I'm trying to setup a NEB calculation using the ase interface.
On my HPC server I cannot access the /tmp folder.
How can I control where the scratch files are written?

I cannot find this information on the ase website.
Can you please give me an help?
Thanks a lot and best regards,
Mauro Sgroi.

**Comment by shankar1729** [comment]
The JDFTx calculator for ASE uses the `tempfile` python module to find a user-writable temp directory. See the [tempfile documentation](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir) for environment variables that can be used to influence where temp files are created. So try setting one of those environment variables eg. `export TMPDIR=/prefix/to/desired/tmp`. This should make all the tmp dirs within that recommended path.

Best,
Shankar

**Comment by maurosgroi** [comment]
Dear Shankar,
I managed to change the temporary directory following your advice.
Thanks a lot.
Mauro.
