### ISSUE TITLE
JDFTX:WannierMinimize: Step failed along negative gradient direction.

### ISSUE THREAD

**Issue by hwmmm1** [shankar1729/jdftx#185]
Dear Dr Shankar,
I try to ues Wannier calcualtion.  The input file as attached but there some erros . I am using a simple wannier input file, but it keeps showing errors. May you tell me how do I correct this problem.
![2](https://user-images.githubusercontent.com/92436849/137119447-64a80f86-a2d7-44ae-b76b-64c219a828d1.png)
odify i
[wannier_in.txt](https://github.com/shankar1729/jdftx/files/7337481/wannier_in.txt)
t?

**Comment by hwmmm1** [comment]
> 这很可能表明内部/外部能量窗口与猜测的万尼尔中心的数量/位置不匹配。如果没有关于系统的具体信息，我的建议是首先尝试选择不同的随机中心，看看是否会遇到相同的问题。如果是这种情况，请缩小内窗或加宽外窗，以减少 Wannier 最小化的约束。或者，尝试为相同的内部窗口大小增加 wannier 中心的数量。

**Comment by hwmmm1** [comment]
> > 这很可能表明内部/外部能量窗口与猜测的万尼尔中心的数量/位置不匹配。如果没有关于系统的具体信息，我的建议是首先尝试选择不同的随机中心，看看是否会遇到相同的问题。如果是这种情况，请缩小内窗或加宽外窗，以减少 Wannier 最小化的约束。或者，尝试为相同的内部窗口大小增加 wannier 中心的数量。

Dear Dr Shankar,
I tried multiple Wannier centers. I couldn't continue counting at that time，still the same error. Are there any rules for the selection of the Wannier center, such as the relationship with the coordinates of the high symmetry point or others？
 

> This most likely points to a mismatch between the inner/outer energy windows and the number/location of the guessed Wannier centers. Without specific information about the system, my recommendation would be to first try selecting different random centers and see if you get the same problems. If that's the case, narrow the inner window or widen the outer window to make the Wannier minimization less constrained. Alternately, try increasing the number of wannier centers for the same inner window size.


Dear Dr Shankar,
I tried multiple Wannier centers. I couldn't continue counting at that time，still the same error. Are there any rules for the selection of the Wannier center, such as the relationship with the coordinates of the high symmetry point or others？

**Comment by shankar1729** [comment]
Please attach the input files as text, so that we can try to reproduce the issue.

**Comment by hwmmm1** [comment]
> Please attach the input files as text, so that we can try to reproduce the issue.

Dear Dr Shankar,
I have solved the Wannier convergence problem. I reset the size of the window. Because the previously set window is too large and the energy band in the window is not discrete enough, the Wannier cannot converge. thanks for your help. 
Thanks for your help.
  At the same time, I have new doubts about the next step of calculating the energy distribution map. In response to this doubt, I asked a new question. Looking forward to your reply.
