### ISSUE TITLE
Convergence report / check

### ISSUE THREAD

**Issue by janklinux** [shankar1729/jdftx#19]
Hej,

I noticed what I think is an inconsistency in either reporting or detecting convergence. When I set i.e. 1E-6 as criteria I get

==== snip ====
SCF: Cycle: 81   G: -1695.487691123765899   dG: +9.598e-07   |Residual|: 9.957e-04   |deigs|: 2.585e-04  t[s]:  21300.77
        FillingsUpdate:  mu: -0.107401297  nElectrons: 450.000000  magneticMoment: [ Abs: 0.02868  Tot: +0.01464 ]
SCF: Cycle: 82   G: -1695.487691396125228   dG: -2.724e-07   |Residual|: 9.426e-04   |deigs|: 1.728e-04  t[s]:  21527.07
        FillingsUpdate:  mu: -0.107371870  nElectrons: 450.000000  magneticMoment: [ Abs: 0.02537  Tot: +0.01242 ]
SCF: Cycle: 83   G: -1695.487693612757539   dG: -2.217e-06   |Residual|: 5.921e-04   |deigs|: 3.370e-04  t[s]:  21753.71
        FillingsUpdate:  mu: -0.107360279  nElectrons: 450.000000  magneticMoment: [ Abs: 0.02329  Tot: +0.01091 ]
SCF: Cycle: 84   G: -1695.487693928076396   dG: -3.153e-07   |Residual|: 5.764e-04   |deigs|: 3.331e-04  t[s]:  21980.58
        FillingsUpdate:  mu: -0.107335098  nElectrons: 450.000000  magneticMoment: [ Abs: 0.02256  Tot: +0.00840 ]
SCF: Cycle: 85   G: -1695.487692831408140   dG: +1.097e-06   |Residual|: 6.822e-04   |deigs|: 3.574e-04  t[s]:  22206.98
        FillingsUpdate:  mu: -0.107327722  nElectrons: 450.000000  magneticMoment: [ Abs: 0.02215  Tot: +0.00664 ]
SCF: Cycle: 86   G: -1695.487692082159811   dG: +7.492e-07   |Residual|: 6.768e-04   |deigs|: 3.742e-04  t[s]:  22433.59
        FillingsUpdate:  mu: -0.107311768  nElectrons: 450.000000  magneticMoment: [ Abs: 0.02120  Tot: +0.00497 ]
SCF: Cycle: 87   G: -1695.487692802139463   dG: -7.200e-07   |Residual|: 7.188e-04   |deigs|: 3.848e-04  t[s]:  22660.05
        FillingsUpdate:  mu: -0.107301472  nElectrons: 450.000000  magneticMoment: [ Abs: 0.01949  Tot: +0.00346 ]
SCF: Cycle: 88   G: -1695.487694482572124   dG: -1.680e-06   |Residual|: 4.556e-04   |deigs|: 2.554e-04  t[s]:  22886.44
        FillingsUpdate:  mu: -0.107290081  nElectrons: 450.000000  magneticMoment: [ Abs: 0.01693  Tot: +0.00235 ]
SCF: Cycle: 89   G: -1695.487694311465248   dG: +1.711e-07   |Residual|: 5.151e-04   |deigs|: 2.866e-04  t[s]:  23112.93
        FillingsUpdate:  mu: -0.107279558  nElectrons: 450.000000  magneticMoment: [ Abs: 0.01182  Tot: +0.00185 ]
SCF: Cycle: 90   G: -1695.487688216131573   dG: +6.095e-06   |Residual|: 5.563e-04   |deigs|: 2.855e-04  t[s]:  23339.43
        FillingsUpdate:  mu: -0.107270014  nElectrons: 450.000000  magneticMoment: [ Abs: 0.01081  Tot: +0.00134 ]
SCF: Cycle: 91   G: -1695.487692918003404   dG: -4.702e-06   |Residual|: 4.676e-04   |deigs|: 9.755e-05  t[s]:  23558.92
        FillingsUpdate:  mu: -0.107268421  nElectrons: 450.000000  magneticMoment: [ Abs: 0.00925  Tot: +0.00152 ]
SCF: Cycle: 92   G: -1695.487690849039836   dG: +2.069e-06   |Residual|: 4.062e-04   |deigs|: 1.418e-04  t[s]:  23778.94
        FillingsUpdate:  mu: -0.107266126  nElectrons: 450.000000  magneticMoment: [ Abs: 0.00872  Tot: +0.00150 ]
SCF: Cycle: 93   G: -1695.487690564602190   dG: +2.844e-07   |Residual|: 3.651e-04   |deigs|: 1.149e-04  t[s]:  24000.44
        FillingsUpdate:  mu: -0.107266135  nElectrons: 450.000000  magneticMoment: [ Abs: 0.00819  Tot: +0.00158 ]
SCF: Cycle: 94   G: -1695.487692948609492   dG: -2.384e-06   |Residual|: 2.994e-04   |deigs|: 1.375e-04  t[s]:  24226.79
        FillingsUpdate:  mu: -0.107263531  nElectrons: 450.000000  magneticMoment: [ Abs: 0.00900  Tot: +0.00135 ]
SCF: Cycle: 95   G: -1695.487694216540376   dG: -1.268e-06   |Residual|: 2.429e-04   |deigs|: 3.559e-04  t[s]:  24448.87
        FillingsUpdate:  mu: -0.107261996  nElectrons: 450.000000  magneticMoment: [ Abs: 0.00850  Tot: +0.00115 ]
SCF: Cycle: 96   G: -1695.487694229407907   dG: -1.287e-08   |Residual|: 2.276e-04   |deigs|: 7.577e-05  t[s]:  24668.75
        FillingsUpdate:  mu: -0.107259591  nElectrons: 450.000000  magneticMoment: [ Abs: 0.00875  Tot: +0.00077 ]
SCF: Cycle: 97   G: -1695.487695213891129   dG: -9.845e-07   |Residual|: 2.538e-04   |deigs|: 1.760e-04  t[s]:  24895.45
SCF: Converged (|Delta E|<1.000000e-06 for 2 iters).
==== snip ====

Convergence reports that |dE| was < 1E-6 for two iterations which is the case for SCF 96/97 there, too. Only dE was actually lower than that for two iterations, when looking at SCF cycle 81/82 and 86/87 |dE| actually already was < 1E-6. Is that intended in this way? I don't see a reason why only dE would have to be smaller than threshold, |dE| makes sense, or am I missing something here? Besides the code is reporting |Delta E| < 1E-6.

Have a nice day, Jan

**Comment by shankar1729** [comment]
You're right: the code is enforcing |Delta E| < specified threshold *and* Delta E < 0 for two consecutive iterations. We previously did not enforce the latter, but found that it sometimes led to premature conclusion of convergence.

Best,
Shankar
