### ISSUE TITLE
Corrupted at the very beginning of the test

### ISSUE THREAD

**Issue by Rangingsword** [shankar1729/jdftx#194]
Hello,
the program run out of memory at the test.

Running tests...
Test project /home/MSI/software/jdftx/jdftx-master/build
      Start  1: openShell
*** Error in `/home/MSI/software/jdftx/jdftx-master/build/jdftx': corrupted size vs. prev_size: 0x0000000001fc7960 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7f3e4)[0x2b0664cbe3e4]
/lib64/libc.so.6(+0x82bf4)[0x2b0664cc1bf4]
/lib64/libc.so.6(__libc_calloc+0xb4)[0x2b0664cc5184]
/lib64/ld-linux-x86-64.so.2(_dl_allocate_tls+0x25)[0x2b0658073775]
/lib64/libpthread.so.0(pthread_create+0x75c)[0x2b065b1c187c]
/lib64/libstdc++.so.6(_ZNSt6thread15_M_start_threadESt10shared_ptrINS_10_Impl_baseEE+0x1a7)[0x2b06644d52d7]
/home/MSI/software/jdftx/jdftx-master/build/libjdftx.so(_Z11setNagIndexRK7vector3IiERK7matrix3IdEiiidPmS7_+0x802)[0x2b06588f1642]
/home/MSI/software/jdftx/jdftx-master/build/libjdftx.so(_ZN11SpeciesInfo22updateLatticeDependentEv+0x670)[0x2b06588ce4f0]
/home/MSI/software/jdftx/jdftx-master/build/libjdftx.so(_ZNK11SpeciesInfo11updateLocalERSt10shared_ptrI20ScalarFieldTildeDataES3_S3_S3_S3_+0x52)[0x2b06588e86d2]
/home/MSI/software/jdftx/jdftx-master/build/libjdftx.so(_ZN7IonInfo6updateER8Energies+0x19f)[0x2b065887cd2f]
/home/MSI/software/jdftx/jdftx-master/build/libjdftx.so(_ZN10Everything5setupEv+0x1048)[0x2b065883cae8]
/home/MSI/software/jdftx/jdftx-master/build/jdftx(main+0x857)[0x40ebc7]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x2b0664c61555]
/home/MSI/software/jdftx/jdftx-master/build/jdftx[0x40e2a9]

Our MPI version is 2021.4.0 , dose this matter?

**Comment by shankar1729** [comment]
Please include the cmake options you are using for compilation, including compiler and library choices, and the OS/distribution/version you are doing this on. This is definitely a library compatibility issue, not a memory error.

**Comment by shankar1729** [comment]
Also, if you are doing this with Intel compilers and MPI, try using gcc if possible. As discussed in many issues here, we've seen issues randomly pop in and out with Intel in certain versions of their compilers.

**Comment by Rangingsword** [comment]
Thanks a lot for your reply
  We have solved the problem by changing the compilers from Intel to gcc. This is may really the point of the problem.
