### ISSUE TITLE
JDFTx GPU version crushing with spin-polarized calculations with fluid ions

### ISSUE THREAD

**Issue by vitalyanich** [shankar1729/jdftx#195]
Dear Shankar,

I tried to perform calculation with Cu slab and CO2 molecule. If I enable spin-polarization by setting the flag pintype z-spin, the calculations is crushing. Start with the same input file but with spintype no-spin goes well. The output file with the system is attached to the massage.

The output from slurm is the following:

CUDA Error: invalid argument
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
srun: error: gn03: task 0: Exited with exit code 1

[output_error.txt](https://github.com/shankar1729/jdftx/files/7666965/output_error.txt)

Thank you for any advice,
Vitaliy

**Comment by shankar1729** [comment]
Dear Vitaliy,

I suspect you are running out of memory for the spin-polarized case. For your case with 732 bands and average nbasis 61114, the memory required for wavefunction coeffiecients per k-point and spin is 732 * 61114 * 16 bytes/complex ~ 0.67 GB. You have nStates = 8, so the memory requirement per wavefunction set is ~ 5.33 GB. The conjugate gradients algorithm for minimize requires several copies of these wavefunctions (search direction, gradient, preconditioned gradient etc.), amounting to about 4-5 sets in working memory. So the working requirement for this calculation is ~ 20 - 25 GB > 16 GB on your V100 GPU.

Your spin unpolarized case required half the memory and just about fit on your GPU.

Simple solution: spread the calculation out onto multiple GPUs. You scale up to nStates = 8 MPI processes with one GPU each for this calculation.

Best,
Shankar

**Comment by vitalyanich** [comment]
Shankar, thank you for the reply!

I've tried to split the task across multiple GPUs, but also got an error. Guess that I just don't have enough RAM.

But am I right, that if I don't need ionic optimization and all atoms in my calculation are fixed than I can manually define k-points and perform N separate calculations instead of one calculation with N irreducible k-points and then just get the weighted average to obtain observables in which I am interested in? I.e., <E> = \sum_{ki} (w_{ki} E_{ki}), where w_{ki} is the weight of the i-th k-point and \sum_{ki} w_{ki} = 1. 


P.S. Error when I've tried to run the calculation at 2 GPUs.

Segmentation Fault.
Segmentation Fault.
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
Abort(1) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
In: PMI_Abort(1, application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0)
In: PMI_Abort(1, application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1)
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 1259693.0 ON gn01 CANCELLED ***
srun: error: gn01: tasks 0-1: Killed

**Comment by shankar1729** [comment]
That's strange: if your spin-unpolarized calculation fit on 1 GPU, the spin-polarized one should fit on two GPUs. Perhaps the issue is with the GPU MPI. Please post the full output file so that we can see where the error is occurring as well as the full set of compilation options (the CMakeCache.txt in the build directory will have most of this information).

And no, you cannot split a DFT calculation (regardless of fixed ionic geometry) in that way because all the k-points/spins contribute to a common electron/spin density and KS potential, which then acts on all the wavefunctions of all the k-points/spins.

Best,
Shankar

**Comment by vitalyanich** [comment]
Yes, you are right. It is an issue with MPI. All the error reports and CMakeCache are attached.

How I compiled the program:

cmake -D EnableCUDA=yes -D EnableMKL=yes -D CUDA_ARCH=compute_70 -D CUDA_CODE=sm_70 -D ForceFFTW=yes -D EnableMPI=yes -D CudaAwareMPI=yes -D PinnedHostMemory=yes -D GSL_PATH=/gpfs/data/gpfs0/vitaliy/_Distributives/gsl_2.7_installed_intel ../jdftx-1.6.0/jdft

[CMakeCache.txt](https://github.com/shankar1729/jdftx/files/7720434/CMakeCache.txt)
[jdftx-stacktrace.txt](https://github.com/shankar1729/jdftx/files/7720440/jdftx-stacktrace.txt)
[output.out.txt](https://github.com/shankar1729/jdftx/files/7720442/output.out.txt)
[slurm.out.txt](https://github.com/shankar1729/jdftx/files/7720444/slurm.out.txt)

Best regards,
Vitaliy

**Comment by shankar1729** [comment]
Yep, you are using IntelMPI which does not support direct transfers between NVIDIA GPUs. To continue to use this MPI, recompile with CudaAwareMPI=No. Note that this will involve additional CPU-GPU transfers during MPI operations and will have higher communication overhead.

Alternatively, consider using a cuda-aware build of OpenMPI. Note that the OS package manager versions of openmpi typically do not include this support by default and you will typically need to build it locally.

Best,
Shankar

**Comment by vitalyanich** [comment]
Thank you a lot! Finally, it works.
