### ISSUE TITLE
JDFTX：How to improve the calculation speed of electron scattering

### ISSUE THREAD

**Issue by hwmmm1** [shankar1729/jdftx#196]
Dear Shankar, 
    
I tried to calculate electron-electron scattering. But it takes a long time. The following picture is the result of continuous calculation for 24 hours. Is there any way to improve the calculation speed? The input files are already added below.

![1291639996572_ pic_hd](https://user-images.githubusercontent.com/92436849/146858656-15435052-0585-4c6b-be7f-2aaa4a6876ec.jpg)

![image](https://user-images.githubusercontent.com/
[totalEin.txt](https://github.com/shankar1729/jdftx/files/7758887/totalEin.txt)
92436849/146858164-75ebbe33-6c98-4f79-97
[ commonin.txt](https://github.com/shankar1729/jdftx/files/7758888/commonin.txt)
8f-a372f2d09ac3.png)

**Comment by shankar1729** [comment]
How many processes are you running this with, and what system size are you using? The input files did not come through. Also please post any input/output as text, and not screenshots.

Note that electron scattering is essentially a part of a G0W0 excited states calculation, and will be much much slower than a DFT calculation in general.

Best,
Shankar

**Comment by hwmmm1** [comment]
> How many processes are you running this with, and what system size are you using? The input files did not come through. Also please post any input/output as text, and not screenshots.
> 
> Note that electron scattering is essentially a part of a G0W0 excited states calculation, and will be much much slower than a DFT calculation in general.
> 
> Best, Shankar
Dear Shankar,
    I have uploaded my input file.

**Comment by shankar1729** [comment]
Input files are still not coming through. Try attaching on the web interface rather than by email.

**Comment by hwmmm1** [comment]
[ commonin.txt](https://github.com/shankar1729/jdftx/files/7761014/commonin.txt)
[totalEin.txt](https://github.com/shankar1729/jdftx/files/7761015/totalEin.txt)

I uploaded the file again. I use a server with 24 processes with 520G memory

**Comment by shankar1729** [comment]
The only thing I can think of is setting omegaMax. If you are only interested in linewidths of states within a few eV of the Fermi level, which is typically the case, you can set omegaMax (input in Hartree) around the max energy away from fermi level that you care about. We typically set it to about 5 eV or 0.2 Eh. This could substantially reduce the number of points on the frequency grid.

Additonally, for parallelism, it might be more efficient to use one process per core and no threads/core (in contrast to what works best for DFT claculations).

Best,
Shankar

**Comment by hwmmm1** [comment]
Dear Shankar,
Do you ever know that electron-electron scattering can be ignored in some cases,

**Comment by shankar1729** [comment]
Depends on the material and energy. Electron-electron scattering scales as (E-Ef)^2 for metals and similarly increases away from the band edges in semiconductors. Electron-phonon scattering is typically roughly proportional to DOS with a material-dependent prefactor.

So for hot carriers in metals, e-e scattering dominates once for increasing hot carrier energy. In contrast, mobility (near Fermi-level/band edge transport) is limited primarily by e-ph scattering in crystalline materials.

**Comment by hwmmm1** [comment]
Dear Shankar,
  Thank you so much
