### ISSUE TITLE
Compiling on Perlmutter (new NERSC machine)

### ISSUE THREAD

**Issue by zoowe** [shankar1729/jdftx#198]
Does anyone successfully compile jDFTx on Perlmutter and do not mind sharing some hints? I have no luck after trying many options/combinations.

**Comment by shankar1729** [comment]
Hi Duy,

Perlmutter compilation is somewhat tricky and is a moving target at the moment as the Cray libraries are changing rapidly on that system as they are finalizing software there.

I have added [detailed compilation instructions](http://jdftx.org/Supercomputers.html) just now along with the 1.7.0 release that includes optimizations for the new GPU architecture.

Best,
Shankar

**Comment by zoowe** [comment]
Thank Shankar. It works like a charm.

**Comment by shankar1729** [comment]
Any one who followed this previously, the Perlmutter cuda modules have been reorganized substantially and the old instructions won't work any more. Please check [this page](http://jdftx.org/Supercomputers.html) for updated instructions.

Best,
Shankar
