### ISSUE TITLE
nStates = 1: How to scale up?

### ISSUE THREAD

**Issue by zoowe** [shankar1729/jdftx#199]
Dear all,

I am new to jdftx and need your help to figure out how to do speed up calculations for large systems. From documentations and issues reported here, I see that jdftx parallelization is based on nStates. Because of this, for large system, nStates = 1,  we can use only one mpi task and rely on multithread CPU or gpu for further penalization. 

I did a test with 1700 electrons, 1100 bands, 1 k-point and found that it takes about 16 seconds for 1 SCF cycle with1 MPI task and 1 A100 GPU. Is there any possible parallelization scheme to further improve computational time? I did try to add 2 GPU to 1 MPI task but the code take only one.

Below is my inputs and batch job file
Thanks.
:one: input.in
```
#Structure information for 31x27x75 cell, Initialized 5 species with 332 total atoms.
kpoint-folding 1  1  1
ion-species GBRV/$ID_pbe.uspp
elec-cutoff 20 100
elec-smearing Fermi 0.01
elec-n-bands 1100
dump ionic IonicPositions

electronic-minimize  \
        dirUpdateScheme      FletcherReeves \
        linminMethod         DirUpdateRecommended \
        nIterations          100 \
        history              15 \
        knormThreshold       0 \
        energyDiffThreshold  1e-08 \
        nEnergyDiff          2 \
        alphaTstart          1 \
        alphaTmin            1e-10 \
        updateTestStepSize   yes \
        alphaTreduceFactor   0.1 \
        alphaTincreaseFactor 3 \
        nAlphaAdjustMax      3 \
        wolfeEnergy          0.0001 \
        wolfeGradient        0.9 \
        fdTest               no

electronic-scf  \
        nIterations     50 \
        energyDiffThreshold     1e-08 \
        residualThreshold       1e-07 \
        mixFraction     0.5 \
        qMetric 0.8 \
        history 10 \
        nEigSteps       2 \
        eigDiffThreshold        1e-08 \
        mixedVariable   Density \
        qKerker 0.8 \
        qKappa  -1 \
        verbose no         mixFractionMag  1.5
```
:two: batch job
```batch job
#!/bin/bash
#SBATCH -C gpu
#SBATCH -q debug
#SBATCH -t 0:30:00
#SBATCH -n 1
#SBATCH --ntasks-per-node=1
#SBATCH -c 128
#SBATCH --gpus-per-task=1

export SLURM_CPU_BIND="cores"
export JDFTX_MEMPOOL_SIZE=8192      # adjust as needed (in MB)
export MPICH_GPU_SUPPORT_ENABLED=1  # needed for CUDA-aware MPI support

export JDFTx_pseudo='~/PERLMUTTER/apps/jdftx/jdftx/pseudopotentials/'
export bindir='~/PERLMUTTER/apps/jdftx/build3/'

srun $bindir/jdftx_gpu -i input.in > output_1node_1task_1gpupertask.out

```

:three: header of output_1node_1task_1gpupertask.out
```
*************** JDFTx 1.6.0 (git hash 8d4bd51b) ***************

Start date and time: Wed Jan  5 18:03:48 2022
Executable ~/PERLMUTTER/apps/jdftx/build3//jdftx_gpu with command-line: -i input.in
Running on hosts (process indices):  nid002773 (0)
Divided in process groups (process indices):  0 (0)
gpuInit: Found compatible cuda device 0 'A100-SXM4-40GB'
gpuInit: Selected device 0
Resource initialization completed at t[s]:      2.16
Run totals: 1 processes, 128 threads, 1 GPUs
Memory pool size: 8192 MB (per process)
```

**Comment by zoowe** [comment]
Thanks Shankar. 
About memory, I did increase it but it seems 8GB is the limit to make the code run. Anything higher causes ```GPU memory allocation failed (out of memory)```

**Comment by shankar1729** [comment]
I've had a few jobs set to use a 32768 MB memory pool that worked fine, and I expect up to 39000 to work okay. Could you post a self-contained example along with sbatch script that failed? Could it be that your job ended up sharing a GPU with another, perhaps on the login node and not the queue?

**Comment by zoowe** [comment]
Hi Shankar, 

Thank you for this feedback. I did submit to queue. And sometimes even 8GB does not work either. Here is the self-contained example with 8GB memory, which is failed.
[H2OAu.tar.gz](https://github.com/shankar1729/jdftx/files/7907942/H2OAu.tar.gz)

**Comment by shankar1729** [comment]
Hi Duy,

The issue in this case is that this system requires about 6 GB / wavefunction set and you need several of them for the overall calculation. 40 GB may just about be borderline to fit this system in memory.

So the error is not in being able to set up the memory pool, but that eventually you run out of memory on the GPU. When using the memory pool, the allocator first tries to allocate from the pool, and if full, from the main memory. That may be why you are getting slightly random results with respect to pool size: it may be about how much memory is wasted when trying to allocate large (~ 6 GB) objects out of a pool of a specified size. In that sense, using no pool or a pool of the maximum possible size may work the best for such borderline cases.

To reduce memory, I note that your system has a lot of vacuum/fluid region and is not using coulomb truncation. Using coulomb-interaction Slab and coulomb-truncation-embed, you can substantially reduce the gap region. I expect that you may be able to reduce 10-15 bohrs easily, which may save you up to 20% in memory. (In addition to the obvious ones of reducing number of layers or in-plane supercell size, which would be much more effective if allowable.)

Best,
Shankar

**Comment by zoowe** [comment]
Indeed with out  memory pool, the job works. I am new at this and thank you very much for your help.
