### ISSUE TITLE
is it possible to use vdw functionals?

### ISSUE THREAD

**Issue by hellozhaoming** [shankar1729/jdftx#200]
I want to use some vdw contained funtionals (beef-vdw, B97m-v, scan-rvv10). These funtionals can be found in libxc. However,  libxc does not include the VDW contribution in BEEFVDW that has to be added in separately. Is it possible to use link the libvdwxc in jdftx?

**Comment by shankar1729** [comment]
It should be possible to add support to use libvdwxc in jdftx-, but this will require a modest amount of work. Of you are interested in adding this feature, we would greatly appreciate a pull request.

Best,
Shankar
