### ISSUE TITLE
libxc_oPBE-D functional

### ISSUE THREAD

**Issue by Liuly98** [shankar1729/jdftx#202]
Dear shankar,
I try to use JDFTx to calculate adsorption energies of small molecules (CO2/N2) on different metal sufaces, I know JDFTx can directly use functionals from libxc through command line,for example,"elec-ex-corr gga-opbe-d" means using GGA_XC_OPBE_D functional in libxc. So I try GGA_XC_OPBE_D functional in my calculation because I think the oPBE-D functional of Goerigk and Grimme can consider the VDW contribution to some extent. 
 I wonder if I just specify "elec-ex-corr gga-opbe-d" without  using "van-der-waals D3" in the latest JDFTx version, can it include the long range dispersion correction in my calculations? I know this question may sound strange, but I just want to keep the same functional with my previous calculations(which have used oPBE-D functional already) .
Thanks a lot !

 Best regards,

**Comment by shankar1729** [comment]
No, you need to specify van-der-waals D3 explicitly.

At the time the libxc interface was wrtten for jdftx, there was no information in libxc about extra terms like vdw. Recent versions of libxc seem to have introduced some information about it, so perhaps this can be a feature in the future.

In the same vein, note that JDFTx does not yet implement any nonlocal electronic vdW functionals. So using something like BEEF-vdw from libxc will miss the long-range vdw part.

Best,
Shankar
