### ISSUE TITLE
Fixing bottom layers of a slab

### ISSUE THREAD

**Issue by krl52** [shankar1729/jdftx#203]
Hi Shankar,
I am running some surface energy calculations on a copper slab and I would like to fix the bottom layers of the slab to mimic the bulk structure. However, I am getting the following error message: "Species Cu atoms 0 and 4 are related by symmetry but have different move scale factors or inconsistent move constraints.". Is it possible to resolve this? I have posted my input file below for a 5 layer slab, where I would like to fix the bottom 2 layers. 
Thank you very much,
Kelsey

```
# 5 layer slab, Cu 100, 23 A vacuum, bottom 2 layers fixed, 10x10x1 kpoint mesh, 550 eV cutoff energy

# lattice
lattice Tetragonal 5.008438 61.171293

# ionpos
ion Cu 0.0000000000 0.0000000000 -0.1157896258 0
ion Cu 0.5000000000 0.5000000000 -0.0578948129 0
ion Cu 0.0000000000 0.0000000000 0.0000000000 0
ion Cu 0.5000000000 0.5000000000 0.0578948129 1
ion Cu 0.0000000000 0.0000000000 0.1157896258 1

# common
ion-species GBRV/$ID_pbe.uspp
elec-ex-corr gga-PBE

coulomb-interaction Slab 001
coulomb-truncation-embed 0 0 0
elec-cutoff 20.2121

kpoint-folding 10 10 1
elec-smearing MP1 0.00367493 # Methfessel – Paxton scheme with a smearing width of 0.1 eV
electronic-SCF
ionic-minimize nIterations 10  #Uncomment to enable geometry optimization

dump-name Cu-5layers-Vacuum.$VAR
dump End State IonicPositions

```

**Comment by shankar1729** [comment]
Hi Kelsey,

The reason for this check is that if you move only the top surface atoms, ionic minimization will change the symmetries of the system.

The simple fix is manually break the symmetries: just slightly displace the top layer in its third coordinate - maybe change it to 0.1160, such that the top and bottom surfaces are no longer identical. After that, you should be able to minimize with bottom layers fixed without an issue.

Also note that your example input above has three layers fixed, not two. (0 is fixed, 1 is free.)

Finally, I assume you will eventually add an adsorbate on the top surface. Once you do that, that will also break symmetry anyway, so you will no longer need to worry about this issue.

Best,
Shankar
