### ISSUE TITLE
Is it possible to use TB09 exchange  in new vervion of JDFTx (1.7.0)?

### ISSUE THREAD

**Issue by Zeinabmrd** [shankar1729/jdftx#204]
Hi dear shankar，

I wanna use the tb09 exchange functional in my band structure calculations.  is it possible in new version of JDFTX1.7.0 or not?

Best regards

**Comment by shankar1729** [comment]
Yes, potential-only functionals from LibXC should now work (eg. `elec-ex-corr mgga-x-tb09 mgga-c-tpss` for this one).

Make sure you use electronic-SCF; functionals without energy can fundamentally not be used in the variational electronic-minimize algorithm. Also for meta-GGAs such as this one, you will need to use norm-conserving pseudopotentials.

Finally, note that SCF convergence of such functionals can be much more finicky than regular functionals that define an energy and correspond to a well-defined variational problem.

Best,
Shankar

**Comment by Zeinabmrd** [comment]
thanks in advance dear Shankar

I have another question, is it possible to consider meta‐GGA TB09 including spin orbit coupling effects (TB09+SOC) or Hybrid functionals including spin orbit coupling  (HSE06+SOC) effects in new version?

best regards,

**Comment by shankar1729** [comment]
SOC with meta-GGA is supported, but not yet (correctly) with hybrids.

**Comment by shankar1729** [comment]
Hi Zeinab,

The distributed pseudopotentials (GBRV and SG15) are not relativistic. You can get compatible UPF-format pseudopotentials from the PseudoDOJO website (norm-conserving) or from the QE PSlib website (ultrasoft).

Best,
Shankar

**Comment by Zeinabmrd** [comment]
Dr.Shankar
Thank you again, 

We need LDA+mbj+soc exchange correlation functionals for studying the bandstructure but unfortunately the pseudo Dojo site has only pbe and pbesol type for FR and ONCV and I think because of this matter,the value of bandgap with this type psedo(pbe or pbesol+soc+mbj) become half the amount that is expected(with lda+soc+mbj).

Thanks in advance,
Zeinab
