### ISSUE TITLE
How to split the  calculation with  computeRange in electron electron scattering？

### ISSUE THREAD

**Issue by hwmmm1** [shankar1729/jdftx#205]
Dear Shankar,

I found that in electron  electron scattering, the input parameter **computeRange <iqStart> <iqStop>**can be used to spilt the calculation.
I would like to know how **computeRange** should be used. Is this a representation of energy or another segmentation method using numbers? Could you provide any example that I could follow it.
Thank you so much

**Comment by shankar1729** [comment]
As mentioned in [the command documentation](https://jdftx.org/CommandElectronScattering.html), the split is over momentum transfers. When you run e-e scatter, you will see blocks starting with lines e.g. "Momentum transfer 1 of 72: ...". In that case, you could split the job in two by using e.g. "computeRange 1 36" and "computeRange 37 72" within the electron-scattering command in two different jobs that could be independently run in parallel.

After those have finished, just run another job with no computeRange specified, and it will collect everything together (quickly, without much computation) into the final outputs. Of course you should adjust the numbers above depending on the actual number of momentum transfers for your system, and for how many ever jobs you want to split them over.

Best,
Shankar

**Comment by hwmmm1** [comment]
Dear Shankar, 
![12211643562480_ pic](https://user-images.githubusercontent.com/92436849/151709722-09d1619d-3fd6-4d3b-9bb5-ed20d3646471.jpg)
![12201643562480_ pic](https://user-images.githubusercontent.com/92436849/151709727-ec2132e7-af0e-4260-b790-86bb231e7b99.jpg)
[common.txt](https://github.com/shankar1729/jdftx/files/7966436/common.txt)
[totalE.txt](https://github.com/shankar1729/jdftx/files/7966437/totalE.txt)
I tried to split the calculation of the electron  electron scattering , but the error occurred and my input file has been added to the link. My Momentum transfer 1of 45, so the  I set computeRange 1 25，may be a reasonable value.I still do not understand why the error are showed. 
Looking forward to your reply

**Comment by shankar1729** [comment]
Maybe you are using an older version of the code, prior to the implementation of the computeRange functionality? Per the [change log](http://jdftx.org/ChangeLog.html), this feature was added between 1.6.0 and 1.7.0, so not too long ago. Please update the code and check.

Best,
Shankar

**Comment by hwmmm1** [comment]
Thank you soooo much
