### ISSUE TITLE
compiling errors JDFTX with libxc 

### ISSUE THREAD

**Issue by Zeinabmrd** [shankar1729/jdftx#207]
Hi dear shankar，
I want to compile JDFTX(1.7.0) with  MPI and MKL from Intel(2020.4.304) and with LibXC(5.1.4)(compiled with Intel). I use below command line:

CC=mpiicc FC=mpiifort CXX=mpicxx cmake   -D EnableCUDA=no   -D LinkTimeOptimization=yes  -D EnableMKL=yes  -D EnableFFTW=yes -D EnableLibXC=yes  -D LIBXC_PATH="/home/zmrd/Desktop/install/qelibxc/kl/libxc-5.1.4"  -D MKL_PATH="/opt/intel/compilers_and_libraries_2020.4.304/linux/mkl" -D FFTW3_PATH="/home/zmrd/Desktop/install/qeintel/fftw-3.3.7"  ../jdftx
make all -j12

and I am get below errors:

[ 84%] Building CXX object CMakeFiles/jdftxlib.dir/fluid/VDWCoupling.cpp.o
[ 85%] Linking CXX shared library libjdftx.so
/usr/bin/ld: /home/zmrd/Desktop/install/qelibxc/kl/libxc-5.1.4/lib/libxc.a(functionals.o): relocation R_X86_64_PC32 against symbol `xc_functional_keys' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/jdftxlib.dir/build.make:1919: libjdftx.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:290: CMakeFiles/jdftxlib.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

How can I fix these errors?

Best regards,
Zeinab

**Comment by shankar1729** [comment]
It appears that LibXC has been compiled to only generate the static library (libxc.a), and not the shared library (libxc.so). Please include --enable-shared when you configure the LibXC build.

Best,
Shankar
