### ISSUE TITLE
can JDFTx work with "COHP/COOP" analysis?

### ISSUE THREAD

**Issue by Liuly98** [shankar1729/jdftx#209]
Dear Shankar,

I wonder if I can use JDFTx to analyze bonding and antibonding contributions （like COHP(crystal orbital Hamilton population) or COOP(crystal orbital overlap population) analysis）for solids? or it need interfaces with other codes?

Best,
Leo

**Comment by shankar1729** [comment]
Hi Leo,

That is not natively supported. Those analyses are complex enough that an interface with other codes would make more sense. A contribution of that nature would be highly useful.

Best,
Shankar
