### ISSUE TITLE
Linker errors while building static JDFTx

### ISSUE THREAD

**Issue by ximik69** [shankar1729/jdftx#21]
Hello, dear Shankar.

Several days before I started installing linux (mageia 6) and JDFTx on new laptop.
Hardware is: CPU Core i7-7700HQ(avx,avx2,sse4.1,4.2),  2x8Gb DDr4 2400 MHz, Nvidia 1060 6Gb.

Unfortunately gcc spits lot of linker errors at the last stage while linking executables, see [jdftx_build.txt](https://github.com/shankar1729/jdftx/files/1845900/jdftx_build.txt).
As for me, many of them are because lapack.a misses symbols from ATLAS.

I have installed every library dependency from source, in order to obtain well optimized static libs (my distro has only dynamic ones). Long time ago I tried _statifier_ for making static bins from dynamic ones, but it fails with JDFTx. 

I tried installing JDFTx with script 
[install-jdftx1.4.1.sh.txt](https://github.com/shankar1729/jdftx/files/1845908/install-jdftx1.4.1.sh.txt), which produced that big amount of linker errors. 

The biggest problem with ATLAS is that installs FOUR HOURS due to many speed tests. 
I used this script for installing it 
[atlas.sh.txt](https://github.com/shankar1729/jdftx/files/1845911/atlas.sh.txt)

I am not sure that I managed to switch off throttling, by disabling intel-pstate in the bootloader, setting frequency to 2.8GHz, performance governor and disabling boost [cpufreq.sh.txt](https://github.com/shankar1729/jdftx/files/1845910/cpufreq.sh.txt), as ATLAS still complained about throttling.

L1 and L2 cache sizes guesses are 128K and 32M,which are far from reality (L1 32K insructions+32K data, L2 256K, L3 6M)
Besides that, it shows quite good performance in *make time*.

Then after installing ATLAS, I installed gsl ([install-gsl.sh.txt](https://github.com/shankar1729/jdftx/files/1845913/install-gsl.sh.txt))  and libfftw ([install-fftw.sh.txt](https://github.com/shankar1729/jdftx/files/1845914/install-fftw.sh.txt))

I did not change C_INCLUDE_PATH, LIBRARY_PATH and other enc. vars, as I thought they will not greatly affect compiling process for static binaries. I just added locations of libs directly to cmake arguments.

As a result, linking failed. Even after adding  LIBRARY_PATH and LDFLAGS to install-jdftx1.4.1.sh, I was unable to improve something.

Could you give me some hints what to try,
in order to fix this problem with static linking?

If I succeed, I think it is good idea to post these revised scripts, as a starting point for others. May be they could be helpful for someone.

Thank you in advance,
with best wishes,
Igor.

**Comment by abhiShandy** [comment]
Hi Igor,

I appreciate your enormous effort to install JDFTx. Generally, it is not very difficult to install all the dependencies on an Intel machine like yours. I would suggest you to [install MKL](https://software.intel.com/en-us/mkl) and avoid ATLAS as MKL is more optimized for Intel platforms and easier to install. You may also install CUDA and switch on EnableCuda, EnableMKL , EnableMPI, CudaAwareMPI, PinnedHostMemory for best performance.

Regards,
Abhishek

**Comment by ximik69** [comment]
Hi Abhishek,

thanks a lot for your hint. I planned to use both MPI and CUDA in the way that calculations will run on CPU and GPU simultaneously. But Installing cuda-development-toolkit from my distro lead to conflicting drivers, unability to startx X, finally I had to reinstall everything from scratch after trying to repair. 
The efforts to use OpenMPI(rpms from my distro) lead to unability to find MPI_C and MPI_CXX by cmake. 
While having other errors, I switched to installing everything one by one, starting from minimal configuration.

And even this minimal configuration wasn't successful.

Also I tried using deps from my distro for compiling, but unsuccesfully.

The number of linker errors lowered drastically, but still unresolved symbols like "zeev__" , "ATL_....." existed.

Later I'll post install script and results.

I'll try MKL and see what happens. I'll also try CUDA from nvidia website and see if it will work without troubles.

Also I'd like to ask you some questions regarding MKL and icc.

1)Is it possible to make fully static binaries using OpenMPI with ability to use CUDA?
I have read that CudaAwareMPI needs to load libcuda.so and thus can not be static.
2)Is it possible to make similar binaries without CudaAwareMPI?
To sacrifice performance a bit in favour of portability.

I want to create binaries, which will survive some "evil update" breaking toolchain or compatibility of libs.
I had this problem with VESTA, where update of distro made impossible to run it.

3)Could you advice me some building practices or deployment systems for less difficult build process?
I've heard about EasyBuild and BuildRoot, but have you used them? Will they solve all build problems, or just

**Comment by ximik69** [comment]
substitute existing troubles with another ones?

4)Should I change mageia 6 distro to another one? 
I used mga4 on laptop and scientific linux 6 on two clusters. I had some serious troubles with software building almost in each case.

5)are there some pitfalls with icc and mkl, that could suddenly break everything?

With best wishes,
Igor.

**Comment by abhiShandy** [comment]
Hey Igor,

1. Static linking the CUDA might bloat up the binary, but should be possible.
2. Ya, CudaAwareMPI is completely optional. Memory transfer costs will increase though.
3. We use simple scripts similar to yours to save all the options for configure or CMake.
4. I have no experience with Mageia 6 distro. I have seen it working on CentOS and Ubuntu so far.
5. ICC and MKL should not have any issue. If you have access to ICC, please share the performance differences compared to GCC. I expect ICC to provide better performance. Currently, we use GCC C11 with MKL in our group.

Shankar is busy in a conference. He'll give you clearer suggestions than me. He has tried ICC for JDFTx earlier, and has lot more experience with Linux. I will also discuss about publishing binaries and installation scripts on the website when he returns.

Regards,
Abhishek

**Comment by ximik69** [comment]
Hi Abhishek,

thanks a lot for your answers.

I also thought about possibility to release static binaries "for desperate and impatient users":)

I considered even to make addon to some LiveCD/DVD/USB, to make running JDFTx as easy as booting from LiveCD.
There are two requirements for such distro:
1)easy customization, preferably w/o rebuild of squashfs image
2)ability to run VESTA, gnuplot, and possibly, Octave.

I know that systemrescuecd (http://www.system-rescue-cd.org/) is very well documented and easy to customize (the easiest way is here http://www.system-rescue-cd.org/Modules/, there are also other ways), its relatively easy to boot from network. 
But it doesn't run VESTA due to missing OpenGL libs, namely libGL.



Recently I looked at another BLAS/LAPACK libs and found that OpenBLAS(former GotoBLAS) is included in Buildroot, which looks nice. ATLAS is included into easyBuild. On the first glance Buildroot looks quite easy to install, in contrast to easyBuild. 

Some cluster admins liked GotoBLAS, as it was well optimized.
Have you worked with its ancestor OpenBLAS?

Does it worth to try?

I have downloaded mkl. I've never worked with mkl and icc before. Maybe i'll find icc on cluster at the university, if yes it will be much much later.

With best wishes,
Igor.

**Comment by ximik69** [comment]
Small update,
using libs from my distro
[install-jdftx1.4.1_d.sh.txt](https://github.com/shankar1729/jdftx/files/1853151/install-jdftx1.4.1_d.sh.txt)
[jdftx_build.txt](https://github.com/shankar1729/jdftx/files/1853154/jdftx_build.txt)

**Comment by ximik69** [comment]
Bigger update in progress

using Openblas
[install-jdftx1.4.1_o.sh.txt](https://github.com/shankar1729/jdftx/files/1853179/install-jdftx1.4.1_o.sh.txt)


added openblas in 
[FindCBLAS.cmake.txt](https://github.com/shankar1729/jdftx/files/1853183/FindCBLAS.cmake.txt)

still lots of unresolved symbols.


builds successfully:
[install-jdftx1.4.1_o.sh2.txt](https://github.com/shankar1729/jdftx/files/1853222/install-jdftx1.4.1_o.sh2.txt)

crashes with

*************** JDFTx 1.4.1 (git hash f023bd26) ***************

Start date and time: Wed Mar 28 09:13:47 2018
Executable ./jdftx with empty command-line (run with -h or --help for command-line options).
/src/jdftx-1.4.1_o/jdftx-git/jdftx/core/MPIUtil.cpp:64: MPIUtil:
        Assertion '!procDivision' failed
Stack trace:
         0: [0x4cd0ff]
         1: [0x4cd587]
         2: [0x4cfc43]
         3: [0x4d164e]
         4: [0x40161f]
         5: [0xd40fe3]
         6: [0x449439]
Writing 'jdftx-stacktrace' (for use with script printStackTrace): done.

**Comment by ximik69** [comment]
With added MPI
[install-jdftx1.4.1_o.sh3.txt](https://github.com/shankar1729/jdftx/files/1853278/install-jdftx1.4.1_o.sh3.txt)

something can not find pthread while linking.

[CMakeError.log](https://github.com/shankar1729/jdftx/files/1853287/CMakeError.log)
[CMakeOutput.log](https://github.com/shankar1729/jdftx/files/1853289/CMakeOutput.log)

Short conclusion -it seems to be possible to use openblas, but with additional effort.

With best wishes,
Igor.

**Comment by shankar1729** [comment]
Hi Igor,

That's a lot of stuff for me to parse up there! :)

Is there a reason you are trying to static link? In general getting that to work nicely is more painful, especially with cmake. I would avoid it unless absolutely necessary eg. on platforms that don't support it like BlueGene/Q, or on Windows.

Also, for HPC, it doesn't usually make sense to distribute statically-linked binaries because you want to link to the highest-performing libraries on each platform. I would recommend against using static linking just to gaurd against OS / library updates. Usually, the task of recompiling and linking the code (dynamically) would be far less than getting a static build to work correctly, as you're now encountering. Also for things like CUDA, static linking is highly discouraged as they also need to be constistent with device driver versions (which may get updated).

Finally, I would strongly recommend you to use support libraries / dependencies from the system package management as far as possible. I was skimming through Mageia's list and they al seem to be available; is there a reason you were trying to install your own? If at all you are installing performance libraries, I would recommend MKL on Intel systems as Abhishek did. I have compiled JDFTx against OpenBLAS before on the BlueGene; in that case it was good, but could not match up with IBM's proprietary ISSL libs. Likewise, i you can install MKL, it will almost certainly be faster. If not, use ATLAS and FFTW3 installed from the system package managers.

Best,
Shankar

**Comment by ximik69** [comment]
Hi dear Shankar,

HURRA IT WORKS!!!

Now several comments - I built JDFTx using shared system libs, incl. ATLAS(). I tried this at the very beginning but encountered first pitfall -

**Comment by ximik69** [comment]
> Is there a reason you are trying to static link? In general getting that to work nicely is more painful, especially with cmake. I would avoid it unless absolutely necessary eg. on platforms that don't support it like BlueGene/Q, or on Windows.

Also, for HPC, it doesn't usually make sense to distribute statically-linked binaries because you want to link to the highest-performing libraries on each platform. I would recommend against using static linking just to gaurd against OS / library updates. Usually, the task of recompiling and linking the code (dynamically) would be far less than getting a static build to work correctly, as you're now encountering. Also for things like CUDA, static linking is highly discouraged as they also need to be constistent with device driver versions (which may get updated).

I agree with you, but I had two reasons to try: 1)I failed with the first build using shared libs
2)My setup is quite unstable. It freezes at least once per day due to presence of NVIDIA and Intel GPUs, which confuses X.org. First programs refuse to start, then either mouse or CapsLock stops responding, then both mouse and CapsLock don't respond. (errata from distro show similar but not the same problems). Also while installing cuda-toolkit-devel I destroyed everything. I'll experiment a lot. I wanted to have stable build without troubles with deps.  Thus I thought I can build static binaries (difficult) and then just have fun, regardless any need to reinstall something, or even change distro. I am not sure that I can reproduce my environment if I'd need to change something seriously. But we'll see.

The second reason was the most important for me.

Also now I understand that static linking with cuda is useless as it adds troubles with driver after it's update.

**Comment by ximik69** [comment]
> Finally,

 I would strongly recommend you to use support libraries / dependencies from the system package management as far as possible. I was skimming through Mageia's list and they al seem to be available;

**Comment by shankar1729** [comment]
Hi Igor,

Thanks for the tip about non-MPI version crashing: that is now fixed in latest commit. As for the other points above:

* The reference lapack is only needed by cmake's FindLapack; if you've linked ATLAS, that will get used and not the slower one.

* I don't ever use swap on my compute machines, so I'm not sure about that. I would imagine that using swap could be bad for lower-end SSDs that have fewer write/erase cycles. But this is a general question about whether or not to swap on SSDs at all, and any info you can get from the internet (from sources better informed about this) would be applicable.

Best,
Shankar
