### ISSUE TITLE
definition of "oxidation-state" in the report

### ISSUE THREAD

**Issue by moyulyy** [shankar1729/jdftx#211]
Hello, Shanka,
As a beginner, I do not understand the meaning of some parameters, and I am looking forward to your help.
The Lowdin Population Analysis is always displayed at the end of the total energy calculation.
For example, in the optimization calculation of water, the output Lowdin Population analysis report is as follows,

#--- Lowdin population analysis ---
 oxidation-state H +0.424 +0.424
 oxidation - state O - 0.733

The problem is that I want to clarify the exact concept or definition of "oxidation-state" in the report.
One of my guesses is that the reported value is the number of charge transfers relative to the free atom,
Another guess, of course, is that the reported value is the charge of each atom at the end of the JDFTX calculation.
But I don't understand why the sum of charges corresponding to each atom is not zero. Is this a factor in the constant-potential model?
Similarly, the concept of reported values for the "magnetic-moments" parameter is ambiguous.

I have not read a clear explanation of this before, and I hope to get your explanation. 
Thank you again.

**Comment by shankar1729** [comment]
The reported oxidation states are Lowdin charges of each atom. This is computed by projecting the wavefunctions onto symmetrically-orthonormalized atomic orbitals (aka Lowdin analysis), and counting the total contribution on each atom. This gives the Lowdin electron number of each atom, which is subtracted from the nuclear charge to get the Lowdin charge. An analogous calculation counting the spin difference of these projections yields the Lowdin magnetic moments.

Note that in atomic-basis-set codes, the wavefunctions are linear combinations of atomic orbitals, and the Lowdin electron numbers will add up to the total electron count, and similarly the magnetic moments to the overall one. However, in the plane-wave basis, there is a residual of electron wavefunctions beyond the atomic orbital subspace. That is why the sum of oxidation states do not add up to the total charge.

Best,
Shankar
