### ISSUE TITLE
the exact meaning of each energy in the output report

### ISSUE THREAD

**Issue by moyulyy** [shankar1729/jdftx#212]
Hello, Shankar,
I am a beginner and do not understand the meaning of some simple parameters. I am eager for your help.
At the end of the total calculation, values for various energies are displayed, as an example in the output report section.

#Energy components:
   A_diel =       61.3405967527107947
   Eewald =     4702.9680318706014077
       EH =     5356.7041881986961016
     Eloc =   -10560.8874080963396409
      Enl =       28.6177217285249874
      Exc =     -145.5659104506369488
 Exc_core =       80.8751162737223410
       KE =      220.7219802955927150
  MuShift =       -0.2275834415947720
#-------------------------------------
     Etot =     -255.4532668687240857
       TS =        0.0042550691004206
#-------------------------------------
        F =     -255.4575219378245095
      muN =        0.9339899722051752
#-------------------------------------
        G =     -256.3915119100296920

I would like to know the exact meaning of each energy in the above output report: A_diel, Eewald, EH, Eloc, Enl, Exc, Exc_core, KE, MuShift, Etot, TS, F, muN, G

I already understand some of the parameters. 
For example, 
Etot stands for internal energy U; 
TS is the electron entropy due to the Fermi smear; 
F= Etot-TS represents helmholtz free energy;
mu is the value of the last mu in the process of "Electronic minimization", that is, the applied potential mu; 
N is the last 'nElectrons' in "Electronic minimization," representing the number of electrons; 
G=F-muN represents the grand free energy term in GC-DRT theory

However, I am not clear about other parameters in "Energy Components", and I hope to get your explanation. 
In addition, if there is any mistake in my understanding, please criticize and correct me.

Thank you again.

**Comment by shankar1729** [comment]
You are correct about the terms mentioned. The remaining:

- A_diel: Helmholtz free energy contribution from fluid (see the GC-DFT paper for definition of this)
- Eewald: Ewald sum i.e. nuclear-nuclear Coulomb repulsion
- EH: Hartree term (electron-electron mean field Coulomb)
- Eloc: local part of pseudopotential contribution (electron-nuclear)
- Enl: nonlocal part of pseudopotential contribution (electron-nuclear)
- Exc: exchange-correlation
- Exc_core: exchange-correlation contribution from nonlinear/partial core correction. (Subtract this if comparing total energy with other codes)
- KE: electron (Kohn-Sham) kinetic energy
- MuShift: correction accounting for G=0 (unit cell average) terms in electrostatics for non-neutral systems. This compensates for differences in the nuclear charge density as seen by the electrons (sharp) vs fluid (broadened). You can logically group this into the overall electrostatics (Eewald + EH + Eloc)

Best,
Shankar
