### ISSUE TITLE
adsorption energy calculations

### ISSUE THREAD

**Issue by DaisyWang20** [shankar1729/jdftx#213]
dear shankar :
In my system a H3O+ adsorbed on a slab, mu=-0.12642 (U=-1V vs SHE)
*    deltaGcpm= Gsol(H3O+/slab) - Gsol(slab) - Gsol(H2O)-Gsol(H+)
in which Gsol(H+) =(1/2) G(H2(g)) at SHE conditions, which implies Gsol(H+) = (1/2) A(H2(g)) -muSHE, Therefore the result will be
*    deltaGcpm(eV) =Gsol(H3O+/slab) - Gsol(slab) - (Gsol(H2O)-mu*8) - (Gsol(H2)-mu*2)/2+ muSHE
=(Gsol(H3O+/slab) - Gsol(slab) - (Gsol(H2O)-muN) - (Gsol(H2)-muN)/2)*27.2114+(-1) (G obtained directly from jdftx output file so the unit is Hartree)

is it right?
Thanks!

**Comment by shankar1729** [comment]
The first line looks correct. In the second one, it should be Asol(H2O) and Asol(H2) since you are separating out their muN's, right? Looks fine to me at a glance otherwise.

Best,
Shankar

**Comment by DaisyWang20** [comment]
Thanks very much!!

I meet a new problem today. when I do frequency calculations on a H30 adsorbed on a slab to get the adsorption free energies, I fix the coordinates of all the slab and only relax H3O. But the output file reports an error : 

"Encountered 1 errors while parsing input:
Command 'latt-scale' is missing dependencies { lattice }"

Below is my input file and can you check what the problem is?

include contcar.lattice
coords-type lattice
include contcar.ionpos
vibrations \
    dr 0.01 \
    centralDiff yes \
    translationSym no \
    rotationSym no \
    T 298 \

dump-name $VAR
elec-cutoff 20 100
elec-ex-corr gga-PBE
core-overlap-check None
kpoint-folding 3 3 1
elec-smearing Fermi 0.003675
fluid LinearPCM
pcm-variant CANDLE
fluid-solvent H2O
fluid-cation Na+ 1.
fluid-anion F- 1.
electronic-minimize nIterations 500 energyDiffThreshold  1e-06
van-der-waals D3
target-mu -0.163167
spintype z-spin
elec-initial-magnetization 5 no


ion-species GBRV/$ID_pbe.uspp

coulomb-interaction slab 001
coulomb-truncation-embed 6.86685 12.0753 9.43178
dump End State
dump End Forces
dump End Ecomponents

**Comment by shankar1729** [comment]
Check the contcar.lattice file: this error indicates that the lattice command is missing, so maybe that file is empty somehow?

**Comment by DaisyWang20** [comment]
Thanks, that helps a lot! 
I read a paper just now (J. Am. Chem. Soc. 2018, 140, 29, 9127–9131). In the SI it says : 

> the vibration contribution to the free energy is nearly not affected by the charge and the solvation, thus we can use the difference in electronic energy to approximate the difference in free energy.

I wonder whether we can use the structures optimized by jdftx (with solvation and target-mu) and use other DFT codes such as VASP ( in vacuum)  to do frequency calculations. Is it proper?

Thanks again for your kind help!

**Comment by shankar1729** [comment]
Yes, that should be fine in most cases. However, in special situations where solvation substantially weakens a bond for example, it could affect the vibration frequencies significantly. So, if you find solvation to strongly impact geometries of the surface, you may need to check if the vibrations are changing as well.

Best,
Shankar

**Comment by DaisyWang20** [comment]
Thanks for your reply!  That really helps a lot!

**Comment by DaisyWang20** [comment]
dear shankar :   I'm really confused about the bold terms:
In my system a H3O+ adsorbed on a slab, mu=-0.12642 (U=-1V vs SHE)

deltaGcpm= Gsol(H3O+/slab) - Gsol(slab) - Gsol(H2O)-Gsol(H++e-)
in which Asol(H++e-) =(1/2) A(H2(g)) at SHE conditions, which implies Asol(H+) = (1/2) A(H2(g)) -muSHE, Gsol(H+)=Asol(H+) = (1/2) A(H2(g)) -muSHE, Therefore the result will be
deltaGcpm(eV) =Gsol(H3O+/slab) - Gsol(slab) - (Asol(H2O)-mu8) - (**Asol(H2)**)/2+ **muSHE**
=(Gsol(H3O+/slab) - Gsol(slab) - (Asol(H2O)-muN) - (Asol(H2))*27.2114+(-1) (G obtained directly from jdftx output file so the unit is Hartree)
 I don't know if there is Asol(H2)-**muN** or just Asol(H2)?
Thanks!

**Comment by shankar1729** [comment]
See the recent discussion on [Issue 234](https://github.com/shankar1729/jdftx/issues/234), which describes a very similar situation. In particular, note that in the grand canonical ensemble of e-, you don;t have G(H++e-), but just G(H+).

After following through that discussion, please let me know if you have further questions beyond that.

Best,
Shankar

**Comment by DaisyWang20** [comment]
Dear Shankar: 
Thanks. Yes, I saw it before.
My problem is, the e- is injected from outer circuit, so I'm confused with why it is:
**note that in the grand canonical ensemble of e-, you don;t have G(H++e-), but just G(H+).**

**Comment by shankar1729** [comment]
It doesn't matter where the e- comes from; when you are dealing with grand free energies in this ensemble, you don't count the e-. The mu N terms are already taking care of the e- balance, so if you do it separately, you are double counting.

And yes, mu_H+ (for an ensemble made grand canonical with respect to protons too), equal to G_H+ (for an ensemble which is canonical w.r.t protons), does not depend on mu_e because the H+ has no electrons.

**Comment by DaisyWang20** [comment]
I’m sorry I still don't understand......

In CHE model, A(H+ + e-)=1/2A(H2), which means **A(H+ + e-)** = 1/2A(H2) -eU_SHE, not just A(H+).
So I don't think the fomula 

> **G(H+) = (1/2)G(H2)** = (1/2) (E(H2)  - mu_SHE * 2) =.......

is workable.

**Comment by shankar1729** [comment]
Yes, the above is all correct. It's just that as you showed, G(H+ + e-) = G(H+), so it is pointless to write the (+e-). Essentially, in the grand canonical ensemble of e-, you don't need to balance the e- in your subtraction because they will come automatically from the electrode at the current mu. All you need to do is make sure you use the correct grand free energy for each of the species.

I'm not sure what your pending question is. Please let me know what you are confused about. (And there's nothing stupid about these questions; happy to help getting to a clearer picture.)

Best,
Shankar

**Comment by DaisyWang20** [comment]
Thanks very much!
To make sure that my understanding is right, if I use explict solvation model by adding 3H2O molecule, so that CHE model will not be used:
the adsorption energy of a hydrogen on a slab(initial state:slab+3H2O;final state:slab*H+2H2O+OH-,ΔN_electron≈0.5), is directly [G(slab*H+2H2O+OH-)-G(slab+3H2O)] , which are the G terms extracted from the outputs of the two structures, without any corrections? 

When I compare the adsorption energy in this two ways, I found an energy difference of about 1eV(in CHE model, ΔG=-0.24eV while in the latter, ΔG=0.77eV). So I wonder if there is a problem.

Thanks again for your patient help!

**Comment by shankar1729** [comment]
In your example, it appears that there is a significant change in charge state by about half an electron. This is precisely the limit in which the conventional CHE approach breaks down. So this may be showing you that problem.

If you were in the situation where the GC-DFT charge is close to what you expected for the adsorbate in the CHE model eg. 0 / neutral for an H adsorption, then these should have been closer.

Best,
Shankar

**Comment by DaisyWang20** [comment]
In the process  [slab+3H2O - > slabH+2H2O+OH-], ΔN_electron≈0.52 comes from an electron increase resulting from OH- formation, and 0.48 e- lost from surface positively charged H+ formation, which proved the conclusion you write above [if you were....... CHE model eg. 0 /neutral for a H adsorption.)
 
You mean in this situation, the equation A(H++e-)=1/2A(H2)+eU is no more suitable? But why...

Thanks again for patiently answering these questions!!

**Comment by DaisyWang20** [comment]
> 

Maybe that's because in the process [slab + H+ + e- ->slab*H ] we consider the only e- combined with H+ forms H*?

**Comment by shankar1729** [comment]
It's not that A(H++e-)=1/2A(H2)+eU becomes unsuitable. That part of CHE remains fine.

The issue is that working in the canonical ensemble, you have to balance the electrons. So the typical CHE mode of doing these calculations forces the number of electrons to be integers, such as enforcing slab-H is neutral etc. This causes the partial charges like you observed, which is called electrosorption valency in the old echem literature, to be neglected. (This is pretty much what you mentioned in your last comment from what I understood.)

Best,
Shankar

**Comment by DaisyWang20** [comment]
Yes, but my CHE model (slab+H++e-->slab*H) is also calculated in GC-DFT so I think that part of electron change is counted in....

For example, in the process  [slab(Q1)+H++1.3e- - > slab*H(Q2), Q1=300, Q2=300.3, we have:
ΔA=A( slab*H)-A(slab)-A(H+)-A(1.3e-)=A( slab*H)-A(slab)-(0.5A(H2)+4.44)-**1.3mu** rather than **- 1*mu** , 
ΔG=G( slab*H)-G(slab)-G(H+)=G( slab*H)-G(slab)-(0.5A(H2)+4.44)=A( slab*H)-A(slab)-(0.5A(H2)+4.44) -0.3mu;
while in CHE model, we have ΔA=A( slab*H)-A(slab)-A(H+)-A(e-)=A( slab*H)-A(slab)-(0.5A(H2)+4.44)-**mu**, which seems to cause the difference in ΔA, while in ΔG these two are the same (because G(e-)=0)?

**Comment by shankar1729** [comment]
If that's the case, it should all line up. If you did the calculations in the canonical ensemble with the correct number of electrons and added the appropriate mu N terms, it should give you exactly the same result as the grand-canonical ensemble.

So, write out your final equations both ways and expand them all to the same form eg. write out all the G's in terms of the corresponding A's. You should reach exactly the same equation from both starting points. If they don;t match, you should be able to back trace to where they diverge.

**Comment by krl52** [comment]
If I may jump in, I've also been wondering about the difference between the charge neutral / CHE method vs. the grand canonical. For example, I found that the H binding energy differs by 0.1-0.2 eV between the two methods over the potential range ~ -1.2 to -1.6 V vs. SHE (the fixed potential method yields slightly more negative values). Also, for the fixed potential method, the charge difference between the slab+adsorbate and slab (N(slab+H) - N(slab) with N being the number of electrons reported by JDFTx output) is about 1.2, whereas the charge neutral method suggests that exactly one electron is transferred to the slab surface with H adsorption.

I thought there must be a reason for developing and using the fixed potential JDFT over the CHE, and I'm wondering if it has to do with what you said, that the conventional CHE approach breaks down when there is a significant change in charge state. By this, do you mean the difference between the change between the slab and slab+adsorbate? Or is it the difference between the neutral and charged system?

**Comment by shankar1729** [comment]
For your example, the difference that the GC-DFT makes is the 0.2 e-. The conventional CHE method would assume both slab+H and slab to be neutral, requiring them to differ by 1 electron. The GC-DFT accounts for the fact that the charge of the slab and slab+H vary differently with potential, amounting to an electrosorption valency that could vary with potential.

It is important to note that you could do the same analysis with fixed-charge calculations alone, as long as you manually adjust the charges to get the potential you care about. GC-DFT does not fundamentally change the thermodynamics of the interface of course; it only makes it more convenient to do a bunch of calculations all at the same potential (without assuming / guessing charge states).

That's why the key point to consider here is whether the appropriate charge states are being captured, regardless of the methdo used to the DFT calculation. GC-DFT just makes that easy to do.

Best,
Shankar

**Comment by DaisyWang20** [comment]
> 
I found the problem......the equation should be : 
in the process [slab(Q1)+H++1.3e- - > slabH(Q2), Q1=300, **Q2=301.3**, we have:
ΔA=A( slabH)-A(slab)-A(H+)-A(1.3e-)=A( slabH)-A(slab)-(0.5A(H2)+4.44)-1.3mu rather than **- 1mu** ,
ΔG=G( slabH)-G(slab)-G(H+)=**G( slabH)-G(slab)-(0.5A(H2)+4.44)**=A( slab*H)-A(slab)-(0.5A(H2)+4.44) -1.3mu;
So ΔA equals ΔG.

**Comment by DaisyWang20** [comment]
But still, in the process [slab+H+ e- > slab*H], I think the CHE model is used to calculate the energy of H+, which has one integral electron.  And here in the process we  already considered charge changes, ie., slab(Q1) and slab*H(Q1+0.5). So I still don't understand

> So the typical CHE mode of doing these calculations forces the number of electrons to be integers, such as enforcing slab-H is neutral etc. This causes the partial charges like you observed, which is called electrosorption valency in the old echem literature, to be neglected.

you said before...

**Comment by DaisyWang20** [comment]
> But still, in the process [slab+H+ e- > slab_H], I think the CHE model is used to calculate the energy of H+, which has one integral electron. And here in the process we already considered charge changes, ie., slab(Q1) and slab_H(Q1+0.5). So I still don't understand
> 
> > So the typical CHE mode of doing these calculations forces the number of electrons to be integers, such as enforcing slab-H is neutral etc. This causes the partial charges like you observed, which is called electrosorption valency in the old echem literature, to be neglected.
> 
> you said before, ie., charge neutral method isn't equal to CHE model.

**Comment by shankar1729** [comment]
The CHE approach is used to calculate the energy difference between H+ and H2, which always has an integral electron change, so there is no issue there.

The difference between the approaches comes in when the charge of surface adsorption matters.

**Comment by krl52** [comment]
Is that due to the fact that the Helmholtz energy in the fixed potential calculation differs from the Helmholtz energy of the neutral calculation? Why would that be, if GC-DFT does not fundamentally affect the thermodynamics of the calculation?

**Comment by DaisyWang20** [comment]
Great thanks. I find reaction energies calculated in this two ways have a constant energy difference (≈1.06eV).

slab + H+ + e- -> slab*H    ΔG1   .............E1
slab + H2O + e- -> slab*H + OH-   ΔG2  ............E2

E2-E1, we have ΔG2-ΔG1=Gsol(OH-)+G(H+)-Gsol(H2O)≈1.06eV, which means if we want to use CHE model (H2) as the reference energy(rather H+ from H2O), we should use ΔG2-1.06 eV ( which is exactly ΔG1). My calculation results (ΔG1=-0.24 eV and ΔG2=0.77 eV) proves that.

**Comment by DaisyWang20** [comment]
Great thanks. I find reaction energies calculated in this two ways have a constant energy difference (≈1.06eV).

slab + H+ + e- -> slab*H    ΔG1   .............E1
slab + H2O + e- -> slab*H + OH-   ΔG2  ............E2

E2-E1, we have ΔG2-ΔG1=Gsol(OH-)+G(H+)-Gsol(H2O)≈1.06eV, which means if we want to use CHE model (H2) as the reference energy(rather H+ from H2O), we should use ΔG2-1.06 eV ( which is exactly ΔG1). My calculation results (ΔG1=-0.24 eV and ΔG2=0.77 eV) proves that.

**Comment by shankar1729** [comment]
@krl52 The difference is whether you allow the surfaces to adopt their natural charge states at a given potential (GC-DFT) or if you constrain them to pre-specified charge states (typically done in CHE-based calculations). The point is that surface configurations can and will change their charge in response to a potential due to the electrode freely providing electrons, whereas molecules and ions in gas phase / solution won't do that.

**Comment by shankar1729** [comment]
The CHE approach is used to calculate the energy difference between H+ and
H2, which always has an integral electron change, so there is no issue
there.

The difference between the approaches comes in when the charge of surface
adsorption matters.
