### ISSUE TITLE
vibration calculations for adsorption species only

### ISSUE THREAD

**Issue by DaisyWang20** [shankar1729/jdftx#215]
Dear Shankar,

I tried to do frequency calculations for adsorption species only (fix the slab) through adding "1" to the end of ions coordinates . Take H2 gas as an example (fix a H atom and calculate another H atom's free energy correction, remove symmetry):

> ion H   0.000000000000000   0.000000000000000   0.719643787015941 0
> ion H   0.000000000000000   0.000000000000000  -0.719643787015941 1

But I found that in the output it says:

> Degrees of freedom: 6 total, 6 symmetry-independent.

and 13 configurations calculated.

It seems that the code still calculated theVibrations of the fixed atom . Is there a way to do vibration calculations on part of the system? 

Great thanks!!

**Comment by shankar1729** [comment]
Use parameter useConstraints in the [vibrations command] (http://jdftx.org/CommandVibrations.html). 

Best,
Shankar

**Comment by shankar1729** [comment]
No, at the moment, phonons include all degrees of freedom. (Phonon dispersions etc. are not particularly physical if some atoms fixed.)
