### ISSUE TITLE
How can I calculate Quantum capacitance of a supercapacitor? 

### ISSUE THREAD

**Issue by Skeptikadam** [shankar1729/jdftx#217]
Hello, I am trying to calculate supercapacitor applications of 2D materials. I did some calculations (DOS, phonon, surface charge density etc.). Now I want to obtain capacitance values. How can I obtain it?

**Comment by shankar1729** [comment]
Take a look at the [fixed-potential calculations tutorial](http://jdftx.org/FixedPotential.html), which shows you how to compute a charge vs potential curve. Adapting it to 2D materials is straightforward.

Once you have charging curve, you can differentiate it to get the differential capacitance vs potential. You may need to fit the charging curve with a smoothing spline to do this reliably without introducing too much noise. See the [SI of one of our recent papers](https://doi.org/10.1063/5.0076038) that describes this in a bit more detail; it's in the context of classical MD, but the capacitance extraction considerations are very similar.

Best,
Shankar

**Comment by Skeptikadam** [comment]
Thank you so much for quick and helpful response. The differential capacitance is equal to electrochemical double layer capacitance. Am I right? If yes, how can I calculate quantum capacitance which is needed to obtain total capacitance?

**Comment by shankar1729** [comment]
No, what you calculate here will be the total capacitance: when you change the potential, you are also changing the occupations of the electrons and accounting for the quantum capacitance (determined by the Fermi level DOS).

So, if you want to separate out the liquid capacitance, you will need to estimate the quantum capacitance from the DOS and subtract it (in series) from the total capacitance.

Best,
Shankar

**Comment by shankar1729** [comment]
Just to clarify further above, Quantum Capacitance = e^2 g_A(Ef), where g_A is the density of states at Fermi level per unit surface area. The DOS output by JDFTx is normalized per unit cell, so you just need to divide by the surface area to get this. (If you do that all in atomic units, you will get quantum capacitance per unit area in atomic units, and can convert it to units like uF/cm^2 as needed.)

Best,
Shankar

**Comment by alex-aziz** [comment]
I have a follow-up question on this topic. I have been doing some tests on graphene single-layer surfaces and find that the quantum capacitance is larger than the total capacitance. The results seem to agree with the paper from Zhan and Jiang (https://pubs.acs.org/doi/10.1021/acs.jpclett.6b00047) (Fig4 vs Fig2). So maybe I am missing some fundamental explanation here.

Many thanks for your time, it is greatly appreciated.

Alex

**Comment by alex-aziz** [comment]
That makes sense now, thank you very much for your time and clarification.
