### ISSUE TITLE
Dipole correction for an asymmetric slab

### ISSUE THREAD

**Issue by krl52** [shankar1729/jdftx#218]
Hi Shankar
I was curious to know if JDFTx can implement a dipole correction for, say, calculating the adsorption energy of an adsorbate of an asymmetric slab. Or is it necessary to model a symmetric slab with adsorbate on both sides?
Thank you

**Comment by shankar1729** [comment]
The truncated Coulomb interaction in JDFTx removes the need to separately implement a dipole correction: you can check the electrostatic potential output by the code to make sure that it does not create the short-circuit boundary that introduces the 1/Lz dependence in the potential in the periodic case.

Additionally, if you are using solvation, the solvent screens the dipole-dipole interaction such that such a correction should not be required (even without truncation).

I personally tend to make slabs inversion symmetric whenever possible to be extra cautious, but this is definitely not required when using coulomb truncation and/or solvation.

Best,
Shankar
