### ISSUE TITLE
Octave crashes when doing createVASP

### ISSUE THREAD

**Issue by ximik69** [shankar1729/jdftx#22]
Hi dear Shankar,
I've found another trouble - Octave crashes when doing createVASP.

[user@localhost ecut30]$ createVASP X.out X.vasp X.n 5
terminate called after throwing an instance of 'octave::exit_exception'
panic: Aborted -- stopping myself...
attempting to save variables to 'octave-workspace'...
save to 'octave-workspace' complete
octave exited with signal 6

The same trouble is with scale factor 1.

Version:
[user@localhost ecut30]$ octave --version
GNU Octave, version 4.2.1
Copyright (C) 2017 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.

Octave was configured for "x86_64-mageia-linux-gnu".

It creates vasp file but it is truncated:
[user@localhost ecut30]$ bader X.vasp 

  GRID BASED BADER ANALYSIS  (Version 1.03 11/13/17)

  OPEN ... X.vasp              
  VASP4-STYLE INPUT FILE
At line 89 of file chgcar_mod.f90 (unit = 100, file = 'X.vasp')
Fortran runtime error: End of file

Where can I look in order to give you more info?

Best wishes, Igor

**Comment by ximik69** [comment]
Hi dear Shankar,

I've checked createVASP on my old laptop with mga4 distro. It works but partially. If size of vasp file is bigger than approx. 1.4G(needs to be tested more), bader complains for end of file, like in previous post.

Octave version on mga4 is 3.6.4.  Both distros mageia 4 and 6 are 64bit, octave and bader programs too.

bader complaints for end of file, look like in
http://theory.cm.utexas.edu/henkelman/forum/viewtopic.php?f=1&t=3315

but no ulimits for RAM and file sizes, 64bit executables. I'll continue search.

Best, Igor.

**Comment by ximik69** [comment]
Dear Shankar,

unfortunately I don't have access to VASP. 

Also I have tried again to run **createVASP X.out X.vasp X.n 3** on my new laptop(mga6, octave 4.2.1). It crashed again with the same message as in the first post, but produced quite reasonable file. 
Please don't ask me why did it work. I have totally no idea. I think I need to test several versions of octave in order to have any ideas.

**Comment by ximik69** [comment]
Do you know any easy way to obtain configuration options of octave? Maybe they will give some useful info.

And is it good idea to make symlink called **octave**, pointing to **matlab** on cluster? They don't have octave, but have matlab. Will your scripts work? I can ask admins to install octave, but I don't know appropriate version.

With best wishes,
Igor.

**Comment by shankar1729** [comment]
I have not tested scripts on matlab. Octave supports most matlab syntax, but the reverse is not true. It shoudl be possible to adapt the scripts for matlab fairly easily (eg. switch comment character from # to %, swap string quotes from double to single etc.), but it will likely not work out of the box in matlab.

Best,
Shankar

**Comment by ximik69** [comment]
For instance these:
http://calaba.tumblr.com/post/107087607479/octave-64
https://github.com/calaba/octave-3.8.2-enable-64-ubuntu-14.04

I think "the lazy solution"  is worthwhile to try:
http://calaba.tumblr.com/post/107087607479/octave-64#solution_lazy

I'll see whether createVASP will crash Octave with 64bit indices.

Best wishes,
Igor.

**Comment by ximik69** [comment]
Ok, 
I've managed to build and install octave from this receipt https://github.com/calaba/octave-3.8.2-enable-64-ubuntu-14.04

I installed almost all prereqs,
and adapted scripts a bit(different source and installation dirs, all apt-get commands commented).

It runs. But make test lead to crash.

running
createVASP X.out X.vasp X.n 4
emits:
Sshift =

   40   56   72

terminate called after throwing an instance of 'octave::exit_exception'
panic: Aborted -- stopping myself...
attempting to save variables to 'octave-workspace'...
save to 'octave-workspace' complete
octave exited with signal 6


testing with scaling 1-5 gives the same  but vasp file looks intact. It can be opened by VESTA w/o errors. 

The program *bader*, I used before, was built on mga4 distro and then just binary was copied. Rebuilding it on mga6 seems to eliminate the problem with *At line 89 of file chgcar_mod.f90 (unit = 100, file = 'X.vasp')
Fortran runtime error: End of file*

But this needs more thorough testing.

**Comment by shankar1729** [comment]
Hi Igor,

Thank you for trying out all these options to make it work! It may actually make sense to just translate the functionality out of octave to make this work. One possibility could be to translate the octave portion of the createVASP bash script to python/numpy instead; that shouldn't be too complicated overall.

Best,
Shankar

**Comment by ximik69** [comment]
Hi Shankar,
thanks for your suggestions.

As a conclusion we had two problems:
octave crash and bader error.

The second problem disappeared after rebuild with newer compiler. By the way both binaries are static, thus no troubles of missing/wrong/incompatible ABI deps. Only compiler/flags could be the reason. Now I see it's over.

Octave 3.6.4(mga4 distro) seems to work, 4.2.1(mga6) and 3.8.2 (self built https://github.com/calaba/octave-3.8.2-enable-64-ubuntu-14.04) crash, but seem to produce good files.

**Comment by ximik69** [comment]
I;ve found that this is bug in octave:

https://savannah.gnu.org/bugs/?49271
https://stackoverflow.com/questions/45362265/abnormal-termination-of-gnu-octave-script



Let's run x.m
>>x=5
>>exit(0)

 v.4.2.1
>>[user@localhost ~]$ /usr/bin/octave ./test.m 
warning: function ./test.m shadows a core library function
x =  5
terminate called after throwing an instance of 'octave::exit_exception'
panic: Aborted -- stopping myself...
attempting to save variables to 'octave-workspace'...
save to 'octave-workspace' complete
octave exited with signal 6

v.3.8.2
>>/src/octave/bin/octave ./test.m
warning: function ./test.m shadows a core library function
GNU Octave, version 3.8.2
Copyright (C) 2014 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-unknown-linux-gnu".

Additional information about Octave is available at http://www.octave.org.

Please contribute if you find this software useful.
For more information, visit http://www.octave.org/get-involved.html

Read http://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

x =  5

It crashes due to exit(0) function:)
