### ISSUE TITLE
Converge problems in SCF of slab model

### ISSUE THREAD

**Issue by Rangingsword** [shankar1729/jdftx#220]
I am using jdftx to optimize the geometry of Co001 slab. In the calculation process, it is found that the convergence of SCF slows down step by step until it exceeds the set number of steps and failed. Could you please give me some advice about the problems?  Thanks a lot.

Co001.lattice
lattice \
	18.950172 -9.475086 0.000000 \
	0.000000 16.411331 0.000000 \
	0.000000 0.000000 39.879832 \

Co001.ionpos
ion Co         0.166669995         0.083329998         0.000050000  0
ion Co         0.166669995         0.083329998         0.192860007  1
ion Co         0.083329998         0.166669995         0.096450001  0
ion Co         0.083329998         0.166669995         0.289260000  1
ion Co         0.416669995         0.083329998         0.000050000  0
ion Co         0.416669995         0.083329998         0.192860007  1
ion Co         0.333330005         0.166669995         0.096450001  0
ion Co         0.333330005         0.166669995         0.289360000  1
ion Co         0.666670024         0.083329998         0.000050000  0
ion Co         0.666670024         0.083329998         0.192860007  1
ion Co         0.583329976         0.166669995         0.096450001  0
ion Co         0.583329976         0.166669995         0.289260000  1
ion Co         0.916670024         0.083329998         0.000050000  0
ion Co         0.916670024         0.083329998         0.192860007  1
ion Co         0.833329976         0.166669995         0.096450001  0
ion Co         0.833329976         0.166669995         0.289260000  1
ion Co         0.166669995         0.333330005         0.000050000  0
ion Co         0.166669995         0.333330005         0.192860007  1
ion Co         0.083329998         0.416669995         0.096450001  0
ion Co         0.083329998         0.416669995         0.289260000  1
ion Co         0.416669995         0.333330005         0.000050000  0
ion Co         0.416669995         0.333330005         0.192860007  1
ion Co         0.333330005         0.416669995         0.096450001  0
ion Co         0.333330005         0.416669995         0.289260000  1
ion Co         0.666670024         0.333330005         0.000050000  0
ion Co         0.666670024         0.333330005         0.192860007  1
ion Co         0.583329976         0.416669995         0.096450001  0
ion Co         0.583329976         0.416669995         0.289260000  1
ion Co         0.916670024         0.333330005         0.000050000  0
ion Co         0.916670024         0.333330005         0.192860007  1
ion Co         0.833329976         0.416669995         0.096450001  0
ion Co         0.833329976         0.416669995         0.289260000  1
ion Co         0.166669995         0.583329976         0.000050000  0
ion Co         0.166669995         0.583329976         0.192860007  1
ion Co         0.083329998         0.666670024         0.096450001  0
ion Co         0.083329998         0.666670024         0.289260000  1
ion Co         0.416669995         0.583329976         0.000050000  0
ion Co         0.416669995         0.583329976         0.192860007  1
ion Co         0.333330005         0.666670024         0.096450001  0
ion Co         0.333330005         0.666670024         0.289260000  1
ion Co         0.666670024         0.583329976         0.000050000  0
ion Co         0.666670024         0.583329976         0.192860007  1
ion Co         0.583329976         0.666670024         0.096450001  0
ion Co         0.583329976         0.666670024         0.289260000  1
ion Co         0.916670024         0.583329976         0.000050000  0
ion Co         0.916670024         0.583329976         0.192860007  1
ion Co         0.833329976         0.666670024         0.096450001  0
ion Co         0.833329976         0.666670024         0.289260000  1
ion Co         0.166669995         0.833329976         0.000050000  0
ion Co         0.166669995         0.833329976         0.192860007  1
ion Co         0.083329998         0.916670024         0.096450001  0
ion Co         0.083329998         0.916670024         0.289260000  1
ion Co         0.416669995         0.833329976         0.000050000  0
ion Co         0.416669995         0.833329976         0.192860007  1
ion Co         0.333330005         0.916670024         0.096450001  0
ion Co         0.333330005         0.916670024         0.289260000  1
ion Co         0.666670024         0.833329976         0.000050000  0
ion Co         0.666670024         0.833329976         0.192860007  1
ion Co         0.583329976         0.916670024         0.096450001  0
ion Co         0.583329976         0.916670024         0.289260000  1
ion Co         0.916670024         0.833329976         0.000050000  0
ion Co         0.916670024         0.833329976         0.192860007  1
ion Co         0.833329976         0.916670024         0.096450001  0
ion Co         0.833329976         0.916670024         0.289260000  1

common.in
ion-species SG15/$ID_ONCV_PBE.upf
elec-ex-corr gga-PBEsol
elec-cutoff 20 200

coulomb-interaction Slab 001
coulomb-truncation-embed 0 0 0.14458

#core-overlap-check none

spintype z-spin                     #z-spin = up/dn polarization (non-relativistic spin)
elec-initial-magnetization 64 no

kpoint-folding  2 2 1
elec-smearing Fermi 0.001
lcao-params  200  1e-06 0.005

van-der-waals D3

ionOPT.in
include common.in
include Co001.lattice
include Co001.ionpos

electronic-scf  \
        nIterations     200 \
        energyDiffThreshold     1e-07 \
        residualThreshold       1e-06 \
        mixFraction     0.5 \
        qMetric 0.8 \
        history 10 \
        nEigSteps       2 \
        eigDiffThreshold        1e-06 \
        mixedVariable   Density \
        qKerker 0.8 \
        qKappa  -1 \
        verbose no \
        mixFractionMag  1.5

ionic-minimize  \
        nIterations 200 \
        knormThreshold  0.001 \
        energyDiffThreshold  1e-07 \

dump-name Co001_Vaccum.$VAR
dump End State IonicPositions

**Comment by shankar1729** [comment]
I suspect the low smearing is the key issue here. You seem to have 3x3 in-plane supercell with 2x2 k-points, effectively 6x6 k-points for a unit cell. This would need smearing at least 10x higher for typical metals. So try something like 0.01 Eh; you can use Cold smearing or MP1 if you are concerned about the electronic entropy contributions.

With such a low smearing, you have eigenvalues separated by more than the smearing and an energy vs occupation factors that has several local minima, especially when including magnetization. That is the source of the convergence issues. YOu may have better luck with electronic minimization than SCF, but it will still be quite slow due to this fundamental issue.

Best,
Shankar

**Comment by Rangingsword** [comment]
Thanks for your reply，

I set the smearing width by 0.1 with using Fermi-Dirac function, and the calculation seems to work. Then in the wiki, it is said that the entropy contribution at the same width will follow the order Fermi > Gauss >> (Cold, MP1). I want to ask if you recommend Cold smearing or MP1 because it can better consider the contribution of electronic entropy or just because the 
entropy contribution can not be considered correctly by  Fermi-Dirac function under the current width setting?

Thanks again.

**Comment by shankar1729** [comment]
Right, both Cold and MP1 smearing aim to minimize the contribution of the fake electron entropy introduced by the high smearing. Neither of them is intended to be better suited at capturing electronic entropy effects at some target temperature. Both schemes introduce occupation factors outside the 0 to 1 range to achieve this, with the difference being that MP1 does this symmetrically on both sides of that range, while Cold smearing avoids negative occupations but ends up exceeding 1 by a larger margin instead.

Typically, electronic entropy effects at room temperature are negligible for the structure and energetics of metal surfaces. If you do need to account for them, perhaps a better approach may be to use cold/MP1 smearing to effectively eliminate the electronic entropy effects, and then calculate them after the fact from the density of states at the Fermi level.

Finally, 0.1 Eh = 2.7 eV is way too large for smearing. Typically, for the size of system and k-mesh you are using, 0.01 Eh is much more typical.

Best,
Shankar

**Comment by Rangingsword** [comment]
The convergence are much better by using electronic minimization. Thanks for your help. ^_^
