### ISSUE TITLE
Filling of state 0 band 156 is negative

### ISSUE THREAD

**Issue by krl52** [shankar1729/jdftx#221]
When I attempted to re-start my JDFTx calculation by appending the output, I received the following error:
Filling of state 0 band 156 is negative.

I could not find any information on how to resolve this error, so I am posting it here. I attached my input and output files below as .txt. 
[H_on_Cu100.out.txt](https://github.com/shankar1729/jdftx/files/8499081/H_on_Cu100.out.txt)

[H_on_Cu100.in.txt](https://github.com/shankar1729/jdftx/files/8499082/H_on_Cu100.in.txt)

**Comment by shankar1729** [comment]
Thanks for pointing out this issue! Indeed, the read-back of fillings was not updated after adding support for MP1 smearing (which introduces slightly negative fillings just above the Fermi level).

The latest commit should fix this issue.

Best,
Shankar
