### ISSUE TITLE
compilation error of ‘JDFTX_BUILD_DIR’ was not declared in this scope

### ISSUE THREAD

**Issue by Yaxian0516** [shankar1729/jdftx#226]
Dear Shankar,
I am compiling JDFTx on my institution-run cluster and got the following error

> [  8%] Building CXX object CMakeFiles/jdftxlib.dir/commands/ion_species.cpp.o
/home/users/yaxianw/util/JDFTx/jdftx-1.6/jdftx/commands/ion_species.cpp: In function ‘const std::vector<std::__cxx11::basic_string<char, ichar_traits> >& getPseudopotentialPrefixes()’:
/home/users/yaxianw/util/JDFTx/jdftx-1.6/jdftx/commands/ion_species.cpp:128:22: error: ‘JDFTX_BUILD_DIR’ was not declared in this scope
prefixes.push_back(JDFTX_BUILD_DIR "/pseudopotentials/"); //search paths relative to psp library in build next
                      ^~~~~~~~~~~~~~~
/home/users/yaxianw/util/JDFTx/jdftx-1.6/jdftx/commands/ion_species.cpp:129:13: error: ‘JDFTX_INSTALL_DIR’ was not declared in this scope
   if(strlen(JDFTX_INSTALL_DIR)) //search paths relative to psp library in install target, if any, last
             ^~~~~~~~~~~~~~~~~
/home/users/yaxianw/util/JDFTx/jdftx-1.6/jdftx/commands/ion_species.cpp:130:40: error: expected ‘)’ before string constant

I am using the following settings in the GNU environment which used to work well

> CC=gcc CXX=g++ cmake\
   -D EnableCUDA=no \
   -D EnableMKL=yes \
   -D ForceFFTW=yes \
   -D FFTW3_PATH="/home/users/yaxianw/util/fftw-3.3.10/" \
   -D GSL_PATH="/home/users/yaxianw/util/gsl-2.7.1" \
   -D MKL_PATH="/opt/ohpc/pub/apps/intel2020/compilers_and_libraries_2020.2.254/linux/mkl"\
   -D CMAKE_INCLUDE_PATH="/home/users/yaxianw/anaconda3/lib"\
   ../jdftx
make -j12

I also checked the `config.h` file where it has the variable and does not seem abnormal to me --

> #define PACKAGE_NAME "JDFTx"
#define PACKAGE_DESCRIPTION "The playground for joint density functional theory"
#define PACKAGE_SUMMARY "Toolkit for rapid development of density-functional methods"
#define VERSION_MAJOR_MINOR_PATCH "1.6.0"
#define VERSION_HASH "0da2b54"
#define JDFTX_BUILD_DIR "/home/users/yaxianw/util/JDFTx/jdftx-1.6/build"
#define JDFTX_INSTALL_DIR "/usr/local"

Can you please let me know what the possible reasons might be? 

Thanks,
Yaxian

**Comment by shankar1729** [comment]
Post your CMakeCache.txt to get full information about compiler and library versions.

This seems to be similar to [Issue 132](https://github.com/shankar1729/jdftx/issues/132), which was using Intel compilers. Using GNU compilers fixed the issue there. Here too, this seems to be the compiler complaining about very basic C macro string concatenation syntax.

**Comment by shankar1729** [comment]
One suspicious thing I noted here is that the g++ is a new version from within /opt, but the C compiler is the potentially old system compiler. This could mean that "cpp", the c-preprocessor executable could also be coming from your old system version, leading to this issue. You may want to ensure that all the gcc and g++ related tools are coming from your selected location within /opt.

You may need to load appropriate modules, or set variables like PATH manually: this will depend on how your cluster has been configured. Alternately, try specifiying explicit full paths to both g++ and gcc?

**Comment by shankar1729** [comment]
This issue is most likely because of a "config.h" from one of the directories you are including masking the one in JDFTx. We encountered this with libraries like GSL, if you directly specify the path where you built it, instead of installing it and linking to the installed location.

So please check any dependencies you built from source, and make sure you don;t have a config.h in their include paths. If present, make sure you run a "make install" for those libraries to a local path, and use that path instead of the build directory.

Best,
Shankar
