### ISSUE TITLE
An error in ExCorr.cpp

### ISSUE THREAD

**Issue by antoscha** [shankar1729/jdftx#23]
ExCorr.cpp requires xc_func_info_get_ref from LIBXC, but the function doesn't exist.

**Comment by abhiShandy** [comment]
Did you install LibXC? If not, please install a version >= 3 and add **-D EnableLibXC=yes** to the cmake command. CMake should print out **Found LibXC: \<address of libxc.so>**. If CMake couldn't find it, please add **-D LIBXC_PATH=\<address of libXC>**

**Comment by shankar1729** [comment]
@abhiShandy, it looks like LibXC 4 has changed the interface to get functional info (again!). So it is not backwards compatible with the LibXC 3 interface.

@antoscha, could you please confirm what LibXC version you have installed? If it is 4.*, can you try with 3.* if possible and let us know if that works.

Best,
Shankar

**Comment by antoscha** [comment]
Yes, you're right I use LIBXC 4.0.4. I tried 3.0.1 and things got weird: after the successful compilation all tests have failed with segmentation fault, although without linking to LIBXC all works fine.

**Comment by shankar1729** [comment]
Latest commit on git adds support for LibXC 4. Please test and let me know if it works for you!

When switching to without LibXC vs with LibXC, maybe clean out build directory and start cmake from scratch. This type of segfault has arisen in the past when different files got compiled with different flags i.e. with/without LIBXC_ENABLED in this case. CMake should and usually takes care of this, but once in a while it messes up.

Best,
Shankar

**Comment by antoscha** [comment]
Now works well, thank you! Binaries from the master branch 11% faster than 1.4.1!

**Comment by shankar1729** [comment]
Great, glad to hear it!
