### ISSUE TITLE
Segmentation faults, illegal instruction 4

### ISSUE THREAD

**Issue by krl52** [shankar1729/jdftx#230]
Dear Shankar,
I have been encountering an issue where JDFTx seems to get "stuck" and stops generating output, although the job still seems to be running in my terminal. I keep restarting my calculation (sometimes the process is killed by me but sometimes it aborts with an error message). The first time this happened, the error says:

--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node kelseys-MBP exited on signal 4 (Illegal instruction: 4).

The second time this happened the message simply reported a segmentation fault (aborted) and jdftx dumped a stacktrace file, though I tried running printStacktrace jdftx-stacktrace and did not see any output. The system does not seem to be converging well (I tried running for longer with a different starting geometry and hydrogen atoms closer to the surface, and the system only converges after 56 ionic iterations, and when I restart the calculation from the end state, it can run again for 13 more iterations before converging.) I'm not if that has to do with the segmentation faults. I attached the input, output, and stack trace.

[Cu100.in.txt](https://github.com/shankar1729/jdftx/files/8839060/Cu100.in.txt)
[Cu100.out.txt](https://github.com/shankar1729/jdftx/files/8839061/Cu100.out.txt)
[jdftx-stacktrace.txt](https://github.com/shankar1729/jdftx/files/8839062/jdftx-stacktrace.txt)

**Comment by krl52** [comment]
I saw that there is a similar open issue, so I have tried running tests in the JDFTx build directory. Indeed, it appears that the tests do not pass. So I create a new build directory and run the following to compile:

CC=gcc CXX=g++ cmake EnableMKL=yes -D MKL_PATH=/opt/intel/oneapi/mkl/latest EnableLibXC=yes -D LIBXC_PATH=Users/kelseylevine/JDFTXDIR/LibXC/libxc-5.2.2 ../jdftx-git/jdftx

All tests pass in serial, but tests 5-10 fail in parallel. I'm guessing this has to do with incorrect linking to MKL, but I can't figure out what the problem is. I attached the output of CMakeCache.txt. 

[CMakeCache.txt](https://github.com/shankar1729/jdftx/files/8839429/CMakeCache.txt)

**Comment by krl52** [comment]
I have run JDFTx for a while now without encountering any issues. Now I still have the issue of poor convergence with my system. I am guessing it is due to repulsive effects from the full monolayer of hydrogen atoms in the hollow sites. With only half the hollow sites filled, I achieve much better convergence in only 7 ionic minimizations. However I need to model the full ML which is present at the more negative potentials (see for example fig3c: https://doi.org/10.1021/acscatal.0c05564) Do you have any suggestion for how I can minimize the system and trust that the geometry is well converged?

**Comment by shankar1729** [comment]
Can you explain in more detail the specific issue with convergence that you are encountering in the full monolayer case? Is the issue in geometry optimization or the electronic convergence within each ionic step? Have you tried an inversion symmetric slab in case you were only covering one surface with H?

**Comment by krl52** [comment]
Yes, I believe it's an issue with the geometry optimization since I notice that the system with the full monolayer requires over 50 ionic minimizations to converge and |grad|_K does not decrease consistently, which is what I see when running a DFT calculation for an adsorbate on its least preferred site (for example, H* on a Cu100 on-top site is unstable and shifts to the hollow site). When I re-started the calculation from the end state, it could run for 13 more ionic iterations before finishing again. I haven't tried the symmetric slab yet, but could try that next.

[H_on_Cu100_05ML.out.txt](https://github.com/shankar1729/jdftx/files/8856650/H_on_Cu100_05ML.out.txt)
[H_on_Cu100_1ML.out.txt](https://github.com/shankar1729/jdftx/files/8856655/H_on_Cu100_1ML.out.txt)
[Cu100.in.txt](https://github.com/shankar1729/jdftx/files/8856659/Cu100.in.txt)

**Comment by krl52** [comment]
I tried again with the symmetric slab and the convergence is much better (now it only requires 6 ionic iterations) so I suppose I should use a symmetric slab for the rest of my calculations. I am curious as to why there is a difference, do you have any insight?

**Comment by shankar1729** [comment]
When affordable, top-down symmetric slabs are preferable as you have the same surface on both sides and don't have to worry about what's happening at the bare surface as a function of potential etc. (It also removes any net dipole, but that is screened by the electrolyte and not as much of a concern in solvated calculations; but it is an important concern for vacuum cases.)

That being said, I think one-sided calculations should work just fine here. One thing I noticed is that you are using NonlinearPCM with the gummel-loop iteration which may not be converging sufficiently in some cases, leading to inaccurate forces. I would recommend adding the [pcm-nonlinear-scf](https://jdftx.org/CommandPcmNonlinearScf.html) command, which will solve NonlinearPCM using an alternate algorithm (SCF over fluid potential with an inner linear PCM solve). Let me know if that helped with force accuracy and hence ionic convergence: this was implemented a long time ago and we always use this version, but somehow I missed making it the default yet.

Finally, minor point: I noticed that you are output State at every electronic step, which could be adding a severe disk I/O overhead. You may want to use "dump-interval Electronic 10" or so to avoid such frequent writes of large wfns files.

Best,
Shankar

**Comment by shankar1729** [comment]
One other thing to try: your calculation for the full monolayer seems to be a supercell with an extra space group symmetry. Perhaps, you could try reducing it to the smallest possible cell to both save computational time and not have minimization degrees of freedom constrained by symmetries.

**Comment by krl52** [comment]
I am using a 2x2 supercell since I will eventually place an adsorbed CO* on one of the on-top sites which has coverage of 1/4-/1/2 ML. I seem to have the same issue for the slab with CO* at 1/4 ML (I am just using the slab without CO* for trying different things).

**Comment by krl52** [comment]
The 1x1 supercell (asymmetric slab with added pcm-nonlinear-scf) converges with |grad|_K < 1e-4 after 42 ionic minimizations and the calculation will still converge in one iteration after I restart it. The The 2x2 supercell (asymmetric) with added pcm-nonlinear-scf (from before) converges after 11 iterations (maybe I started from one of my previously optimized geometries). Would you recommend to continue calculations on the asymmetric slab and allow JDFTx to use as many ionic iterations as needed to converge |grad|_K?

Thanks for all your help!

**Comment by shankar1729** [comment]
Yes, I'd say if it's only this one system creating an issue, and the final geometry looks reasonable, it would be better to use the same treatment for all the adsorbate configurations.

Best,
Shankar

**Comment by krl52** [comment]
Alright, thank you so much for the help! I will close the issue.
