### ISSUE TITLE
The difference between 'electronic-scF' and 'electronic-minimize'

### ISSUE THREAD

**Issue by moyulyy** [shankar1729/jdftx#232]
Hello, Shanka,

In the calculation of fixed potential mode that does not involve 'target-mu' command,
is there only a difference in computation speed between the two methods of 'electronic-SCF' and 'electronic-minimize'?

In other words,
the structure or energy data optimized by using an 'electronic-minimize' calculation method,
whether the structure or energy data after structure optimization can be compared with that after using 'electronic-SCF' calculation method.

Here's a simple example:
In a vacuum,
Using the 'electronic-minimize' calculation method, slab and N2 with optimized structure,
compared with *N2 after structure optimization using 'electronic-SCF' calculation method,
Whether the adsorption energy of N2 can be calculated directly or the change of N-N bond length before and after adsorption can be compared.

Thank you again for your generous contribution to my issue.

**Comment by shankar1729** [comment]
Yes, you can use electronic-minimize or SCF interchangeably within a sequence of calculations to most efficiently converge your systems. They are different algorithms to optimize exactly the same free energy functional.

For example, you could use SCF (often faster for metals) for a metal surface in vacuum calculation, and then switch to electronic-minimize (more stable) for a grand-canonical solvated calculation, which is likely faster than using the same algorithm for both steps.

So feel free to mix and match, and test to see which algorithms work better for your specific systems. As in the above example, SCF is often faster, but minimize is often much more stable. So you could start with SCF as a first choice, and then switch to elec-minimize if you encounter convergence difficulties.

Best,
Shankar
