### ISSUE TITLE
Dispersion(vdW) correction

### ISSUE THREAD

**Issue by Jinzz98** [shankar1729/jdftx#236]
Hi,
I am using D3 correction,  should I manually set C6 parameters or use the default value？

**Comment by shankar1729** [comment]
D3 computes C6 parameters based on coordination environment for each atom. This parameterization is much more complex than D2, and JDFTx does not support changing the parameters manually for C6.

If you need to change the parameters manually, you will need to modify the arrays in electronic/VanDerWaalsD3_data.h and electronic/VanDerWaalsD3_data_C6.h and recompile. However, this is going to be a rather challenging endeavor, as will be apparent if you glance at those arrays!

If you want to manually tune the dispersion correction, you may as well just use D2 anyway.

Best,
Shankar
