### ISSUE TITLE
'~' is not a valid command.

### ISSUE THREAD

**Issue by Jinzz98** [shankar1729/jdftx#237]
Hi Shankar,

A puzzling error appears.  
Encountered 1 errors while parsing input: '~' is not a valid command.
But the same input file works well for other calculations. I wonder what causes this error.
Here is the input file.

#------------Pseudopotentials-----
ion-species usr/bin/software/JDFTx/GBRV/$ID_pbe_v1.4.uspp
ion-species usr/bin/software/JDFTx/GBRV/$ID_pbe_v1.2.uspp
elec-cutoff 20
elec-ex-corr gga-PBE
core-overlap-check None

#----------Electronic--------
kpoint-folding 4 4 1
elec-smearing Gauss 0.01
electronic-minimize nIterations 100
exchange-regularization AuxiliaryFunction
spintype z-spin
elec-initial-magnetization 3 no
van-der-waals D3

#----------Geometry----------
ionic-minimize nIterations 200
coulomb-interaction Slab 001
coulomb-truncation-embed 0 0 0
include in.lattice
include in.ionpos

#-----------------fluid----------
fluid LinearPCM
pcm-variant CANDLE
fluid-solvent H2O
#------Outputs------
dump Ionic IonicPositions Ecomponents ElecDensity Lattice
dump-name slab.$VAR

**Comment by shankar1729** [comment]
Please also post `in.ionpos` and `in.lattice`. Very likely, there is a misplaced ~ character in one of those files.

Best,
Shankar
