### ISSUE TITLE
The results of Wannier aren't quite right

### ISSUE THREAD

**Issue by hwmmm1** [shankar1729/jdftx#239]
Dear Dr.Shanker 
![微信截图_20220725165425](https://user-images.githubusercontent.com/92436849/180740420-42e34810-186f-491c-81f1-3fe6e034fb97.png)
![微信截图_20220725165503](https://user-images.githubusercontent.com/92436849/180740431-01e90ecb-e558-41f0-a920-431ad7170204.png)
I ran the bandstructure  and  Wannier calculation，the results show that the convergence.But the drawn band results are consistent with the published results, the Wannier results are strange.The input files are attached below
[bandstruct.txt](https://github.com/shankar1729/jdftx/files/9179704/bandstruct.txt)
[bandstruct.kpoints.txt](https://github.com/shankar1729/jdftx/files/9179705/bandstruct.kpoints.txt)
[common.txt](https://github.com/shankar1729/jdftx/files/9179707/common.txt)
[totalE.txt](https://github.com/shankar1729/jdftx/files/9179708/totalE.txt)
[wannier.txt](https://github.com/shankar1729/jdftx/files/9179709/wannier.txt)
.

**Comment by shankar1729** [comment]
Please explain the curves: which points are Wannier, direct band structure and published? (If you had file names for the figrues that were meaningful, the posted versions have randomized names so that information is lost.)

Also, please post the wannier log file and the mlwfBandRanges file.

**Comment by hwmmm1** [comment]
> Please explain the curves: which points are Wannier, direct band structure and published? (If you had file names for the figrues that were meaningful, the posted versions have randomized names so that information is lost.)
> 
> Also, please post the wannier log file and the mlwfBandRanges file.
[wannier_mlwfBandRanges.txt](https://github.com/shankar1729/jdftx/files/9187630/wannier_mlwfBandRanges.txt)
[wannierout.txt](https://github.com/shankar1729/jdftx/files/9187631/wannierout.txt)
Ande the red line is the wannier result，the colore
![微信截图_20220726154556](https://user-images.githubusercontent.com/92436849/180952087-1d49b0ea-80fd-4f2d-a284-b3590a0d69f3.png)
d line is the direct band structure.The publishen result is attached below.

**Comment by shankar1729** [comment]
Your inner and outer windows are not set correctly: at the bottom end, they seem to be cutting a band (looking at the band ranges file), but they both coincide to -0.204. From the ranges, you might want to work with a lower cutoff of both inner and outer window set to -0.28, which would then lie in a gap (likely between valence and semi-core states, or between two sets of disconnected valence bands).

You may of course also need to increase your number of centers to account for the expanded windows  (by ~ 10, again looking at where -0.204 and -0.28 lie relative to the band ranges).

Best,
Shankar

**Comment by hwmmm1** [comment]
Dear Shanker

 I checked the mlwfBandRanges file，I don't understand the meaning of parameters in mlwfBandRanges. And I didn't find the answer on the Jdftx website or in the issues. What are the meanings of these two columns in the mlwfBandRanges. file？

Could you plerase explain this meaning， so that I can check it in other calculations.

Best,
Hwm

**Comment by shankar1729** [comment]
Each line is the lowest and highest energy of a band, across all k. So if the highest energy of one band is greater than the lowest energy of the next band, those bands are overlapping in energy. If not, you have a gap between those two bands.

So did the above changes work for your case?

**Comment by hwmmm1** [comment]
![微信截图_20220727195851](https://user-images.githubusercontent.com/92436849/181405186-9ce7ef4e-4dab-4e5a-8f08-8fd1ea3e2280.png)
Thank you for your help. By modifying the size of the inner and outer window, I have obtained the correct results
