### ISSUE TITLE
Linker errors

### ISSUE THREAD

**Issue by ahmedhany93** [shankar1729/jdftx#24]
I am having the following error while installing jdftx-1.4.1

[ 96%] Linking CXX executable jdftx
libjdftx.so: error: undefined reference to '__intel_avx_rep_memcpy'
libjdftx.so: error: undefined reference to '__intel_avx_rep_memset'
libjdftx.so: error: undefined reference to '__intel_ssse3_rep_memmove'
collect2: error: ld returned 1 exit status
make[2]: *** [jdftx] Error 1
make[1]: *** [CMakeFiles/jdftx.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 96%] Building CXX object CMakeFiles/wannier.dir/wannier/commands.cpp.o
[ 97%] Building CXX object CMakeFiles/wannier.dir/wannier/WannierMinimizerRS.cpp.o
[ 98%] Linking CXX executable phonon
/eb/software/binutils/2.26-GCCcore-5.4.0/bin/ld.gold: fatal error: phonon: open: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [phonon] Error 1
make[1]: *** [CMakeFiles/phonon.dir/all] Error 2
[100%] Linking CXX executable wannier
/eb/software/binutils/2.26-GCCcore-5.4.0/bin/ld.gold: fatal error: wannier: open: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [wannier] Error 1
make[1]: *** [CMakeFiles/wannier.dir/all] Error 2
make: *** [all] Error 2

My install script is
module load imkl/11.3.3.210-iimpi-2016b 
module load CMake/3.4.3-intel-2016b 
module load GSL/1.16-intel-2016b 
module load FFTW/3.3.4-intel-2016b
module load Doxygen/1.8.11-intel-2016b

 CC=/eb/software/GCCcore/5.4.0/bin/gcc CXX=/eb/software/GCCcore/5.4.0/bin/g++ \
 cmake \
   -D EnableMPI=YES \
   -D EnableMKL=yes \
   -D ForceFFTW=yes \
   -D MKL_PATH="/eb/software/imkl/11.3.3.210-iimpi-2016b/mkl"  \
   ../jdftx

 make -j12

Any help will be appreciated.

**Comment by shankar1729** [comment]
Are you perhaps trying to build in the same directory as the source instead of creating a separate build directory? This does not work for jdftx since there are executables with the same name as subdirectories of the source tree.

Best,
Shankar

**Comment by ahmedhany93** [comment]
Thanks, already resolved this issue and it was as you mentioned.

**Comment by shankar1729** [comment]
Great, glad to hear it!
