### ISSUE TITLE
Units of forces in JDFTx

### ISSUE THREAD

**Issue by itando01** [shankar1729/jdftx#244]
Hello 

I have just started using jdftx for my electronic structure calculations. During the ionic minimization, I noticed that even though I set my knormThreshold to 0.0001, in Ionic-minimizer, the job ended but some atoms didn't reach this threshold. My question are:
1.  does the knormThreshold control the force/gradient stopping criteria on each ion position
2. what are the units of force in JDFTx, is it Ha/Bohr?

Thank you for your time

**Comment by shankar1729** [comment]
Forces are in Hartree/Bohrs indeed, and the stopping criterion is on the RMS force component (and not the max, unlike some other codes).

Best,
Shankar
