### ISSUE TITLE
Electrochemical calculation in vacuum using JDFTx

### ISSUE THREAD

**Issue by KevinLiu7** [shankar1729/jdftx#245]
Hi Shankar,

I understand that the fluid component is essential for the constant-potential calculation using JDFTx. However, my electrochemical reaction occurs in the gas phase without electrolyte. I know I cannot do the constant-potential calculation, so I want to do the constant-charge calculation with the elec-initial-charge flag. We know that in VASP if we use the NELECT flag to assign the number of electrons, it would be a homogeneous distribution of the whole system. My question is if I do the constant-charge calculation using JDFTx, will it be the same as VASP? Or the charge can be more ‘smart’, going to the electrode? I do not learn a lot from the tutorial page.

Thank you for answering my questions!

**Comment by shankar1729** [comment]
In any DFT code, the extra electrons are not forced to be homogeneous over the entire system: they will always go (near) where their potential energy is lowest. This will typically be where there are atoms, such as on the electrode.

I think you are referring to the countercharge necessary to the neutralize the unit cell in periodic DFT, which will be effectively distributed throughout the unit cell in the plane-wave basis. Once again, this behavior will be identical between VASP and JDFTx, if you use the default `coulomb-interaction Periodic` mode.

If you use coulomb truncation in JDFTx, the counter-charge distribution for charged calculations is 'smarter' than the usual periodic case. However, you will still need to fundamentally consider what experimental situation you are modeling, as you are unlikely to have charged electrodes with sizeable electrode charge per atomic-scale unit cell in vacuum (where there is no electrlolyte to produce a countercharge nearby and stabilize it). If you are trying to model a single charged site on the electrode in isolation, you will need to treat it like a charged defect to get the correct energetics. See the [JDFTx defects tutorials](http://jdftx.org/SurfaceDefects.html) for a starting point, but this is its own field separate from electrochemistry that you may need to familiarize yourself with.

Best,
Shankar
