### ISSUE TITLE
Splitting phonon calculations

### ISSUE THREAD

**Issue by hwmmm1** [shankar1729/jdftx#246]
Dear Shankar：

![1661930729183](https://user-images.githubusercontent.com/92436849/187618459-a77d5494-b518-43d1-a2ab-a956f0fe13e4.png)
When I read the tutorials on the web page， in the part of  Splitting phonon calculations. 
For different number of nstates, you suggest set different processes. Is it feasible to set processes to a multiple of nstates？

For example, when nStates is 20, the process is set to 40 or 60? Isn't process the more the better?

Best
Hwmmm

**Comment by shankar1729** [comment]
No, please see the Getting Started page on the hybrid MPI-threads parallelization in JDFTx. The phonon perturbation calculations are each DFT calculations of a supercell, and are MPI-parallelized only over k-points and spin (i.e. nStates). Any additional processes you use will remain idle. So, to use the maximum cores, specify entire sockets or nodes for each process. So you could use up to 20 full compute nodes when nStates is 20, which should be sufficient for reasonable throughput.

Best,
Shankar
