### ISSUE TITLE
Running erro when using ClassicalDFT model in the calculation of solvated H2O

### ISSUE THREAD

**Issue by jiangkaijiangkai** [shankar1729/jdftx#247]
Dear Shankar,
I followed the "Solvation of molecules" tutorial to calculate the H2O in the solution. All the calculation went well, except when I used the ClassicalDFT, the error happened as follows:
  `The output (if any) follows:

/public/home/software/JDFTx/jdftx-1.7.0/jdftx/fluid/FluidSolver.cpp:118: ConvolutionJDFT:
        Assertion 'e.vanDerWaals' failed/public/home/Reru_zjwu_04/software/JDFTx/jdftx-1.7.0/jdftx/fluid/FluidSolver.cpp:118: ConvolutionJDFT:
        Assertion 'e.vanDerWaals' failedapplication called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0`

This is the first time this problem has occurred. I have run printStackTrace, but get nothing.
I've attached the output file below. Could you give me some advice?
Thanks,
Kai
[output.txt](https://github.com/shankar1729/jdftx/files/9554883/output.txt)

**Comment by shankar1729** [comment]
Hi Kai,

Thank you for reporting this bug! It was introduced during the implementation of the D3 vdW corrections, and has now been fixed by commit https://github.com/shankar1729/jdftx/commit/69d1b071381e3ad35c9a5216e8bdea436ef2206c.

Best,
Shankar
