### ISSUE TITLE
jdftx

### ISSUE THREAD

**Issue by Severus0723** [shankar1729/jdftx#248]
Dear Shankar,

I carried out calculations with jdftx for some structures, but often meet an error information:
“ElecMinimize: 	Step failed to reduce F after 3 attempts. Quitting step.
ElecMinimize: 	Undoing step.
	Linear fluid (dielectric constant: 78.4, screening length: 5.74355 Bohr) occupying 0.772517 of unit cell:	Completed after 3 iterations at t[s]:  81394.24
ElecMinimize: 	Step failed along negative gradient direction.
ElecMinimize: Probably at roundoff error limit. (Stopping)”

ElecMinimize always makes a lot of steps when I try to add solvent for calculations. Sometimes ElecMinimize Step failed to reduce F after 3 attempts. So I would like to ask how I should adjust the parameters to make ElecMinimize work, or simplify the steps of it
I'm looking forward to your help!
Best,
jay

**Comment by shankar1729** [comment]
Most likely, this would be because the inner FluidMinimize is not converging correctly, leading to a noisy energy landscape for the outer minimization algorithm. Please attach an example log file where you encounter this and we can confirm that this is the case.

Best,
Shankar

**Comment by Severus0723** [comment]
[Li.zip](https://github.com/shankar1729/jdftx/files/9592934/Li.zip)
Dear Shankar,
Thank you very much, here are all my input and output files, I am wondering if there is some problem with my input parameters or structure. Can you tell me how should I correct it? thanks again

**Comment by shankar1729** [comment]
The fluid minimize seems fine, but the electronic convergence is definitely quite slow for both the vacuum and solvated parts. Looking through your inputs, the smearing of 0.05 Eh (~ 0.55 eV) seemed unusually high and that may be the culprit.

Try the calculation with a more typical smearing in the range of 0.005 - 0.01 Eh, and see if that fares better.

Finally, a few performance tips (that run time is on the extremely high side):

1. You have nStates = 10 and are using 20 processes, leading to 10 wasted processes. Use hybrid MPI - threads parallelism of jdftx appropriately to speed up (see Getting Started). 
2. You have also asked for 8 threads per process for 20 processes on the single node. This is only correct if you actually have 160 physical cores on that node, which seems unlikely to me. My guess is that you have a 2 processor compute node with somewhere in the 8 - 16 cores / socket. If so, run with 2 processes and that many threads / process for best efficiency for such calculations.
3. Optional: you may also be able to reduce the vacuum thickness in the z direction a bit more given that you are using Coulomb trunction (needs convergence testing of course).

Best,
Shankar

**Comment by Severus0723** [comment]
I guess I know how to do , thank you again

best,
jay

**Comment by Severus0723** [comment]
Dear Shankar,
I'm sorry to bother you again, I followed the tutorial on JDFTX, but there are two parameters (coulomb-interaction, coulomb-truncation-embed) that I don't quite understand, so I want to ask you. I want to know the meaning of these two parameters, will it affect the result of the calculation, and how is this parameter set in general? I've attached the input file for my calculation, can you give me a reference?Thank you
best,
jay
![Snipaste_2022-09-19_21-50-17](https://user-images.githubusercontent.com/113652460/191033102-2fe616ce-0712-4704-9c2a-a6f5d9a33baa.png)

**Comment by shankar1729** [comment]
Please first see the following tutorials:

- http://jdftx.org/CoulombTrunc.html
- http://jdftx.org/TwoDmaterials.html

and the corresponding command documentations:

- http://jdftx.org/CommandCoulombInteraction.html
- http://jdftx.org/CommandCoulombTruncationEmbed.html

which describe the meaning in fair amount of detail altogether. There are also a few issue pages that discuss questions on these further already. Let me know if you have questions after looking at these.

Best,
Shankar

**Comment by Severus0723** [comment]
Dear Shankar,
I guess I can probably understand the meaning of these parameters, thank you again

best,
jay
