### ISSUE TITLE
Oscillations in the Kohn-Sham Potential for an Au (100) Slab Calculation

### ISSUE THREAD

**Issue by TheOneWhoCannotBeNamed** [shankar1729/jdftx#251]
Hello Shankar and other users,

As described in post # 249, I am doing a slab calculation for Au (100). I want to plot the electrostatic and Kohn-Sham potentials along a normal line to the surface. Output from the Vscloc file has been normalized, as Shankar has suggested in post # 249. 

While the total electrostatic potential is smooth, the Kohn-Sham potential shows fast oscillations in vacuum, as shown in the following figure. I have tried using different exchange-correlation functionals (GGA-PBE vs GGA-PW91) and increasing the z-dimension of the supercell from 20 to 22 lattice constants, but the oscillations will not disappear.

<img width="641" alt="KN_dtot_potential_Au_100_v4_E0" src="https://user-images.githubusercontent.com/86387952/191978685-03c80526-a0d7-4053-afbd-714b8789e926.png">

I wonder if I have done something incorrect, or whether there are built-in features in JDFTx to correct for such oscillations. Otherwise, I will have to manually smooth out the oscillations in potential.

# Lattice file:
lattice Tetragonal 5.45179 154.2

# Ionic position file:
ion Au   0.500000000000000   0.500000000000000   0.175000000000000 1
ion Au   0.000000000000000   0.000000000000000   0.150000000000000 1
ion Au   0.500000000000000   0.500000000000000   0.125000000000000 1
ion Au   0.000000000000000   0.000000000000000   0.100000000000000 0
ion Au   0.500000000000000   0.500000000000000   0.075000000000000 0
ion Au   0.000000000000000   0.000000000000000   0.050000000000000 0
ion Au   0.500000000000000   0.500000000000000   0.025000000000000 0
ion Au   0.000000000000000   0.000000000000000   0.000000000000000 0
ion Au   0.500000000000000   0.500000000000000  -0.025000000000000 0
ion Au   0.000000000000000   0.000000000000000  -0.050000000000000 0
ion Au   0.500000000000000   0.500000000000000  -0.075000000000000 0
ion Au   0.000000000000000   0.000000000000000  -0.100000000000000 0
ion Au   0.500000000000000   0.500000000000000  -0.125000000000000 1
ion Au   0.000000000000000   0.000000000000000  -0.150000000000000 1
ion Au   0.500000000000000   0.500000000000000  -0.175000000000000 1

# Main input file: 
include Au_100_E0.lattice
include Au_100_E0.ionpos

electric-field 0 0 0

ion-species GBRV/$ID_pbe.uspp
elec-ex-corr gga-PW91
elec-cutoff 20 100

coulomb-interaction Slab 001
coulomb-truncation-embed 0 0 0

kpoint-folding 12 12 1
elec-smearing Fermi 0.01
electronic-minimize
ionic-minimize nIterations 100

dump-name Au_100_E0.$VAR
dump Ionic State
dump End State EigStats Dtot Vscloc

Thank you!

Best,
Yiming Li

**Comment by shankar1729** [comment]
These appear to be Nyquist frequency oscillations in the self-consistent potential, which don't matter for the internal calculation, but indeed can be a problem when trying to analyze it in post-processing. The electrostatic potential has an atom-potential subtraction built into it, which helps minimize such issues and also suppress the magnitude of the nuclear potential oscillations in the region of the material [[J. Chem. Phys. 146, 104109 (2017)](http://doi.org/10.1063/1.4978238)].

Try increasing the charge density cutoff, say to 200 (i.e. `elec-cutoff 20 200`); that may be the easiest way to suppress these Fourier-transform artifacts. If the issue continues, apply a 1-grid point width gaussian filter in your post processing script, and that should get rid of the oscillations entirely.

Best,
Shankar

**Comment by TheOneWhoCannotBeNamed** [comment]
Hi Shankar,

When I increase the charge density cutoff to 200, a sharp maximum and minimum start to appear between z = 30 and 40 a.u. As I further increase the charge density cutoff, the potential becomes smoother and the local extrema get shallower. The results continue to get better as I increase the cutoff from 200 to 300 and 400. I am not sure how large a charge density cutoff is safe to use.
<img width="630" alt="KN_potential_Au_100_E0_original" src="https://user-images.githubusercontent.com/86387952/193728336-7da91e28-1679-4d28-9ba6-7aa894984864.png">

I have also tried applying a Gaussian filter. That is effective in removing the fast oscillations within the potential.

Best,
Yiming
