### ISSUE TITLE
issue with running the test (make test)

### ISSUE THREAD

**Issue by riyazpu** [shankar1729/jdftx#253]
Hi
I have done the basic compilation of jdftx and it completed smoothly, but when i run the make test command it fails. plz have a look. i have also run the command ./jdftx and ldd ./ jdftx and i dont know what it means so the output is pasted below.  so if you can please give any suggestion, it will be a great help for me.

Thank you for your time

sebastian@sebastian-Precision-7920-Tower:~/JDFTx/build$ make test
Running tests...
Test project /home/sebastian/JDFTx/build
      Start  1: openShell
 1/10 Test  #1: openShell ........................***Failed    1.48 sec
      Start  2: vibrations
 2/10 Test  #2: vibrations .......................***Failed    1.46 sec
      Start  3: moleculeSolvation
 3/10 Test  #3: moleculeSolvation ................***Failed    1.55 sec
      Start  4: ionSolvation
 4/10 Test  #4: ionSolvation .....................***Failed    1.32 sec
      Start  5: latticeOpt
 5/10 Test  #5: latticeOpt .......................***Failed    1.55 sec
      Start  6: metalBulk
 6/10 Test  #6: metalBulk ........................***Failed    1.54 sec
      Start  7: plusU
 7/10 Test  #7: plusU ............................***Failed    1.56 sec
      Start  8: spinOrbit
 8/10 Test  #8: spinOrbit ........................***Failed    1.50 sec
      Start  9: graphene
 9/10 Test  #9: graphene .........................***Failed    1.37 sec
      Start 10: metalSurface
10/10 Test #10: metalSurface .....................***Failed    1.45 sec

0% tests passed, 10 tests failed out of 10

Total Test time (real) =  15.15 sec

The following tests FAILED:
	  1 - openShell (Failed)
	  2 - vibrations (Failed)
	  3 - moleculeSolvation (Failed)
	  4 - ionSolvation (Failed)
	  5 - latticeOpt (Failed)
	  6 - metalBulk (Failed)
	  7 - plusU (Failed)
	  8 - spinOrbit (Failed)
	  9 - graphene (Failed)
	 10 - metalSurface (Failed)
Errors while running CTest
make: *** [Makefile:85: test] Error 8

sebastian@sebastian-Precision-7920-Tower:~/JDFTx/build$ ./jdftx
[sebastian-Precision-7920-Tower:460684] *** Process received signal ***
[sebastian-Precision-7920-Tower:460684] Signal: Segmentation fault (11)
[sebastian-Precision-7920-Tower:460684] Signal code: Address not mapped (1)
[sebastian-Precision-7920-Tower:460684] Failing at address: 0x440000e8
[sebastian-Precision-7920-Tower:460684] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x43090)[0x7f6d33880090]
[sebastian-Precision-7920-Tower:460684] [ 1] /usr/local/openmpi/lib/libmpi.so.40(MPI_Comm_size+0x37)[0x7f6d33578b77]
[sebastian-Precision-7920-Tower:460684] [ 2] libjdftx.so(_ZN7MPIUtilC1EiPPcNS_12ProcDivisionE+0x88)[0x7f6d342ddc38]
[sebastian-Precision-7920-Tower:460684] [ 3] libjdftx.so(_Z17initSystemCmdlineiPPcR10InitParams+0x6e)[0x7f6d3433773e]
[sebastian-Precision-7920-Tower:460684] [ 4] ./jdftx(main+0x66e)[0x5570f2c9bfae]
[sebastian-Precision-7920-Tower:460684] [ 5] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f6d33861083]
[sebastian-Precision-7920-Tower:460684] [ 6] ./jdftx(_start+0x2e)[0x5570f2c9c7de]
[sebastian-Precision-7920-Tower:460684] *** End of error message ***
Segmentation fault (core dumped)

(base) sebastian@sebastian-Precision-7920-Tower:~/JDFTx/build$ ldd ./jdftx
	linux-vdso.so.1 (0x00007ffea8503000)
	libjdftx.so (0x00007f81c14ac000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f81c107c000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f81c0e64000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f81c0c72000)
	libmpi.so.40 => /usr/local/openmpi/lib/libmpi.so.40 (0x00007f81c093e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f81c091b000)
	libgsl.so.27 => /usr/local/lib/libgsl.so.27 (0x00007f81c062d000)
	libfftw3_threads.so.3 => /usr/lib/x86_64-linux-gnu/libfftw3_threads.so.3 (0x00007f81c0621000)
	libfftw3.so.3 => /usr/lib/x86_64-linux-gnu/libfftw3.so.3 (0x00007f81c041b000)
	libgslcblas.so.0 => /usr/local/lib/libgslcblas.so.0 (0x00007f81c03d9000)
	libmkl_intel_lp64.so.2 => /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_intel_lp64.so.2 (0x00007f81bf539000)
	libmkl_intel_thread.so.2 => /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_intel_thread.so.2 (0x00007f81bbdd7000)
	libmkl_core.so.2 => /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_core.so.2 (0x00007f81b7a22000)
	libiomp5.so => /opt/intel/oneapi/compiler/2022.0.2/linux/compiler/lib/intel64_lin/libiomp5.so (0x00007f81b75ff000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f81b74b0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f81c1b7d000)
	libopen-rte.so.40 => /usr/local/openmpi/lib/libopen-rte.so.40 (0x00007f81b71f9000)
	libopen-pal.so.40 => /usr/local/openmpi/lib/libopen-pal.so.40 (0x00007f81b6ee1000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f81b6ed7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f81b6ecf000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f81b6eb3000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f81b6eae000)
(base) sebastian@sebastian-Precision-7920-Tower:~/JDFTx/build$

**Comment by shankar1729** [comment]
This seems to be an issue with your MPI library itself, as it is failing immediately upon MPI_Init.

It looks like you built OpenMPI yourself (since it's in /usr/local). Have you tested that it works correctly? Try compiling a basic MPI hello world program and see if you get the same sort of errors as above when you run it. (It just needs to call MPI_Init.)

Best,
Shankar
