### ISSUE TITLE
Questions regarding imaginary phonon frequencies in alpha quartz

### ISSUE THREAD

**Issue by AliGhorashiCMT** [shankar1729/jdftx#255]
Hi Shankar, 

I've been doing some calculations for alpha quartz and been running into some issues.
 1) It seems the SG15 pseudopotentials have cores that are too big to be suitable at the equilibrium lattice configuration of alpha quartz. I can circumvent this issue by using "core overlap check none" but I wonder if this could introduce any other issues down the line? 
2) I used the GBRV pseudopotentials to get around the above problems. I relaxed the lattice and ionic positions and obtained relatively low forces: 
force Si   0.000004722046387  -0.000002361023193  -0.000000000000000 1
force Si  -0.000002361023193   0.000004722046387  -0.000000000000000 1
force Si  -0.000002361023193  -0.000002361023193  -0.000000000000000 1
force O  -0.000002306274202  -0.000002051595234  -0.000007694039485 1
force O   0.000004357869439  -0.000002306274202  -0.000007694039487 1
force O  -0.000002051595234   0.000004357869439  -0.000007694039486 1
force O  -0.000002051595234  -0.000002306274205   0.000007694039486 1
force O  -0.000002306274202   0.000004357869438   0.000007694039485 1
force O   0.000004357869439  -0.000002051595234   0.000007694039487 1

However, I still get imaginary frequencies as shown below: 

Strongest imaginary |omega|: 0.000657 at k: [ 0 0 -0.491518 ]

3) I tried getting rid of these imaginary frequencies by tweaking different phonon parameters, for instance dr. Question: how should one in general pick dr? What's an acceptable range of values and is this range dependent on the material in question? 

4) I should caveat that I have been running phonon calculations with a supercell of 1x1x1 or 2x2x2 due to computational cost. However, I don't believe the phonon supercell should change whether or not I get unstable phonon modes- am I correct in assuming this? 

Thanks,

Ali

**Comment by shankar1729** [comment]
Hi Ali,

For 1., you can check the equilibrium lattice constant, formation energy etc. to ensure that the pseudopotential is not misbehaving due to the core overlap. I've had to often disable that check with SG15, usually without issues.

For the remainder, please post the resulting phonon band structure and specify which supercell you used. The supercell does matter, because it determines whether the observed imaginary frequency is on an explicitly captured q point, or arising from interpolation.

Best,
Shankar

**Comment by AliGhorashiCMT** [comment]
![image](https://user-images.githubusercontent.com/75496694/199592493-2611d694-0a50-4b1e-ba76-81f9a6768a46.png)
I've attached an image of the bandstructure- the supercell for this was 1x1x1 but we're trying a larger supercell now (4x4x4)

**Comment by shankar1729** [comment]
Right, at 1 x 1 x 1, Gamma is the only directly computed q-point, while the rest are interpolated. At Gamma, your phonon frequencies are fine, and they become negative in interpolation. So definitely, higher supercell size is the way to go.

Best,
Shankar
