### ISSUE TITLE
The single point energy of JDFTx

### ISSUE THREAD

**Issue by Lee12402** [shankar1729/jdftx#256]
Dear Shankar,
I am a novice in JDFTx. I am trying to calculate the single point energy of a water molecule, and the result is very different from that obtained by VASP. May I ask if there is anything wrong with my settings or the structure?
Thank you very much for your help!
[jdft.txt](https://github.com/shankar1729/jdftx/files/10068487/jdft.txt)
[VASP.txt](https://github.com/shankar1729/jdftx/files/10068489/VASP.txt)

**Comment by Lee12402** [comment]
By the way, here's the results from jdftx:
<img width="272" alt="屏幕截图 2022-11-22 230114" src="https://user-images.githubusercontent.com/118829502/203347640-91e8ab79-1c76-4cee-8edf-25f9cf35c157.png">
The energy is -14.222780eV from VASP.
Looking forward to your reply.

**Comment by shankar1729** [comment]
Absolute energies and its components are dependent on the pseudopotential used, so they will definitely be rather different between VASP which uses its own pseudos and other codes that may use common pseudo sets. In particular, JDFTx and QE should agree quite closely on total energies when used with the same pseudos (with a caveat about partial core correction handled slightly differently).

Regardless, all physical results are based on energy differences, and these should be close for appropriately converged calculations in different codes.

Best,
Shankar
