### ISSUE TITLE
How to set the value of symmetry-threshold

### ISSUE THREAD

**Issue by moyulyy** [shankar1729/jdftx#257]
Hello, Shankar,

In the two-dimensional material structure optimization calculation, the report is printed as follows:
//Symmetry operations do not seem to form a group.
//This is most likely because the geometry has some border-line symmetries.
//Try either tightening or loosening the symmetry-threshold parameter.

In some tests, using symmetry-threshold = 0.00015, the calculations worked well, although I'm not sure what this slightly more specific parameter means.
As mentioned above, symmetry has been increased by only 0.00005 compared to the default value. Is that acceptable?

I am looking forward to your opinions and suggestions on my questions, which I believe will help me a lot.
Thank you again for your generous contribution to my issue.

**Comment by shankar1729** [comment]
Most likely, this is due to insufficient precision in the lattice vectors or atomic positions. Rather than adjusting the threshold, it would be better to improve the geometry precision.

Post your lattice and ionpos, and we can identify the issue quickly.

(This has nothing to do with 2D materials per se.)

**Comment by moyulyy** [comment]
Isn't it computationally rigorous to just tweak the threshold a little bit? So should I be wary of any calculations performed to adjust this threshold? (Can these calculations be trusted?)

The lattice is set to
lattice\
28.221274364523200       0.000000000000000       0.000000000000000\
-16.291471988524000      32.58501833024680       0.000000000000000\
0.0000000000000000        0.000000000000000       28.34574246948110

The atomic position pattern is
ion B -0.0000005000000000      0.1721215000000000    0.3        1
ion B 0.3278794999999999       0.32787899999999        0.3        1
ion B 0.1721210000000000      -0.0000005000000000   0.3         1
...
ion N 0.5000005000000000      0.8239374999999999    0.3        1
ion N 0.6760614999999999      0.6760619999999999    0.3        1
ion N 0.8239379999999998      0.50000099999999        0.3        1


For more details, see the attached printed output report.
[Ion_opt.zip](https://github.com/shankar1729/jdftx/files/10082097/Ion_opt.zip)


In addition, I am curious about how to improve the geometric accuracy and which method to use to determine whether the accuracy of lattice vector or atomic position meets the requirements. Is there a tutorial or literature on this?

I think I need to supplement this part of knowledge, which seems to involve more profound and basic knowledge.

**Comment by shankar1729** [comment]
Raising the threshold seems to have worked well in this case, but it can lead to problems when border-line symmetries leads to detection of some symmetry operations but not the others. This can cause problems with fundamental assumptions in the algorithms used for symmetrization of various quantities, especially if the detected list of operations do not form a group. (JDFTx will flag an error if this happens.)

I would still recommend using a structure with high precision, wherever possible. The easiest way to do this is what you have already done: if you can get JDFTx to run with a higher threshold, do so for at least one ionic step and output the positions. The output positions will have symmetries enforced to machine precision, and you can use this as an input for subsequent calculations. I would just recommend that you use the high accuracy structure as your version of record for all further processing.

Best,
Shankar
