### ISSUE TITLE
JDFTx cannot find MKL

### ISSUE THREAD

**Issue by krl52** [shankar1729/jdftx#260]
Hi Shankar,
I was rebuilding / testing JDFTx and had an issue with only one of the tests (test 9) failing. I traced it back to a library loading issue even though my LD_LIBRARY_PATH is set in my bash profile (to $HOME/opt/openmpi/lib). In the build directory, I ran `cmake -D EnableMKL=yes MKL_PATH=/opt/intel/oneapi EnableLibXC=yes LIBXC_PATH=/Users/kelseylevine/libxc-6.0.0 ../jdftx-git/jdftx`  ) which returned the following:

```
CMake Warning:
  Ignoring extra path from command line:

   "/Users/kelseylevine/JDFTXDIR/build/MKL_PATH=/opt/intel/oneapi"


CMake Warning:
  Ignoring extra path from command line:

   "LIBXC_PATH=/Users/kelseylevine/libxc-6.0.0"

```
I decided to try running a script with one of the LibXC functionals and indeed it failed, so I guessed that JDFTx was not finding/using MKL either. I can cd to the MKL path that I had specified, so it does exist. I even tried installing MKL in the default location /opt/intel, clearing out the build directory, and re-running cmake without the MKL path specified. I'm not sure what I've done but JDFTx cannot find MKL at all anymore, even when I try clearing the build directory and re-running make with the MKL path specified. 

```
CMake Error at CMake-Modules/FindMKL.cmake:48 (message):
  Could not find the MKL interface-layer library (Add -D MKL_PATH=<path> to
  the cmake commandline for a non-standard installation)
Call Stack (most recent call first):
  CMakeLists.txt:72 (find_package)

```
[CMakeOutput.log](https://github.com/shankar1729/jdftx/files/10138176/CMakeOutput.log)

[CMakeCache.txt](https://github.com/shankar1729/jdftx/files/10138177/CMakeCache.txt)

**Comment by shankar1729** [comment]
Could this be an issue due to filenames in the most recent oneAPI MKL changed from what it used to be in previous versions? If you have an older MKL installation elsewhere on this machine, could you please check if the compilation works normally when you point MKL_PATH to that installation?

**Comment by krl52** [comment]
I have an older version of MKL from March or so, but that doesn't seem to make a difference... cmake still ignores the MKL path.

**Comment by shankar1729** [comment]
Noticed something strange in the error message above: it complains about unused path "/Users/kelseylevine/JDFTXDIR/build/MKL_PATH=/opt/intel/oneapi". The variable passed to cmake should have just been MKL_PATH.

Perhaps the issue is that you are missing a `-D`. It should be `cmake -D MKL_PATH=/opt/intel/oneapi ...`

Please try that and confirm if the issue persists.

Best,
Shankar

**Comment by krl52** [comment]
OK, yes, strangely, that does seem to be the issue. 

`cmake -D EnableLibXC=yes LIBXC_PATH=/Users/kelseylevine/libxc-6.0.0 -D EnableMKL=yes MKL_PATH=/opt/intel/mkl ../jdftx-git/jdftx
`Results in a cmake error: `Could not find the MKL interface-layer library`

`cmake -D LIBXC_PATH=/Users/kelseylevine/libxc-6.0.0 EnableLibXC=yes -D MKL_PATH=/opt/intel/mkl EnableMKL=yes ../jdftx-git/jdftx
`
completes with only a warning that “Manually-specified variables were not used by the project”

All the tests passed except 9 and I realized this was because octave was not installed. At first JDFTx could not find the LibXC functionals so I did `make clean` and then complied with:
`cmake -D LIBXC_PATH=Users/kelseylevine/libxc-6.0.0 -D EnableLibXC=yes ../jdftx-git/jdftx`
