### ISSUE TITLE
Calculating ∆G of an electrochemical systen

### ISSUE THREAD

**Issue by itand16** [shankar1729/jdftx#262]
Dear Developer

I recently started using JDFTx, great software, and I have a couple of questions related to electrochemical systems. It is easy to draw an energy diagram for an electrochemical system, in my case CO2 reduction at any applied potential using Vacuum DFT, computational hydrogen electrode (CHE), by applying the linear relationship between ∆G and U, as ∆G(U) = ∆G(U@0V) - eU. As I understand it JDFTx applies a potential through target-mu command, therefore is it correct to say then that ∆G between two states is just the difference between the product(G) and the reactant(G), corrected for vibrational terms? or are there additional terms as in CHE?

My second inquiry related to how to set target-mu, say I want to run a calculation at -0.6V vs RHE which is -1.043V vs SHE. Would target-mu be -4.44 eV(mu_SHE)-(-1.043)/27.21?

Thank you for your time.

**Comment by shankar1729** [comment]
That's correct: you directly get the grand free energy G at the specified potential U, and you can subtract the G of all species in the reaction to get the reaction free energy change. (You only need to be careful if there are some species not calculated using grand-canonical DFT eg. if you have a electosorption reaction like M + A -> M-A, where M is the metal surface and A is a molecule in solvent. In this case, you will calculate isolated A without standard canonical DFT, and will need to compute its grand free energy as G = E - mu N manually, where mu is the current absolute electrode voltage. You could also perform grand-canonical DFT for the isolated molecule, but this is unnecessary and can be difficult to converge.)

As for the mu, that is correct up to a parenthesis. Specifically, in your example, the mu for target-mu in Hartrees should be  (-4.44 - (-1.043))/27.21. (Unless you meant eV = 1/27.21, in which case that was already correct.) 

Best,
Shankar

**Comment by itand16** [comment]
Hello

Thanks for your reply. It makes sense. One follow-up question, in calculating the grand free energy of a free molecule by G = E - mu N, what does N means, is it the total number of electrons in the molecule? and the mu will be the absolute voltage or it will be the same mu value as set in the target-mu keyword? 

Thanks again for your time

**Comment by shankar1729** [comment]
That's right: N is the total number of (pseudo-valence) electrons in the molecule i.e.  the nElectrons reported during initialization of the molecule calculation (must use the same pseudopotentials of course), and mu is the absolute chemical potential in Hartrees as given in the target-mu command. (The potential vs. SHE in Volts does not appear directly in any JDFTx inputs/outputs.)
