### ISSUE TITLE
Certain Phonon Supercells Crashing

### ISSUE THREAD

**Issue by ddai2025** [shankar1729/jdftx#263]
Hi Professor Sundararaman,

I'm running into some strange issues when doing phonon calculations in lithium peroxide. Some phonon supercells, despite being compatible with the electronic kpoint folding, cause phonon calculations to crash. For example, the following is from a phonon dry run with an 8 by 8 by 8 electronic kpoint folding and phonon supercell 4 4 4. Notably, I only got issues when the z-component of the phonon supercell was above 2. For example, phonon supercell 2 2 2 and phonon supercell 4 4 2.

**Total Energy Calculation**
> lattice \
>        5.975527403168104   -2.987716702385684    0.000000000000000  \
>        0.000054269999656    5.174985667153457    0.000000000000000  \
>        0.000000000000000    0.000000000000000   14.548846284231365
>        
> ion Li   0.000000000000000   0.000000000000000   0.000000000000000 1
> ion Li   0.000000000000000   0.000000000000000   0.500000000000000 1
> ion Li   0.333333333333333  -0.333333333333333   0.250000000000000 1
> ion Li  -0.333333333333333   0.333333333333333  -0.250000000000000 1
> ion O   0.333333333333333  -0.333333333333333  -0.350428161519706 1
> ion O   0.333333333333333  -0.333333333333333  -0.149571838480294 1
> ion O  -0.333333333333333   0.333333333333333   0.149571838480294 1
> ion O  -0.333333333333333   0.333333333333333   0.350428161519706 1
>
> electronic-minimize energyDiffThreshold 1e-10
> ion-species SG15/$ID_ONCV_PBE.upf
> core-overlap-check none
> elec-cutoff 40
> kpoint-folding 8 8 8
>
> elec-smearing Fermi 0.0003
> spintype z-spin
> elec-initial-magnetization 0 no
> elec-n-bands 24
> converge-empty-states yes
>
> dump End State

**Phonon Calculation**
> include neutral.in
> initial-state neutral.$VAR
> dump-only
>
> phonon supercell 4 4 4 Fcut 0 ${phononParams}
>

**Error Message from Phonon Dry Run**

> ------- Configuring supercell and perturbation modes -------
> 
> ---------- Setting up symmetries ----------
> 
> Found 24 point-group symmetries of the bravais lattice
> Found 24 space-group symmetries with basis (with translations restricted to unit cells)
> Applied RMS atom displacement 9.92892e-16 bohrs to make symmetries exact.
> 
> Finding maximally-symmetric orthogonal basis for displacements:
>  [ +0.000000 +0.000000 +1.000000 ] |Stabilizer|: 12
>  [ +0.500000 +0.866025 +0.000000 ] |Stabilizer|: 4
>  [ -0.866025 +0.500000 +0.000000 ] |Stabilizer|: 4
> /home/gridsan/ddai/jdftx1/jdftx-git/jdftx/electronic/ColumnBundleTransform.cpp:64: ColumnBundleTransform:
> 	Assertion '*std::min_element(index.begin(), index.end()) >= 0' failed--------------------------------------------------------------------------
> MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
> with errorcode 1.
> 
> NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
> You may or may not see output from other processes, depending on
> exactly when Open MPI kills them.
> --------------------------------------------------------------------------

Would you happen to know why this happens and how to fix it? Thank you so much for your help!

Sincerely,
David Dai

**Comment by shankar1729** [comment]
Dear David,

My best guess is that this is a borderline symmetry issue. I noticed that your lattice vectors have a component 0.000054, which is just below 1E-4, the default symmetrization threshold. To this extent, your lattice is almost hexagonal.

Try making the lattice exactly hexagonal using `lattice hexagonal 5.975527403168104 14.548846284231365`. It will be essentially the same as what you gave, but with that small component exactly zero and the remaining non-zero in-plane components in exactly a 2 : 1 : sqrt(3) ratio (yours are currently off at the 5th digit). Hopefully that resolves the error you encountered.

Best,
Shankar

**Comment by ddai2025** [comment]
Hi Professor Sundararaman,

That fixes the issue! Thank you so much for your help!

Sincerely,
David
