### ISSUE TITLE
Frequent Segmentation Faults for Phonon Calculations

### ISSUE THREAD

**Issue by ddai2025** [shankar1729/jdftx#264]
Hi Professor Sundararaman,

I'm having frequent segmentation faults when running phonon calculations. For example, I'm currently doing a phonon supercell 4 4 4 calculation for alpha-quartz and getting many segmentation faults. The input files, as well as compute resources, are pasted below.

**Total Energy Calculation**
> lattice \
>            9.510703213196763   -4.755351508924099    0.000000000000000  \
>            0.000000003536884    8.236510588601009    0.000000000000000  \
>           -0.000000000000000    0.000000000000000   10.434275160820617
> 
> ion Si   0.476210397179168  -0.000000000000000   0.333333339222223 1
> ion Si  -0.000000000000000   0.476210397179168   0.666666672555556 1
> ion Si   0.523789602820831   0.523789602820831   0.000000005888890 1
> ion O   0.415052632242475   0.256659934987424   0.205970428695385 1
> ion O   0.743340065012575   0.158392697255050   0.539303762028718 1
> ion O   0.841607302744949   0.584947367757525   0.872637095362052 1
> ion O   0.256659934987424   0.415052632242475   0.794029583082394 1
> ion O   0.158392697255050   0.743340065012575   0.460696249749061 1
> ion O   0.584947367757525   0.841607302744949   0.127362916415728 1
> 
> electronic-minimize energyDiffThreshold 1e-10
> ion-species SG15/$ID_ONCV_PBE.upf
> core-overlap-check none
> elec-cutoff 40
> kpoint-folding 8 8 8

**Phonon Calculation**
> include neutral.in
> initial-state neutral.$VAR
> dump-only
> 
> phonon supercell 4 4 4 dr 0.05 ${phononParams}

**SBATCH Script**
> #!/bin/bash
> 
> #SBATCH -o wet2.out
> #SBATCH -c 6
> #SBATCH -n 8
> #SBATCH -N 3
> #SBATCH --exclusive
> #SBATCH --array=19,20,21,22
> #SBATCH --mem=180G
> 
> source /etc/profile
> module load mpi/openmpi-4.1.3
> 
> export OPENBLAS_NUM_THREADS=1
> export phononParams="iPerturbation $SLURM_ARRAY_TASK_ID"
> mpirun --bind-to none phonon -i phonon.in | tee phonon.$SLURM_ARRAY_TASK_ID.out

**Segmentation Fault Message**
> ---------- Setting up ewald sum ----------
> Optimum gaussian width for ewald sums = 5.172562 bohr.
> Real space sum over 343 unit cells with max indices [  3  3  3  ]
> Reciprocal space sum over 21141 terms with max indices [  13  13  14  ]
> 
> ---------- Setting up ewald sum ----------
> Optimum gaussian width for ewald sums = 5.172562 bohr.
> Real space sum over 343 unit cells with max indices [  3  3  3  ]
> Reciprocal space sum over 21141 terms with max indices [  13  13  14  ]
> 
> ---------- Setting up ewald sum ----------
> Optimum gaussian width for ewald sums = 5.172562 bohr.
> Real space sum over 343 unit cells with max indices [  3  3  3  ]
> Reciprocal space sum over 21141 terms with max indices [  13  13  14  ]
> 
> ---------- Setting up ewald sum ----------
> Optimum gaussian width for ewald sums = 5.172562 bohr.
> Real space sum over 343 unit cells with max indices [  3  3  3  ]
> Reciprocal space sum over 21141 terms with max indices [  13  13  14  ]
> 
> ---------- Allocating electronic variables ----------
> Skipped wave function initialization.
> 
> 
> ---------- Allocating electronic variables ----------
> Skipped wave function initialization.
> 
> 
> ---------- Allocating electronic variables ----------
> Skipped wave function initialization.
> 
> 
> ---------- Allocating electronic variables ----------
> Skipped wave function initialization.
> 
> Segmentation Fault.
> Segmentation Fault.
> Segmentation Fault.
> Segmentation Fault.
> Segmentation Fault.
> Segmentation Fault.
> --------------------------------------------------------------------------
> MPI_ABORT was invoked on rank 4 in communicator MPI_COMM_WORLD
> with errorcode 1.
> 
> NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
> You may or may not see output from other processes, depending on
> exactly when Open MPI kills them.
> --------------------------------------------------------------------------
> fatal flex scanner internal error--end of buffer missed
> [d-3-8-2:28765] 4 more processes have sent help message help-mpi-api.txt / mpi-abort
> [d-3-8-2:28765] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
> Segmentation Fault.
> Segmentation Fault.
> Segmentation Fault.
> Segmentation Fault.
> Segmentation Fault.
> Segmentation Fault.
> --------------------------------------------------------------------------
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code. Per user-direction, the job has been aborted.
> --------------------------------------------------------------------------
> --------------------------------------------------------------------------
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code. Per user-direction, the job has been aborted.
> --------------------------------------------------------------------------
> --------------------------------------------------------------------------
> mpirun noticed that process rank 0 with PID 0 on node c-16-8-3 exited on signal 9 (Killed).
> --------------------------------------------------------------------------
> --------------------------------------------------------------------------
> mpirun noticed that process rank 1 with PID 0 on node d-6-6-4 exited on signal 11 (Segmentation fault).
> --------------------------------------------------------------------------

I'm running these jobs on MIT Supercloud. Each of the nodes I'm using has 2 x 24 CPU cores, each with 4 GB of ram. I'd really appreciate any ideas on how to fix this. In particular, do you think this is an issue with JDFTX or the supercomputer that I'm running on? Thank you so much for your help!

Sincerely,
David Dai

**Comment by shankar1729** [comment]
From the numbers you posted, a typical wavefunction set per k-point takes 1536 bands *  632119.875 basis/band * 16 bytes/complex = 15 GB. You need ~ 5 copies of the wavefunction during minimization/SCF, so you need ~ 80 GB memory with margin for each k-point. So, it would be best to have one k-point per process, and one or two processes per node to have sufficient memory, since you have 192 GB/node.

Consequently, I would recommend running with -n X -c 24 for each perturbation, where X is the number of k-points. (You can optionally also set -N to ceil(X/2) if needed.

Best,
Shankar

**Comment by ddai2025** [comment]
Hi Professor Sundararaman,

Thank you so much for your help on this! These guidelines make sense to me.

Sincerely,
David Dai
