### ISSUE TITLE
Data processing of GC-DFT

### ISSUE THREAD

**Issue by moyulyy** [shankar1729/jdftx#269]
Hi Shankar，

I'm sorry to bother you, but I have trouble with the data processing of GC-DFT. I hope to get your guidance or correction.

1.. Understandings and confusions of 'grand free energy' and 'grand canonical energy'.
We know from the literature,
grand free energy is defined as: Φ = A-μN,
grand canonical energy is defined as: Ω = E + μNe
Among them,
Φ  is the Helmholtz free energy,
μ is the chemical formula, refers to the value set by the target-mu parameter,
N is the value of the last reported Nelectron when the structure relaxation converges,
Ne is the difference of nElectrons reported before and after structural relaxation convergence.

Is grand free energy strictly separated from grand canonical energy? Or are they the same?

Here are two examples. Do you think the data was handled correctly?

(1) Adsorption process:
	*+N2 ——> *N2

	G(* )  =E(* )-μN(*)
	G(N2) =E(N2)-μN(N2),μ = -4.66 at CANDLE，and N(N2) = nElectrons 
	G(*N2)=E(*N2)-μN(*N2)
	ΔG = G(*N2) - G(*) - G(N2)

(2) Faradaic processes
	*NH3 + OH-    ——> *NH2 + H2O + e-

	G(*NH3)=E(*NH3)-μN(*NH3)
	G(*NH2)=E(*NH2)-μN(*NH2)
	ΔG = G(*NH2) + G(H2O) + μe - G(*NH3) - G(OH-)

What's more, do I need to use ZPE and TS to correct G ? Can 'G = E + ZPE - TS - μN' be adopted?

2.. Processing of electronic density file (xx.n) when target-mu parameter is used.
Computing in vacuum can use the script (createVASP) to create the jdftx Electronic density file (xx.n) as the CHGCAR file of vasp.

Then, is it possible to convert the electron density file (xx.n) to the CHGCAR file for vasp to calculate the charge density difference, bader charge and PDOS when the fixed potential is applied?

In addition, it is known that jdftx can be used as a calculator to cooperate with ASE for NEB calculation. 
Then, can we carry out NEB calculation of constant-potential model using target-mu parameter?
And can jdftx compute the Electron Localization Function (ELF) information file similar to ELFCAR?

The above is my understandings and confusions of data processing by applying the output data calculated by target-mu command under the constant-potential model. I am looking forward to any opinions and suggestions from you, which I believe will benefit a lot.

I'm sorry to bother you with so many questions and thank you again for your generous efforts on this issues.

Best,
lyy

**Comment by shankar1729** [comment]
- I have not heard of grand canonical energy in the context you are using here: can you point me to a reference for that part? 
- It would be best to work with the grand free energy and compute differences at fixed potential as discussed in many threads here before. And yes, if vibrations matter, you should add ZPE  - TS from vibrations to G in your analysis.
- Yes, you can use the fixed-potential densities for the createVASP script and Bader analysis, just as for the neutral cases
- Yes, you can do fixed-potential NEB. See examples from last year's [BEAST workshop](http://beast-echem.org/workshops/2022)
- We don't have an ELF implementation at the moment, but would welcome feature contributions of that sort

**Comment by moyulyy** [comment]
1..References to 'grand canonical energy'

ref1 : J. Mater. Chem. A, 2020,8, 20402-20407     
title : Ruthenium Single-Atom Catalysis for Electrocatalytic Nitrogen Reduction Unveiled by Grand Canonical Density Functional Theory

ref2 : J Chem Phys. 2019 Jan 28;150(4):041706     
title : Grand-canonical approach to density functional theory of electrocatalytic systems:Thermodynamics of solid-liquid interfaces at constant ion and electrode potentials

2..ELF
In an accidental attempt, it was discovered that the xxx.xsf file output using the createXSF script, and opened by VESTA, could generate ELF images.
The question worth asking is, is this image accurate? In other words, is ELF really reliable data from this way?
Also, the boundary of the cell (rhomboid black line) does not coincide with the actual boundary (rhomboid ELF diagram boundary), is this wrong? 
The bottom image is an example of a C2N cell with a C2N.xsf file attached. Look forward to your suggestions on this.
[C2N.zip](https://github.com/shankar1729/jdftx/files/11070861/C2N.zip)
![C2N-ELF](https://user-images.githubusercontent.com/38726781/227757353-8a16c8b7-b652-4739-86c1-e2ae9cf86ef7.png)


BEAST workshop is an excellent work. I am very interested in JDFTx sessions in BEAST workshop page, but unfortunately some content in the page cannot be opened and read.May I ask if you can help me with this content? In addition, I did not find anything related to GCNEB.

Thanks.

**Comment by shankar1729** [comment]
Thanks, I'll take a look and get back on those. However, as mentioned above, my recommendation would be to stick to grand free energy for clarity, and avoid any such confusing definitions.

What did you include in the XSF file for VESTA to compute ELF? From what I understand, you need both electron density and KE density to compute ELF, and you can;t have both in an xsf file at once. It should be possible to add ELF output to JDFTx and then use VESTA to plot it, but I don't think this can be reliably done from an XSF output alone.

Finally, please clarify what information/data was missing in the BEAST workshop page? I thought we had packaged all the tutorial files and scripts needed into that Calculations-clean.tbz2 attachment. It would be helpful to know what was missing.

Best,
Shankar

**Comment by moyulyy** [comment]
The xsf file that drew the ELF image above contains only the electron density information, thank you for pointing out that this is an unreliable image.
Also, if you have any methods or suggestions for jdftx to generate ELF diagrams, please tell me

I have found the content about GC-NEB and tried to learn how to use it. I am sorry for my carelessness before.

Thanks.

**Comment by shankar1729** [comment]
Dump both the KE density and ElecDensity (tau and n files) from JDFTx. You can then use a couple of lines of python code to compute the ELF using the formula say on the wiki page, and dump it back in the same format. Then create an XSF file with that file as the scalar field to visualize the ELF.

Once you are happy with that, you can also look into adding an ELF dump option directly from JDFTx. It should be relatively easy to do.

Best,
Shankar
