### ISSUE TITLE
Classical DFT, solution with charged species, convergency problem

### ISSUE THREAD

**Issue by CaFa2** [shankar1729/jdftx#27]
Dear Shankar,

I tried to extend the tutorial on ions in solution to the case of Classical DFT:

lattice Cubic 15
coulomb-interaction Isolated
coulomb-truncation-embed 0 0 0
ion-species GBRV/$ID_pbe.uspp
elec-cutoff 20 100
coords-type cartesian

include ${CONFIG}.ionpos
initial-state ${CONFIG}_withoutNaF.$VAR
dump-name ${CONFIG}.$VAR
dump End State BoundCharge

elec-initial-charge ${CHARGE}

fluid ClassicalDFT
fluid-solvent H2O
fluid-cation Na+ 1.
fluid-anion F- 1.

It seems that there are problems to minimize the fluid (e.g. in the case of H3O+):
-------- Electron <-> Fluid self-consistency loop -----------

---------------------- Fluid Minimization # 1 -----------------------
FluidMinimize: Iter:   0  Etot: -0.112314314797106  |grad|_K:  6.726e-04  alpha:  1.000e+00
FluidMinimize:  Test step failed with Etot = nan, reducing alphaT to 1.000000e-01.
FluidMinimize: Iter:   1  Etot: -0.113684120916717  |grad|_K:  6.475e-04  alpha:  2.257e-03  linmin: -5.820e-02  cgtest:  9.940e-01  t[s]:     50.05
FluidMinimize: Encountered beta<0, resetting CG.
FluidMinimize:  Predicted alpha/alphaT>3.000000, increasing alphaT to 6.771822e-03.
FluidMinimize:  Predicted alpha/alphaT>3.000000, increasing alphaT to 2.031546e-02.
FluidMinimize:  Predicted alpha/alphaT>3.000000, increasing alphaT to 6.094639e-02.
FluidMinimize:  Step failed with Etot = nan, reducing alpha to 2.264617e-02.
FluidMinimize: Iter:   2  Etot: -0.125970640910727  |grad|_K:  8.415e-04  alpha:  2.265e-02  linmin: -8.800e-03  cgtest:  6.197e-01  t[s]:     87.07
FluidMinimize: Iter:   3  Etot: -0.126213844302949  |grad|_K:  8.517e-04  alpha:  1.755e-04  linmin: -1.330e-02  cgtest:  9.998e-01  t[s]:    101.87
FluidMinimize:  Wrong curvature in test step, increasing alphaT to 5.264390e-04.
...
FluidMinimize:  Step increased Etot by 7.808285e-04, reducing alpha to -4.743449e-05.
FluidMinimize:  Step increased Etot by 6.284198e-05, reducing alpha to -4.743449e-06.
FluidMinimize:  Step failed to reduce Etot after 3 attempts. Quitting step.
FluidMinimize:  Undoing step.
FluidMinimize:  Step failed along negative gradient direction.
FluidMinimize: Probably at roundoff error limit. (Stopping)
Fluid minimize took 6.16e+02 s.

Fluid minimization # 1 changed total free energy by -3.409663e-02 at t[s]:    636.73

-------------------- Electronic Minimization # 1 ---------------------
ElecMinimize: Iter:   0  Etot: -17.552467983906091  |grad|_K:  3.014e-04  alpha:  1.000e+00
ElecMinimize: Iter:   1  Etot: -17.556383547399736  |grad|_K:  1.256e-04  alpha:  7.479e-01  linmin:  2.824e-03  t[s]:    640.36
ElecMinimize: Iter:   2  Etot: -17.556922039525979  |grad|_K:  6.568e-05  alpha:  5.949e-01  linmin: -4.891e-04  t[s]:    642.36
ElecMinimize: Iter:   3  Etot: -17.557065290112568  |grad|_K:  2.747e-05  alpha:  5.777e-01  linmin:  7.724e-04  t[s]:    644.38
ElecMinimize: Iter:   4  Etot: -17.557100159165245  |grad|_K:  1.419e-05  alpha:  8.044e-01  linmin: -8.364e-04  t[s]:    646.40
ElecMinimize: Iter:   5  Etot: -17.557109778103854  |grad|_K:  7.744e-06  alpha:  8.302e-01  linmin: -3.270e-02  t[s]:    648.43
ElecMinimize: Iter:   6  Etot: -17.557112733643866  |grad|_K:  3.605e-06  alpha:  8.370e-01  linmin: -5.939e-05  t[s]:    650.44
ElecMinimize: Converged (|Delta Etot|<1.000000e-05 for 2 iters).
Setting wave functions to eigenvectors of Hamiltonian
...
Electronic minimization # 1 changed total free energy by -4.644750e-03 at t[s]:    650.44

---------------------- Fluid Minimization # 2 -----------------------
FluidMinimize: Iter:   0  Etot: -0.143990422635435  |grad|_K:  1.203e-03  alpha:  1.000e+00
FluidMinimize:  Test step failed with Etot = -nan, reducing alphaT to 1.000000e-01.
FluidMinimize:  Test step failed with Etot = nan, reducing alphaT to 1.000000e-02.
FluidMinimize:  Test step failed with Etot = nan, reducing alphaT to 1.000000e-03.
FluidMinimize:  Step failed with Etot = -nan, reducing alpha to 1.000000e-01.
FluidMinimize:  Step failed with Etot = nan, reducing alpha to 1.000000e-02.
FluidMinimize:  Step failed with Etot = nan, reducing alpha to 1.000000e-03.
FluidMinimize:  Step failed to reduce Etot after 3 attempts. Quitting step.
FluidMinimize:  Undoing step.
FluidMinimize:  Step failed along negative gradient direction.
FluidMinimize: Probably at roundoff error limit. (Stopping)
Fluid minimize took 6.68e+01 s.

Fluid minimization # 2 changed total free energy by nan at t[s]:    717.95
...
---------------------- Fluid Minimization # 10 -----------------------
FluidMinimize: Iter:   0  Etot: +nan  |grad|_K:  3.133e+11  alpha:  1.000e+00
FluidMinimize: E=nan. Stopping ...
Fluid minimize took 1.48e+01 s.

Fluid minimization # 10 changed total free energy by nan at t[s]:    850.08

-------------------- Electronic Minimization # 10 ---------------------
ElecMinimize: Iter:   0  Etot: +nan  |grad|_K:  5.791e-01  alpha:  1.000e+00
ElecMinimize: E=nan. Stopping ...
Setting wave functions to eigenvectors of Hamiltonian

Electronic minimization # 10 changed total free energy by nan at t[s]:    851.15

Fluid<-->Electron self-consistency loop not yet converged to 1.000000e-05 hartrees after 10 minimization pairs at t[s]:    851.15.

I tried to use different starting points, e.g. a Classical DFT calculation with H20 solvent (but without Na and F ions), but the result is the same.

Do you have an idea what the problem could be?

Best regards

**Comment by shankar1729** [comment]
The classical DFT for electrolytes is still a work in progress with both physical instabilities and convergence issues in the presence of strong potentials, as is the case next to bare ions. In particular, only certain ions in the electrolyte have been parametrized fully for classical DFT functionals: any pointers regarding this @klweaver630?

Best,
Shankar
