### ISSUE TITLE
Error initializing an OpenFabrics device

### ISSUE THREAD

**Issue by 24sunho** [shankar1729/jdftx#270]
Inputing a jdftx command yielded the following error regarding "initializing an OpenFabrics device" and I was hoping to find a solution to this issue? Thank you.

> jdftx -i in -o output1.out
--------------------------------------------------------------------------
By default, for Open MPI 4.0 and later, infiniband ports on a device
are not used by default.  The intent is to use UCX for these devices.
You can override this policy by setting the btl_openib_allow_ib MCA parameter
to true.

  Local host:              coe
  Local adapter:           hfi1_0
  Local port:              1

--------------------------------------------------------------------------
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   coe
  Local device: hfi1_0
--------------------------------------------------------------------------

**Comment by shankar1729** [comment]
This is an OpenMPI warning that usually has no impact. See OpenMPI's FAW on how to set MCA parameters to prevent warnings such as this.

Best,
Shankar
