### ISSUE TITLE
Issue in installation 

### ISSUE THREAD

**Issue by XiongyiLIANG** [shankar1729/jdftx#272]
Dear Developers,

When I install JDFTx 1.7.0 in my servers, some error happens as follows:

-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.39.2")
-- Looking for gsl_integration_glfixed_point
-- Looking for gsl_integration_glfixed_point - found
-- Found GSL: /gauss21/home/cityu/xiongyiliang/software/gsl-2.7.1/lib/libgsl.so
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found MKL: /gauss21/home/cityu/xiongyiliang/intel/oneapi/mkl/2023.0.0/lib/intel64/libmkl_intel_lp64.so;/gauss21/home/cityu/xiongyiliang/intel/oneapi/mkl/2023.0.0/lib/intel64/libmkl_gnu_thread.so;/gauss21/home/cityu/xiongyiliang/intel/oneapi/mkl/2023.0.0/lib/intel64/libmkl_core.so;gomp
-- Found FFTW3:  /gauss21/home/cityu/xiongyiliang/software/fftw/lib/libfftw3f.a /gauss21/home/cityu/xiongyiliang/software/fftw/lib/libfftw3.so
-- Found MPI_C: /gauss21/home/cityu/xiongyiliang/intel/oneapi/mpi/2021.8.0/lib/release/libmpi.so (found version "3.1")
-- Found MPI_CXX: /gauss21/home/cityu/xiongyiliang/intel/oneapi/mpi/2021.8.0/lib/libmpicxx.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- Found LibXC: /data/opt/local/libxc/4.3.4/gcc/10.3.1/lib/libxc.so
-- Performing Test HAS_NO_UNUSED_RESULT
-- Performing Test HAS_NO_UNUSED_RESULT - Success
-- Performing Test HAS_TEMPLATE_DEPTH
-- Performing Test HAS_TEMPLATE_DEPTH - Success
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: /gauss21/home/cityu/xiongyiliang/jdftx/build
[  0%] Building CXX object CMakeFiles/jdftxlib.dir/commands/command.cpp.o
[  1%] Building CXX object CMakeFiles/jdftxlib.dir/commands/coulomb_interaction.cpp.o
[  2%] Building CXX object CMakeFiles/jdftxlib.dir/commands/debug.cpp.o
[  2%] Building CXX object CMakeFiles/jdftxlib.dir/commands/density_of_states.cpp.o
[  3%] Building CXX object CMakeFiles/jdftxlib.dir/commands/dump.cpp.o
[  3%] Building CXX object CMakeFiles/jdftxlib.dir/commands/elec_ex_corr.cpp.o
[  4%] Building CXX object CMakeFiles/jdftxlib.dir/commands/elec_fillings.cpp.o
[  4%] Building CXX object CMakeFiles/jdftxlib.dir/commands/elec_misc.cpp.o
[  5%] Building CXX object CMakeFiles/jdftxlib.dir/commands/fluid.cpp.o
[  7%] Building CXX object CMakeFiles/jdftxlib.dir/commands/initial_state.cpp.o
[  7%] Building CXX object CMakeFiles/jdftxlib.dir/commands/ion.cpp.o
[  8%] Building CXX object CMakeFiles/jdftxlib.dir/commands/ion_species.cpp.o
/gauss21/home/cityu/xiongyiliang/jdftx/jdftx-master/jdftx/commands/ion_species.cpp: In function ‘const std::vector<std::__cxx11::basic_string<char, ichar_traits> >& getPseudopotentialPrefixes()’:
/gauss21/home/cityu/xiongyiliang/jdftx/jdftx-master/jdftx/commands/ion_species.cpp:128:36: error: ‘JDFTX_BUILD_DIR’ was not declared in this scope
  128 |                 prefixes.push_back(JDFTX_BUILD_DIR "/pseudopotentials/"); //search paths relative to psp library in build next
      |                                    ^~~~~~~~~~~~~~~
/gauss21/home/cityu/xiongyiliang/jdftx/jdftx-master/jdftx/commands/ion_species.cpp:129:27: error: ‘JDFTX_INSTALL_DIR’ was not declared in this scope
  129 |                 if(strlen(JDFTX_INSTALL_DIR)) //search paths relative to psp library in install target, if any, last
      |                           ^~~~~~~~~~~~~~~~~
/gauss21/home/cityu/xiongyiliang/jdftx/jdftx-master/jdftx/commands/ion_species.cpp:130:61: error: expected ‘)’ before string constant
  130 |                         prefixes.push_back(JDFTX_INSTALL_DIR "/share/jdftx/pseudopotentials/");
      |                                           ~                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                             )
make[2]: *** [CMakeFiles/jdftxlib.dir/build.make:230: CMakeFiles/jdftxlib.dir/commands/ion_species.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:156: CMakeFiles/jdftxlib.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

Many thanks.
Best regards,
LIANG Xiongyi
City University of Hong Kong

**Comment by shankar1729** [comment]
This issue happens if one of your dependencies incorrectly includes a `config.h` in its installed include path, which is overriding JDFTx's own `config.h`. This can happen if you point jdftx to the build location of a library, rather than to an installed location.

In your case, it looks like you built GSL and FFTW3 in your own directory, so it could be from one of those. For each, make sure you run `./configure --prefix=/some/install/path ...`, `make` and `make install`, and then point jdftx to `/some/install/path` rather than the source/build directory. Basically, make sure you did the `make install` above.

Best,
Shankar

**Comment by shankar1729** [comment]
Yes, those are fine. I think those gcc 12 warnings are already fixed on the git head, so if you started from the 1.7.0 tarball above, try with the latest commit on git, and most likely those warnings should also go away.

Best,
Shankar

**Comment by YanjunLiu2** [comment]
Dear Developer,

I have the following errors in my installation:

[ 87%] Linking CXX shared library libjdftx.dylib
Undefined symbols for architecture x86_64:
  "_ompi_mpi_2int", referenced from:
      ExactExchangeEval::ExactExchangeEval(Everything const&) in ExactExchange.cpp.o
  "_ompi_mpi_byte", referenced from:
      MPIUtil::fread(void*, unsigned long, unsigned long, ompi_file_t*) const in MPIUtil.cpp.o
      MPIUtil::fwrite(void const*, unsigned long, unsigned long, ompi_file_t*) const in MPIUtil.cpp.o
  "_ompi_mpi_c_double_complex", referenced from:
      Dump::operator()(DumpFrequency, int) in Dump.cpp.o
      dumpFCI(Everything const&, char const*) in DumpExcitationsMoments.cpp.o
      Dump::dumpOcean() in DumpOcean.cpp.o
      Dump::dumpQMC() in DumpQMC.cpp.o
      ElectronScattering::dump(Everything const&) in ElectronScattering.cpp.o
      ElectronScattering::dumpSlabResponse(Everything&, diagMatrix const&) in ElectronScattering.cpp.o
      ExCorr::operator()(std::__1::vector<std::__1::shared_ptr<ScalarFieldData>, std::__1::allocator<std::__1::shared_ptr<ScalarFieldData>>> const&, std::__1::vector<std::__1::shared_ptr<ScalarFieldData>, std::__1::allocator<std::__1::shared_ptr<ScalarFieldData>>>*, IncludeTXC, std::__1::vector<std::__1::shared_ptr<ScalarFieldData>, std::__1::allocator<std::__1::shared_ptr<ScalarFieldData>>> const*, std::__1::vector<std::__1::shared_ptr<ScalarFieldData>, std::__1::allocator<std::__1::shared_ptr<ScalarFieldData>>>*, matrix3<double>*) const in ExCorr.cpp.o
      ...
  "_ompi_mpi_char", referenced from:
      MPIUtil::checkErrors(ostringstream const&) const in MPIUtil.cpp.o
      MPIUtil::send(std::__1::basic_string<char, ichar_traits, std::__1::allocator<char>> const&, int, int, ompi_request_t**) const in MPIUtil.cpp.o
      MPIUtil::recv(std::__1::basic_string<char, ichar_traits, std::__1::allocator<char>>&, int, int, ompi_request_t**) const in MPIUtil.cpp.o
      MPIUtil::bcast(std::__1::basic_string<char, ichar_traits, std::__1::allocator<char>>&, int, ompi_request_t**) const in MPIUtil.cpp.o
  "_ompi_mpi_comm_world", referenced from:
      MPIUtil::MPIUtil(int, char**, MPIUtil::ProcDivision) in MPIUtil.cpp.o
      MPIUtil::~MPIUtil() in MPIUtil.cpp.o
      MPIUtil::~MPIUtil() in MPIUtil.cpp.o
  "_ompi_mpi_double", referenced from:
      RadialFunctionR::transform(int, double, int, RadialFunctionG&) const in RadialFunction.cpp.o
      sphericalize(std::__1::shared_ptr<ScalarFieldData> const*, int, double, vector3<double>*) in ScalarFieldIO.cpp.o
      initSystem(int, char**, InitParams const*) in Util.cpp.o
      DOS::dump() in DOS.cpp.o
      Dump::operator()(DumpFrequency, int) in Dump.cpp.o
      dumpExcitations(Everything const&, char const*) in DumpExcitationsMoments.cpp.o
      dumpFCI(Everything const&, char const*) in DumpExcitationsMoments.cpp.o
      ...
  "_ompi_mpi_double_int", referenced from:
      Dump::operator()(DumpFrequency, int) in Dump.cpp.o
  "_ompi_mpi_info_null", referenced from:
      MPIUtil::fopenRead(ompi_file_t*&, char const*, unsigned long, char const*) const in MPIUtil.cpp.o
      MPIUtil::fopenWrite(ompi_file_t*&, char const*) const in MPIUtil.cpp.o
      MPIUtil::fopenAppend(ompi_file_t*&, char const*) const in MPIUtil.cpp.o
  "_ompi_mpi_int", referenced from:
      readInputFile(std::__1::basic_string<char, ichar_traits, std::__1::allocator<char>>) in parser.cpp.o
      MPIUtil::checkErrors(ostringstream const&) const in MPIUtil.cpp.o
      MPIUtil::send(bool const*, unsigned long, int, int, ompi_request_t**) const in MPIUtil.cpp.o
      MPIUtil::recv(bool*, unsigned long, int, int, ompi_request_t**) const in MPIUtil.cpp.o
      MPIUtil::bcast(bool*, unsigned long, int, ompi_request_t**) const in MPIUtil.cpp.o
      MPIUtil::allReduce(bool*, unsigned long, MPIUtil::ReduceOp, bool, ompi_request_t**) const in MPIUtil.cpp.o
      MPIUtil::reduce(bool*, unsigned long, MPIUtil::ReduceOp, int, ompi_request_t**) const in MPIUtil.cpp.o
      ...
  "_ompi_mpi_long", referenced from:
      ElecInfo::write(std::__1::vector<ColumnBundle, std::__1::allocator<ColumnBundle>> const&, char const*) const in ColumnBundle.cpp.o
      ElecInfo::read(std::__1::vector<ColumnBundle, std::__1::allocator<ColumnBundle>>&, char const*, ElecInfo::ColumnBundleReadConversion const*) const in ColumnBundle.cpp.o
  "_ompi_mpi_op_band", referenced from:
      l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
  "_ompi_mpi_op_bor", referenced from:
      l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
  "_ompi_mpi_op_bxor", referenced from:
      l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
  "_ompi_mpi_op_land", referenced from:
      l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
      Symmetries::reduceKmesh(std::__1::vector<QuantumNumber, std::__1::allocator<QuantumNumber>> const&) const in Symmetries.cpp.o
  "_ompi_mpi_op_lor", referenced from:
      l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
  "_ompi_mpi_op_lxor", referenced from:
      l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
  "_ompi_mpi_op_max", referenced from:
      l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
      ElectronScattering::dump(Everything const&) in ElectronScattering.cpp.o
      ExCorr_OrbitalDep_GLLBsc::getExtremalEnergy(bool) const in ExCorr_OrbitalDep_GLLBsc.cpp.o
      ExCorr_OrbitalDep_GLLBsc::dump() const in ExCorr_OrbitalDep_GLLBsc.cpp.o
      IdealGasPomega::initState(std::__1::shared_ptr<ScalarFieldData> const*, std::__1::shared_ptr<ScalarFieldData>*, double, double, double) const in IdealGasPomega.cpp.o
  "_ompi_mpi_op_maxloc", referenced from:
      Dump::operator()(DumpFrequency, int) in Dump.cpp.o
  "_ompi_mpi_op_min", referenced from:
      l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
      ElectronScattering::dump(Everything const&) in ElectronScattering.cpp.o
      ExCorr_OrbitalDep_GLLBsc::getExtremalEnergy(bool) const in ExCorr_OrbitalDep_GLLBsc.cpp.o
      ExCorr_OrbitalDep_GLLBsc::dump() const in ExCorr_OrbitalDep_GLLBsc.cpp.o
      Symmetries::reduceKmesh(std::__1::vector<QuantumNumber, std::__1::allocator<QuantumNumber>> const&) const in Symmetries.cpp.o
      IdealGasPomega::initState(std::__1::shared_ptr<ScalarFieldData> const*, std::__1::shared_ptr<ScalarFieldData>*, double, double, double) const in IdealGasPomega.cpp.o
  "_ompi_mpi_op_minloc", referenced from:
      Dump::operator()(DumpFrequency, int) in Dump.cpp.o
      ExactExchangeEval::ExactExchangeEval(Everything const&) in ExactExchange.cpp.o
  "_ompi_mpi_op_prod", referenced from:
      l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
  "_ompi_mpi_op_sum", referenced from:
      MPIUtil::checkErrors(ostringstream const&) const in MPIUtil.cpp.o
      l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
      RadialFunctionR::transform(int, double, int, RadialFunctionG&) const in RadialFunction.cpp.o
      sphericalize(std::__1::shared_ptr<ScalarFieldData> const*, int, double, vector3<double>*) in ScalarFieldIO.cpp.o
      initSystem(int, char**, InitParams const*) in Util.cpp.o
      Dump::operator()(DumpFrequency, int) in Dump.cpp.o
      ImagPartMinimizer::ImagPartMinimizer(Everything const&) in DumpQMC.cpp.o
      ...
  "_ompi_mpi_unsigned_long", referenced from:
      MPIUtil::send(std::__1::basic_string<char, ichar_traits, std::__1::allocator<char>> const&, int, int, ompi_request_t**) const in MPIUtil.cpp.o
      MPIUtil::recv(std::__1::basic_string<char, ichar_traits, std::__1::allocator<char>>&, int, int, ompi_request_t**) const in MPIUtil.cpp.o
      MPIUtil::bcast(std::__1::basic_string<char, ichar_traits, std::__1::allocator<char>>&, int, ompi_request_t**) const in MPIUtil.cpp.o
      dumpExcitations(Everything const&, char const*) in DumpExcitationsMoments.cpp.o
      ElectronScattering::dump(Everything const&) in ElectronScattering.cpp.o
  "_ompi_mpi_unsigned_long_long", referenced from:
      Symmetries::reduceKmesh(std::__1::vector<QuantumNumber, std::__1::allocator<QuantumNumber>> const&) const in Symmetries.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libjdftx.dylib] Error 1
make[1]: *** [CMakeFiles/jdftxlib.dir/all] Error 2
make: *** [all] Error 2

Thank you very much!

Best regards,

Yanjun Liu

**Comment by YanjunLiu2** [comment]
> Yes, those are fine. I think those gcc 12 warnings are already fixed on the git head, so if you started from the 1.7.0 tarball above, try with the latest commit on git, and most likely those warnings should also go away.
> 
> Best, Shankar

Dear Developer,

I have the following errors in my installation:

[ 87%] Linking CXX shared library libjdftx.dylib
Undefined symbols for architecture x86_64:
"_ompi_mpi_2int", referenced from:
ExactExchangeEval::ExactExchangeEval(Everything const&) in ExactExchange.cpp.o
"_ompi_mpi_byte", referenced from:
MPIUtil::fread(void*, unsigned long, unsigned long, ompi_file_t*) const in MPIUtil.cpp.o
MPIUtil::fwrite(void const*, unsigned long, unsigned long, ompi_file_t*) const in MPIUtil.cpp.o
"_ompi_mpi_c_double_complex", referenced from:
Dump::operator()(DumpFrequency, int) in Dump.cpp.o
dumpFCI(Everything const&, char const*) in DumpExcitationsMoments.cpp.o
Dump::dumpOcean() in DumpOcean.cpp.o
Dump::dumpQMC() in DumpQMC.cpp.o
ElectronScattering::dump(Everything const&) in ElectronScattering.cpp.o
ElectronScattering::dumpSlabResponse(Everything&, diagMatrix const&) in ElectronScattering.cpp.o
ExCorr::operator()(std::__1::vector<std::__1::shared_ptr, std::__1::allocator<std::__1::shared_ptr>> const&, std::__1::vector<std::__1::shared_ptr, std::__1::allocator<std::__1::shared_ptr>>, IncludeTXC, std::__1::vector<std::__1::shared_ptr, std::__1::allocator<std::__1::shared_ptr>> const, std::__1::vector<std::__1::shared_ptr, std::__1::allocator<std::__1::shared_ptr>>, matrix3) const in ExCorr.cpp.o
...
"_ompi_mpi_char", referenced from:
MPIUtil::checkErrors(ostringstream const&) const in MPIUtil.cpp.o
MPIUtil::send(std::__1::basic_string<char, ichar_traits, std::__1::allocator> const&, int, int, ompi_request_t**) const in MPIUtil.cpp.o
MPIUtil::recv(std::__1::basic_string<char, ichar_traits, std::__1::allocator>&, int, int, ompi_request_t**) const in MPIUtil.cpp.o
MPIUtil::bcast(std::__1::basic_string<char, ichar_traits, std::__1::allocator>&, int, ompi_request_t**) const in MPIUtil.cpp.o
"_ompi_mpi_comm_world", referenced from:
MPIUtil::MPIUtil(int, char**, MPIUtil::ProcDivision) in MPIUtil.cpp.o
MPIUtil::~MPIUtil() in MPIUtil.cpp.o
MPIUtil::~MPIUtil() in MPIUtil.cpp.o
"_ompi_mpi_double", referenced from:
RadialFunctionR::transform(int, double, int, RadialFunctionG&) const in RadialFunction.cpp.o
sphericalize(std::__1::shared_ptr const*, int, double, vector3) in ScalarFieldIO.cpp.o
initSystem(int, char**, InitParams const) in Util.cpp.o
DOS::dump() in DOS.cpp.o
Dump::operator()(DumpFrequency, int) in Dump.cpp.o
dumpExcitations(Everything const&, char const*) in DumpExcitationsMoments.cpp.o
dumpFCI(Everything const&, char const*) in DumpExcitationsMoments.cpp.o
...
"_ompi_mpi_double_int", referenced from:
Dump::operator()(DumpFrequency, int) in Dump.cpp.o
"_ompi_mpi_info_null", referenced from:
MPIUtil::fopenRead(ompi_file_t*&, char const*, unsigned long, char const*) const in MPIUtil.cpp.o
MPIUtil::fopenWrite(ompi_file_t*&, char const*) const in MPIUtil.cpp.o
MPIUtil::fopenAppend(ompi_file_t*&, char const*) const in MPIUtil.cpp.o
"_ompi_mpi_int", referenced from:
readInputFile(std::__1::basic_string<char, ichar_traits, std::__1::allocator>) in parser.cpp.o
MPIUtil::checkErrors(ostringstream const&) const in MPIUtil.cpp.o
MPIUtil::send(bool const*, unsigned long, int, int, ompi_request_t**) const in MPIUtil.cpp.o
MPIUtil::recv(bool*, unsigned long, int, int, ompi_request_t**) const in MPIUtil.cpp.o
MPIUtil::bcast(bool*, unsigned long, int, ompi_request_t**) const in MPIUtil.cpp.o
MPIUtil::allReduce(bool*, unsigned long, MPIUtil::ReduceOp, bool, ompi_request_t**) const in MPIUtil.cpp.o
MPIUtil::reduce(bool*, unsigned long, MPIUtil::ReduceOp, int, ompi_request_t**) const in MPIUtil.cpp.o
...
"_ompi_mpi_long", referenced from:
ElecInfo::write(std::__1::vector<ColumnBundle, std::__1::allocator> const&, char const*) const in ColumnBundle.cpp.o
ElecInfo::read(std::__1::vector<ColumnBundle, std::__1::allocator>&, char const*, ElecInfo::ColumnBundleReadConversion const*) const in ColumnBundle.cpp.o
"_ompi_mpi_op_band", referenced from:
l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
"_ompi_mpi_op_bor", referenced from:
l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
"_ompi_mpi_op_bxor", referenced from:
l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
"_ompi_mpi_op_land", referenced from:
l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
Symmetries::reduceKmesh(std::__1::vector<QuantumNumber, std::__1::allocator> const&) const in Symmetries.cpp.o
"_ompi_mpi_op_lor", referenced from:
l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
"_ompi_mpi_op_lxor", referenced from:
l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
"_ompi_mpi_op_max", referenced from:
l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
ElectronScattering::dump(Everything const&) in ElectronScattering.cpp.o
ExCorr_OrbitalDep_GLLBsc::getExtremalEnergy(bool) const in ExCorr_OrbitalDep_GLLBsc.cpp.o
ExCorr_OrbitalDep_GLLBsc::dump() const in ExCorr_OrbitalDep_GLLBsc.cpp.o
IdealGasPomega::initState(std::__1::shared_ptr const*, std::__1::shared_ptr, double, double, double) const in IdealGasPomega.cpp.o
"_ompi_mpi_op_maxloc", referenced from:
Dump::operator()(DumpFrequency, int) in Dump.cpp.o
"_ompi_mpi_op_min", referenced from:
l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
ElectronScattering::dump(Everything const&) in ElectronScattering.cpp.o
ExCorr_OrbitalDep_GLLBsc::getExtremalEnergy(bool) const in ExCorr_OrbitalDep_GLLBsc.cpp.o
ExCorr_OrbitalDep_GLLBsc::dump() const in ExCorr_OrbitalDep_GLLBsc.cpp.o
Symmetries::reduceKmesh(std::__1::vector<QuantumNumber, std::__1::allocator> const&) const in Symmetries.cpp.o
IdealGasPomega::initState(std::__1::shared_ptr const, std::__1::shared_ptr, double, double, double) const in IdealGasPomega.cpp.o
"_ompi_mpi_op_minloc", referenced from:
Dump::operator()(DumpFrequency, int) in Dump.cpp.o
ExactExchangeEval::ExactExchangeEval(Everything const&) in ExactExchange.cpp.o
"_ompi_mpi_op_prod", referenced from:
l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
"_ompi_mpi_op_sum", referenced from:
MPIUtil::checkErrors(ostringstream const&) const in MPIUtil.cpp.o
l_switch.table._ZNK7MPIUtil6reduceEPbmNS_8ReduceOpEiPP14ompi_request_t in MPIUtil.cpp.o
RadialFunctionR::transform(int, double, int, RadialFunctionG&) const in RadialFunction.cpp.o
sphericalize(std::__1::shared_ptr const, int, double, vector3) in ScalarFieldIO.cpp.o
initSystem(int, char**, InitParams const) in Util.cpp.o
Dump::operator()(DumpFrequency, int) in Dump.cpp.o
ImagPartMinimizer::ImagPartMinimizer(Everything const&) in DumpQMC.cpp.o
...
"_ompi_mpi_unsigned_long", referenced from:
MPIUtil::send(std::__1::basic_string<char, ichar_traits, std::__1::allocator> const&, int, int, ompi_request_t**) const in MPIUtil.cpp.o
MPIUtil::recv(std::__1::basic_string<char, ichar_traits, std::__1::allocator>&, int, int, ompi_request_t**) const in MPIUtil.cpp.o
MPIUtil::bcast(std::__1::basic_string<char, ichar_traits, std::__1::allocator>&, int, ompi_request_t**) const in MPIUtil.cpp.o
dumpExcitations(Everything const&, char const*) in DumpExcitationsMoments.cpp.o
ElectronScattering::dump(Everything const&) in ElectronScattering.cpp.o
"_ompi_mpi_unsigned_long_long", referenced from:
Symmetries::reduceKmesh(std::__1::vector<QuantumNumber, std::__1::allocator> const&) const in Symmetries.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libjdftx.dylib] Error 1
make[1]: *** [CMakeFiles/jdftxlib.dir/all] Error 2
make: *** [all] Error 2

Thank you very much!

Best regards,

Yanjun Liu

**Comment by shankar1729** [comment]
Hi Yanjun,

This seems to be an issue in linking to your MPI library, as all the errors are related to symbols not found in OpenMPI libraries. I would recommend taking an example MPI C++ program (eg. a [hello world example](https://mpitutorial.com/tutorials/mpi-hello-world/)) and check that you are able to build and run it with your MPI installation.

At the moment, this error does not seem to be related to the jdftx build system.

Best,
Shankar

**Comment by YanjunLiu2** [comment]
> 

Dear Shankar,

I tried to fix the problem with OpenMPI and after that the installation can be completed. However, when I tried the first example of water.in I got:

Aborted.
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor

Does this still mean that my installation of the MPI library is not correct?

I'm not quite familiar with programming so these all look mysterious to me. Thank you for your patience!

Best wishes,
Yanjun

**Comment by shankar1729** [comment]
Yes, that means that the MPI installation is still not working correctly. If you have modules set up for the MPI, eg. on an HPC machine, make sure the same modules are loaded during compilation and when you run it.

Best,
Shankar

**Comment by YanjunLiu2** [comment]
Dear Shankar,

Thank you for your previous help! I successfully installed jdftx on my own laptop and now I'm trying to install it on a cluster. Since I have no sudo access, I work with a conda virtual environment and I had the following error while cmake:

-- Looking for gsl_integration_glfixed_point
-- Looking for gsl_integration_glfixed_point - not found
CMake Error at CMake-Modules/FindGSL.cmake:36 (message):
  Unsupported GNU Scientific Library version; need version >= 1.15
Call Stack (most recent call first):
  CMakeLists.txt:59 (find_package)

While I had installed gsl through conda and the version is:

(DFT) yl3447@g2-login-01:~/jdftx/build$ conda list|grep gsl
gsl                       2.7.1                h6e86dc7_1    anaconda

Do you know what's the problem here? Thank you!

Best wishes,

Yanjun

**Comment by shankar1729** [comment]
Most likely cmake found your system GSL before the conda one. Set GSL_PATH to your conda prefix, if you didn't already do that.

Best,
Shankar

**Comment by YanjunLiu2** [comment]
> Most likely cmake found your system GSL before the conda one. Set GSL_PATH to your conda prefix, if you didn't already do that.
> 
> Best, Shankar

Hi Shankar,

I got the sudo access and reinstalled all the dependencies through homebrew again. But now I got the following error:

CMake Error at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.27.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)
Call Stack (most recent call first):
  /home/linuxbrew/.linuxbrew/Cellar/cmake/3.27.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /home/linuxbrew/.linuxbrew/Cellar/cmake/3.27.0/share/cmake/Modules/FindBLAS.cmake:1383 (find_package_handle_standard_args)
  /home/linuxbrew/.linuxbrew/Cellar/cmake/3.27.0/share/cmake/Modules/FindLAPACK.cmake:247 (find_package)
  /home/linuxbrew/.linuxbrew/Cellar/cmake/3.27.0/share/cmake/Modules/FindLAPACK.cmake:283 (_lapack_find_dependency)
  CMake-Modules/FindLAPACK_ATLAS.cmake:20 (find_package)
  CMakeLists.txt:87 (find_package)

Does this mean that cmake can't find atlas? Or it's something else? Thank you!

Best,
Yanjun

**Comment by shankar1729** [comment]
Yes, that seems to be the case. You may need to change the directories in which cmake searches for libraries, if they are in a non-standard location. Please see the CMake documentation for that.

Also, why are you using homebrew for this? If you have sudo access, why not install packages to the standard location using your main package manager?

**Comment by shankar1729** [comment]
Great, glad to hear it.
