### ISSUE TITLE
Cmake build with MKL in ./usr/include due to normal Ubuntu 20 install 

### ISSUE THREAD

**Issue by mmarchywka** [shankar1729/jdftx#277]
I'm trying to build 1.7 on ununtu 20 with a fresh install including mkl. I couldn't get
the MKL_PATH to work apparently due to a presumed "include" in the path. Modifying
tthe search criteria in FindMKL_cmake allowed a jdftx object file to be created.

`grep -A 2 include   ../jdftx/CMake-Modules/FindMKL.cmake 
	message(WARNING "Unknown compiler: edit FindMKL.cmake to include appropriate OpenMP link rules.")
endif()

--
	find_path(FFTW3_INCLUDE_DIR NAMES fftw3_mkl.h PATHS ${MKL_PATH}/include/fftw)
endif()
#find_path(MKL_INCLUDE_DIR NAMES mkl_dfti.h PATHS ${MKL_PATH}/include)
find_path(MKL_INCLUDE_DIR NAMES mkl_dfti.h PATHS ${MKL_PATH})

--
		message(WARNING "Unknown compiler: edit FindMKL.cmake to include appropriate BLACS link rules.")
	endif()
`

The command below worked  and the older version of libxc  ( 5.2.1) compiled
but would not link due to lack of PIC ( I thought this was always on now lol ), 

`# /usr/bin/ld: /home/ubuntu/dev/libxc/install/lib/libxc.a(functionals.o): relocation R_X86_64_PC32 against symbol `xc_functional_keys' can not be used when making a shared object; recompile with -fPIC

#cmake ../jdftx/ -D EnableLibXC=yes -D LIBXC_PATH=/home/ubuntu/dev/libxc/install/ -D ForceFFTW=yes -D EnableMKL=yes -D MKL_PATH=/usr/include/mkl
cmake ../jdftx/ -D ForceFFTW=yes -D EnableMKL=yes -D MKL_PATH=/usr/include/mkl
`

**Comment by shankar1729** [comment]
On the first point, could you indicate what the contents of MKL_PATH look like? Are the headers and libraries within the same directory? That seems to be a non-standard layout for MKL.

On the second one, the issue is in LibXC compilation. It seems to only have the static library `libxc.a`. Make sure you compiled LibXC with `--enable-shared` configure option (or `-D BUILD_SHARED_LIBS=yes` if using cmake) to get `libxc.so`. 

Best,
Shankar

**Comment by shankar1729** [comment]
I see, didn't realize that MKL was packaged that way in the distros. I'd only seen the intel layout so far.

To support both layouts, we could add a default path search, editing FindMKL.cmake starting at line 27 to look like this:

```cmake
if(NOT ForceFFTW)
	find_path(FFTW3_INCLUDE_DIR NAMES fftw3_mkl.h PATHS ${MKL_PATH}/include/fftw)
        find_path(FFTW3_INCLUDE_DIR NAMES fftw3_mkl.h)
endif()
find_path(MKL_INCLUDE_DIR NAMES mkl_dfti.h PATHS ${MKL_PATH}/include)
find_path(MKL_INCLUDE_DIR NAMES mkl_dfti.h)
```

This will first check for the intel layout, and then check if the files are already in the standard paths. This should work without setting MKL_PATH at all for the installation you specified.

Could you please test if this works for your installation, and if so, submit a pull request with this change?

Thanks!
Best,
Shankar

**Comment by mmarchywka** [comment]
Maybe I put it in wrong but it did not work. The MKL_PATH is set   to point to the
opt install if it is blank. IT may be better to try to discover the header in include//mkl
to set the blank MKL_PATH.  The attached zip contains a version that worked but
is searched a hard coded /usr/include/mkl. Apparently your source code does
not prefix the mkl includes with "mkl/"  The attached worked with 
this cmake command, 

`cmake ../jdftx/ -D ForceFFTW=yes -D EnableMKL=yes 
`

`diff   ../jdftx/CMake-Modules/FindMKL.*
31,34c31,32
< #find_path(MKL_INCLUDE_DIR NAMES mkl_dfti.h PATHS ${MKL_PATH})
< find_path(MKL_INCLUDE_DIR mkl_dfti.h PATHS mkl )
< find_path(MKL_INCLUDE_DIR NAMES mkl_dfti.h PATHS /usr/include/mkl)
< find_path(MKL_INCLUDE_DIR NAMES mkl_dfti.h  )
---
> find_path(MKL_INCLUDE_DIR NAMES mkl_dfti.h PATHS ${MKL_PATH})
> 
`


[forum.zip](https://github.com/shankar1729/jdftx/files/11560002/forum.zip)




`-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Looking for gsl_integration_glfixed_point
-- Looking for gsl_integration_glfixed_point - found
-- Found GSL: /usr/lib/x86_64-linux-gnu/libgsl.so
-- Looking for pthread.h
CMake Warning (dev) at /usr/share/cmake-3.16/Modules/CheckIncludeFile.cmake:80 (message):
  Policy CMP0075 is not set: Include file check macros honor
  CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  CMAKE_REQUIRED_LIBRARIES is set to:

    /usr/lib/x86_64-linux-gnu/libgsl.so;/usr/lib/x86_64-linux-gnu/libgslcblas.so;;m

  For compatibility with CMake 3.11 and below this check is ignoring it.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindThreads.cmake:128 (CHECK_INCLUDE_FILE)
  CMakeLists.txt:69 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found MKL: /usr/lib/x86_64-linux-gnu/libmkl_intel_lp64.so;/usr/lib/x86_64-linux-gnu/libmkl_gnu_thread.so;/usr/lib/x86_64-linux-gnu/libmkl_core.so;gomp
-- Found FFTW3:  /usr/lib/x86_64-linux-gnu/libfftw3_threads.so /usr/lib/x86_64-linux-gnu/libfftw3.so
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Performing Test HAS_NO_UNUSED_RESULT
-- Performing Test HAS_NO_UNUSED_RESULT - Success
-- Performing Test HAS_TEMPLATE_DEPTH
-- Performing Test HAS_TEMPLATE_DEPTH - Success
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/dev/jdftx/jdftx-1.7.0/build
`

**Comment by shankar1729** [comment]
Another thing to try is whether you can specify MKL_PATH to point within `/usr/lib` to get the mkl libraries detected, and then manually specify `-D MKL_INCLUDE_DIR` and `-D FFTW3_INCLUDE_DIR` to point to `/usr/include/mkl`. CMake should then accept the given include paths and proceed.

**Comment by mmarchywka** [comment]
Thanks. I don't know anything about cmake or most build tools but it looks like there
are maybe 3 cases: the opt install with "include" in the path, the repository
install with "mkl" directory above, and everything else. Discovering the headers
could be independent of the libs I suppose but in the first two cases once the headers
are found the libs are probably easy to find.  There may be issues with versions and name
collisions but probably neither matter here. 
There is probably some other thing with a similar paradigm but I did not know
where to look and if I understand the way cmake works this should pickup the
standard install. 

No idea what the status of  MKL in particular will be I was surprised it was in the repo
then later mention its not free lol.

**Comment by shankar1729** [comment]
Right, I don't think most MKL installations would have this layout, so if it can be done with the existing CMake setup with a few extra variables, that would be ideal. CMake is a lot easier to navigate than the autotools rig, but it still gets really complicated very quickly in the path detection parts.
