### ISSUE TITLE
Assertion 'eos' failed 

### ISSUE THREAD

**Issue by juliayang** [shankar1729/jdftx#287]
Dear Shankar,

I'm new to using JDFTx and am trying to calculate energies of H2O in various liquids. I'm able to calculate H2O for water, but after changing the fluid to ethanol, I see the following error: 

`/n/home07/jhyang/jdftx/jdftx-1.7.0/jdftx/fluid/FluidComponent.cpp:602: addToFluidMixture:`

`Assertion 'eos' failed/n/home07/jhyang/jdftx/jdftx-1.7.0/jdftx/fluid/FluidComponent.cpp:602: addToFluidMixture:`

I'm attaching the input that fails. Thanks a lot for any help here!

```
include common.in
include Vacuum.ionpos
initial-state Vacuum.$VAR
ionic-minimize nIterations 10
dump-name out.$VAR
dump End State BoundCharge

van-der-waals D3

fluid ClassicalDFT  
fluid-solvent Ethanol bulk ScalarEOS

**Comment by shankar1729** [comment]
Hi Julia,

The classicalDFT solvent requires a carefully parameterized functional for each solvent / electrolyte. At the moment, we do not have a parameterized free energy functional for ethanol, which is what is leading to this error.

I would recommend looking into the implicit solvation models instead for the non-aqueous solvents. We have some ongoing work on automating the classical DFT development for other liquids, but that is still an early work in progress that is not ready to deploy in JDFTx yet.

Best,
Shankar

**Comment by juliayang** [comment]
Hi Shankar,

Thanks for the explanation and suggestion to use implicit models! Yes, that seems to be the way forward. 

Best,
Julia
