### ISSUE TITLE
PZC calculation problem

### ISSUE THREAD

**Issue by miaozhuang68** [shankar1729/jdftx#288]
Dear Shankar,
The difference between my calculated PZC of pure magnesium (-1.4V vs. SHE) and the experimental value (-2.3V vs. SHE) is too large, I wonder if I am doing something wrong?
The another thing I want to ask is when I want to get the potential of a charged electrode relative to the solution (not V_SHE, but V_solution), is using the `V_SHE(charged electrode)-PZC (vs. SHE) =V_solution` reliable? Because most of the potential changes are generated by Qnet.
Best,
Jam

```
include contcar.lattice
include contcar.ionpos
ion-species GBRV/$ID_pbe_v1.2.uspp
ion-species GBRV/$ID_pbe_v1.uspp


elec-cutoff 20 100

coulomb-interaction Slab 001
coulomb-truncation-embed 0 0 0.225395

fluid SaLSA
fluid-solvent H2O
fluid-cation Na+ 0.47
fluid-anion Cl- 0.47

van-der-waals D3
elec-ex-corr gga-PBEsol

kpoint-folding 7 7 1
#kpoint 0 0 0  1
elec-smearing Fermi 0.003
electronic-SCF \
    nIterations 1000 \
    energyDiffThreshold 1e-5

ionic-minimize \
    nIterations 100 \
    energyDiffThreshold 1e-5 \
    knormThreshold 0.001 \ # Threshold on RMS cartesian force
    nEnergyDiff 3

dump-name Vacuum.$VAR
dump End IonicPositions Ecomponents Dtot
```

**Comment by shankar1729** [comment]
A couple of quick notes on your question above:

- The PZC of a reactive metal like Mg may depend on explicit adsorption of solvent and ions, which will not be captured by a solvation model alone. That may be the source of your discrepancy.
- The estimate you propose is reasonable, but note that the quantity "potential of electrode relative to solution" is a little difficult to define precisely. It is not experimentally measurable, and requires additional clarification. For example, do you mean the change in energy of an electron when you take it from the electrode to bulk of solution? If so, this can be calculated, but it also depends on the energy levels of electrons in the bulk of the electrode and electrolyte, and is not purely an electrostatic potential. Essentially, what you are estimating is the electrostatic potential difference between the surface of the electrode and the bulk electrolyte, which is not measurable directly.

**Comment by miaozhuang68** [comment]
Dear Shankar,
The measures mentioned in your reply are effective! And you also mentioned in the tutorial of JDFTx that the implicit solvation model does not include the adsorption of solvent ions. In fact I discovered the solution of this problem yesterday. I closed the question, but you replied to me anyway, which is very touching! Your reply helped me a lot!
Regarding the calculation of V_Solution, your reminder is exactly the same as what I have considered. I will use this value to uniformly compare the differences between different metals, rather than combining it with experiments. Thanks for the tip on this!
Best,
jam

**Comment by miaozhuang68** [comment]
Dear Shankar,
Another problem arises, when I use Nonliner solvation, the dtot curve becomes very strange, as shown below, I use Nonliner because it is mentioned in the tutorial that this model is more accurate for calculating the electrochemical process,
![image](https://github.com/shankar1729/jdftx/assets/135727692/ffd5c063-6f7b-4a71-8f97-a2010bb44851)

````
include contcar.lattice
include contcar.ionpos
ion-species GBRV/$ID_pbesol_v1.4.uspp
ion-species GBRV/$ID_pbe_v1.2.uspp
ion-species GBRV/$ID_pbe_v1.uspp

elec-cutoff 20 100

coulomb-interaction Slab 001
coulomb-truncation-embed 0 0 0.225395

fluid NonlinearPCM
pcm-variant GLSSA13
fluid SaLSA
fluid-solvent H2O
fluid-cation Na+ 0.6
fluid-anion Cl- 0.6

van-der-waals D3
elec-ex-corr gga-PBEsol

kpoint-folding 7 7 1
elec-smearing MP1 0.003
electronic-SCF \
    nIterations 1000 \
    energyDiffThreshold 1e-5

ionic-minimize \
    nIterations 100 \
    energyDiffThreshold 1e-5 \
    knormThreshold 0.001 \ # Threshold on RMS cartesian force
    nEnergyDiff 2


dump-name Vacuum.$VAR
dump End IonicPositions Ecomponents Dtot BoundCharge
````

**Comment by shankar1729** [comment]
Please attach a log file as well for the nonlinear case: likely the potential is not yet converged.

**Comment by miaozhuang68** [comment]
Dear Shankar,
Thanks for your thoughtful reply, I will provide my source file below.
Among them, `ClNonlinerPZC` calculates the PZC with 1/4 area of chlorine atoms adsorbed, and `initial_charge_-0.2` calculates the charging potential of Slab (no adsorption), because from my understanding this may cause chlorine atoms to be charged,  and chloride ions do not actually participate in the reaction.
Best,
Jam
[ClNonlinerPZC.zip](https://github.com/shankar1729/jdftx/files/12074712/ClNonlinerPZC.zip)
[initial_charge_-0.2.zip](https://github.com/shankar1729/jdftx/files/12074713/initial_charge_-0.2.zip)

**Comment by shankar1729** [comment]
Try using [command pcm-nonlinear-scf](https://jdftx.org/CommandPcmNonlinearScf.html) to converge the nonlinear fluid using a different algorithm. This generally works better to converge the potential far from the electronic system, which doesn't impact the total energy as much.

**Comment by miaozhuang68** [comment]
Dear Shankar,
I used the command `pcf-nonliner-scf` according to your instructions, and to my delight, the smooth, uncharged Slab converges well, but the dtot curve is still as shown.
<img width="833" alt="image" src="https://github.com/shankar1729/jdftx/assets/135727692/ac0bb854-6d7c-4f2a-93bf-29b3c1034caf">

Cl-adsorbed Slabs and positively charged Slabs still fail to converge after hundreds of SCF. I can feel the energy and potential wildly running around when the Cl is adsorbed(ClNonlinerPZC); and the energy and potential of the positively charged Slab is fluctuating in a small range around the correct value(SlabNonlinerPZC). 

Here is my input file, `ClNonlinerPZC` is a Slab with adsorbed Cl atoms, `initial_charge_-0.2` is a positively charged non-adsorbed Slab, and `SlabNonlinerPZC` is an uncharged Slab with no adsorbed Cl atoms and is converged in the JDFTx calculation. All structures here were fully relaxed using VASP.

[Desktop.zip](https://github.com/shankar1729/jdftx/files/12094156/Desktop.zip)

**Comment by miaozhuang68** [comment]
Dear Shankar, 
I used `pcm-nonlinear-scf` and  `fluid-gummel-loop 100 1.000000e-04`, but my system still needs a lot (more than 20 electronic and fluid loops) to converge, I want to know if I just want to get the potential on the surface of my Slab. Is there a way to speed up my calculation such as reducing the number of loops?

Best,
Jam

**Comment by miaozhuang68** [comment]
Dear Shankar,
I have used `fluid-solve-frequency Inner` and `pcm-nonliner-scf` and have been unable to converge when entering the solution calculation, which never occurs in the Salsa model. Here is my output file

Best,
Jam
[output.txt](https://github.com/shankar1729/jdftx/files/12116166/output.txt)

**Comment by miaozhuang68** [comment]
Dear Shankar,
Noticed in your paper on NonlinerPCM that the NormConserving pseudopotential is used, I think there is a reason for the transition from USPP to NormConserving, and this may be the reason why my previous calculations failed to converge. And you also use Partial Core Corrections to avoid solvent intrusion. I'm testing this method:
1. I want to know that after debugging the parallelization parameters, each SCF still needs to consume about 500s (vs. 80s in uspp), is this normal?
2. Regarding Partial Core Corrections, I know it's supposed to be done using opium, but it seems a bit difficult, can you provide some input files for opium written for Partial Core Corrections?

**Comment by shankar1729** [comment]
Your issues in the previous calculation seem to be with electronic SCF convergence, rather than with the fluid. Please try the electronic minimize algorithm instead, as it was designed specifically to handle these hard to converge metal slab cases where electronic SCF can fail.

As for the latest message, you don't need to use norm-conserving pseudopotentials for this. The only reason the paper used it was that it predated the ultrasoft support and the newer pseudopotential sets (eg. GBRV) now recommended for use with JDFTx. Most of these already have semi-core electrons and/or partial core corrections, and can be used directly with the solvation models.

**Comment by shankar1729** [comment]
Note that your slab extends roughly from 0 to 0.5 in lattice coordinates, with an embed center around 0.24. Consequently, what you are calling the far right is just the surface immediately to the left of 0, and that potential profile seems plausible.

**Comment by shankar1729** [comment]
Yes, you can use `elec-initial-charge` to set the overall charge in a metal+adsorbate system. The charge will redistribute appropriately per the equilibrium configuration, which may include some charge on the adsorbate, depending on its energy levels.

**Comment by miaozhuang68** [comment]
Dear Shankar,
thank you for your patience! After using electronic-minimize, the convergence becomes easier, but the dtot curve still behaves unreasonably in the solvent. I switched to Salsa+H2O adsorption and got relatively reasonable results.
I also report a bug to you here. When I use the tag `ionic-gaussian-potential`, JDFTx prompts that this command does not exist.
Thanks again for your patient reply!

**Comment by shankar1729** [comment]
The command ionic-gaussian-potential is relatively new; you may need to update the code to get that. (The online documentation includes updates since the last numbered release.)

**Comment by miaozhuang68** [comment]
I've updated my code and my calculations are going very smoothly recently, thanks for your help!
Best,
Jam
