### ISSUE TITLE
Gets stuck where it should stop with an error message

### ISSUE THREAD

**Issue by rraffiu** [shankar1729/jdftx#294]
If I have `dump-only` flag in the `phonon.in` file, along with `initial-state`, and `.wfns` from unit cell calculations. When I run
`phonon -ni phonon.in > phonon.out`, the code gets stuck forever. 
Removing `dump-only` **OR** adding `.fillings` and .`eigenvals` files from scf run fixes the problem. 
Shouldn't it produce an error message and stop?

**Comment by shankar1729** [comment]
Thanks for catching this: fixed the dump-only error checking to catch for missing eigenvals when needed in c9bf023d.
