### ISSUE TITLE
Titaniumdioxide

### ISSUE THREAD

**Issue by Lennart-Winter** [shankar1729/jdftx#3]
Dear Shankar,

I just wanted to calculate the bandstructure of titaniumdioxide and I have an Error in common.in (see attached)

I garuntee for the lattice constants to be right I assume the error is in the ion-species command.
But something like ion-species GBRV/Ti_pbe_v1.2.uspp
didn't work.

I would kindly ask of some advice.

Thank you very much and best regards 

Lennart
[common.txt](https://github.com/shankar1729/jdftx/files/1208398/common.txt)
[totalE.txt](https://github.com/shankar1729/jdftx/files/1208397/totalE.txt)

**Comment by shankar1729** [comment]
Your lattice vectors seem to be in Angstrom; jdftx input is in bohrs.  That might be the reason for overlapping ion errors.

**Comment by Lennart-Winter** [comment]
Thank you; I also found some typing errors in common.in I will try that now

**Comment by Lennart-Winter** [comment]
Dear Shankar,

thanks to your advice the calculation worked, but the result is not expected.
I calculated without elec-smearing, because TiO_2 should show insulating or at least semiconducting behaviour.

But the VBM I got from the totalE.eigStats actually crosses a bond (see attached picture).
Since TiO_2 (rutil structure) shows a band gap of ca. 3 eV, I'd expect the VBM to be elsewhere.

Could you please tell me where my error is? (Just for completion I'll attach my input files as well)

Thank you so much for all your support!!

Best,

Lennart

![tio_2](https://user-images.githubusercontent.com/30293901/29119894-3bea53c2-7d08-11e7-9501-f18413c94eae.png)
[bandstruct.txt](https://github.com/shankar1729/jdftx/files/1211291/bandstruct.txt)
[bandstruct.kpoints.txt](https://github.com/shankar1729/jdftx/files/1211294/bandstruct.kpoints.txt)
[common.txt](https://github.com/shankar1729/jdftx/files/1211295/common.txt)
[totalE.txt](https://github.com/shankar1729/jdftx/files/1211296/totalE.txt)

**Comment by shankar1729** [comment]
You have a typo in one of the Ti's z-coordinates: it should be 0.5 not 0.05.  This was presumably causing the Two Ti's to be in the same plane with short bonds to O, making a metallic chain along the diagonal.

Always check your structures using the dry run + createXSF + VESTA / xcrysden!

Shankar

**Comment by Lennart-Winter** [comment]
Dear Shankar,

I'm sorry for bothering I should've seen that myself. 
Nevertheless thank you again.

Best 

Lennart
