### ISSUE TITLE
How to choose coulomb-truncation-embed？

### ISSUE THREAD

**Issue by casstudent** [shankar1729/jdftx#30]
Hi dear shankar，
I‘m a beginner and I had some problem when choosing coulomb-truncation-embed ：
I used the comand：
coulomb-interaction Slab 001
coulomb-truncation-embed 0 0 0
but it failed：
Coulomb truncation embedding center is not invariant under symmetries.

and here is my Ni（111）slab  ionpos：

ion Ni          0.000000000         0.000000000         0.000000000    1
ion Ni          0.333330005         0.166669995         -0.143050000   1
ion Ni          0.166669995         0.333330005         -0.286100000   1
ion Ni          0.500000000         0.000000000         0.000000000    1
ion Ni          0.833329976         0.166669995         -0.143050000   1
ion Ni          0.666670024         0.333330005         -0.286100000   1
ion Ni          0.000000000         0.500000000         0.000000000    1
ion Ni          0.333330005         0.666670024         -0.143050000   1
ion Ni          0.166669995         0.833329976         -0.286100000   1
ion Ni          0.500000000         0.500000000         0.000000000    1
ion Ni          0.833329976         0.666670024         -0.143050000   1
ion Ni          0.666670024         0.833329976        -0.286100000    1

the tutorial about this is too short so i don't understand.
what coulomb-truncation-embed should i use？
thank you very much！

**Comment by shankar1729** [comment]
If your system is symmetric, set the embed-center to the symmetry-center, at least along directions that are truncated. (Otherwise, coulomb truncation will break the symmetries of the system; hence the error.)

In your case, your slab is vertically centered at z = -0.14305 in lattice coordinates. So either use 0 0 -0.14305 as the embed center, or re-center your slab at z=0.

Best,
Shankar

**Comment by casstudent** [comment]
Thanks shankar,
I change the embed center and it really works! But I still have some questions and needs your help:
Q1：
In your last year's paper, JDFTx software for joint density-functional theory, you gave us an example about Pt(111) , in this example, you chose 0 0 0 as the embed center, but actually 0 0 0 is not the symmetry-center(i guess ,because all the Pt atoms are below 0 ) , why do you chose 0 0 0?

and this is the command in the paper:
ion Pt 0.33333 -0.33333 -0.288 0
ion Pt 0.33333 -0.83333 -0.288 0
ion Pt 0.83333 -0.83333 -0.288 0
ion Pt 0.83333 -0.33333 -0.288 0
ion Pt 0.16667 -0.16667 -0.144 0
ion Pt 0.16667 -0.66667 -0.144 0
ion Pt 0.66667 -0.16667 -0.144 0
ion Pt 0.66667 -0.66667 -0.144 0
ion Pt 0.000 0.000 0.000 0
ion Pt 0.000 -0.500 0.000 0
ion Pt 0.500 0.000 0.000 0
ion Pt 0.500 -0.500 0.000 0 #0 => fixed
ion O 0.152 -0.079 0.155 1 #1 => free
ion O -0.152 +0.079 0.155 1
ion C 0.000 0.000 0.190 1 Planar 0 0 1
ion H 0.000 0.000 0.260 1

Q2:
after calculate vacuum condition, i want to add fluid in. but this time the calculation failed with files:
"jdftx-stacktrace" and "core" , and the output flie is:
(first ElecMinimize)...
ElecMinimize: Converged (|Delta F|<1.000000e-08 for 2 iters).
Setting wave functions to eigenvectors of Hamiltonian
Single-point solvation energy estimate, DeltaF = -0.000500772729083
Calculating stress tensor...
How can I solve this problem?

thank you very much!

**Comment by shankar1729** [comment]
1. In that example, the overall system was not top-down symmetric, and the embed-center was still roughly in the middle of the z-range of all atoms (including the adsorbates).

2. That's not enough to debug: please post the full log file and the stacktrace (no need for the core).

Shankar

**Comment by casstudent** [comment]
thanks shankar,
 I think i have already known how to choose the embed center with your help!
And here are stacktrace and output file:(original document can't be uploaded so i save them to txt hope you can read it!)
[ni-111-opt-sol.TXT](https://github.com/shankar1729/jdftx/files/2148212/ni-111-opt-sol.TXT)
[jdftx-stacktrace.txt](https://github.com/shankar1729/jdftx/files/2148213/jdftx-stacktrace.txt)

**Comment by shankar1729** [comment]
Is there a reason you are using lattice minimize? Usually for surfaces like this only ionic minimize is needed, with in place lattice parameters set based on the optimized bulk geometry. This error is likely an interaction of the stress calculator and the solvation model.

Second, the MPI parallelization is not optimal. Currently, if you have nStates 8, keep number of processes a factor of that and use threads to use more cores. See the getting started page on the website. This will make your run much faster and avoid potential memory issues (which could also be another reason for the segfault).

Best,
Shankar

**Comment by casstudent** [comment]
thanks Shankar,
It was my fault to use 'lattice minimize'. I changed it to 'ionic minimize' and it runs successfully!
As for MPI parallelization, i don't know much about it because I'm a beginner in this field. I will reread tutorials and change the number of threads.
Thanks again!

**Comment by shankar1729** [comment]
Great, good luck!
