### ISSUE TITLE
TDOS calculation setup and optical absorption

### ISSUE THREAD

**Issue by moyulyy** [shankar1729/jdftx#300]
Dear Shankar,

When calculating TDOS, whether there are commands to constrain the energy interval and the number of points is similar to the EMIN, EMAX, and NEDOS parameter Settings when calculating dos for vasp.
In addition, whether jdftx can calculate the optical properties of two-dimensional graphene-like materials, such as the optical absorption of C2N at constant electric potential.

Best,
lyy

**Comment by shankar1729** [comment]
There isn't a command to constrain the energy range, as this can be easily adjusted while plotting. You can control the energy resolution using the Esigma input; without it, the energy resolution is set based on the sampled energy points within the tetrahedron point.

There are no built-in commands to output an optical spectrum, but this can be easily computed in post-processing using the energies, occupations and momentum matrix elements outputs (`dump End BandEigs Fillings Momenta`) in a standard Fermi Golden rule expression. The Wannier tutorial shows how to do this using interpolated energies and matrix elements, but this can be adapted to use direct DFT outputs for convenience (to avoid the Wannierization step). This technique will work for 2D materials, and under bias; just output these quantities from the relevant grand-canonical calculations. 

If you adapt the Direct Transitions script from Wannier to DFT and would like to post an example / tutorial, that would be greatly appreciated.

Best,
Shankar
