### ISSUE TITLE
pseudopotential meta-gga functional

### ISSUE THREAD

**Issue by wamuriel** [shankar1729/jdftx#303]
Dear Shankar,

 I want to perform calculations with the SCAN functional, and I understand that to do so the pseudopotential must contain kinetic energy density. I would like to know if the pseudopotentials that are distributed with the code are suitable for use with meta-gga functionals.

Kind regards

Wilver

**Comment by shankar1729** [comment]
Hi Wilver,

Most pseudopotential sets are generated using LDA or PBE exchange-correlation functionals, and do not contain KE density. Correspondingly, meta-GGA calculations are often done with PBE pseudopotentials.

JDFTx does not need KE density in the pseudopotential for meta-GGAs, but it does require the pseudopotential to be norm-conserving. So, you can use the SG15 pseudos installed along with the code, or you can get other norm-conserving ones, eg. from pseudo-DOJO.

Finally, to use SCAN, you would need to build with LibXC support.

Best,
Shankar
