### ISSUE TITLE
Unusually large Bader charge of pyridine defect in graphene

### ISSUE THREAD

**Issue by gmarci** [shankar1729/jdftx#304]
Dear Shankar!

I tried to perform Bader-analysis on pyridine-type defect in graphene, but I got strangely large Bader-charge for nitrogen atoms (more than 2 extra electrons). The input, output, electronic density, and the outputs of the Bader-analysis are attached below (GBRV).
I also examined the effect of the resolution of the real-space grid both by increasing the charge density cutoff and by the Fourier-interpolation, provided by script createVASP, but these did not really help.
I tested the effect of the norm-conserving pseudopotentials (SG15), which leaded to more reasonable results (see folder SG15) but I am still unsure whether the 'issue' comes from the type of the pseudopotential, since both the ultrasoft and norm-conserving ones provide very same results for other type of model systems (like CsCl, discussed in the end of the issue "How to obtain CoreDensity" https://github.com/shankar1729/jdftx/issues/20).

Can you give me some hint, where my computations went wrong?

Thank you in advance!

Best,
Márton
[SG15.zip](https://github.com/shankar1729/jdftx/files/12930495/SG15.zip)
[GBRV.zip](https://github.com/shankar1729/jdftx/files/12930506/GBRV.zip)

**Comment by shankar1729** [comment]
Hi Márton,

I looked at your runs and everything seemed fine to me. The Lowdin charges reported (in the oxidation-state line) as well as the density profiles are very similar.

It looks like the pseudo-atom charge near the center of C is a little lower in the GBRV pseudo compared to the SG15 one. This is leading to the Bader region of N eating up a large part of the adjacent Cs for the GBRV case. I think this is an intrinsic problem with the Bader definition as applied to pseudo-electron densities, and that there is nothing wrong with the pseudos or either calculation.

I don't think a core correction is needed here, but you could add a core charge distribution integrating to 2 electrons each to all the atoms. Maybe this reduces the chance of N eating into the adjacent C.

Best,
Shankar

**Comment by gmarci** [comment]
Dear Shankar!

Thank you very much for your detailed explanation!
I supplemented the electron density with the contribution of core electrons in case of GBRV and it helped me to improve a bit the results about Bader-charges belonging to nitrogen atoms.

Best,
Márton
