### ISSUE TITLE
what is difference between the PZC and U

### ISSUE THREAD

**Issue by Deevansh-123** [shankar1729/jdftx#305]
good morning 
Dr Shankar 
i am confused about like how to differentiate the PZC and U? can you help 
thank you
Deevansh

**Comment by shankar1729** [comment]
Hi Deevansh,

Potential of Zero Charge (PZC) is the electron chemical potential / electrode potential of the neutral surface. Based on context, I'm guessing U is electrode potential here? And typically, that would be reported against a scale such as SHE.

These are standard electrochemistry terms that you can refer to books and reviews on; we can discuss questions that connect to JDFTx implementation details here.

Best,
Shankar
