### ISSUE TITLE
How to view the Fermi level and the potential of zero charge (PZC) of a system under a fixed potential.

### ISSUE THREAD

**Issue by lifei111111** [shankar1729/jdftx#316]
Dear Shankar,

I am using JDFTx for electrochemical simulations under constant potential, but I would like to find the Fermi level and the Potential of Zero Charge (PZC) from the output files. How can I do this? I look forward to your reply.

Kind regards
FeiLi

**Comment by shankar1729** [comment]
Hi Fei Li,

Please see the [Metal Surfaces tutorial](http://jdftx.org/MetalSurfaces.html): it describes this in detail, along with awk scripts to fetch and process the mu from the log files.

Best,
Shankar

**Comment by shankar1729** [comment]
Also, you need to do a neutral calculation to get the PZC. You can't get it from a fixed potential calculation at different potential.

**Comment by lifei111111** [comment]
Dear Shankar,
Thank you for your prompt reply, I have understood now.
Kind regards
FeiLi
