### ISSUE TITLE
How to calculate the Density of States (DOS)

### ISSUE THREAD

**Issue by lifei111111** [shankar1729/jdftx#317]
Dear Shankar,

I'm a bit confused about calculating the Projected Density of States (PDOS). In the tutorial with density-of-states \ OrthoOrbital Si 1 s \ OrthoOrbital Si 1 p, does the number "1" refer to the atomic number, starting from 0?

 My system is an alloy system with 32 Cu atoms and 32 Ag atoms. How should I set up the input file to calculate the PDOS for the d orbitals of the 32 Cu atoms and the d orbitals of the 32 Ag atoms? 

Also, is it necessary to set the elec-n-bands parameter when calculating DOS? If it needs to be set, how should I consider setting it for my system? 

Kind regards
FeiLi

**Comment by shankar1729** [comment]
Yes, the atoms are numbered starting from 1. For your allot system, you will need to do add a line for each oribital on each atom. This maybe a lot of lines for a large supercell, so you may want to write it using a simple script.
