### ISSUE TITLE
Compilation error using icc in file core/Coulomb.cpp

### ISSUE THREAD

**Issue by f-fathurrahman** [shankar1729/jdftx#32]
Dear @shankar1729, I have encountered error when trying to build `jdftx-1.4.1` using Intel compilers.

Here is the output of make:
```
Scanning dependencies of target PseudopotentialLibrary
Scanning dependencies of target jdftxlib
[  0%] Building CXX object CMakeFiles/jdftxlib.dir/core/AutoThreadCount.cpp.o
[  1%] Building CXX object CMakeFiles/jdftxlib.dir/core/BlasExtra.cpp.o
[  2%] Building CXX object CMakeFiles/jdftxlib.dir/core/Blip.cpp.o
[  2%] Building CXX object CMakeFiles/jdftxlib.dir/core/Coulomb.cpp.o
/home/efefer/mysoftwares/jdftx-1.4.1/jdftx/core/Coulomb.cpp(57): error: no suitable constructor exists to convert from "int" to "std::shared_ptr<Coulomb>"
  		default: return 0; //never encountered (to suppress warning)
  		                ^

compilation aborted for /home/efefer/mysoftwares/jdftx-1.4.1/jdftx/core/Coulomb.cpp (code 2)
make[2]: *** [CMakeFiles/jdftxlib.dir/core/Coulomb.cpp.o] Error 2
make[2]: *** Waiting for unfinished jobs....
[  2%] Built target PseudopotentialLibrary
make[1]: *** [CMakeFiles/jdftxlib.dir/all] Error 2
make: *** [all] Error 2
```
Are there any work around for this ?
For the moment, I might try using GNU compiler instead.

I am sorry if this issue has been reported before.

**Comment by f-fathurrahman** [comment]
I am sorry, I forget to include version info of the compiler:
```
icpc --version 
icpc (ICC) 17.0.4 20170411
Copyright (C) 1985-2017 Intel Corporation.  All rights reserved.
```

**Comment by shankar1729** [comment]
Intel compilers rely on a GNU compiler for the C++ standard library. This error seems to be because the version of C++ standard library used pre-dates complete C++11 support that JDFTx needs. Please check your default GNU compiler version (it will probably be 4.6 or older) and see if you can get the intel compiler to use a newer C++ library.

**Comment by f-fathurrahman** [comment]
Thank you very much Shankar. This seems to be the case for our cluster which use rather old version of GCC.
