### ISSUE TITLE
Unable to use EC with softsphere model 

### ISSUE THREAD

**Issue by BCAyers2000** [shankar1729/jdftx#327]
Hi, 

my input file is as follows: 

`electronic-SCF 
elec-n-bands 66
elec-cutoff 40 240
elec-ex-corr gga-PBEsol
elec-smearing cold 0.01

elec-eigen-algo Davidson
davidson-band-ratio  1.3
electronic-minimize \
    nIterations 120 \
    nEnergyDiff   2 \
    energyDiffThreshold 1.0e-10 
    
ionic-minimize \
    nIterations 100 \
    knormThreshold 1e-4\
    dirUpdateScheme     L-BFGS \
    energyDiffThreshold 1.0e-7 

van-der-waals D3
kpoint-folding 2 2 1
coulomb-interaction Slab 001
coulomb-truncation-embed 0 0 0             

fluid LinearPCM
pcm-variant SoftSphere
fluid-solvent EC
fluid-cation  Na+ 1.
fluid-anion   F- 1.

ion-species Li.upf
dump Ionic State IonicPositions ElecDensity Dtot BoundCharge Dvac Dfluid EigStats FluidDensity

lattice \
13.00131575 0.00000000 0.00000000 \
0.00000000 13.00131575 0.00000000 \
0.00000000 0.00000000 58.35474277 \

coords-type cartesian

ion Li -4.87549340 -4.87549340 -6.50065787 1 
ion Li 1.62516447 -4.87549340 -6.50065787 1 
ion Li -4.87549340 1.62516447 -6.50065787 1 
ion Li 1.62516447 1.62516447 -6.50065787 1 
ion Li -1.62516447 -1.62516447 -3.25032894 1 
ion Li 4.87549340 -1.62516447 -3.25032894 1 
ion Li -1.62516447 4.87549340 -3.25032894 1 
ion Li 4.87549340 4.87549340 -3.25032894 1 
ion Li -4.87549340 -4.87549340 0.00000000 1 
ion Li 1.62516447 -4.87549340 0.00000000 1 
ion Li -4.87549340 1.62516447 0.00000000 1 
ion Li 1.62516447 1.62516447 0.00000000 1 
ion Li -1.62516447 -1.62516447 3.25032894 1 
ion Li 4.87549340 -1.62516447 3.25032894 1 
ion Li -1.62516447 4.87549340 3.25032894 1 
ion Li 4.87549340 4.87549340 3.25032894 1 
ion Li -4.87549340 -4.87549340 6.50065787 1 
ion Li 1.62516447 -4.87549340 6.50065787 1 
ion Li -4.87549340 1.62516447 6.50065787 1 
ion Li 1.62516447 1.62516447 6.50065787 1 
`
However when i run said system I get :

WARNING: PCM variant SoftSphere has not been parametrized for this solvent; using bulk
   surface tension as effective cavity tension and water parameters for everything else.
WARNING: SCCS variants have not been parametrized for this solvent; using water parameters
   Initializing fluid molecule 'EC'
     Net charge: 0   dipole magnitude: 0
     Initializing spherical shell mfKernel with radius 0 Bohr

Looking at the documentation I cant determine which solvents can be used with softsphere.

kind regards,
Brad

**Comment by shankar1729** [comment]
Good point, that would be useful to expose in the docs in the future. For now, you can see this in [fluid/FluidSolverParams.cpp](https://github.com/shankar1729/jdftx/blob/master/jdftx/fluid/FluidSolverParams.cpp) within the code, which should be fairly straightforward to follow.

At the moment, SoftSphere is only parameterized for water, as reported in the corresponding paper. If you have solvation energy data for EC, it should be fairly easy to adjust the required radius parameters and set it within the code.
