### ISSUE TITLE
JDFTx stops running at "Allocating Electronic Variables" when using mpiexec to run in the background via PBS

### ISSUE THREAD

**Issue by ColinBundschu** [shankar1729/jdftx#330]
[outfile.txt](https://github.com/shankar1729/jdftx/files/15421206/outfile.txt)

Here is a simple test case (in practice several instances would be launched, which is why this uses the `&` and `wait`)

```
#!/bin/bash -l
#PBS -l select=1:system=polaris
#PBS -l place=scatter
#PBS -l walltime=01:00:00
#PBS -q debug-scaling
#PBS -A von
#PBS -l filesystems=home
#PBS -o /home/cbu/test_mnc_output.log
#PBS -e /home/cbu/test_mnc_error.log

# Number of nodes allocated
NNODES=`wc -l < $PBS_NODEFILE`

# MPI settings
NRANKS_PER_NODE=$(nvidia-smi -L | wc -l)
NDEPTH=8
NTHREADS=1
export MPICH_GPU_SUPPORT_ENABLED=1
export JDFTX_MEMPOOL_SIZE=38000
module load craype-accel-nvidia80

# Define the JDFTx commands
JDFTX_CMD="--ppn ${NRANKS_PER_NODE} --depth=${NDEPTH} --cpu-bind depth --env OMP_NUM_THREADS=${NTHREADS} -env OMP_PLACES=threads /home/cbu/jdftx/build/jdftx_gpu"

# Extract the hostnames of the nodes
NODES=(`cat $PBS_NODEFILE`)

# Run JDFTx commands
cd /home/cbu/dft_out/N4C10/clean/
mpiexec -n ${NRANKS_PER_NODE} --host ${NODES[0]} ${JDFTX_CMD} -i 331.in -o 331.out &

wait
```

Only error output was this, which indicates that jdftx failed:
```
x3008c0s31b0n0.hsn.cm.polaris.alcf.anl.gov: rank 1 died from signal 8 and dumped core
x3008c0s37b0n0.hsn.cm.polaris.alcf.anl.gov: rank 6 died from signal 8 and dumped core
x3008c0s25b1n0.hsn.cm.polaris.alcf.anl.gov: rank 0 died from signal 8 and dumped core
x3008c0s31b0n0.hsn.cm.polaris.alcf.anl.gov: rank 3 died from signal 9
```

**Comment by shankar1729** [comment]
Does the same job without the & and wait runs fine?

**Comment by ColinBundschu** [comment]
It had previously, but it appears that it does not now. I could be confounding this with the fact that I did a new build of JDFTx.  I'll try doing a clean build, but I suspect that when documenting the build steps in the other thread, I missed something important.

**Comment by ColinBundschu** [comment]
The issue appears to be fundamental to the input, not the way I was running it. What happened what that I deleted the Fe from the ionpos file (intentionally). I don't understand why this would cause it to hang on allocation of variables, but I suspect it is because there are no longer any Fe and maybe the `add-U Fe d 0.129` command is causing issues.

**Comment by ColinBundschu** [comment]
Input file for reference:
```
initial-state 331_nlpcm.$VAR
include 331.lattice
include 331.ionpos
ion-species GBRV/$ID_pbe.uspp
elec-cutoff 20 100 #Recommended cutoffs for GBRV pseudopotentials
elec-smearing Fermi 0.1
spintype z-spin
add-U Fe d 0.129
dump Ionic IonicPositions Stress
dump End Stress State
electronic-minimize nIterations 150 alphaTstart 0.1 energyDiffThreshold 1.0000000000000002e-06 nEnergyDiff 5
ionic-minimize nIterations 100 energyDiffThreshold 1e-05 nEnergyDiff 5 alphaTstart 0.1
kpoint 0.5 0.5 0 1
kpoint-folding 3 3 1
fluid NonlinearPCM
fluid-minimize nIterations 222 alphaTstart 0.007
fluid-solvent H2O
pcm-variant GLSSA13
fluid-cation Na+ 1.
fluid-anion F- 1.
lcao-params 150 # More initialization steps for a better starting point
```

**Comment by shankar1729** [comment]
It can't be the missing Fe: that has already been ignored safely in input processing as indicated by the commands that were reproduced at the start of our output file. Can you confirm you get the same failure in regular run mode, without the & and wait (as these could be sending some signals to your job accidentally)?

If the error shows up still, run the same job file on another compute resource you have access to and check that it gets past this stage to help confirm it's something specific to this build/gpu resource. (I don't still entirely trust nvhpc after the weird types of errors it caused.)

**Comment by ColinBundschu** [comment]
It hangs in the exact same spot, using a fresh JDFTx build on my laptop in WSL2 Ubuntu using only CPUs.
[test_case.zip](https://github.com/shankar1729/jdftx/files/15422404/test_case.zip)

**Comment by ColinBundschu** [comment]
My laptop has 128GB of RAM, so that should not be the issue (I custom built it for this exact use case). I don't have access to other, comparable resources that I can test on immediately. But I let it sit for an hour and it made no progress. I have run similar sized calculations on my laptop before without issue in the past.

**Comment by ColinBundschu** [comment]
What is curious is that I am not even seeing any memory pressure when it hangs like this
![image](https://github.com/shankar1729/jdftx/assets/7157190/bb6549b2-6e82-4bed-b50d-acdb20df6a4e)

**Comment by ColinBundschu** [comment]
It seems to hang when I run it with the cases that worked on Polaris, so perhaps your theory that these calcs are too large is correct after all. I'm really not sure the best way to debug this now.

**Comment by ColinBundschu** [comment]
The test_case.zip 5 comments up has everything

**Comment by shankar1729** [comment]
It turned out to actually be the unused `add-U` command that caused the problem. Latest commit fixes this issue such that unused add-U, initial-oxidation-state etc. don't inadvertently create a species with 0 atoms that caused such bugs.
