### ISSUE TITLE
Intermittent hanging on wavefunction saving

### ISSUE THREAD

**Issue by ColinBundschu** [shankar1729/jdftx#335]
I have been extremely hesitant to submit this bug due to its intermittent nature and the possibility that it could have been related to the way I set up my filesystem. However I am now nearly certain that the problem is from JDFTx directly after spending months trying to track it down on my end.

What happens is that once about every 500 wavefunction writes, JDFTx hangs and does not write the wavefunction at all. The last line in the output file is `Dumping 'filename.wfns' ... ` without the usual `done` or a newline. I have verified this happens on NFS and Ceph with extremely high reliability (infiniband) connections. Working with the team, at Jetstream2, we have verified that there does not appear to be any underlying hardware or software issues at play beyond JDFTx simply ceasing to write. The event logs do not have any information that we could discern (note that we were primarily looking for filesystem or connection issues).

[test.txt](https://github.com/shankar1729/jdftx/files/15471971/test.txt)

Unfortunately this is an extremely serious problem if I plan to use Polaris, as the short wall times mean I need to be able to do small numbers of ionic/lattice steps with each job submission. When the writes fail, it leaves the calculation without a wavefunction to resume from, erasing significant progress. Since each calculation requires around 100 steps to converge, this means approximately 20% of calculations will fail.

**Comment by shankar1729** [comment]
One final thing, if you get a hang, can you ssh into that node, gdb attach to each process and see where it's stuck?
