### ISSUE TITLE
createVASP

### ISSUE THREAD

**Issue by ZJZVZS** [shankar1729/jdftx#341]
Dear Shankar,
I want to calculate the Bader Charge after the fix-potential calculations. 
I have already included the line dump End ElecDensity in the input file, but the final output file only contains .n_up and .n_dn files, without the .n file. This makes it unclear how to use createVASP to produce CHGCAR, because in previous responses, it was mentioned that the .n file is required to use the createVASP script.
Could you please help me to carry out the Bader Charge calculation after the fix-potential calculation?

Best
Junze

**Comment by moyulyy** [comment]
see  https://github.com/shankar1729/jdftx/issues/219
This might help you.

Best, 
lyy

**Comment by ZJZVZS** [comment]
I have solved this problem, 非常感谢！
