### ISSUE TITLE
Help with Lattice Minimization

### ISSUE THREAD

**Issue by ahrensaj** [shankar1729/jdftx#349]
Hello Shankar,

I am new to JDFTx, and I am running calculations for anatase TiO2. I am trying to optimize the lattice, but it seems every time I run lattice minimization again the energy spikes up.

If I understand correctly, every lattice minimization iteration during a single run updates lattice vectors, but does not use this new basis until a next separate run. Running at nIterations = 10, I thought maybe this was too high to keep the lattice vector corrections accurate, so I dropped it down to 3, and then 1, but I still get spikes. Here are what the convergence plots look like:

nIterations = 1
![image](https://github.com/user-attachments/assets/c8de4925-9763-42a6-8cce-1c3deeeb6dc4)
nIterations = 3
![image](https://github.com/user-attachments/assets/27f69d87-986a-4780-85e3-8ba1a6fb8329)

I see that lattice-minimize has many additional parameters to guide this process, but I am unsure how to approach using them. If you have any recommendations, or see anything that could be an issue in my input files, let me know.

Thank you for your time!

Input Files:

totalE.lattice
```
lattice Tetragonal 7.14 18.18
```
totalE.ionpos
```
ion Ti 0.500 0.500 0.500 1
ion Ti 0.500 0.000 0.750 1
ion Ti 0.000 0.000 0.000 1
ion Ti 0.000 0.500 0.250 1
ion O 0.000 0.500 0.457 1
ion O 0.500 0.500 0.707 1
ion O 0.500 0.000 0.543 1
ion O 0.000 0.000 0.793 1
ion O 0.500 0.000 0.957 1
ion O 0.000 0.000 0.207 1
ion O 0.000 0.500 0.043 1
ion O 0.500 0.500 0.293 1
```
totalE.in
```
include totalE.lattice
include totalE.ionpos

elec-ex-corr gga-PBE
ion-species /home/alex/PPS/SR_PBE/$ID.upf # from pseudodojo

kpoint-folding 6 6 2
elec-cutoff 20 100
elec-n-bands 96
electronic-SCF

lattice-minimize nIterations 3

dump-name totalE.$VAR
dump Ionic State
dump Init Symmetries Kpoints
dump End  BandEigs Fillings Momenta EigStats ElecDensity
```

**Comment by shankar1729** [comment]
You definitely want to have more iterations than 1 or 3. Can you post what it looked like with 10 instead?

Most likely your issue is plane wave cutoff: the DOJO psps likely need much higher cutoff than 20 Eh; you seem to be using the settings suitable for GBRV ultrasoft psps specifically. Once you are better converged with plane wave cutoff, the jumps in energy due to basis change will become much smaller.

**Comment by ahrensaj** [comment]
Thank you for your reply!

I have since converged with respect to the cutoff energy and found that `elec-cutoff 50 200` seems to do well. 

For the lattice optimization, I tried a variety of `nIterations` values, and ran it 5 times each using a script. Many of the runs ended early, after having reached the convergence condition in a previous run, and logged
```
LatticeMinimize: 	Step failed along negative gradient direction.
LatticeMinimize: Probably at roundoff error limit. (Stopping)
```
This would happen after reaching a lower energy, but I take this message to mean I should have stopped earlier, correct?

If that is the case, I am happy with the geometry at the converged steps and will go with that. Thank you!

**Comment by shankar1729** [comment]
Yes, that should be fine if you are already starting from a previously converged calculation.

**Comment by ahrensaj** [comment]
Great!

I have one last question. In the past, I would calculate the imaginary part of the dielectric function using the direct transitions tutorial under the Wannier section. However, I noticed a recent update added the Dielectric Tensor tutorial with the new epsilon script, which runs much faster and calculates real and imaginary parts.

I would like to understand conceptually what is the difference between these two methods, why one requires a Wannier calculation and the other does not, and if there are differences in accuracy as well. I am hoping to calculate optical properties for this TiO2 I have been optimizing.

If you have any resources you could point me to I would greatly appreciate it!

**Comment by shankar1729** [comment]
The new dielectric tensor directly from DFT is definitely more convenient and recommended in most cases. 

The Wannier requires more steps and is advantageous only if you need very fine brillouin zone convergence. This was originally developed for hot carrier distribution predictions which need this fine convergence.

**Comment by ahrensaj** [comment]
Understood, thank you for your help.
