### ISSUE TITLE
About convergence threshold

### ISSUE THREAD

**Issue by casstudent** [shankar1729/jdftx#35]
Hi shankar，
      I noticed that in the command **ionic-minimize** there are two convergence threshold:
         knormThreshold       0.0001 \    Hartree/bohr?  
         energyDiffThreshold  1e-06 \    Hartree
      I wondered if these two parameters are equal to EDIFFG in VASP. If I set both of the two parameters,  the calculation will end when saitisfied one convergence condition or two?
      What do you recommend?

Best wishes

**Comment by shankar1729** [comment]
knormThreshold specifies a convergence threshold on the RMS force component in Hartree/bohr.

energyDiffThreshold sets threshold in Hartrees for convergence on energy difference between steps, nEnergyDiff (default 2) consecutive times.

Unlike Ediffg in VASP, you can use both together or individually in any combination. If you don't want to use any of a threshold, set it to zero.

Best,
Shankar

**Comment by casstudent** [comment]
Thank you shankar, I understand the relationship between EFIDDG and knormThreshold now.
One more question to bother you:
In the end of the .out file
LatticeMinimize: 	Step failed along negative gradient direction.
LatticeMinimize: Probably at roundoff error limit. (Stopping)
Does it mean the calculation coverge?

Thanks a lot!

**Comment by shankar1729** [comment]
Usually that's not a good sign, but it could happen just if the lattice minimize threshold is unattainably tight. Can you post the output of 'grep LatticeMinimize' on your log file. That may be more helpful to determine if this is the case.
