### ISSUE TITLE
Memory Error when switching from electronic-scf to electronic-minimize on HPC 

### ISSUE THREAD

**Issue by AndrewTaehonKim** [shankar1729/jdftx#352]
Hello Shankar,

Hello Shankar,

I am able to run an electronic-scf calculation for my system (see attached input files). However, running electronic-minimize on the exact same system causes a memory error.  I ran the system on a Tesla V100 (32 GB VRAM) on the SDSC Expanse HPC. I am running on one GPU with 91 GB of memory because I only have 1 nState. I followed your calculation for estimating the memory requirement: `nStates*nBands*nbasis*80`, which is 2.82 GB (1 nState, 322 nBands, 109673 nBasis). I should have more than enough memory, but I am getting the following slurm memory error: `slurmstepd: error: Detected 1 oom_kill event in StepId=33955596.batch. Some of the step tasks have been OOM Killed.`. I have attached the input, lattice, and ionpos files. I do not get this error when running with electronic-scf. 

[Na2S6@N_graphene-vdw.ionpos.txt](https://github.com/user-attachments/files/17063539/Na2S6%40N_graphene-vdw.ionpos.txt)
[Na2S6@N_graphene-vdw.lattice.txt](https://github.com/user-attachments/files/17063540/Na2S6%40N_graphene-vdw.lattice.txt)
[Na2S6@N_graphene-vdw.in..txt](https://github.com/user-attachments/files/17063515/Na2S6%40N_graphene-vdw.in.txt)

Please let me know if you have ever seen such an error and how I may work around this issue. 

Thank you very much for this great software!

Best,
Andrew Kim

**Comment by shankar1729** [comment]
Hi Andrew,

That message is most likely a CPU memory event that is being triggered by your CPU memory crossing the default memory allocated per process to slurm jobs, which is set on some clusters. Often, this limit is set to total memory / number of cores, which is problematic when running a single process with threads. Really, this is irrelevant when running on GPU, but it still creates a problem sometimes.

Try setting the slurm memory flags explicitly, and ask for CPU memory comparable to your GPU size, i.e. ~ 32 GB, and this should most likely go away.

Separately, minimize should take slightly more memory than SCF, so it may have just triggered this issue.

Best,
Shankar

**Comment by AndrewTaehonKim** [comment]
Thank you very much. I will try this!
