### ISSUE TITLE
JDFTX_MEMPOOL_SIZE causes memory allocation errors when memory usage >= JDFTX_MEMPOOL_SIZE / 4

### ISSUE THREAD

**Issue by ColinBundschu** [shankar1729/jdftx#361]
Setting the flag on runs that use around 30-80% of the total GPU memory causes the program to crash with an out of memory error from CUDA in many cases. For example the attached run succeeds with the flag not set, but crashes when the flag is set (all else identical). As profiled in the non-crash case, it uses only 13.2 GB of VRAM (per kpoint, presumably) and each card has 40 GB VRAM. Yet if I set `JDFTX_MEMPOOL_SIZE ` to 38000 it runs out of memory.

Note that this calculation is purely for testing this issue, so please ignore that the number of folded kpoints (9 reduced to 4) is half the number of cards (8), which would be wasteful in practice.
[Untitled.txt](https://github.com/user-attachments/files/17350704/Untitled.txt)

**Comment by ColinBundschu** [comment]
Additionally this issue happens on both Polaris and Jetstream2. It seems platform independent.

**Comment by shankar1729** [comment]
Very interesting: does the crash happen right away, or after some progress through the calculation?

Does it only happen with 38000 on the 40G GPU if the calculation is large enough? That is, does a small calculation still run fine with the same MEMPOOL size?

Finally, what happens if the MEMPOOL is set just above your actual VRAM usage reported in the successful run?

**Comment by ColinBundschu** [comment]
1. The crash happens when OOM crashes typically happen: At the start of LCAO or within a few iterations of the start of the vacuum elec min. So for a long time (months) I assumed I was just out of memory, until I noticed that without it set it worked and VRAM consumption was low.
2. Calculation size matters for making this happen. A small calculation with 38000 set (<10GB VRAM) works fine and runs faster due to not needing to do memory allocations, but anything larger than 15GB VRAM is nearly certain to cause issues.
3. I will need to test this out more carefully, but in general lower values of MEMPOOL reproduce the error in the same way, so I have a hunch it is an issue with using the flag at all. That said I have only tried large values of around 30000+, so its possible 16000 might work.

**Comment by shankar1729** [comment]
Hmm, that is quite strange: maybe there is a sort of fragmentation occurring within the pooled allocator causing this issue. I can imagine that the net memory usage increases due to this, compared to directly allocating with CUDA, but a 3x higher need seems unlikely. Please do check a few intermediate MEMPOOL sizes too; hopefully there is a compromise value that allows most allocations to happen within the pool quickly, but has a margin for external allocations to cover fragmentation.

**Comment by ColinBundschu** [comment]
Ok I did a lot more testing, and I have some interesting results. The following is about the limit at 20 GB VRAM card can handle without the MEMPOOL set:

```
PROFILER:             augmentDensityGrid     0.024223 +/-     0.015364 s, 6460 calls,    156.479009 s total
PROFILER:         augmentDensityGridGrad     0.130269 +/-     0.099259 s, 3356 calls,    437.183329 s total
PROFILER:        augmentDensitySpherical     0.010723 +/-     0.010098 s, 64600 calls,    692.688805 s total
PROFILER:    augmentDensitySphericalGrad     0.011337 +/-     0.010877 s, 33560 calls,    380.460118 s total
PROFILER:                 augmentOverlap     0.014091 +/-     0.012593 s, 122320 calls,   1723.563000 s total
PROFILER:                     changeGrid     0.000638 +/-     0.000299 s, 32510 calls,     20.750032 s total
PROFILER:        ColumnBundle::randomize     0.440921 +/-     0.007479 s,   10 calls,      4.409210 s total
PROFILER:                     diagouterI     0.478478 +/-     0.041694 s, 16150 calls,   7727.414758 s total
PROFILER:              EdensityAndVscloc     0.702803 +/-     0.573104 s, 1616 calls,   1135.729069 s total
PROFILER:                     EnlAndGrad     0.039569 +/-     0.032463 s, 61320 calls,   2426.357904 s total
PROFILER:            ExCorrCommunication     0.000068 +/-     0.000142 s, 10055 calls,      0.683219 s total
PROFILER:               ExCorrFunctional     0.000887 +/-     0.000313 s, 1701 calls,      1.509174 s total
PROFILER:                    ExCorrTotal     0.060760 +/-     0.008857 s, 1701 calls,    103.352041 s total
PROFILER:                   Idag_DiagV_I     0.511145 +/-     0.038260 s, 8180 calls,   4181.167110 s total
PROFILER:                    initWeights     0.467525 +/-     0.000000 s,    1 calls,      0.467525 s total
PROFILER:                    inv(matrix)     0.020051 +/-     0.001490 s, 14930 calls,    299.362189 s total
PROFILER:            matrix::diagonalize     0.012064 +/-     0.002492 s, 24260 calls,    292.667491 s total
PROFILER:                    matrix::set     0.000095 +/-     0.000193 s, 1955348 calls,    185.869736 s total
PROFILER:            orthoMatrix(matrix)     0.018850 +/-     0.001677 s, 15080 calls,    284.262083 s total
PROFILER:     RadialFunctionR::transform     0.005981 +/-     0.006887 s,  267 calls,      1.596807 s total
PROFILER:                    reduceKmesh     0.000281 +/-     0.000000 s,    1 calls,      0.000281 s total
PROFILER:                   rhoAtom_calc     0.014864 +/-     0.016254 s, 6460 calls,     96.022400 s total
PROFILER:                   rhoAtom_grad     0.002343 +/-     0.002720 s, 32680 calls,     76.582593 s total
PROFILER:               WavefunctionDrag     2.222362 +/-     0.332772 s,   21 calls,     46.669593 s total
PROFILER:                            Y*M     0.004818 +/-     0.003313 s, 232878 calls,   1121.913732 s total
PROFILER:                          Y1^Y2     0.005479 +/-     0.003860 s, 214080 calls,   1173.026791 s total

MEMUSAGE:                   ColumnBundle    14.954438 GB
MEMUSAGE:        complexScalarFieldTilde     0.014311 GB
MEMUSAGE:                    IndexArrays     0.008022 GB
MEMUSAGE:                         matrix     0.380554 GB
MEMUSAGE:                           misc     0.053924 GB
MEMUSAGE:                     RealKernel     0.005388 GB
MEMUSAGE:                    ScalarField     0.320435 GB
MEMUSAGE:               ScalarFieldTilde     0.237083 GB
MEMUSAGE:                          Total    15.552403 GB
```

Any more and it runs out of memory. With the MEMPOOL set to 18000, it can run up to 10-10.5 GB VRAM fairly consistently, but no more under any circumstances. This ratio holds roughly true on the larger 40 GB full cards. My previous measurements where I thought I was using less of the card turned out to be wrong - the 50% mark is about where things die. 

So essentially the conclusion is that you can use the MEMPOOL if what JDFTx reports is less than 50% of the the card VRAM, and you can only run JDFTx if it reports memory usage at 75% of the card or less (closer to 80% on the full 40 GB VRAM card).

**Comment by shankar1729** [comment]
Post an example log file from these tests: let me check if there could be memory usage beyond what is reported at fault.

**Comment by ColinBundschu** [comment]
Ok here is a case that runs at the upper limit of what works with the memory pool set on a 40 GB VRAM node.
[test.txt](https://github.com/user-attachments/files/17526142/test.txt)

**Comment by ColinBundschu** [comment]
This is the largest ones I was able to get to run on a 20 GB VRAM without crashing. The Mempool is not set here.
[test.txt](https://github.com/user-attachments/files/17526170/test.txt)

**Comment by ColinBundschu** [comment]
This one runs over 4 x A100 GPUS without MEMPOOL set, but crashes if the MEMPOOL is set.
[231_nlpcm.txt](https://github.com/user-attachments/files/17526219/231_nlpcm.txt)

**Comment by shankar1729** [comment]
Alright, didn't spot anything else suspicious. It must be the fragmentation issue in the memory pool. So I'd recommend not using mempool if you're trying to squeeze large calculations, and hopefully the cuda alloc overhead is not as serious in those cases. If you do need to use mempool for speed, you could try to reduce memory consumption using `cache-projectors no` in the input, which adds some computational cost of recomputing the projectors for saving the memory (could be significant) on those.

**Comment by ColinBundschu** [comment]
When you say "could be significant," do you mean the computational cost is significant or that the memory savings is significant? Can you give me an order-of-magnitude estimate of each?

**Comment by shankar1729** [comment]
It's going to depend strongly on both the size of the calculation and the hardware you're running it on, so it would be best to just test this once with a typical calculation. I would estimate the memory requirement as about 1 - 1.5 copies of the electronic wavefunction at each k-point, compared to about 4-5 copies required for Davidson diagonalization / variational minimization (so about 20%). I have not used this on recent GPUs, so won't venture a guess on the computational cost.
