### ISSUE TITLE
JDFTx switching between two states of largely different energy due to A_diel (NonlinearPCM fluid)

### ISSUE THREAD

**Issue by ColinBundschu** [shankar1729/jdftx#364]
![image](https://github.com/user-attachments/assets/ae2357ab-74dc-464b-b304-50372683dcb6)
I am noticing on some materials that the energy seems to alternate between two different discrete states, even when the ionic positions are converged. It seems to entirely be coming from the A_diel term, which I assume is the implicit solvation model. It happens in materials with a strong Jahn-Teller effect, if that matters. Is there a way to make JDFTx converge to the lower energy state?

Here is another example that is ionically well converged:
[331_nlpcm.txt](https://github.com/user-attachments/files/17446667/331_nlpcm.txt)
![image](https://github.com/user-attachments/assets/9dc8023e-2fb6-4fae-bfb7-dc54130b0b79)
```
IonicMinimize: Iter:   0  Etot: -6783.292298721942643  grad_max:  5.662e-04  t[s]:   2400.24
IonicMinimize: Iter:   1  Etot: -6783.292944680545588  grad_max:  1.360e-04  alpha:  1.000e+00  linmin: -2.855e-04  t[s]:   3271.60
IonicMinimize: Iter:   2  Etot: -6783.409958914136951  grad_max:  4.660e-04  alpha:  1.617e-03  linmin: -5.587e-04  t[s]:   3683.08
IonicMinimize: Iter:   3  Etot: -6783.293007604630475  grad_max:  1.090e-04  alpha: 7.978e-138  t[s]:   4563.34
IonicMinimize: Iter:   4  Etot: -6783.293007763680180  grad_max:  2.931e-04  alpha:  3.000e+00  linmin: -1.021e-09  t[s]:   4602.33
IonicMinimize: Iter:   5  Etot: -6783.410124287774124  grad_max:  4.956e-04  alpha:  5.472e-01  linmin:  1.830e-03  t[s]:   4833.55
IonicMinimize: Iter:   6  Etot: -6783.293010691163545  grad_max:  2.320e-04  alpha:  3.282e-84  t[s]:   5173.18
IonicMinimize: Iter:   7  Etot: -6783.293010971133299  grad_max:  1.638e-04  alpha:  1.000e+00  linmin: -1.883e-03  t[s]:   5214.47
IonicMinimize: Iter:   8  Etot: -6783.293023017102314  grad_max:  1.085e-04  alpha:  1.617e-03  linmin: -2.038e-03  t[s]:   5917.37
IonicMinimize: Iter:   9  Etot: -6783.293023789398831  grad_max:  1.699e-04  alpha:  1.000e+00  linmin:  1.709e-03  t[s]:   6026.57
IonicMinimize: Iter:  10  Etot: -6783.410116291375743  grad_max:  4.924e-04  alpha:  6.073e-05  linmin: -9.930e-04  t[s]:   6295.19
IonicMinimize: Iter:  11  Etot: -6783.292996220496207  grad_max:  1.621e-04  alpha: 1.926e-100  t[s]:   6989.32
IonicMinimize: Iter:  12  Etot: -6783.292996785196010  grad_max:  3.215e-04  alpha:  1.000e+00  linmin: -8.305e-06  t[s]:   7085.06
IonicMinimize: Iter:  13  Etot: -6783.292997458428545  grad_max:  6.926e-05  alpha:  2.784e-03  linmin: -7.697e-04  t[s]:   7239.46
```

**Comment by ColinBundschu** [comment]
Would it make more sense to run this with SaLSA after it ionically converges?

**Comment by ColinBundschu** [comment]
I thought smearing was not needed with metal oxide systems. Am I mistaken? If they are needed, what are typical values?

**Comment by shankar1729** [comment]
Depends on whether the system turns out to be metallic or insulating. If it's insulating, don't need smearing, or can set smearing to a fraction of the gap and get the same result still.

**Comment by ColinBundschu** [comment]
Ok so I did a lot of experimenting with this, and adding smearing fixed pretty much all of my convergence issues universally. This was definitely a huge hole in my understanding.

If you have a moment to indulge me further, I have a couple of follow up questions. I have been trying a range of elec smearing (Fermi) values between 0.05-0.25 eV (2-10 times room temperature, and yes I know that JDFTx takes this input in Hartree so don't worry there). One of the things I have noticed is that a lot of previous calculations which converged with great difficulty now converge to new, lower minima smoothly. This scares me somewhat because I am unsure if these new minima are actually true minima. Of course if I really want to be sure, I could run the calc with a large smearing value, and then make sure the result is close to the calc with a smaller smearing.

But I am curious if in your experience: is it necessary in practice to do this kind of smearing test if convergence looks smooth already? Consider this run for example, where the colors indicate the forces at each ionic step (red is 1 eV/A and teal is <0.02 eV/A). My gut tells me this is good to go, but should I be wary?
![image](https://github.com/user-attachments/assets/0faecce9-b6e8-4b26-bbee-560e6f7f3990)

**Comment by shankar1729** [comment]
It may not be that they are new minima, but rather that F is lower because of the increased electronic entropy contribution (the -TS component). The smooth convergence for high smearing is of course not free: there is a higher than room T entropy contribution in the results now. Usually, these cancel out in energy differences, or one could adopt schemes like MP1 or Cold smearing to minimize the entropy contributions.

Changing the smearing to a smaller value is not recommended if your system turned out to be metallic. Essentially, the smearing and k-point resolution are linked, and trying to lower smearing at fixed k-mesh leads to numerical errors in the BZ integration. For an typical system, plot the F as a function of smearing to see an acceptable trade-off in spurious entropy contribution vs. numerical error. See inset in Fig 11 of  [J. Chem. Phys. 146, 114104 (2017)](http://doi.org/10.1063/1.4978411) for example.

**Comment by ColinBundschu** [comment]
But the energy is increased by the smearing, correct?

For example, I went and did my bulk calculations on all 125 spinel oxides with 0.05 eV smearing and without smearing. In all except 5 cases, the energy did not change by more than ~10 meV, usually ~1 meV. In the 5 exceptions, the energy was 1-3 eV lower with smearing.

I have seen similar results with slab calculations, where I am getting drops of as much as 5 or 6 eV with smearing on (I presume the dangling bonds are creating electronic states near the surface, giving these surfaces a metallic character).

In no cases did the 0.05 eV smearing increase the energy by more than 20 meV, and in 99% of cases the energy increased with smearing it was increased by ~1 meV. 

If my analysis is correct, does this not point to false minima due to a lack of smearing being the issue?

**Comment by shankar1729** [comment]
Ah, I see, you are looking at E, not F. In that case, yes, that must be that the calculations are getting stuck in a local minimum with low smearing. The high smearing case should not be introducing a "false" minimum, but rather smooth out all the local minima, making the path to the global minimum clearer.

**Comment by ColinBundschu** [comment]
Ok great that aligns with my understanding, which is that smearing makes minimization easier but at the cost of accuracy in the computer values (Lattice params and total energy). I am still a little fuzzy (pun intended) on exactly how much smearing I should use, but from what I can tell in the literature 0.05 eV is a fairly standard choice for transition metal oxides, and it seems to be improving things greatly, so I will use that. Of course a standard choice is often not a correct one...

**Comment by shankar1729** [comment]
Yes, that should be fine, and if you do use a higher than room-T smearing, use the same value across your calculation set for consistency.
