### ISSUE TITLE
Container Support for JDFTx?

### ISSUE THREAD

**Issue by ColinBundschu** [shankar1729/jdftx#379]
Does JDFTx have container support already? It would be amazing to just boot it up on any container-ready machine if possible. I saw this issue, but it seems unresolved:
https://github.com/shankar1729/jdftx/issues/52

**Comment by shankar1729** [comment]
There is a Dockerfile that was contributed as a part of https://github.com/shankar1729/jdftx/pull/351; I'm not sure how well it works with current code / on GPU supercomputers though. Regardless, it should be a good starting point.
