### ISSUE TITLE
Large energy shifts in monolayer MoS2

### ISSUE THREAD

**Issue by ciccarino** [shankar1729/jdftx#38]
Hi Shankar, 

I am trying to look at an MoS2 monolayer cell of larger size. I have noticed there are instances in which the total system energy will radically change with slight changes to the input file. These changes are sometimes not even related to the system, but instead the computational resources. I can only suspect that this may be somewhat related to the Coulomb truncation, but I am not too sure. The individual changes which seem to introduce the shift include:
* Changing the charge density cutoff from 80 to 100 hartrees (it works well at 80 hartrees, but surprisingly reverts to a much different  -8000 ha solution at 100 hartrees)
* Changing the jdftx_mempool_size by 100 MB.

I have attached the respective output files here in case they are useful.

I've tried to see if this was a pseudopotential issue but I've noticed this for both norm-conserving and ultrasoft. I was wondering if you had any thoughts on this or if I was doing something incorrectly. Thank you for your help, as always! 

Regards,
Chris

[outputs.zip](https://github.com/shankar1729/jdftx/files/2362144/outputs.zip)

**Comment by shankar1729** [comment]
Hmm, that's very strange! Any reason why you suspect Coulomb truncation? Does this never occur if you turn off Coulomb truncation?

Is the issue limited to the GPU version? Can you try running the same set on the CPU and see if you get the same answers? I'm wondering if it's a memory-related issue of some sort eg. a scary bug in the mempool manager resulting in memory over-writes.

Cheers,
Shankar

**Comment by ciccarino** [comment]
Hi Shankar,

Thanks for your suggestions. I've done some more investigating. It looks like these effects are related specifically to the Hartree energy contribution. In the file attached, the energy minimizes correctly but the total energy evaluation shows virtually zero for the Hartree energy. When I lower the mempool size by 100 MB, the problem seems to disappear. 

I remember when I've tried to do excited state fillings for other cells in the past, the Hartree energy would sometimes show nan, and was I was confused by this then. If it is that these two issues are related, then I suppose this is not an issue with Coulomb truncation (since those previous cells did not have it). But perhaps, if this is a memory related issue, it is related to the Hartree contribution specifically. 

I have yet to try this for a cpu case, but I can try both of these test cases there as well. Thanks for your help. 

Regards,
Chris

[output2.zip](https://github.com/shankar1729/jdftx/files/2371378/output2.zip)
