### ISSUE TITLE
jdftx through the ASE interface

### ISSUE THREAD

**Issue by cma0213** [shankar1729/jdftx#39]
Hi, everyone
when I use jdftx through the ASE interface to calculate the bond length of CO molecule, however, it not work, could you help me?

this is wrong message: Input parsing failed with 2 errors (run with -t for command syntax)
 
In my views, it can't add pseudopotential, however, I already modify the paths.

please tell me if you need any other information.

best wishes

[co.zip](https://github.com/shankar1729/jdftx/files/2387695/co.zip)

**Comment by shankar1729** [comment]
Thanks for pointing out this out. Indeed, the ASE interface has not been updated in a while and is incompatible with the current versions.

This has been on our to-do list for a while: any takers in the group for fixing this? It is mostly an issue with pseudopotential paths.

**Comment by ttgmichael** [comment]
The ase script just needs to be modified to such that line 161 and line 163

L161 `searchPseudo = shellO('ls %s | grep %s.%s' % (self.pseudoDir, atom, filetype))`
L163 `inputfile += 'ion-species %s/%s.%s\n' % (self.pseudoDir, atom, filetype)`

becomes 
L161 `searchPseudo = shellO('ls %s | grep %s_pbe.%s' % (self.pseudoDir, atom.lower(), filetype))`
L163 `inputfile += 'ion-species %s/%s_pbe.%s\n' % (self.pseudoDir, atom.lower(), filetype)`

I'm just using the .uspp files located in the build directory.

Though I'm curious why the pseudopotentials have to be in binary? Is there plans to support the .UPF format?
