### ISSUE TITLE
<< compiling/configuring error >>

### ISSUE THREAD

**Issue by icamps** [shankar1729/jdftx#4]
Hello,

I am trying to configure JDFTx  (v1.3.1) to be compile with compilers, MPI and MKL from Intel and with LibXC (compiled with Intel).

To do that I am using the following command line:
 `CC=mpiicc FC=mpiifort CXX=mpicxx cmake -D EnableMKL=yes -D LinkTimeOptimization=yes -D ForceFFTW=yes -D EnableLibXC=yes -D MKL_PATH=/software/intel/compiladores/composer_xe_2015.1.133/mkl -D LIBXC_PATH =/software/LIBS/LibXC ../jdftx-1.3.1/jdftx`

But I am getting the error:

```
Parse error in command line argument: -D
Should be: VAR:type=value
CMake Error: No cmake script provided.
CMake Error: Problem processing arguments. Aborting.
```

What I am doing wrong?

Regards,

Camps

**Comment by icamps** [comment]
Hi,

I found the error: an extra space between `-D LIBXC_PATH` and `=/software/LIBS/LibXC`.

**Comment by shankar1729** [comment]
I suspect your issue is the space in "-D LIBXC_PATH =/software/LIBS/LibXC"
