### ISSUE TITLE
Regarding formation energy differences between JDFTx and QE

### ISSUE THREAD

**Issue by ttgmichael** [shankar1729/jdftx#40]
Hey @shankar1729 ,

I've been comparing jDFTx energies with the ones I get from QE pwscf for the formation energy of CO and adsorption formation energies of CO on Pt(111) and Cu(111) and I get some deviation in numbers.

I tried switching between the GBRV pseudopotentials from the installation and the one at my cluster and they get the same results.

The XC functional I'm using is PBE. And I kept the elec/ rho energy cutoff to be 500eV / 5000eV. (in hartrees, 18.3746545014 183.746545014)

What I get with jDFTx is similar to the values in the example in the documentation; 

BFGS:   0  15:12:29     -591.216686       8.6057
BFGS:   1  15:15:01     -591.705210       2.9871
BFGS:   2  15:17:30     -591.735280       1.8346
BFGS:   3  15:19:59     -591.748251       0.1889
BFGS:   4  15:22:29     -591.748399       0.0123

What I get with a very similar setting in QE is:

BFGSLineSearch:   0[  0]  15:19:04     -593.902306       8.6049
BFGSLineSearch:   1[  2]  15:22:24     -594.419610       1.7779
BFGSLineSearch:   2[  4]  15:25:12     -594.434013       0.0597
BFGSLineSearch:   3[  5]  15:26:24     -594.434028       0.0044

The E components in both codes seem to only agree on E_xc (I'm not sure how to connect the others from jDFTx to pwscf.) It appears Eewald disagrees between the two codes. I'm just multiplying jDFTx hartree energies by 2 to get the rydberg values from pwscf.

 jDFTx: 
   
     Eewald =       11.1193940300900049
     EH =       28.7476069859467707
     Eloc =      -69.8132696518777323
     Enl =        3.1415972827461465
     Exc =       -5.2632552603605181
     Exc_core =        0.0987190434473193
     KE =       10.2228625447723616
-------------------------------------
     Etot =      -21.7463450252356481
     TS =        0.0000000000000001
-------------------------------------
     F =      -21.7463450252356481

**Pwscf**: 
     The total energy is the sum of the following terms:

     one-electron contribution =     -98.23791950 Ry
     hartree contribution      =      50.17414508 Ry
     xc contribution           =     -10.52677357 Ry
     ewald contribution        =      14.90045088 Ry
     smearing contrib. (-TS)   =      -0.00000000 Ry

Could you point me to a potential area I may have missed in setting up the CO calculation?

my jdftx input looks like this:

lattice \
22.676711  0.000000  0.000000  \
0.000000  22.676711  0.000000  \
0.000000  0.000000  25.038869  

elec-cutoff 18.3746545014 183.746545014
spintype no-spin
elec-smearing Cold 0.00459366362534
elec-ex-corr gga-x-pbe gga-c-pbe
davidson-band-ratio 1.1
kpoint 0 0 0 1
kpoint-folding 1 1 1

coords-type cartesian
ion C 11.338356 11.338356 11.338356 	 1
ion O 11.338356 11.338356 13.700513 	 1

ion-species ..//jdftx-1.4.2/psp/gbrv/c.upf
ion-species ..//jdftx-1.4.2/psp/gbrv/o.upf

coulomb-interaction isolated

pw.inp looks like:
&CONTROL
  calculation='relax',
  prefix='calc',
  pseudo_dir='/home/users/ttgmichael/psp/gbrv1.5pbe',
  outdir='.',
  tprnfor=.true.,
/
&SYSTEM
  ibrav=0,
  celldm(1)=1.8897261245650618d0,
  nat=2,
  ntyp=2,
  ecutwfc=36.7493237909d0,
  ecutrho=367.493237909d0,
  nbnd=15,
  occupations='smearing',
  smearing='fd',
  degauss=0.00734986475817d0,
  input_dft='PBE',
/
&ELECTRONS
  diagonalization='david',
  conv_thr=7.34986475817e-08,
  mixing_beta=0.7d0,
  electron_maxstep=100,
  conv_thr=7.34986475817e-08,
/
&IONS
  ion_dynamics='ase3',
/
CELL_PARAMETERS
   20.000000000000000d0     0.000000000000000d0     0.000000000000000d0
    0.000000000000000d0    21.250000000000000d0     0.000000000000000d0
    0.000000000000000d0     0.000000000000000d0    20.000000000000000d0
ATOMIC_SPECIES
C1 12.011d0 C.UPF
O1 15.9994d0 O.UPF
ATOMIC_POSITIONS {crystal}
C1       0.500000000000000d0     0.470588235294118d0     0.500000000000000d0
O1       0.500000000000000d0     0.529411764705882d0     0.500000000000000d0
K_POINTS automatic
1 1 1 0 0 0

**Comment by shankar1729** [comment]
This is a convention difference between JDFTx and QE on how the internal (partial) core energies are handled. In JDFTx, the partial core energy (Exc_core) is subtracted from the total energy. Since this is a constant per atom, this does not affect energy differences. (We may switch this to make it more consistent with other codes in the next major version change (i.e. in 2.x).) You can see that the forces are very similar between the two codes.

The remaining components are probably disagreeing because of Coulomb truncation in JDFTx vs not in QE. For systems without net charges and dipoles, the total energy will be similar between these cases, but the breakup into Hartee, Ewald etc. will differ.

Best,
Shankar
