### ISSUE TITLE
phonons in hBN

### ISSUE THREAD

**Issue by ciccarino** [shankar1729/jdftx#42]
Hi Shankar,

Thanks for your suggestion. I have relaxed the lattice to account for the new symmetry, and stuck with testing the monolayer case for computational efficiency. I have found that the system is still showing imaginary frequencies, unfortunately. The system generally has some difficulty in minimizing grad_K, and will instead converge with the Etot criteria. I've tried removing the energyDiffThreshold and still the grad_K will not effectively minimize below 1e-4. Perhaps this could be related to the imaginary frequencies, however the system does find the lower symmetry structure from the original hexagonal lattice. I was wondering if you had any more thoughts as to what could be causing this issue.

Thank you very much for your help.
[CBVN-sevens.zip](https://github.com/shankar1729/jdftx/files/2501963/CBVN-sevens.zip)

Regards,
Chris

**Comment by ciccarino** [comment]
Hi Shankar,

Hmm yep I have looked at the eigendisplacements and they look to be certainly out of plane and defect-related. I have attached the xsf files here. It seems like it wants to buckle. 

Regards,
Chris
[imagFreqModes.zip](https://github.com/shankar1729/jdftx/files/2502638/imagFreqModes.zip)

**Comment by shankar1729** [comment]
Oh ok, ionic minimize would not allow those displacements due to symmetries. So introduce a slight displacement along these eigen-directions to break the z reflection symmetry, and then re-relax the structure. Hopefully that should get rid of the imaginary frequencies.

Best,
Shankar

**Comment by ciccarino** [comment]
Hi Shankar,

The new results show no imaginary mode at -50 meV, only very slight instabilities (on the order of fractions of meV), so I think this out-of-plane distortion was the main issue. Thank you very much for your help.

Regards,
Chris

**Comment by shankar1729** [comment]
Hi Chris,

That's great - glad to hear that it worked out!

Best,
Shankar
