### ISSUE TITLE
About adsorption energy

### ISSUE THREAD

**Issue by casstudent** [shankar1729/jdftx#46]
Hi Shankar，
      Recently I used JDFTx to calculate species adsorbed on metal surface. I have some problems and need your help.
      In output files we got Etot, F(Helmholtz free energy) and G(grand free energy,if target-mu).  As you mentioned in the tutorial, F should be used when calculated surface energy. Which one should we use when calcutate adsorption energy? 
     Shall we use F again ,or Etot as usual？
     If the slab is charged，shall we use G to calculate adsorption energy？
     Thank you very much!

**Comment by shankar1729** [comment]
Always use the variational free energy of the given calculation for property predictions, as far as possible. So Etot if no smearing, F with smearing and G in fixed-potential calculations. Also make sure that any energy difference you calculate always involves (free-)energies of the same type, adding muN or TS terms for adsorbates as appropriate. Please refer to our grand canonical DFT JCP paper from last year for a longer explanation.

Cheers,
Shankar
