### ISSUE TITLE
How to speed up the convergence?

### ISSUE THREAD

**Issue by ximik69** [shankar1729/jdftx#47]
Hi dear Shankar.

I'd like to ask you how to speed up the convergence?

I often face the following convergence issues - E steadily decreases, |grad|_K and SubspaceRotationAdjust oscillate and I need enormous number of cycles to converge to EnergyDiffThreshold 1e-8. There are XC functionals, that show such behaviour more often, like TPSS, orbGLLB-SC, maybe SCAN. But I often face convergence issues with GGA PBE. Just a few days ago I spent 15 hours for ElecMinimize with GGA PBE on Mg-transition metal compound, in contrary ElecMinimize took only 5h using SCAN with similar compound.

Facing problems with convergence, I often see similar messages:
ElecMinimize: 	Predicted alpha/alphaT>3.000000, increasing alphaT to 1.242439e-01.
ElecMinimize: 	Wrong curvature in test step, increasing alphaT to 3.094212e-02.
ElecMinimize: 	Undoing step.
ElecMinimize: 	Step failed: resetting search direction.

Convergence problems are with bulk, slabs, regardless of containing transition elements, etc. Thus they are not connected with some particular type of objects.

What settings could you advice me for electronic-minimize? 
K-point folding?
Ecutoff?
I use mostly SG15 PPs, as they support wider range of functionals.

Here I submit output for several calculations for magnesium, XC SCAN. I just wanted to test it on simple objects.

Best wishes,
Igor.
[X.zip](https://github.com/shankar1729/jdftx/files/2653039/X.zip)

**Comment by shankar1729** [comment]
Hi Igor,

These all seem to be metallic calculations without smearing. Very likely adding elec-smearing will fix your convergence issue. 

Best,
Shankar

**Comment by ximik69** [comment]
Ok, thank you for pointing this out. Actually, I've forgotten to set it up. I used elec-smearing for 10*300K for calculations of DOS. But here for energies of reactions, I wanted to calculate with smearing for 300K and forgot to set it up.
I hope that it will help.

Best wishes,
Igor.

**Comment by ximik69** [comment]
Small addition - setting elec-smearing for 300K did not completely eliminate slow convergence, but made good progress instead.

Best wishes,
Igor.

**Comment by shankar1729** [comment]
Hi Igor,

For the k-point samplings you are using, smearing will need to be about an order of magnitude higher. You should try to use cold smearing instead of Fermi if you are worried about the elevated electronic entropy.

Best,
Shankar

**Comment by ximik69** [comment]
Ok, thanks a lot.
Best wishes,
Igor.
