### ISSUE TITLE
meta-gga or hybrid functionals

### ISSUE THREAD

**Issue by pmmargl** [shankar1729/jdftx#51]

**Comment by pmmargl** [comment]
Thanks! That was quick!

My reason for trying to use JDFTx is because I need accurate solvation treatment of ions in hydrocarbon solution (=gasoline). Can you recommend a webpage/tutorial that would help me get started in that direction? I see there are quite a few solvents already predefined in JDFTx, but I’m not seeing anything that is close to e.g. n-hexane.

Again, thanks for your help!
pmm

**Comment by shankar1729** [comment]
I see: as far as I can remember, none of our solvents resemble that, as most were parametrized for electrochemical / battery applications. Parametrizing a simple solvation model like GLSSA13 shoudln't require too much data though: it will require a handful of expt solvation free energies from literature and corresponding calculations done with manually altered parameters (using pcm-params). You could give that a shot and discuss the fitting part here if you are able to find the data.

Best,
Shankar

**Comment by pmmargl** [comment]
Thank you!
