### ISSUE TITLE
gpu_jdftx singularity container build

### ISSUE THREAD

**Issue by gvarnavi** [shankar1729/jdftx#52]
Hey Shankar,

Hope all is well!
I've being trying to build jdftx inside a [Singularity container](https://www.sylabs.io/docs/) (mostly for reproducibility, but also to facilitate compiling in certain clusters w/o module support etc).
I've successfully built container images with cuda (+openmpi, hdf5, fftw, mkl) which compile and run properly on _one_ GPU. I.e. if I were to run  `srun -N1 -n2 -c1 --gres=gpu:2 singularity exec --nv jdftx-image.simg jdftx_gpu -ni totalE.in`[1,2], I can 'see' all the available GPUs, yet jdftx_gpu selects to only use one of them (output below bolded for emphasis):

_Executable jdftx_gpu with command-line: -ni totalE.in
Running on hosts (process indices):  seasdgx101.rc.fas.harvard.edu (0)
Divided in process groups (process indices):  0 (0)
gpuInit: Found compatible **cuda device 0 'Tesla V100-SXM2-16GB'**
gpuInit: Found compatible **cuda device 1 'Tesla V100-SXM2-16GB'**
gpuInit: Selected device 0
Resource initialization completed at t[s]:      1.14
**Run totals: 1 processes, 1 threads, 1 GPUs**_

I was wondering if I need to specify any compilation options explicitly so that it uses all available GPUs?

Cheers,
George

[1] Not sure how familiar you are with with singularity containers, so here's a brief workflow just in case - and I'm obviously happy to provide more details on this:
So to build a singularity image one would run (either on the cluster directly or to a workstation/laptop with sudo privileges)  `sudo singularity build jdftx-image.simg singularity-recipe`, where the singularity recipe is a text file with the compile script (including things like apt-get install commands, and wget of packages etc). I've attached my recipe file here [singularity-recipe.txt](https://github.com/shankar1729/jdftx/files/2891301/singularity-recipe.txt).
[2] The --nv flag loads the nvidia drivers on the host. This step works properly (as seen by commands like `singularity exec --nv jdftx-image.simg nvidia-smi -L`
[3] I'm debugging this on a DGX1 machine (8 GPUs with cuda_code=sm_70)

**Comment by shankar1729** [comment]
Hi George,

That is the GPU being selected by process 0. You need to use two MPI processes and check the log of the second process (--mpi-debug-log or -m) to confirm that the second GPU is being used as well. 

You seem to have specified -n 2, yet it ran with one process only. You might need to debug that part (not specific to jdftx) first.

Best,
Shankar

**Comment by gvarnavi** [comment]
Hey Shankar,

Pardon the delayed response.
Yes, it turned out to be an mpi integration thing. Singularity uses an 'outside-in' implementation for mpi + containers, so version (+ config options) matching of openmpi inside and outside of the container did the trick. In case it's helpful for anyone, we pulled the current ompi from the master branch (v3.1), and configured using --with-cuda, --with-slurm and --with-pmi.

Cheers,
George

**Comment by ColinBundschu** [comment]
Did you ever get this container working, and if so, is it available?
