### ISSUE TITLE
How to read the file Dtot？

### ISSUE THREAD

**Issue by casstudent** [shankar1729/jdftx#54]
Hi shankar,
      I want to draw a picture about electrostatic potential along the z direction. So I used the conmand "dump Dtot" in the input file and got an output file named ****.dtot but I can't open it. Can you teach me how to open it on a windows operating computer?
     Thank you for your help!

**Comment by shankar1729** [comment]
See this tutorial:

http://jdftx.org/OxideSurfaces.html

It demonstrates how to read the 3D potential file and plot a planar average (using either python or octave/matlab).

Best,
Shankar
