### ISSUE TITLE
dos output file in JDFTx and DOSCAR in VASP

### ISSUE THREAD

**Issue by Wangfeiteng1** [shankar1729/jdftx#55]
Dear Shankar,

In the helper script part, you provide a script to transform the charge file into CHGCAR. I am wondering if it is theoretically possible to transform the dos output file into DOSCAR in VASP? Does  the dos output file has all the message the DOSCAR needed? 

Best,
Woffett

**Comment by shankar1729** [comment]
Hi Woffett,

I have not looked into the DOS format of VASP, but it should be possible to convert the dos output to the DOSCAR format. Note that the CHGCAR output script reads not only the density file output by JDFTx, but also the output file to extract any additional information required. Correspondingly, we can collect any additional information required beyond the .dos* files from the log file.

I don't know how involved this would be and how much time it would take to develop. If there are any volunteers to figure out the DOSCAR format specification and adapt the createVASP script to handle DOS output, I'd be happy to help.

Best,
Shankar
