### ISSUE TITLE
What does Sample count mean？

### ISSUE THREAD

**Issue by casstudent** [shankar1729/jdftx#57]
Hi Shankar,
      I have already read the tutorial "oxide surface" but I still have some problems to be solved.
      In the python script you offer, I don't know what **Sample count** means. How can we find the sample count in our own system?

      S = [ 56, 28, 160 ]            #Sample count
      L = [ 12.26123, 5.59, 33. ]    #Lattice vector lengths (bohrs)

Thank you for help!

**Comment by shankar1729** [comment]
The sample count S refers to the number of grid points per dimension used in the fast fourier transfom. In the code output, search for the line that contains "Chosen fftbox size, S = [ ... ]".

Best,
Shankar
