### ISSUE TITLE
A problem about MPI

### ISSUE THREAD

**Issue by Yanhuanjin** [shankar1729/jdftx#58]
Hi Shankar,

I compiled the JDFTx on my own computer, and it could run the _water example_ well if I used only one computer core. However, when I use two cores or more to run JDFTx, the package went wrong and I could not get the right answer. 
I notice that the first line it went wrong goes like this, "`LCAOMinimize:   Test step failed with Etot = nan, reducing alphaT to 1.000000e-01.`", followed by many "nan". Can you help me?

Best,
Daniel

**Comment by shankar1729** [comment]
Hi Daniel,

This seems very strange. Could you please post an example output file showing this behavior? Also, what operating system, jdftx version and compilation options (eg. which blas, fft libraries etc.) did you encounter this with?

Best,
Shankar

**Comment by Yanhuanjin** [comment]
Hi Shankar,

Thank you for your reply. Here are two files containing information of STDOUT and JDFTx output. The operating system is CentOS 7.6, JDFTx version 1.4.2, compiled with gcc and openmpi. (I am not sure with the libraries...)

[STDOUT.txt](https://github.com/shankar1729/jdftx/files/3275554/STDOUT.txt)
[water_out.txt](https://github.com/shankar1729/jdftx/files/3275555/water_out.txt)

Best,
Daniel

**Comment by shankar1729** [comment]
Glad to hear that!
