### ISSUE TITLE
Does JDFTx support transition state calculations?

### ISSUE THREAD

**Issue by Yanhuanjin** [shankar1729/jdftx#59]
Hi Shankar,

Does jdftx have built-in _Transition State(TS)_ search modules? I want to use jdftx to calculate the transition state of some reactions, however, I did not see any examples in the online manuals. Where can I find some examples? Thank you.

Best,
Daniel

**Comment by shankar1729** [comment]
Hi Daniel,

This is not a built-in functionality within JDFTx, but can be achieved using the ASE interface. Please see http://jdftx.org/ASE.html and the nudged elastic band tutorials in the ASE website; you can drop in JDFTx as a calculator there.

Best,
Shankar

**Comment by Yanhuanjin** [comment]
Hi Shankar,
I got it, thank you very much.
Best,
Daniel
