### ISSUE TITLE
ASE Interface ERROR

### ISSUE THREAD

**Issue by Yanhuanjin** [shankar1729/jdftx#60]
Hi Shankar,

I installed ASE and tried to run it using JDFTx as a calculator, however, mpirun could not work. 
`mpirun -n 2 python3 ASE_INPUT.py 2>&1 | tee print-out`
The error messages (print-out) looks like following:

> [cli_0]: write_line error; fd=16 buf=:cmd=init pmi_version=1 pmi_subversion=1
> :
> system msg for write_line failure : Bad file descriptor
> [cli_0]: Unable to write to PMI_fd
> [cli_0]: write_line error; fd=16 buf=:cmd=barrier_in
> :
> system msg for write_line failure : Bad file descriptor
> [cli_0]: write_line error; fd=16 buf=:cmd=get_ranks2hosts
> :
> system msg for write_line failure : Bad file descriptor
> [cli_0]: expecting cmd="put_ranks2hosts", got cmd=""
> Fatal error in MPI_Init: Other MPI error, error stack:
> MPIR_Init_thread(784): 
> MPID_Init(1276)......: channel initialization failed
> MPID_Init(1583)......: PMI_Init returned -1
> Traceback (most recent call last):
>   File "test.py", line 13, in <module>
>     commands={'elec-cutoff' : '20 100'}
>   File "/home/users/yhjin/example/jdftx/ase/JDFTx.py", line 52, in __init__
>     self.template = str(shell('%s -t' % (self.executable)))
>   File "/home/users/yhjin/example/jdftx/ase/JDFTx.py", line 15, in shell
>     return subprocess.check_output(cmd, shell=True)
>   File "/home/users/yhjin/python3/lib/python3.6/subprocess.py", line 356, in check_output
>     **kwargs).stdout
>   File "/home/users/yhjin/python3/lib/python3.6/subprocess.py", line 438, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '/data/software/apps/jdftx-master/jdftx/build/jdftx -t' returned non-zero exit status 1.

It is worth mentioning that, a non-mpirun job could be done with no errors, so the problem comes from the mpi.
The JDFTx was compiled with the configuration like  `CC=/home/apps/intel/impi/5.0.3.049/intel64/bin/mpiicc CXX=/home/apps/intel/impi/5.0.3.049/intel64/bin/mpiicpc cmake -D EnableMKL=yes  -D ForceFFTW=yes  MKL_PATH="$MKLROOT" -D`

Best,
Daniel

**Comment by shankar1729** [comment]
Hi Daniel,

As mentioned in the AS-JDFTx interface page, add mpirun in the calculator line eg.

        calculator = JDFTx(executable='mpirun -n Nprocs /path/to/jdftx')

instead of running python with mpi. Also make sure that the mpirun used above is compatible with teh one you used to compile jdftx, supplying a full /path/to/mpirun if needed.

Best,
Shankar

**Comment by Yanhuanjin** [comment]
Hi Shankar,

Wow~, it works, thank you very much. 
Thank you!

Best wishes,
Daniel

**Comment by shankar1729** [comment]
Glad to hear that worked!
