### ISSUE TITLE
Truncation boundary.

### ISSUE THREAD

**Issue by jayuw** [shankar1729/jdftx#61]
Hi Shankar

I am trying to run ionic optimisation for an amorphous surface, but always end up failing with this error: Atom 28 lies within the margin of 5 bohrs from the truncation boundary.
Expand unit cell, or if absolutely sure, reduce coulomb-truncation-ion-margin.

Do you have any idea on what should I do? I have decreased the margin up to 1 bohr, but the issue remains.

In that case, should I use coulomb interaction periodic or slab 001? (knowing that my structure is amorphous)

The issue is gone if I don't use the coulomb interaction. What would be the significance of using this setting for interface calculation?

Regards,
Jay

**Comment by shankar1729** [comment]
This probably means that during ionic relaxation, your system is distorting and pushing atoms too close to the truncation boundary (assuming it didn't happen at your initial geometry). 

Coulomb truncation effectively breaks translation invariance along one or more directions, so it is important to make sure your system does not cross the boundary where the unit cell is effectively cut. Make sure your coulomb-truncatoin-embed <center> is set appropriately for your geometry. 

The advantage of using truncation, of course, is that you will have no interactions with periodic images along truncated directions, which can be quite important for systems with significant charge  distributions, especially such as ones with net dipoles.

**Comment by jayuw** [comment]
Thanks for your prompt reply and for a detailed explanation. If I may ask further on the technical aspect, how to adjust the coulomb-truncation-embed? Is it by defining the origins in z-axis?

I obtained the structure from VASP, and I transformed it to input files for JDFTx using xyzToIonpos code (from xyz) without centerBox option (as I have amorphous structure). I also considered Bohr and cartesian coordinate in the input files. However, the issue remains, could you please help me on this?
I really appreciate for your help.

**Comment by shankar1729** [comment]
Yes, you should set the embed center to the center of your z range. I would recommend centering your atoms around zero and using embed center to 0 0 0 .You could use centerBox to achieve this in xyzToIonpos, provided the xyz file has all the atoms together without being wrapped in periodic boundaries. If you attach your xyz file and ionpos/lattice files, I can take a look.

**Comment by jiangyimin123456** [comment]
[xxx}$ xyzToIonpos water.xyz  yes
# Ionic positions in cartesian coordinates:
ion  O   0.000000000000000   0.000000000000000   0.600543636422734  0
ion  H   0.000000000000000   1.432393534717671  -0.600543636422733  1
ion  H   0.000000000000000  -1.432393534717671  -0.600543636422733  1
Offseting atoms by ( -0.000000000000000 -0.000000000000000 0.360325425963175 ) bohrs
Bounding box x: [ 0.000000000000000 to 0.000000000000000 ] bohrs
Bounding box y: [ -1.432393534717671 to 1.432393534717671 ] bohrs
Bounding box z: [ -0.600543636422733 to 0.600543636422733 ] bohrs
 [xxx}$ xyzToIonposOpt water.xyz 15
nConfigs =  1
initialVolume =  4341.4
error: fun(0): subscripts must be either integers 1 to (2^63)-1 or logicals
error: called from
    fminsearch>nmsmax at line 275 column 8
    fminsearch at line 165 column 25
    .tmp.m at line 43 column 8


Dear Shankar, the output when I use xyzToIonposOpt and xyzToIonpos is shown above. There is an error in xyzToIonposOpt, but I know the reason for this error, I really appreciate for your help.

**Comment by shankar1729** [comment]
This is likely an Octave compatibility issue with certain versions of octave. If you are able to try a different octave version, that would be best. Additionally, you should for the most part be able to do without this script, since it's only advantage over xyzToIonpos is that it also finds the best rotation to pack a molecule into the box (a niche use case).

**Comment by Acheulian** [comment]
Hi Shankar
I am currently trying to use JDFTX for surface fixed potential calculation. After seeing the above communication, I realized that I should set the position of my Coulomb truncation center reasonably. However, the task prompt reported an error stating that atom 58 is located near 1Bohrs of the Coulomb truncation center. But I am not sure how to set the corresponding parameters. Could you please help me ? Here is my structure CONTCAR and the set parameters .Atom 58 is the surface N atom

[CONTCAR.txt](https://github.com/user-attachments/files/20015100/CONTCAR.txt)

include contcar.lattice   #晶胞参数，每一列代表一个晶格矢量，原子单位制Bohr

include contcar.ionpos   #原子坐标

coords-type Lattice   #分数坐标，默认为笛卡尔坐标Cartesian

#赝势

#GBRV超软赝势，用$ID代替任意元素，优先使用v1.2版赝势，如果没有该元素再用v1版赝势

ion-species GBRV/$ID_pbe_v1.2.uspp

ion-species GBRV/$ID_pbe_v1.uspp

kpoint-folding 1 1 1   #n×n×n K点，默认 1 1 1
kpoint 0 0 0  1.        #K点位移，默认Gamma centered

spintype z-spin   #自旋极化，z-spin = up/dn polarization (non-relativistic spin)
elec-ex-corr gga-PBEsol

elec-cutoff 20 100

coulomb-interaction Slab 001
coulomb-truncation-embed 0 0 0
coulomb-truncation-ion-margin 3    
elec-smearing Fermi 0.01

#溶剂模型参数
fluid LinearPCM
pcm-variant CANDLE
fluid-solvent H2O
fluid-cation Na+ 1.
fluid-anion F- 1.

#外加电极电势：
#target-mu -0.171252  # U = 0.00V vs SHE (4.66V)，1Hartree = 27.2114eV

#target-mu -0.189626  # U = +0.5V vs SHE

#target-mu -0.208001  # U = +1.0V vs SHE

#target-mu -0.226376  # U = +1.5V vs SHE

#target-mu -0.152877  # U = -0.5V vs SHE

#target-mu -0.134502  # U = -1.0V vs SHE

#target-mu -0.116128  # U = -1.5V vs SHE


#输出
dump-name common.$VAR      #This will overwrite outputs from successive runs
initial-state common.$VAR  #This will initialize from the preceding calculation
dump End State BoundCharge
#mv common.nbound Charged$mu.nbound

**Comment by shankar1729** [comment]
Your atoms seem to be ranging from around 0.02 to 0.52 in fractional coordinates along z. Consequently, your goemetric center for truncation in z should be ~ 0.27 (do this precisely if your slab is symmetric; see #402 for a recent discussion on this matter).
