### ISSUE TITLE
Atoms are too close, have overlapping pseudopotential cores

### ISSUE THREAD

**Issue by Yanhuanjin** [shankar1729/jdftx#62]
Hi Shankar，
I used the output file of VASP and wanted do a fix potential calculation, and it worked well for Orthorhombic systems. However, for Hexagonal system, it kept warning me like this 
"O #22 and H #41 are closer than the vector-sum of their core radii..."
"Atoms are too close, have overlapping pseudopotential cores."
I am sure that the item "coords-type cartesian"  was writen in my input file. I also write a Python script to check the each two atoms' distance in file `structure.in`, and it shows that all of them have a safe distance larger than 1.7 bohr. 

```
import math
import re

regex = re.compile("\s+")
count = 0
with open("structure.in", "r") as f:
    lines = f.readlines()

for i in range(1, len(lines)):
    # x, y, z
    check_point_1 = regex.split(lines[i])[2:5]
    for j in range(len(lines)-1, i, -1):
        check_point_2 = regex.split(lines[j])[2:5]
        sub_x = (float(check_point_1[0]) - float(check_point_2[0]))
        sub_y = (float(check_point_1[1]) - float(check_point_2[1]))
        sub_z = (float(check_point_1[2]) - float(check_point_2[2]))
        distance_square = sub_x**2 + sub_y**2 + sub_z**2
        distance = math.sqrt(distance_square)
        count += 1
        if distance < 1.7:
            print(check_point_1, check_point_2)
            print(distance)
print("Total checked: %d" % count)

>> Total checked: 6216
```
and my common input file,
```
coords-type cartesian
include lattice.in
include structure.in

ion-species GBRV/$ID_pbesol.uspp
elec-ex-corr gga-PBEsol
elec-cutoff 20 100

kpoint-folding 3 3 1
elec-smearing Fermi 0.01

fluid LinearPCM
pcm-variant CANDLE
fluid-solvent H2O
fluid-anion Cl- 1.
fluid-cation Na+ 1.

dump-name common.$VAR      #This will overwrite outputs from successive runs
initial-state common.$VAR  #This will initialize from the preceding calculation
dump End State BoundCharge
```
lattice.in file,

```
lattice\
Hexagonal\
14.132143332139153\
41.669812444250702
```

So, where is the problem?

Daniel

**Comment by shankar1729** [comment]
Hi Daniel,

Lattice vectors are in columns in jdftx, so transpose your matrix.

Best,
Shankar

**Comment by Yanhuanjin** [comment]
Hi Daniel,

Do you mean writing like this?
`lattice Hexagonal 14.132143332139153 41.669812444250702`
The problem still exits.

Best,
Daniel

**Comment by Yanhuanjin** [comment]
And my structure.in file
ion H 6.030270930701951 1.321724085810525 8.516402008104656 1
ion H 3.907681989149282 3.492256296286290 9.570818672722641 1
ion H 2.560948337923501 5.830702837729405 9.973781687076174 1
ion H 4.760444849483588 0.916391289975681 9.985802024958618 1
ion H -2.839612612396849 6.003352229475496 10.286829565970420 1
ion H 1.099090843573354 0.662436211583397 10.364101418078766 1
ion H 6.332817889381616 0.768088582405514 10.635135190968436 1
ion H -1.922495225469856 4.273392957188491 10.683837872355372 1
ion H -0.034434538360744 6.350541297380658 10.777984378245742 1
ion H 4.778416921895000 5.128142077726417 11.002070262401624 1
ion H 5.523757897736709 2.655877094222236 11.222962552076467 1
ion H 3.768911973819974 7.100116764823168 11.242768888150023 1
ion H -0.462915398561745 5.146112218703119 12.009465951586231 1
ion H 7.393160627202342 0.211028169764977 12.565583237836996 1
ion H 5.550257079521487 3.559378498099568 12.605550619516716 1
ion H 2.466187558835705 0.525232888417796 14.441077729148411 1
ion H 1.938488482436135 4.279370689616615 14.465292994487639 1
ion H 0.352355162800721 4.299981017602284 14.484935673044726 1
ion H 4.048817734901142 0.513507499557992 14.487395986285971 1
ion H 4.680945882206360 4.290195234821303 14.536937719261132 1
ion H -0.256156840741315 0.604181001057992 14.545592821356175 1
ion H -2.338765512725082 4.296234035397221 14.559062167215043 1
ion H 6.764608177876670 0.565770231502393 14.628882458610324 1
ion H 1.114302780793326 2.344765603796183 14.709734109164383 1
ion H -1.055003024410936 6.071588895313574 14.748820005092295 1
ion H 3.318832873142620 6.044511728709840 14.810698533037399 1
ion H 5.446166865128418 2.286649115040693 14.847467250734020 1
ion H 1.106853569744373 1.424551366722103 16.048629671414893 1
ion H -1.037138792948244 5.134197923571501 16.085633221950079 1
ion H 3.329957194807416 5.095139240074460 16.113451059751210 1
ion H 5.408682438703847 1.356997011193215 16.164423453123845 1
ion H 1.894172892457804 0.887254040627842 18.196398193390689 1
ion H 4.620848235907697 0.859003174674226 18.214230215631936 1
ion H 0.297933343139717 0.890222041898325 18.219084239756537 1
ion H -0.238114816120448 4.616759399895763 18.226944087998675 1
ion H 6.227966693651964 0.849572490535919 18.228426823614754 1
ion H -1.836227149993624 4.600973172333735 18.233578310654970 1
ion H 2.493317746919032 4.598336773301958 18.246146007395410 1
ion H 4.093999711746665 4.593682060360772 18.263746785903770 1
ion H -1.053216656947398 6.568308713083151 18.430353792684496 1
ion H 1.105625089029197 2.839862409050799 18.480300593917544 1
ion H 5.445694542846182 2.808352057400028 18.481408089578292 1
ion H 3.277329660106008 6.558388630857759 18.483363246195772 1
ion H 3.292744374441582 0.057328254549796 19.715604751373007 1
ion H 7.537727038905736 0.043969079626227 19.772580276600049 1
ion H 1.102428775783843 3.788301956846906 19.786432322764416 1
ion H 5.468527822291887 3.729978898093735 19.796773721991109 1
ion C 2.873161221275084 3.616781760987261 9.868872514192079 1
ion C 2.178090781431516 4.826210150908467 10.086145963009457 1
ion C 2.041622026002229 1.175864142860359 10.106770326863906 1
ion C 1.982075827140254 2.590154045202937 10.163743851540389 1
ion C 0.915294564010165 4.482072038006803 10.534339657311246 1
ion C -0.256714120132026 5.290283971097873 10.935096126536539 1
ion O 3.058774475709180 0.517793450479600 9.771374495067331 1
ion O 5.677115934147903 1.306432627319331 10.019393598113250 1
ion O -1.389212494373656 4.932475141790856 10.140632867309577 1
ion O 4.834928260668853 5.995453434745762 10.531598182956772 1
ion O 0.779189505070394 3.135996940079812 10.578559831950297 1
ion O 7.367529055708286 0.229086082213438 11.562910875381153 1
ion O 5.555466945288145 3.568294479909463 11.596208694461195 1
ion O 1.136450374933563 3.798250211342171 14.126404226596071 1
ion O 3.264875747575894 0.013031573422704 14.131954635810350 1
ion O 5.491590193275218 3.779730415313293 14.222873526504058 1
ion O 7.564476507087488 0.089584509307605 14.241260964535401 1
ion O 1.095206824980583 1.379896646772127 15.060378623477513 1
ion O -1.043343911431956 5.101176448004155 15.095535817841807 1
ion O 3.350829365851725 5.080681106225008 15.121939385625549 1
ion O 5.420551358930825 1.328398935574945 15.170257998372302 1
ion O 1.091801428260685 1.394427463803380 17.875167813116075 1
ion O -1.043599571574510 5.105223328897150 17.882947637329220 1
ion O 5.430692716841638 1.360276355363887 17.893558305942371 1
ion O 3.298770145953927 5.092599426503985 17.910455119407835 1
ion O 3.264534115058634 0.071576707601524 18.730356893132928 1
ion O 7.574525082066563 0.058078226014424 18.787604721218344 1
ion O 1.118333477182684 3.814220811848527 18.801722607310623 1
ion O 5.452901213767468 3.778787015048186 18.812442683580731 1
ion Ag 5.756908451065000 -0.000000000000000 0.000000000000000 0
ion Ag -1.439205523158855 2.492777088646500 0.000000000000000 0
ion Ag 1.439205525776144 2.492777088646500 0.000000000000000 0
ion Ag 4.317702927906145 2.492777088646500 0.000000000000000 0
ion Ag -2.878454222915172 4.985628961353500 0.000000000000000 0
ion Ag -0.000043173980172 4.985628961353500 0.000000000000000 0
ion Ag 2.878454228149828 4.985628961353500 0.000000000000000 0
ion Ag -4.317659746074027 7.478406050000000 0.000000000000000 0
ion Ag -1.439248697139027 7.478406050000000 0.000000000000000 0
ion Ag 0.000000000872430 1.661851392431000 2.350164548167200 0
ion Ag 2.878411049807430 1.661851392431000 2.350164548167200 0
ion Ag 5.756908451937430 1.661851392431000 2.350164548167200 0
ion Ag -1.439248698883887 4.154703265138000 2.350164548167200 0
ion Ag 1.439162350051113 4.154703265138000 2.350164548167200 0
ion Ag 4.317659752181114 4.154703265138000 2.350164548167200 0
ion Ag -2.878454222042742 6.647480353784500 2.350164548167200 0
ion Ag -0.000043173107742 6.647480353784500 2.350164548167200 0
ion Ag 2.878454229022258 6.647480353784500 2.350164548167200 0
ion Ag 7.209326887631402 0.805901218889558 4.700962472383546 1
ion Ag 4.323125582023263 0.795584538521588 4.702656987373365 1
ion Ag 2.889891790862639 3.290476283632693 4.702949168747300 1
ion Ag 5.775710084623503 3.298789033332044 4.708171006743860 1
ion Ag 1.449456822857611 0.796288968213405 4.714987291562807 1
ion Ag 4.323286790602323 5.788619347094222 4.715133185381045 1
ion Ag -1.432054724227015 5.790829282415459 4.719836651278915 1
ion Ag 1.443449258781114 5.800346895515777 4.725683997786063 1
ion Ag -0.011999650310739 3.287177904772321 4.732153696222777 1
ion Ag 1.438315170531585 2.440093065819980 7.037808361540394 1
ion Ag 4.342038627348022 2.443105837719957 7.038874989299409 1
ion Ag 2.878616240857916 4.935973061485667 7.047442374865425 1
ion Ag -0.006396546991818 4.929265612294820 7.078979649607475 1
ion Ag 4.329875928025574 7.423858032498697 7.078684402104527 1
ion Ag 5.764486071734743 4.937463226114833 7.080997874405488 1
ion Ag -1.423426371634729 7.425556577879479 7.085400998535400 1
ion Ag 1.462399544098964 7.441022162963913 7.105168844435154 1
ion Ag 7.187168373889905 2.415816176635529 7.175311303390003 1

**Comment by Yanhuanjin** [comment]
Hi Shankar,

I know where problem happens, just because I write my own script and the space can not be read by jdftx correctly. Anyway, thank you .

Best,
Daniel
