### ISSUE TITLE
Need to Update Compiling Instructions

### ISSUE THREAD

**Issue by TiffanyAnn** [shankar1729/jdftx#64]
This is an issue with the online documentation rather than the code itself. 
Compilation fails when following the instructions on the website for building on NERSC systems (http://jdftx.org/Supercomputers.html) and results in the following error:

```
-- Found GSL: /usr/common/software/gsl/2.1/gnu/lib/libgsl.a
-- Found MKL:
/opt/intel/mkl/lib/intel64/libmkl_intel_lp64.a;/opt/intel/mkl/lib/intel64/libmkl_sequential.a;/opt/intel/mkl/lib/intel64/libmkl_core.a
CMake Error at CMake-Modules/FindFFTW3.cmake:34 (message):
Could not find FFTW3 headers (Add -D FFTW3_PATH=<path> to the cmake
commandline for a non-standard installation)
Call Stack (most recent call first):
CMakeLists.txt:75 (find_package)
```

The issue is that the instructions online say `module load gcc cmake gsl fftw`, but this loads FFTW2, not FFTW3. 

To remedy this, it was necessary to do `module load cray-fftw`, which provides FFTW3 on NERSC Cori.

**Comment by abhiShandy** [comment]
Thanks for pointing it out.
