### ISSUE TITLE
 Error opening file 'totalE.fillings' for writing

### ISSUE THREAD

**Issue by goudarzi58** [shankar1729/jdftx#66]
Hello Shankar,

I'm kind of new in JDFTx, and I'm running the examples in the tutorial to figure out the software. I got this error while running the calculation for Al energies. 
  
#--- Lowdin population analysis ---
# oxidation-state Al +0.045
Dumping 'totalE.fillings' ... Error opening file 'totalE.fillings' for writing.
End date and time: Fri Jul 26 14:55:34 2019  (Duration: 0-0:00:07.69)
Failed

I was wondering if you kindly help me to figure out where this error originates from.  

Thank you in advance
Abbas

**Comment by shankar1729** [comment]
Do you have write permissions in the directory you are running in? Does this happen only for this tutorial?

**Comment by goudarzi58** [comment]
I checked the write permission in the directory, that was the cause of the problem. I used the following script to give the permission:
sudo chmod -R ugo+rw ~/Al
and it worked. Thank you so much for the help!

**Comment by shankar1729** [comment]
Great, glad that worked.

Best,
Shankar
