### ISSUE TITLE
Fixed Poetntial calculations

### ISSUE THREAD

**Issue by khyeoh** [shankar1729/jdftx#70]
Hello,

I am trying to go through the tutorial for the fixed-potential calculations in the jDFTx website.
When I execute the following script as given in the tutorial:

#!/bin/bash
for file in Charged*.out; do
    awk '/FillingsAux/ {mu=$3; N=$5} END {print mu, N}' "$file"
done

I notice that no data is extracted into mu_N.dat. 
Correct me if I am wrong, the "FillingsAux" suppose to be replaced by "FillingsUpdate"
Am I right?

Thanks
Yeoh KH

**Comment by shankar1729** [comment]
Hi Yeoh,

Indeed, that's correct; thanks for catching that! The fillings line used to start with FillingsAux. FillingsMix etc. before 1.2, and we missed this in the tutorial once we unified all the fillings algorithms in 1.2.

I've fixed this internally in the tutorial code now, and the doc change will roll out to the website soon.

Thanks!
Best,
Shankar

**Comment by khyeoh** [comment]
Dear Dr Shankar,

Thanks!

**Comment by khyeoh** [comment]
Dear Dr Shankar,

Referring to the tutorial for the fixed-potential calculations , in the gnu script, there is a line:

A = 2*((5.23966*0.529e-8)**2)*sin(pi/3)

I understood that it tries to compute the top and bottom surface area in cm^2 of the Pt surface, with 5.23966 is the lattice constant. However, why we need the sin(pi/3) ? 

I apologize if this question is very basic. I tried but did not find any reference on this,


Thanks

Regards
Yeoh KH

**Comment by shankar1729** [comment]
Here, 5.23966 is a/sqrt(2), the length of the in-plane lattice constant for the 111 slab, which is the nearest neighbor distance in FCC. This surface unit cell is hexagonal, the sin(pi/3)  comes from the corresponding area formula.

**Comment by khyeoh** [comment]
Dear Dr Shankar.

Thank you so much. This is very helpful!
