### ISSUE TITLE
unable to plot bandstructure

### ISSUE THREAD

**Issue by AlphaKnight999** [shankar1729/jdftx#73]
# gnuplot --presist bandstruct.plot
unrecognized option --presist

gnuplot: unable to open display ''
gnuplot: X11 aborted.

# ls
bandstruct.eigenvals  bandstruct.kpoints  bandstruct.kpoints.in  common.in  gC.xsf  totalE.in  totalE.out
bandstruct.in         bandstructKpoints   bandstruct.plot        createXSF  jdftx   totalE.n

**Comment by shankar1729** [comment]
Remove the "set term x11" line from your bandstruct.plot if it is not available on your platform (what OS/distribution are you using?). Also the warning in your output is because it should be "persist" not "presist".
