### ISSUE TITLE
No module named scipy.interpolate

### ISSUE THREAD

**Issue by AmyJcc** [shankar1729/jdftx#74]
Hello Shankar,

I'm kind of new in JDFTx, and I'm running the examples in the tutorial to figure out the software. I got this error while running the calculation for Phonon dispersion. 
 
Enter PhononDispersion.py according to the example and there is an error message after running: No module named scipy.interpolate.

 I was wondering if you kindly help me to figure out What is the reason for this error?

Thank you in advance
AmyJcc

**Comment by shankar1729** [comment]
This would most likely be because you do not have scipy installed in the python distribution that you're using. If you do have scipy installed in some non-system python eg. in an anaconda install, then make sure your script is using that python instead of the system one.

Best,
Shankar
