### ISSUE TITLE
wannier-center  Gaussion   X Y Z

### ISSUE THREAD

**Issue by AmyJcc** [shankar1729/jdftx#75]
Hello Shankar,

I'm running the examples in the tutorial to figure out the Entangled bands of Al. I use "wannier-center Gaussion <x0><y0><z0>"commands to generate a initial guess. 

The example points out "This time we have specified five wannier-center commands with trial orbitals centered at random coordinates." 

I am confused why using randomly generated coordinates and how to generate random coordinates inthe example?

Thank you in advance
AmyJcc

**Comment by shankar1729** [comment]
Sometimes it is difficult to find symmetric wannier orbitals based on intuitive guesses (such as atomic or bond orbitals), and then we typically fall back to random gaussians. (See the extensive Wannier function literature for more on this.) You can generate the random coordinates using the random number generator in matlab or python.

**Comment by AmyJcc** [comment]
Thanks for your answer！
and What is the range of generating the random coordinates? Why choose this range?

**Comment by shankar1729** [comment]
Since these are fractional coordinates, you can set them in the range [0,1) or equivalently, [-0.5,0.5).

**Comment by goudarzi58** [comment]
Hi Shankar,

I found your explanation here interesting. I'm running Wannier calculation for gold and some of the optimum values I'm getting after 1200 iterations are slightly above one. 
         [ -1.00109 -0.000778458 0.989038 ] spread: 3.72816 bohr^2
        [ -0.0278742 0.0030933 -1.00041 ] spread: 4.54713 bohr^2
        [ 0.0268208 0.997135 -1.00897 ] spread: 4.05265 bohr^2
        [ 0.0586753 0.871261 -0.123528 ] spread: 18.4043 bohr^2
        [ 1.00562 -0.999982 1.00824 ] spread: 3.94469 bohr^2
        [ -0.0207565 0.00421827 0.0146974 ] spread: 5.61999 bohr^2
        [ -0.35357 -0.301665 0.700755 ] spread: 23.9899 bohr^2

is there any problem with my inputs? Also, is it possible to perform Wannier calculations using Spin-Orbit? What would be the changes in the Wannier inputs that case?

**Comment by shankar1729** [comment]
Try starting out the centers with random values that are closer to the location of the gold atom at 0,0,0. So instead of uniform random numbers in (0,1), use random numbers that are say in the (-0.1,0.1) range in this case.

**Comment by goudarzi58** [comment]
**Thank you for your answer. I choose random numbers in the (-0.1, 0.1) range, and after 1200 iterations, the winner centers stood almost in the same range close to zero. I'm not sure if this is correct. The other parameters which I'm curious about their optimum values are Omega and OmegaI. What is the relation between the wannier - center values and omegas values?
here's the output of my run for 7 bands of gold:**


Optimum spread:
        Omega:  4.189344259459271e+01
        OmegaI: 3.623312432367051e+01

Centers in lattice coords:
        [ -0.25459 -0.254902 0.441661 ] spread: 11.418 bohr^2
        [ -0.032253 0.0321831 0.0287844 ] spread: 4.25519 bohr^2
        [ 0.254895 0.254611 -0.0678132 ] spread: 11.4178 bohr^2
        [ -5.89984e-05 5.79504e-05 -0.00460713 ] spread: 3.49508 bohr^2
        [ -0.0037924 0.00375635 -0.000699044 ] spread: 3.38599 bohr^2
        [ 0.0322501 -0.0323055 0.0287275 ] spread: 4.25331 bohr^2
        [ 0.00380325 -0.00363604 -0.0269786 ] spread: 3.66809 bohr^2

**Comment by shankar1729** [comment]
These centers look reasonable and are somewhat close to the d5t2 tight-binding model in gold.

Omega is the sum of squares of the spreads of all centers. Please read the original maximally-localized Wannier function refs for further information about the physical meaning of these quantities.

**Comment by goudarzi58** [comment]
Thank you so much for your answer!

Best,
