### ISSUE TITLE
ValueError: total size of new array must be unchanged

### ISSUE THREAD

**Issue by AmyJcc** [shankar1729/jdftx#76]
Hello Shanlar,

I'm running the examples in the tutorial to get the wannier bandstruct of separated bands. I got
this error while running the "WannierBandstruct.py"

#--- Lowdin population analysis ---
Traceback (most recent call last):
  File "wannierbandstruct.py", line 10, in <module>
    Hwannier = np.reshape(Hwannier, (nCells,nBands,nBands))
  File "/usr/lib64/python2.7/site-packages/numpy/core/fromnumeric.py", line 172, in reshape
    return reshape(newshape, order=order)
ValueError: total size of new array must be unchanged

All calculation scripts are provided as examples，and I was wondering if you kindly help me to figure out where this error originates from.

Thank you in advance
AmyJcc

**Comment by shankar1729** [comment]
This is because v1.5 of jdftx changed the Wannier output format to be more compact on disk. We have not yet updated the tutorials to match.

We'll do that soon; in the meantime, you can use a version of Wannier just before 1.5.0.

Best,
Shankar

**Comment by AmyJcc** [comment]
I use the version of Wannier just is 1.5.0, but  this problem still exists. I don't know where the problem is.

**Comment by shankar1729** [comment]
I meant < 1.5, not = 1.5.

**Comment by AmyJcc** [comment]
Thank you !

AmyJcc

**Comment by shankar1729** [comment]
The Wannier tutorials are now up to date with the new format.

Best,
Shankar
