### ISSUE TITLE
including spin-orbit coupling in Wannier calculations.

### ISSUE THREAD

**Issue by goudarzi58** [shankar1729/jdftx#77]
Hi Shankar,

I'm trying to include spin-orbit coupling in wannier calculations of 7 bands of gold, but I'm facing the following error:

Encountered 7 errors while parsing input:

Command 'wannier-center'  with command line:
        wannier-center Gaussian  -0.993542 -0.0129647 1.00009  
failed with message:
        Must specify a specific projection eg. px,py (not just p)
The correct usage of this command is described below:
        wannier-center <aorb1> [<aorb2> ...]
Specify trial orbital for a wannier function as a linear combination of
atomic orbitals <aorb*>. The syntax for each <aorb> is one of:

 +  <species> <atom> <orbDesc> [<coeff>=1.0]
 +  Gaussian <x0> <x1> <x2>  [<sigma>=1] [<orbDesc>=s] [<coeff>=1.0]
 +  Numerical <b>  [<x0> <x1> <x2>] [<coeff>=1.0]
#####

I was wondering if you help me out to figure out what I'm missing in the Wannier input. 

Thank you,
-Abbas

**Comment by shankar1729** [comment]
Hi Abbas,

If you're using random centers in spin orbit mode, then just suffix the
usual Gaussian wannier-center command with sUp or sDn to specify spherical
Gaussians in space with a specific spin polarization. Note that you
probably want 14 centers for gold now due to the two fold degeneracy of
each band. (Pick 7 Gaussians, and put each once with sUp and once with sDn.)

If you want to use atomic orbitals, you will need to use the j,mj notation
as specified in the density-of-states command documentation.

Best,
Shankar

**Comment by goudarzi58** [comment]
**Thank you for your explanation. I implanted the Wannier centers in this way:**
wannier \
    innerWindow  -0.042 0.911 \
    outerWindow  -0.042 2.00 \
    saveMomenta yes

wannier-center Gaussian  -0.05  -0.09 0.100 1.5  sUp
wannier-center Gaussian  -0.05  -0.09 0.100 1.5  sDn

**But it runs into this error:**
**Trial orbitals are linearly dependent / do not cover desired subspace at k = [ 0.0625 0 0 ]**

**I'm wondering where this error origion from? I share the totalE.in and common.in inputs below just in case. ** 
##########common.in
lattice face-centered Cubic 7.6817367
ion-species SG15/$ID_ONCV_PBE.upf
elec-ex-corr gga-PBEsol
elec-cutoff 30
ion Au 0.00 0.00 0.00 0
spintype spin-orbit
##########
include common.in
kpoint-folding 16 16 16
elec-n-bands 24
elec-smearing Fermi 0.01
electronic-SCF
converge-empty-states yes
dump-name totalE.$VAR
dump End State BandEigs ElecDensity
density-of-states Total
add-U Au d 0.07496862 #2.04eV
dump End EigStats

**Comment by shankar1729** [comment]
You need to add many more centers to cover the energy range of your inner / outer windows. Having only two centers for that range seems incorrect.

**Comment by goudarzi58** [comment]
Dr. Shankar,
Sorry for not copying the full wannier input and causing this misunderstanding, I actually have 7 pairs of wannier-centers for sUp and sDn. I found that the error can be solved by adjusting the inner and outer energy windows which are different from those I used to calculate 7 wannier-centers without spin-orbit calculations. Now I run into another error when plotting the wannier bands in Python: 
for     innerWindow   0.24 0.811 \
          outerWindow  -0.24 1.200 \
**in  Hwannier = np.reshape(Hwannier, (nCells,nBands,nBands))
ValueError: cannot reshape array of size 1762824 into shape (4497,19,19)**

I'm supposed to have 7 pairs of bands, but the code gives me 19 bands and wannier.mlwfH can not be reshaped into  (4497,19,19). 

Changing the energy windows does not look to fix the problem. On the other hand, plotting the bandstructure using bandstruct.plot results in a wired figure, while the same plot without spin-orbit looks reasonable. 
Moreover, the calculated mu recorded in totalE.eigStats is +0.471507 which is different from the one from the regular calculation (mu = 0.772218).
 I'm guessing that the problem may originate from  Pseudopotential. I have used:
**Au.rel-pbe-n-rrkjus_psl.1.0.0.UPF.** 
Is this a correct Pseudopotentioal for spin-orbit calculations? If it's not, I was wondering if you could introduce me a suitable Pseudopotential. 

Best 
Abbas

##############
include totalE.in

wannier \
    innerWindow   0.40 0.777777711 \
    outerWindow  -0.24 1.000 \
    saveMomenta yes

wannier-center Gaussian  -0.05  -0.09 0.100  1 sUp
wannier-center Gaussian  -0.10  -0.11 0.088 1 sDn
wannier-center Gaussian   0.037 0.097 -0.087   1 sUp
wannier-center Gaussian   0.037 0.078 -0.093  1 sDn
wannier-center Gaussian   0.092 -0.066 0.088    1 sUp
wannier-center Gaussian   0.097 -0.076 0.098   1 sDn
wannier-center Gaussian  -0.089 -0.099 0.072  1 sUp
wannier-center Gaussian  -0.055 -0.088 0.078  1 sDn
wannier-center Gaussian  -0.04 0.06 -0.03 1 sUp
wannier-center Gaussian  -0.058 0.067 -0.043   1 sDn
wannier-center Gaussian   0.0265317 0.095 -0.02233  1 sUp
wannier-center Gaussian   0.092 0.065  0.095  1 sDn
wannier-center Gaussian  -0.00800219 0.0140073 0.009  1 sUp
wannier-center Gaussian  -0.091 0.081 0.037  1 sUp
![bandplot](https://user-images.githubusercontent.com/53313334/64936523-0ff66280-d81c-11e9-80a2-95e7c29a4450.jpg)

**Comment by shankar1729** [comment]
That pseudopotential should be fine, but your bandstructure definitely looks completely off. Could you please attach all relevant input and log files (for totalE and bandstruct calculations)?

**Comment by goudarzi58** [comment]
Sure, here are the files:

**Comment by goudarzi58** [comment]
Sure, here are the files:
https://drive.google.com/file/d/1TvaDJldkOLiHZMPUyNVFhzC7BCY82ta3/view?usp=sharing


[Bands.zip](https://github.com/shankar1729/jdftx/files/3617765/Bands.zip)
[TotalE.zip](https://github.com/shankar1729/jdftx/files/3617766/TotalE.zip)

**Comment by shankar1729** [comment]
I noticed several issues in these calculations:
1. Your totalE calc was not converged, which could be related to below issues.
2. Did not have enough bands, use at least 18 here to have enough for subsequent wanneirization etc.
3. Using PBEsol on a PBE pseudopotential
4. Add-U was only in totalE and not bandstruct; move this command to common.in
5. Charge density cutoff was not sufficient for pseudopotential. This UPF file recommends 423 Ry rho-cutoff and 42 Ry wfns-cutoff. So in Eh units, use elec-cutoff 21 212.

Despite fixing all these issues, the band structure tsill had the strange flat line you saw above, indicating that it has a "ghost" state. That means that this pseudopotential is problematic and you should find another. Look at the pseudopotentials available in pseudo DOJO for example.

**Comment by goudarzi58** [comment]
Thank you for your feedback, I learned a lot. Trying to use Au-sp.psp8, I run into the following error:

Command 'ion-species'  with command line:
        ion-species Au-sp.psp8
failed with message:
        unknown pseudopotential format extension 'psp8'
The correct usage of this command is described below:
        ion-species [<path>/]<id>[<suffix>].<format>
          | [<path>/]$ID[<suffix>].<format>
.
.
.
Currently supported <format>'s are:
+ .fhi   ABINIT format FHI98 norm-conserving pseudopotentials (eg. generated by OPIUM).
+ .uspp  Ultrasoft pseudopotentials generated by the USPP program (native binary format).
+ .upf   Quantum Espresso Universal Pseudopotential Format (only the XML-like version 2).

**Comment by shankar1729** [comment]
The DOJO website also has UPF format files; download those. Read the documentation there about recommended plane wave cutoffs and other details about using the files.

**Comment by goudarzi58** [comment]
Hi Shankar,
For some reasons, I could only see psp8 format in my browser. I downloaded the PBE and PBEsol pseudopotentioal with UPF format using another computer and tried to run the code for 26 bands, elec-cutoff 30 125, and 7 pairs of wannier-bands for sUp and sDn. I ran into the same error. 

in Hwannier = np.reshape(Hwannier, (nCells,nBands,nBands))
ValueError: cannot reshape array of size 1976072 into shape (5041,19,19)

I have tried different adjustments in the energy windows and also the different number of wannier-bands pairs; all of them resulted in the same error. However, graphing bandsruct.plot results in a smooth band structure.  I'm using JDFTx-1.4.2 and I'm not sure that the problem gets solved by upgrading the code. Here are the input and output files:
 
https://drive.google.com/file/d/1iLDjdeIcc5OaR67Pp9dIlluCZA6_YSej/view?usp=sharing
https://drive.google.com/file/d/1TY_IODNa_QvuZAQu2Ynw0HgmdJoCwiZO/view?usp=sharing

**Comment by shankar1729** [comment]
Add dtype=np.complex128 to the mlwfH fromfile call; the Wannier matrix elements are complex when using spin orbit coupling.

**Comment by goudarzi58** [comment]
Thank you for that. The code works now and this is the resulting bandstructure. I think it needs some adjustment in the input. 
![bands](https://user-images.githubusercontent.com/53313334/65183810-d98e3280-da29-11e9-9c50-209d3244b35c.jpg)
