### ISSUE TITLE
Calculating diagonalizing factor from Wannier functions 

### ISSUE THREAD

**Issue by goudarzi58** [shankar1729/jdftx#78]
Hi Shankar,

I'm trying to calculate diagonalizing factor **(exp(iq.R||)** at the from the outputs of the Wannier calculation. I was wondering if you could tell me which outputs contain **q and R||**? 
I know q is the electron wave vector in the first Brillouin Zone which could be read from bandstructure.kpoint. However, R||, the separation between two Wannier sites looks kind of tricky. Is there any output file which contains data of R||?

Best,
Abbas

**Comment by shankar1729** [comment]
See the Wannier bandstruct script in the tutorials. That is doing precisely the diagonalization you want. The separation between sites in the Wannier Hamiltonian is precisely the contents of the cellMap file.

Best,
Shankar

**Comment by goudarzi58** [comment]
Thank you for the response. I still have some questions about values in CellMap and the diagonalization process. I noticed that the same type of diagonalization is used in WannierDOS.py and WannierImEps.py. **My goal is to calculate the decay rate based on Fermi golden rule for both interband and intraband transitions according to the equation.14 in your 2013 paper**. In there, there is a factor of **exp(iq.R||)** next to the momentum matrix, while it's missing in the equation of the imaginary part of the dielectric function and therefore in WannierImEps.py. I was wondering if you help me out to figure out the difference here.

Best,
Abbas

**Comment by shankar1729** [comment]
The cell map files contain integer coordinates (dimensionless) in first three columns and Cartesian coordinates (bohrs) in last three columns.

The intraband calculation in the 2013 paper constructed a tight-binding model for a surface slab from the bulk Wannier Hamiltonian; this is a much more involved process, beyond the scope of the tutorials. This Hamiltonian is then periodic in only two directions (in plane), and exp(i q R||) is the corresponding phase factor. The tutorial scripts are all for bulk and work directly with exp(iq R) in 3D.

**Comment by goudarzi58** [comment]
Thank you so much for the clarification. That's a very good point which helping my research. 

Best,
Abbas
