### ISSUE TITLE
delta function

### ISSUE THREAD

**Issue by AmyJcc** [shankar1729/jdftx#79]
Hello Shankar,

I am trying to run example of Direct transitions, where the example pointed out that the delta function implements energy conservation.

I am confused which method is used to approximate delta function?

Thank you in advance
AmyJcc

**Comment by abhiShandy** [comment]
Delta function is used in the analytical integral, but the Python script directly uses `omega = Ef - Ei` to conserve energy.

**Comment by shankar1729** [comment]
That's right; so effectively the delta function is being approximated by a box function with width equal to that of the histogram bins.

Best,
Shankar
