### ISSUE TITLE
cast phonon energies into Wannier basis

### ISSUE THREAD

**Issue by AmyJcc** [shankar1729/jdftx#80]
Hello Shankar,

After calculating the phonon spectrum for Al, I need to cast phonon energies into Wannier basis. The example gives the calculation of the energy band. 

How can I use the wannier command in JDFTX to calculate phonons?   Is "include totalE.in” changed to “include phonon.in”?

#Save the following to wannier.in:
include totalE.in

wannier \
    saveWfnsRealSpace yes

wannier-initial-state totalE.$VAR
wannier-dump-name wannier.$VAR

wannier-center Gaussian 0.125 0.125 0.125
wannier-center Gaussian 0.625 0.125 0.125
wannier-center Gaussian 0.125 0.625 0.125
wannier-center Gaussian 0.125 0.125 0.625

Thank you in advance
AmyJcc

**Comment by shankar1729** [comment]
The phonon force matrix (omegaSq) file output by JDFTx is already the "wannier" basis i.e. it is n real space. That is why the phonon band structure script in the tutorial closely resembles the Wannier electronic band structure.

**Comment by AmyJcc** [comment]
is totalE.phononOmegaSq ?

**Comment by shankar1729** [comment]
Yes, totalE.phononOmegaSq is the force matrix I was referring to above.

**Comment by AmyJcc** [comment]
Is the wannier file for calculating Wannierized electron-phonon matrix elements the same as the wannier file for bandstruct ? Mainly the number of wannier centers and the size of the window. If not, how should electron-phonon wannier file be described? 

and could  you give me a reference wannier file for me to learn?

**Comment by AmyJcc** [comment]
I think the phonon energy after the wannier interpolation should be the value output by PhononDispersion.py. This value is used for the electron-phonon absorption calculation. Is this correct?

 For example, in the example of Direct transitions, I consider using the electron energy in wannier.eigenvals, so why use wannier.mlwfH in the example?

**Comment by shankar1729** [comment]
No, electron-phonon matrix elements are in totalE.phononHsub, which are then wannierized to produce wannier.mlwHeph. Unlike the phonon force matrix, the e-ph matrix element start out in electron bands - atom displacement basis, and the electronic part needs to be Wannierized before interpolation. We hope to eventually bring this part to a tutorial, but note that it is of significantly higher complexity then the electron-only or phonon-only parts, especially because the e-ph matrix elements are a 5-dimensional object.

I don't understand your second comment.

**Comment by AmyJcc** [comment]
Thank you for your reply! Could you provide a wannier.in that performs wanniered electron-phonon matrix elements as a example ?

**Comment by shankar1729** [comment]
Just add "phononSupercell x y z" to the wannier command, with x y z matching the supercell in the completed phonon calculation. See the documentation of the wannier command.

**Comment by AmyJcc** [comment]
I understand this command, but I am confused about the settings for  window size and the number of wannier-center. Can you explain it briefly ?

**Comment by shankar1729** [comment]
The first two Wannier tutorials discuss this in detail. Read the references pointed to in the first tutorial for a detailed introduction to Wannier functions. These settings don't change whether you want to wannierize electron phonon quantities or not. The Wannier minimization process is identical; it only applies the same unitary transformations to the e-ph elements in addition to pure electronic quantities.

**Comment by AmyJcc** [comment]
Thank you very much for your reply, which is very helpful for me to learn jdftx ！
