### ISSUE TITLE
Solvated ion near constant-potential electrode

### ISSUE THREAD

**Issue by astronomydomine2** [shankar1729/jdftx#85]
Hello,

I have completed the separate tutorials on ion solvation and constant-potential electrode surfaces. I am trying to combine the two into a model of a solvated ion near the constant-potential electrode surface. I am unsure on the practical details of doing so, so I was wondering if you have any tutorials or tips available.

Thank you.

**Comment by shankar1729** [comment]
I attach example input files for the Cl on Pt from the grand-canonical DFT J. Chem. Phys. paper. You only need to construct the appropriate supercell with the adsorbate configuration you seek; everything else stays the same. Note that these input files are a part of a scripted system that launched all the various configurations using a single common.in; that should hopefully make sense based on the tutorials.

Best,
Shankar
[UPD-example.zip](https://github.com/shankar1729/jdftx/files/3680928/UPD-example.zip)
