### ISSUE TITLE
slab optimisations crash with coulomb-truncation & solvation

### ISSUE THREAD

**Issue by nagb** [shankar1729/jdftx#89]
Hi,

I keep getting a segfault crash when I try to run the following file adapted from the tutorials. Am I doing something wrong, is it a bug or a machine specific issue? 

The crash occurs during the calculation of the stress tensor. 

This is the error message:
"Segmentation Fault.
Segmentation Fault.
Segmentation Fault.
"

Next follows my input file:

lattice Hexagonal 4.651 20

ion C  0.000000  0.000000  0.0   1
ion C  0.333333 -0.333333  0.0   1

ion-species GBRV/$ID_pbe.uspp
elec-cutoff 20 100

lattice-minimize niterations 100
latt-move-scale 1 1 0 

electronic-scf nIterations 400
lcao-params 100
coulomb-interaction Slab 001
coulomb-truncation-embed 0 0 0

fluid LinearPCM 298.15 
pcm-variant CANDLE
kpoint-folding 12 12 1
elec-n-bands 8

dump-name C2.$VAR
dump End State BandEigs Eigstats Fillings Lattice Kpoints DOS

**Comment by shankar1729** [comment]
I can confirm this bug: there seems to be an issue with stress calculation with any solvation model. I will look into this further, but in most cases lattice optimization with solvation models should not be required / solvation models will have negligible effect.

**Comment by nagb** [comment]
Agreed, but this is not the case for chemical changes (i.e. NEBs/reaction paths).

**Comment by shankar1729** [comment]
This issue should now be fixed as a part of the recent analytic lattice derivative implementation.

-Shankar
