### ISSUE TITLE
Constant mu application to all atoms except one?

### ISSUE THREAD

**Issue by anneb101** [shankar1729/jdftx#91]
Hello, I was interested in simulating a case where there is a distinction between electrode atoms (held at constant mu) and an adsorbate atom (its mu may vary). From the tutorials, I was able to gather that mu can be controlled for the entire system. However, is there any way to exclude specified atoms from the constant mu condition?
Thank you,
Anne

**Comment by shankar1729** [comment]
Hi Anne,

All DFT calculations here are in equilibrium by default, so the whole unit cell has to be at the same electron chemical potential by definition. It is therefore not possible to exclude atoms or regions from it. If you are trying to do something like that, it is a non-equilibrium situation that probably requires something like partition DFT which is beyond the scope of JDFTx.

Best,
Shankar
