### ISSUE TITLE
Net charge distribution of the electrode−electrolyte

### ISSUE THREAD

**Issue by khyeoh** [shankar1729/jdftx#93]
Dear Dr Shankar,

I am interested in calculating the Net charge distribution of the electrode−electrolyte system along the a given direction as shown in Fig. 3 of the paper given in the link below (i.e.  ACS Energy Lett. 2016, 1, 6, 1241-1246) The calculations were done using jDFT. I was wondering if you have any tutorials or tips available on that?

[https://pubs.acs.org/doi/abs/10.1021/acsenergylett.6b00483](url)

Thanks!
Yeoh

**Comment by shankar1729** [comment]
Please see the planarly-averaged electrostatic potential plots in this tutorial:

http://jdftx.org/OxideSurfaces.html

You should be able to adapt the same technique using the BoundCharge and ElecDensity to get what you want. Specifically, you should read ElecDensity of the neutral and charged systems and take the difference to get the electrode charge, and then add that to the bound charge to get the total charge. Then use that quantity for subsequent plotting as in the tutorial.

Best,
Shankar

**Comment by khyeoh** [comment]
Thank you!

**Comment by miaozhuang68** [comment]
Dear Shankar,
This is a very impressive explanation!
I think I should have a framework for practice.
1. Calculate the ElecDensity of neutral systems and charged (controlled by overpotential) systems
2. Compare the difference between the two curves to obtain the charge deficiency
3. Add this charge deficiency to BoundCharge and calculate again (if I also examine the polarization under a given charge deficiency, it feels like I can directly use the charge deficiency I specified to add it to the BoundCharge calculation. Of course, this charge deficiency value should be tested to prove that it is also applicable to this calculation)
4. Draw a curve (it feels like I need to set a reference zero point?)

Best,
Jam
