### ISSUE TITLE
Lattice optimization

### ISSUE THREAD

**Issue by khyeoh** [shankar1729/jdftx#94]
Dear Dr. Shankar,

I tried to carry out lattice optimization on a 2D system and ended up with the following:

**LatticeMinimize: 	Step failed along negative gradient direction.
LatticeMinimize: Probably at roundoff error limit. (Stopping)**

I grep the Lattice Minimize in the log file which gave us the following info:

LatticeMinimize: Iter:   0  F: -821.729011961387414  |grad|_K:  2.968e-02  t[s]:   3815.51
LatticeMinimize: 	Wolfe criterion not satisfied: alpha: 1  (E-E0)/|gdotd0|: 0.0871758  gdotd/gdotd0: -1.28844 (taking cubic step)
LatticeMinimize: 	Wolfe criterion not satisfied: alpha: 0.474271  (E-E0)/|gdotd0|: 0.0386057  gdotd/gdotd0: -1.03225 (taking cubic step)
LatticeMinimize: 	Wolfe criterion not satisfied: alpha: 0.210804  (E-E0)/|gdotd0|: 0.0157544  gdotd/gdotd0: 0.0611815 (taking cubic step)
LatticeMinimize: 	Wolfe criterion not satisfied: alpha: 0.0594357  (E-E0)/|gdotd0|: 0.00500995  gdotd/gdotd0: -0.0660324 (taking cubic step)
LatticeMinimize: 	Undoing step.
LatticeMinimize: 	Step failed along negative gradient direction.
LatticeMinimize: Probably at roundoff error limit. (Stopping)
LatticeMinimize: Iter:   0  F: -821.729011961360470  |grad|_K:  2.968e-02  t[s]:   3821.14
LatticeMinimize: 	Wolfe criterion not satisfied: alpha: 1  (E-E0)/|gdotd0|: 0.0871753  gdotd/gdotd0: -1.3203 (taking cubic step)
LatticeMinimize: 	Wolfe criterion not satisfied: alpha: 0.478064  (E-E0)/|gdotd0|: 0.0357162  gdotd/gdotd0: -0.52913 (taking cubic step)
LatticeMinimize: 	Wolfe criterion not satisfied: alpha: 0.176991  (E-E0)/|gdotd0|: 0.0154759  gdotd/gdotd0: 0.396534 (taking cubic step)
LatticeMinimize: 	Wolfe criterion not satisfied: alpha: 0.0422058  (E-E0)/|gdotd0|: 0.00282226  gdotd/gdotd0: 0.240041 (taking cubic step)
LatticeMinimize: 	Undoing step.
LatticeMinimize: 	Step failed along negative gradient direction.

May I know how to overcome this issue?

Thanks
Yeoh

**Comment by shankar1729** [comment]
Check the convergence of the electronic minimize / SCF: this sort of issue can crop up particularly if the electronic iterations are not converging.

If that looks fine, try adjusting the dirUpdateScheme in command lattice-minimize to FletcherReeves or PolarkRibiere (see http://jdftx.org/CommandLatticeMinimize.html)

Best,
Shankar

**Comment by khyeoh** [comment]
Dear Dr Shankar,

Correct me if I am wrong, the electronic minimize SCF seems converge. (Please see attached files)
I try both scheme but it did not work. I attached the output file here for your reference.

[Outputfile.zip](https://github.com/shankar1729/jdftx/files/3833977/Outputfile.zip)

Hope you can help.

Thanks!
Yeoh

**Comment by shankar1729** [comment]
Indeed, the electronic minimization seems fine. The other point might just be that your lattice already happens to be quite close to converged. I'm not sure exactly what the issue is, but you can try a few things:

1. Switch to the primitive cell of the surface for lattice optimization if that's an option. This will reduce internal degrees of freedom and overall make your calculation much faster anyway.

2. Ionically minimize the system more throughly before starting a lattice minimize.

If all this fails, simply do calculations at a few different strains and fit for the equilibrium. We've had to do this in some problematic cases.

Best,
Shankar

**Comment by khyeoh** [comment]
Dear Dr. Shankar,

Previously, the input coordinate that I used are those already relaxed using Quantum Espresso. I re-do the calculations, by using the un-optimized input coordinate and it works. I am using the FletcherReeves  scheme.

Thanks!

**Comment by hemant0723** [comment]
Dear Dr. Shankar and Khyeoh,

I am encountering exactly the same issue in slab model, however my SCF has converged as well. I would appreciate your insights on how you resolved this problem.

Thank you!

**Comment by shankar1729** [comment]
Please post your log file.
