### ISSUE TITLE
invalid value encountered in sqrt plt.plot (np.sqrt(omegaSq)/meV) 

### ISSUE THREAD

**Issue by omehe** [shankar1729/jdftx#95]
Hi,
How do I get pass this. I tried the phonon for So and I could not plot the phonon bands. My input was from the tutorials. What am I doing wrong?

**Comment by shankar1729** [comment]
The "invalid value encountered in sqrt" is just a warning because at Gamma the zero frequency squared might be slightly negative (invalid for the sqrt, and it sets it to zero instead).

That should not prevent you from plotting the phonon band structure. Please provide more information about the output you are getting to see if we can find the problem.

Best,
Shankar

**Comment by omehe** [comment]
Do you mean the output from the phonon calculation?

**Comment by omehe** [comment]
Hello,
Attached are the output of the So tutorial.
Thank for your assistance.
On Nov 12, 2019 17:59, "Ravishankar Sundararaman" <notifications@github.com>
wrote:

The "invalid value encountered in sqrt" is just a warning because at Gamma
the zero frequency squared might be slightly negative (invalid for the
sqrt, and it sets it to zero instead).

That should not prevent you from plotting the phonon band structure. Please
provide more information about the output you are getting to see if we can
find the problem.

Best,
Shankar

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/shankar1729/jdftx/issues/95?email_source=notifications&email_token=ANX67A7YHAHRXQ6VB2AZKO3QTLOGFA5CNFSM4JMGB2V2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOED26KEI#issuecomment-552985873>,
or unsubscribe

**Comment by shankar1729** [comment]
The attachment did not come through.

Also, please describe the issue more clearly. When you say you are unable to plot the phonon bands, what do you mean exactly? As discussed above, the message in your thread title is only a warning. So do you get this message and then no plot? If there were any other error messages when running the plot script, please mention them.

**Comment by omehe** [comment]
Hello,
When I use the Python script, it just gives the error I mention earlier
without any plot. No other error note. I have also attached the output from
both runs.
Thanks.
On Nov 12, 2019 20:01, "Ravishankar Sundararaman" <notifications@github.com>
wrote:

The attachment did not come through.

Also, please describe the issue more clearly. When you say you are unable
to plot the phonon bands, what do you mean exactly? As discussed above, the
message in your thread title is only a warning. So do you get this message
and then no plot? If there were any other error messages when running the
plot script, please mention them.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/shankar1729/jdftx/issues/95?email_source=notifications&email_token=ANX67A7TNFGERYTPALQJDADQTL4R7A5CNFSM4JMGB2V2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOED3QR4A#issuecomment-553060592>,
or unsubscribe

**Comment by shankar1729** [comment]
Still no attachment: please use the web interface; email attachments do not get uploaded.

Did other python plotting examples from other jdftx tutorials work? What OS and python version are you using?

**Comment by omehe** [comment]
I did not try others since I am interested just in the vibrational property
for now. I am using fedora 30 and python2.7.

**Comment by shankar1729** [comment]
Double check the plot script: in particular, make sure you did not forget the plt.show() line which could make the plot not show up.

Without further details, I can't really help debug any jdftx-specific issue. Based on what you have described so far, I suspect it is a problem in the plot script you pasted or your python plotting environment.

Best,
Shankar

**Comment by omehe** [comment]
I will try to upload the script.

**Comment by omehe** [comment]
I tried uploading the files, I don't know if I succeeded.

**Comment by omehe** [comment]
Let me try to upload the files

**Comment by shankar1729** [comment]
No, there are no file attachments visible on any of these posts.

**Comment by omehe** [comment]
Hello,
Thank you so much for your assistance, I have been able to resolve the
issue.
