### ISSUE TITLE
Error in H2 molecular optimization 

### ISSUE THREAD

**Issue by Bobjnu** [shankar1729/jdftx#99]
Hi Shankar:
I got in trouble when I tried to optimize the geometry of a H2 molecule in a large vaccum box. The program end with an error:
"WARNING: H #0 and H #1 are closer than the vector-sum of their core radii. Atoms are too close, have overlapping pseudopotential cores."

As we know, H2 molecule has a bond length of ca. 0.75 angstrom. This is exactly what I set in my input file:
H2.ionpos:
ion  H   0.5996085575323801  0.5996423515789648  0.7000660385248226 0
ion  H   0.6545962661394188  0.6498820020782854  0.6907043551727637 1

H2.lattice:
lattice \
    19  0  0 \
    0  19  0 \
    0  0  19

opt.in:
include H2.lattice
include H2.ionpos
ion-species GBRV/$ID_pbe.uspp
elec-cutoff 12 60
electronic-SCF \
        energyDiffThreshold 1e-06 \
        nIterations 100
ionic-minimize \
        nIterations 200 \
        energyDiffThreshold  1e-06 \
        knormThreshold 1e-4
dump-name opt.$VAR
dump end State Lattice IonicPositions

Could you please give me some suggestion?
Thanks!

**Comment by shankar1729** [comment]
This is an issue with the GBRV H pseudopotential having a core that is too large when trying to do H2. You need to add command "core-overlap-check None" to bypass this check, as discussed in the [vibrational free energy](http://jdftx.org/FreeEnergy.html) tutorial.

Best,
Shankar
